### PR TITLE
gcc12 fixes

### PR DESCRIPTION
**Pull request by quaresmajose**

### CODE REVIEW

**Review by jforissier — APPROVED** [review]
Hi @quaresmajose, thanks for the patches.

`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by quaresmajose** [comment]
> Hi @quaresmajose, thanks for the patches.
> 
> `Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

Thanks for the review, added the `Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by clementfaure** [comment]
For `eb12a9916c1812fb79a2bbb4d6a6fe460ee4580b`
`Acked-by: Clement Faure <clement.faure@nxp.com>`

**Comment by quaresmajose** [comment]
The `CI / Code style (pull_request) ` job is falling because the line is bigger than 75 chars but this line is the compiler stdout and IMO is better to have it as is.
```
dd2c90e6 drivers: imx: dcp: fix compilation address error
WARNING: Possible unwrapped commit description (prefer a maximum 75 chars per line)
#15: 
| core/drivers/imx/dcp/dcp_huk.c:71:23: error: the comparison will always evaluate as 'true' for the address of 'data' will never be NULL [-Werror=address]
```

**Comment by jforissier** [comment]
> The `CI / Code style (pull_request) ` job is falling because the line is bigger than 75 chars but this line is the compiler stdout and IMO is better to have it as is.

I agree. It seems checkpatch is confused by the new error reporting style of GCC (with a `|` character at the start of the line). Let's just ignore that for the moment. Longer term it would be good to update the regexp in checkpatch.

**Pull request merged**
