### PR TITLE
Update CHANGELOG.md for 3.0.0

### PR DESCRIPTION
**Pull request by jforissier**
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
Preparing for the next release...

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)`

**Comment by jforissier** [comment]
For 3.0.0-rc1:
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey)`

**Comment by igoropaniuk** [comment]
Except of known issue of rcu_sched stall on CPU, for 3.0.0-rc1:

```bash
$ xtest -l 15
+-----------------------------------------------------
35645 subtests of which 0 failed
67 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```
`Tested-by: Igor Opaniuk <igor.opaniuk@linaro.org> (RPi3)`

**Comment by nodeax** [comment]
`
Tested-by: Akshay Bhat <akshay.bhat@timesys.com> (Atmel SAM)
`
```
15702 subtests of which 0 failed
67 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```

**Comment by glneo** [comment]
https://github.com/OP-TEE/optee_os/pull/2083#issuecomment-359071860

**Comment by glneo** [comment]
With https://github.com/OP-TEE/optee_os/pull/2089 merged:

```
Tested-by: Andrew F. Davis <afd@ti.com> (plat-ti)
```
```
15706 subtests of which 0 failed
68 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```

**Comment by lorc** [comment]
UPD: While single `xtest` invocation works just  fine, looped testing fails  with `TEEC_ERROR_OUT_OF_MEMORY` in various test cases (for now I have seen failures in 1008.4, 6016, 6018).

**Comment by jforissier** [comment]
@lorc 
> I don't know if it intentional or not, but last release can't be built with gcc-5.

No it's not intentional. Can you share the error or propose a fix? Thanks.

**Comment by MrVan** [comment]
`Tested-by: Peng Fan <peng.fan@nxp.com> (mx6ulevk mx7dsabresd)`

```
#xtest
15701 subtests of which 0 failed
67 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```

**Comment by jbech-linaro** [comment]
`Tested-by: Joakim Bech <joakim.bech@linaro.org> (mtk8173)`

```bash
I/TC:  OP-TEE version: 3.0.0-rc1 #1 Fri Jan 19 13:28:05 UTC 2018 aarch64
...
root@MT8173_EVB:/ xtest -l15
...
35645 subtests of which 0 failed
67 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```

**Comment by jforissier** [comment]
@lorc 
> [...] looped testing fails  with `TEEC_ERROR_OUT_OF_MEMORY` [...]

I could not reproduce this on HiKey. I've let xtest run in a loop for about an hour and it is still running fine.

There is an app that lets you print some statistics about the OP-TEE heap memory: https://github.com/jforissier/tee-stats. You need to build OP-TEE with `CFG_WITH_STATS=y` to enable the stats pseudo-TA. Then you can monitor the `cur_alloc` number after each invocation of `xtest`. If it increases then there is definitely a leak. This may help you narrow down which test causes the leak and/or bisect the git commits.

**Comment by lorc** [comment]
Hi @jforissier, 

I'll try to build it with stats. But at this moment, I can confirm, that I'm seeing similar problem on qemu_v8.

**Comment by lorc** [comment]
@jforissier, 

Regarding broken build with gcc5. It is introduced in ed17deb.
Build error looks like following:

> core/arch/arm/kernel/thread_a64.S:394: Error: non-constant expression in ".if" statement
> core/arch/arm/kernel/thread_a64.S:400: Error: non-constant expression in ".if" statement
> core/arch/arm/kernel/thread_a64.S:406: Error: non-constant expression in ".if" statement
> core/arch/arm/kernel/thread_a64.S:411: Error: non-constant expression in ".if" statement
> core/arch/arm/kernel/thread_a64.S:420: Error: non-constant expression in ".if" statement
> core/arch/arm/kernel/thread_a64.S:425: Error: non-constant expression in ".if" statement
> core/arch/arm/kernel/thread_a64.S:430: Error: non-constant expression in ".if" statement
> core/arch/arm/kernel/thread_a64.S:435: Error: non-constant expression in ".if" statement

According to GAS documentation on `.align` it is a valid change. I can't see, why changing fill value leads to such spectacular result. Looks like it is a bug in GAS itself.
I tried to invent some workaround, but without any success.

**Comment by vchong** [comment]
@lorc This is a known issue. You just need to use a different linaro gcc5 release. See [1] for details.

[1] https://github.com/ARM-software/tf-issues/issues/401

**Comment by kevin-peng-hao** [comment]
3.0.0-rc2

`Tested-by: Kevin Peng <kevinp@marvell.com> (Armada 7K, 8K, 3700)`

**Comment by vchong** [comment]
For optee-os 3.0.0-rc2,
optee-client 3.0.0-rc1
and optee-test 3.0.0-rc1:

`Tested-by: Victor Chong <victor.chong@linaro.org> (hikey aosp)`

```
hikey:/ # xtest
15702 subtests of which 0 failed                                                                                       
67 test cases of which 0 failed                                                                                        
0 test case was skipped                                                                                                
TEE test application done!                                                                                             
```

Note: SDP disabled for now since TEE driver patches were reverted in android-hikey-linaro-4.9 (4.4) to resolve merge conflicts from Android Common, but AC has only the 'basic' OP-TEE patches compared to android-hikey-linaro-4.9 (4.4) which had all the more 'advanced' ones (e.g. kernel internal client interface, sdp, etc).

**Comment by JosephChen2017** [comment]
3.0.0-rc2

```Tested-by: Joseph Chen <chenjh@rock-chips.com> (RK322X)```

**Comment by igoropaniuk** [comment]
RPi3 `optee_os` 3.0.0-rc2 (other reps on 3.0.0-rc1):
```
+-----------------------------------------------------
35645 subtests of which 0 failed
67 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```

`Tested-by: Igor Opaniuk <igor.opaniuk@linaro.org> (RPi3)`

**Comment by lorc** [comment]
Hi @jforissier, 

sorry for late answer. I tested again on qemu with stats enabled. You can find results in #2095. 
I'll try to isolate test that causes this.

**Comment by jforissier** [comment]
3.0.0-rc2
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (D02)`

**Comment by jforissier** [comment]
c10e9d48 = 3.0.0-r2 + "secstor: fix memory leak in install_ta()":
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (QEMU)`
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (QEMUv8)`

**Comment by jforissier** [comment]
@ all: thanks for testing.

**Pull request merged**
