### PR TITLE
core: small fixes

### PR DESCRIPTION
**Pull request by ghost**
### There are two points of correction:

1. Issue with DH (Diffie-Hellman):
    The DH secret, due to its mechanism, becomes a value less than the key length of the Private key. Consequently, when obtaining the maximum size of the secret from the current key length of the Public key, the secret length falls short.

1. Typo in the ECC Crypt API header file:
    According to the OP-TEE specification, the size passed as an argument to gen_keypair should be in terms of bit length. However, the variable name for the argument is bytes.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Since these two patches are fixes, please add "Fixes: " tags too, pointing out the commit which is fixed.

**Comment by jenswi-linaro** [comment]
Please fix the checkpatch complaints.
If you're not sure how to proceed, please let us know and we'll help you.

**Comment by TE-0000106830** [comment]
@jenswi-linaro 
Than you for your kind follow. I'm trying to contribute with Contribute Section in OP-TEE Docs but I may miss something to do because this is my first contribute in my life.

I fixed commit message first. And I'll fix `checkpatch complaints` .

**Comment by jenswi-linaro** [comment]
Please fix up the commit messages along something like this:
```
drivers: crypto: fix to extract DH secret length from modulus

Prior to this patch, the DH secret, due to its mechanism, becomes a value
less than the key length of the Private key. Consequently, when obtaining
the maximum size of the secret from the current key length of the Public
key, the secret length falls short. So change this to extract DH secret
length from modulus instead of public key length.

Fixes: f6e2b9e2d1a2 ("drivers: crypto: implement crypto driver - DH")
Signed-off-by: Katsunori Kikuchi <Katsunori.Kikuchi@sony.com>
```

and this:
```
core: crypto_api: fixes typo "bytes" to "bits"

Fixes a typo for *gen_keypair() in struct drvcrypt_ecc where the last
parameter was "size_bytes" while the value represents bits, so fix this by
renaming it to "size_bits".

Fixes: d29cd2efcd46 ("core: driver: generic resources for crypto device driver - ECC")
Signed-off-by: Katsunori Kikuchi <Katsunori.Kikuchi@sony.com>
```

**Comment by TE-0000106830** [comment]
@jenswi-linaro
Thank you for your support. I misunderstood the "fixes:" tag usage.
And can I use the commit message sample you gave? Because the sample seems perfect and I don't think that I can write commit messages better than the ones.

**Comment by jenswi-linaro** [comment]
> @jenswi-linaro Thank you for your support. I misunderstood the "fixes:" tag usage.

No problem.

> And can I use the commit message sample you gave? Because the sample seems perfect and I don't think that I can write commit messages better than the ones.

Yes, feel free to use them as is.

**Comment by TE-0000106830** [comment]
Thank you for your kind support.
I just pushed commits with your perfect sample commit messages!

**Comment by TE-0000106830** [comment]
Thank you for your continuous support.
I jsut add it to the commits.

**Pull request merged**
