### PR TITLE
drivers: crypto: hisilicon: implement QM driver

### PR DESCRIPTION
**Pull request by xiaoxuZeng**
The Hisilicon QM is a Queue Management module.
In order to unify the interface between accelerator and software, a unified queue management module QM is used to interact with software. Each accelerator module integrates a QM. Software issues tasks to the SQ (Submmision Queue),and the QM obtains the address of the SQE (Submmision Queue Element). The BD (Buffer Description, same as SQE) information is sent to the accelerator. After the task processing is complete, the accelerator applies for a write-back address from the QM to write back the SQ.

### CODE REVIEW

**Comment by xiaoxuZeng** [comment]
The experts from community have provided many constructive and helpful suggestions, which we have incorporated through multiple rounds of revisions. However, the original PR https://github.com/OP-TEE/optee_os/pull/5894  contained too many modules, making it difficult to review. Therefore, we have split out a completed module into a separate PRfor easier review. We look forward to receiving valuable feedback from the experts.

**Comment by jenswi-linaro** [comment]
Makes sense, it's not the first time this approach has been needed.

**Comment by ZijjWang** [comment]
Acked-by: wangzijian <wangzijian22@huawei.com>

**Comment by jenswi-linaro** [comment]
How about something like:
``` diff
--- a/core/drivers/crypto/hisilicon/hisi_qm.c
+++ b/core/drivers/crypto/hisilicon/hisi_qm.c
@@ -93,11 +93,16 @@ enum qm_mailbox_cmd_v3 {
 };
 
 struct qm_mailbox {
-	uint16_t w0;
-	uint16_t queue;
-	uint32_t base_l;
-	uint32_t base_h;
-	uint32_t token;
+	union {
+		struct {
+			uint16_t w0;
+			uint16_t queue;
+			uint32_t base_l;
+			uint32_t base_h;
+			uint32_t token;
+		};
+		uint64_t x[2];
+	};
 };
 
 struct qm_dfx_registers {
@@ -148,18 +153,12 @@ static enum hisi_drv_status qm_wait_mb_ready(struct hisi_qm *qm)
 					  POLL_TIMEOUT);
 }
 
-static void qm_mb_write(struct hisi_qm *qm, void *src)
+static void qm_mb_write(struct hisi_qm *qm, struct qm_mailbox *mb)
 {
 	vaddr_t dst = qm->io_base + QM_MAILBOX_BASE;
-	unsigned long tmp0 = 0;
-	unsigned long tmp1 = 0;
 
 	/* 128bits should be written to hardware at one time */
-	asm volatile ("ldp %0, %1, %3\n"
-		      "stp %0, %1, %2\n"
-		      : "=&r"(tmp0), "=&r"(tmp1), "+Q"(*((char *)dst))
-		      : "Q"(*((char *)src))
-		      : "memory");
+	write_64bit_pair(dst, mb->x[0], mb->x[1]);
 	dsb();
 }

```
to avoid mixing inline assembly directly and also fix the potential alignment problem with struct qm_mailbox.

`write_64bit_pair()` should obviously be introduced in a separate patch.

**Comment by xiaoxuZeng** [comment]
> to avoid mixing inline assembly directly and also fix the potential alignment problem with struct qm_mailbox.
> 
> `write_64bit_pair()` should obviously be introduced in a separate patch.

has been implement in a new pr #6228
https://github.com/OP-TEE/optee_os/pull/6228/files

**Pull request closed without merging**
