### PR TITLE
hikey: register additional dyn shm

### PR DESCRIPTION
**Pull request by vchong**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
@vchong so, is dynamic shm working reliably on a 2GB HiKey with this patch?

**Comment by vchong** [comment]
@jforissier Yes. With dynamic shm, and without this patch, almost all xtest cases will fail with `TEEC_COMMUNICATION_ERROR`. With dynamic shm and this patch, all xtest cases pass except for 1014.2, which crashes, but is fixed with https://github.com/linaro-swg/linux/pull/60.

**Comment by jforissier** [comment]
@vchong excellent, thanks.

**Pull request merged**
