### PR TITLE
Update CHANGELOG.md for 2.4.0

### PR DESCRIPTION
**Pull request by jforissier**
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
Preparing for the next OP-TEE release. Please test on your preferred platform and report any issue or success here. If things work as expected, please post a `Tested-by:` and I will update the "Tested on" section of the change log. I will also collect the T-b's in the commit message.

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey)`

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (D02)`

**Comment by b49020** [comment]
plat-ls seems to be broken on 2.4.0. I am debugging the issue. While debugging I found following patch applied:

commit cd62910052268f367ca06d5844d74ae762a73c60
Author: yanyan-wrs <yan.yan@windriver.com>
Date:   Wed Nov 9 09:40:34 2016 +0800

    core: arm: update plat-ls to support secondary core boot

Being Platform Maintainer for plat-ls, please notify me on any platform specific affecting plat-ls.
@yanyan-wrs Have you tested plat-ls (ls1021atwr) platform after applying above patch?

**Comment by yanyan-wrs** [comment]
@b49020 Yes I tested ls1021atwr board, that is the target I intended to support. Could you please be more specific about what's broken? Our team is testing OP-TEE 2.4.0, ls1021atwr is one of the target, and everything seems OK.

**Comment by b49020** [comment]
@yanyan-wrs Can you provide more details on patch? Is this patch regarding PSCI framework for booting up secondary core? As earlier I added support for spin-table approach to wake up secondary core.

**Comment by yanyan-wrs** [comment]
@b49020 My patch is also about booting up the secondary core, but not following PSCI framework. Essentially, all secondary codes are brought up by core0 during the generic boot process, and are put in a PEN. Then NS OS would issue OP-TEE defined SMC to request release of secondary cores into NS worlds.

This was added somewhere around OP-TEE 2.2.0. This same technology is applied to i.MX6 and ZYNQ7K.

**Comment by b49020** [comment]
@yanyan-wrs As per my knowledge there are two approaches in Linux (NS OS) to wake up secondary cores: either via spin table approach or via PSCI approach and this info is passed through device tree from boot-loader.
So is your implementation similar to spin table approach in OP-TEE to wake up secondary cores? If yes, then do you fix up device tree in OP-TEE for the Linux to know this approach?

**Comment by yanyan-wrs** [comment]
@b49020 It's an OP-TEE specific method for secondary core boot, see SMC request number 12 here:
https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/include/sm/optee_smc.h
So Linux has to be patched to use this request to boot secondary cores.

I am not sure if we can switch the OP-TEE to follow PSCI, so that Rich OS can have a standard interface talking to us (at least I didn't see PSCI support back then).

**Comment by etienne-lms** [comment]
Dear all,

For info, there is already a basic PSCI framework in the OP-TEE, but it leaves all the PSCI management to the platform. @MrVan is also working on this.
There is also an initiative for porting the ARM TrustedFirmware PSCI library into OP-TEE to get generic PSCI sequences common to all platform. Study is on-going.

**Comment by b49020** [comment]
@yanyan-wrs I don't think custom approach to boot secondary cores would in acceptable in Linux. So we should shift to PSCI framework existing in OP-TEE added by @MrVan for imx-mx6ulevk platform.
@MrVan Does the PSCI framework in OP-TEE updates device tree regarding PSCI info that Linux needs to wake up secondary cores?

**Comment by yanyan-wrs** [comment]
@b49020 Most ARMv7 does not support PSCI, so I am not sure if we can come up with a design around it.

**Comment by b49020** [comment]
@yanyan-wrs Can you please clarify on your statement "Most ARMv7 does not support PSCI"? Is it regarding platform support in OP-TEE? I have tested PSCI on ls1021atwr platform.

**Comment by MrVan** [comment]
@b49020 I have tested 6q-sabresd with PSCI in OP-TEE, cpu hotplug and suspend/resume works well. You could have a check. suspend code has not been upstreamed.

**Comment by yanyan-wrs** [comment]
@b49020 Sorry I mean ARMv7 does not support ARMTF, which in turn supports PSCI.
@MrVan do you mean you implemented PSCI in OP-TEE? since which version?

**Comment by b49020** [comment]
@etienne-lms Can you please share you road-map for porting PSCI library from ARMTF to OP-TEE for ARMv7 platforms?

**Comment by MrVan** [comment]
`Tested-by: Peng Fan <peng.fan@nxp.com> (imx6ulevk)` only tested with directly run `xtest`

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)`

**Comment by etienne-lms** [comment]
@b49020, about PSCI, the aim is to have a generic PSCI implementation platforms could rely on. ARMTF PSCI library is mature so it is a good candidate. I cannot tell when this work will land in the mainline: ATF dependencies, interactions between PSCI and secure monitor, suspended RAM cases...

**Comment by etienne-lms** [comment]
@jforissier, regarding 2.4.0:
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (b2260, GP)`

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU v7)`

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (FVP)`
with https://github.com/OP-TEE/build/pull/132

**Comment by jbech-linaro** [comment]
```bash
arm-trusted-firmware -- 8b2410c Resolve GCC6.x build errors in MTK8173
build -- 26739bc qemu: fix linux kernel config regarding SDP support
busybox -- dbf5a6d blkdiscard: new applet
evb-utils -- 5494df3 upadte preloader for official ARM-TF
gen_rootfs -- 102d55c Configure loopback device
hello_world -- a2c215b ta:Makefile: Remove 'all' and 'clean' targets
linux -- 961993f ion: unmapped heap support in ion dummy driver **not for mainline**
mtk_tools -- 1460d82 support build ARM-TF from source
optee_client -- 1df4046 ree_fs_new_opendir(): ignore empty directory
optee_os -- 68f38a1 plat-vexpress: move QEMU SDP test memory to end of the secure RAM
optee_test -- 11e1860 GP: do not expect to find non-standard macros in tee_internal_api.h
```

```bash
root@MT8173_EVB:/ xtest -l 15
...
+-----------------------------------------------------
46907 subtests of which 0 failed
75 test cases of which 0 failed
0 test case was skipped
TEE test application done!
root@MT8173_EVB:/
```

`Tested-by: Joakim Bech <joakim.bech@linaro.org>` (MTK8173)

**Comment by lorc** [comment]
Fails on RCAR H3. Board just does not boots up. Refer to #1460 
I'm looking for proper fix.

**Comment by lorc** [comment]
With patches proposed in https://github.com/OP-TEE/optee_os/pull/1462 I was able to run tests:

> 23996 subtests of which 0 failed
> 75 test cases of which 0 failed
> 0 test case was skipped
> TEE test application done!
>

**Comment by b49020** [comment]
Tested-by: Sumit Garg <sumit.garg@nxp.com> (ls1021atwr - Single core)

For multi-core PSCI support is to be added for ls1021atwr in OP-TEE.

24002 subtests of which 0 failed
75 test cases of which 0 failed
0 test case was skipped
TEE test application done!

**Comment by jbech-linaro** [comment]
Thanks @b49020 / Sumit! I'll add that tomorrow to the Changelog, when I'm about to tag everything.

**Comment by sorenb-xlnx** [comment]
`Tested-by: Sören Brinkmann <soren.brinkmann@xilinx.com> (zynqmp)`

23996 subtests of which 0 failed
75 test cases of which 0 failed
0 test case was skipped
TEE test application done!

**Comment by jbech-linaro** [comment]
Thanks @sorenb-xlnx  and @lorc , just as I told Sumit, I'll add your platforms to the Changelog tomorrow.

**Comment by jbech-linaro** [comment]
So, I'm starting to wrap up this release. First, since Jerome created this PR I don't think I can push patches to it (I'll give it a try though using my admin account).

I'm expecting, but I haven't received feedback for:
* RPi3 @igoropaniuk 
* DRA7xx @glneo 

There are quite a few others where I haven't heard anything from the maintainers. The list of tested so far are as follows:
```
d02: extended
hikey: extended
imx-mx6ulevk: standard
ls-ls1021atwr: standard (single core)
mediatek-mt8173: standard
rcar-h3: standard
stm-b2260: extended
vexpress-fvp: standard
vexpress-juno: standard
vexpress-qemu_armv8a: standard
vexpress-qemu_virt: standard
zynqmp-zc1751_dc1: standard
zynqmp-zc1751_dc2: standard
zynqmp-zcu102: standard
```
Please shout load if I've missed any that **has** been tested, but aren't found there.

Also for #1464 (TIAM43xx) we have to wait including that until 2.5.0 I guess, since there is still no reviewed-by tags and we won't have time to do that today.

**Comment by jbech-linaro** [comment]
> I'm expecting, but I haven't received feedback for:
> 
> RPi3 @igoropaniuk

I've just tested RPi3 here on my side (using NFS), so @igoropaniuk you don't have to do it.
```
+-----------------------------------------------------
23997 subtests of which 0 failed
76 test cases of which 0 failed
0 test case was skipped
```

**Comment by igoropaniuk** [comment]
Sorry for the late answer
Extended test case results for RPi3:
```
# ./xtest -l 15
....
+-----------------------------------------------------
46908 subtests of which 0 failed
76 test cases of which 0 failed
0 test case was skipped
TEE test application done!

```

**Comment by glneo** [comment]
DRA7xx looks good:

```
+-----------------------------------------------------
23997 subtests of which 0 failed
76 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```

**Comment by jbech-linaro** [comment]
> DRA7xx looks good:

Thanks Andrew!

**Comment by jbech-linaro** [comment]
All, please check #1475 instead, then I have an RB there I can do the final test build and then finalize the 2.4.0 release.

**Comment by jbech-optee-adm** [comment]
Closing the PR since it was completed in #1475, thanks Jerome for doing the majority of the work here!

**Pull request closed without merging**
