### PR TITLE
core: fix reference counting in tee_tadb_open()

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Fixes reference counting error in tee_tadb_open() that was exposed by
99f969dd6c99 ("core: fine grained tee_ta_mutex locking")

Fixes: 5baee69a0140 ("core: add tadb")
Reported-by: Andrew Davis <andrew.davis@linaro.org>
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey)`

FWIW, although I could not reproduce any crash on HiKey without this patch, I did observe memory leaks (`TEE_ERROR_OUT_OF_MEMORY`) when running `while true; do xtest 1013; done` (it fails after a few loops). This patch does fix the issue.

Please fix the checkpatch warning.

**Comment by jenswi-linaro** [comment]
Checkpatch warning fixed, tag applied.
I was able to recreate the problem on QEMU v7 using:
`-accel tcg,thread=multi -accel tcg -smp 2,sockets=2,cores=2,threads=2,maxcpus=8`
This seems to test races between threads quite well.
I think we should give @glneo a chance to give some feedback too.

**Comment by jforissier** [comment]
> I think we should give @glneo a chance to give some feedback too.

Sure.

**Comment by glneo** [comment]
I'm no longer seeing any lockups, thanks

```
Tested-by: Andrew F. Davis <afd@ti.com>
```

**Comment by jforissier** [comment]
Merged with T-b tag added.

**Pull request closed without merging**
