### PR TITLE
hikey: Add support for UART2

### PR DESCRIPTION
**Pull request by michpappas**
UART2 is console interface provided on the 40-pin Low Speed
Connector in addition to the default UART3.

Signed-off-by: Michalis Pappas <mpappas@fastmail.fm>

### CODE REVIEW

**Comment by michpappas** [comment]
Hi, this is mainly for being able to use the Secure96 mezzanine board on hikey. Secure96 uses UART2, so there's no console output using the default configuration (ie UART3).

**Comment by vchong** [comment]
`Reviewed-by: Victor Chong <victor.chong@linaro.org>`

Will you need to add this for arm-tf and uefi as well?

**Comment by michpappas** [comment]
I just sent a PR for ATF. There are no changes required on edk2; the console's address is passed through OP-TEE/build. I'll leave the PR for changes on OP-TEE/build last, until all dependencies have been approved / merged first.

**Comment by michpappas** [comment]
@vchong added your RB to the commit

**Pull request merged**
