### PR TITLE
RSA algorithm improvements

### PR DESCRIPTION
**Pull request by bogdan-liulko**
1. Can be allowed to use TEE_MODE_SIGN and TEE_MODE_VERIFY with TEE_ALG_RSA_NOPAD
2. Use default salt size for RSA PSS

### CODE REVIEW

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

@bogdan-liulko would you by chance have some test vectors that we could add to `xtest`?

**Comment by jforissier** [comment]
Sorry I'm removing my Ack for the second patch ("core: Set salt size equal to hash size for RSA PSS"), until the following is clarified:
How can `salt_len` be equal to `-1` in `rsassa_sign()`, unless the caller of `TEE_AssymmetricSignDigest()` adds a `TEE_ATTR_RSA_PSS_SALT_LENGTH` parameter with this very value (which is invalid, and should therefore be reported as such, not changed to the default to the hash size)?
The case when salt lenght is not specified is handled here: https://github.com/OP-TEE/optee_os/blob/master/core/tee/tee_svc_cryp.c#L3381 and here: https://github.com/OP-TEE/optee_os/blob/master/core/tee/tee_svc_cryp.c#L3500.
Therefore I think the second patch is incorrect (useless). I am missing something?

**Comment by bogdan-liulko** [comment]
@jforissier, you are right. The second patch is useless. I've been working with old version of optee and there is no default value on reading PSS from parameters. I tried to find out if it has been fixed already, but I didn't notice it.
Talking about tests for the first patch. I use Android CTS for keymaster to test it. I have no my own tests.

**Comment by jforissier** [comment]
@bogdan-liulko thanks for clarifying. So I will take only the first patch. Would you please:
- Remove the Change-Id: tag
- Add a small note saying you have tested with Android CTS for keymaster.
- Add my `Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jforissier** [comment]
First patch cherry-picked and applied on master. Thanks @bogdan-liulko.

**Comment by jforissier** [comment]
@bogdan-liulko I'm curious how you got `TEE_AsymmetricSignDigest()` and `TEE_AsymmetricVerifyDigest()` to work with only patch 1. Did you?

I tried, and I think it's impossible without additional modifications, for many reasons:
-  `TEE_AllocateOperation()` needs to set `operationClass` to `TEE_OPERATION_ASYMMETRIC_SIGNATURE`, or `TEE_AsymmetricSignDigest()` will fail ([here](https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/tee_api_operations.c#L1709-L1711)), and the same for `TEE_AsymmetricVerifyDigest()`.
- `syscall_asymm_operate()` does not allow modes other that encrypt and decrypt ([here](https://github.com/OP-TEE/optee_os/blob/master/core/tee/tee_svc_cryp.c#L3323-L3329))
- `syscall_asymm_verify()` can't get the hash size from the algo when it is `TEE_ALG_RSA_NOPAD` ([here](https://github.com/OP-TEE/optee_os/blob/master/core/tee/tee_svc_cryp.c#L3493)).
- ...

Do you have other patches to make this work? I don't fell good with having only a part of the solution merged. If I can't get the necessary updates I'll just cancel/revert the patch.

[FYI, it's the last time I'm merging crypto patches without an update to xtest showing that the patch works as advertised. My mistake].

**Comment by bogdan-liulko** [comment]
@jforissier, sorry. I have just looked to Android CTS code. Test for unpadded RSA operations only creates operation for unpadded RSA with mode sign or verify. And that's all. Now I see, if it would try to operate it I would see panic. Android documentation says that RSA with no padding must support modes Sign and Verify. That is why I thought it must be covered with tests. But I was wrong. Sorry.

**Comment by jforissier** [comment]
Closing (invalid).

**Pull request closed without merging**
