### PR TITLE
Refactor ta man3

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Replacing what's left of https://github.com/OP-TEE/optee_os/pull/592
Note that I've included the RB-tags from https://github.com/OP-TEE/optee_os/pull/592

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
First 2 commits look good to me.
3rd one moves generic information to arm specific one. As I did not complete the sync in STM prior to this patch yet, this is difficult for me to know if this is not too much.

**Comment by jenswi-linaro** [comment]
@pascal-brand-st-dev take your time, I did this PR to make it clear what's left of the old PR.

**Comment by jenswi-linaro** [comment]
@pascal-brand-st-dev how can we progress?

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jenswi-linaro** [comment]
Rebased and tags applied

**Pull request merged**
