### PR TITLE
stm32mp1: PMIC regulators exposed thru SCMI and minor fixes

### PR DESCRIPTION
**Pull request by etienne-lms**
This P-R is the companion of https://github.com/OP-TEE/optee_os/pull/4134 that introduced SCMI voltage domains.
This P-R allows STM32MP15 boards to expose some PMIC regulators to the non-secure world thorugh SCMI.
It also includes minor fixup commits to clean platform implementation in the SCMI service.

### CODE REVIEW

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by jforissier** [comment]
@etienne-lms can you please squash/rebase and apply the tag?

**Comment by etienne-lms** [comment]
Hi @jforissier. I thought i already posted an comment for this.
We're internally discussing the bindings (commit "plat-stm32mp1: scmi: expose STPMIC1 regulators when secured") so I prefer to stall this P-R until we agree.
I can close the P-R and open a new one once we come to a conclusion if you want.

**Comment by jforissier** [comment]
> We're internally discussing the bindings (commit "plat-stm32mp1: scmi: expose STPMIC1 regulators when secured") so I prefer to stall this P-R until we agree.

That's fine. Don't you want the other commit merged regardless? It looks like they make sense on their own. If so, please open another PR. This one can be closed in any case.

**Comment by etienne-lms** [comment]
Right. I'll keep the generic implementation and remove the one related to bindings.

**Comment by etienne-lms** [comment]
Since you acked all these, i propose to squash a new [fixup commit](https://github.com/OP-TEE/optee_os/pull/4146/commits/506fb73705803dde837af071a877bd91697ec049) that reverts some of my change.
If you agree, I can squash, apply your review tag and make it ready for merge.

**Comment by jforissier** [comment]
OK

**Comment by etienne-lms** [comment]
squashed, tag applied.

**Comment by etienne-lms** [comment]
thanks

**Pull request merged**
