### PR TITLE
Fix comment in tee_ree_fs.c

### PR DESCRIPTION
**Pull request by wellsleep**
correct the file layout comment in the file. add some comments for better understanding.
 issue #1894

### CODE REVIEW

**Comment by jforissier** [comment]
Thanks @wellsleep , can you please change the commit subject to "Fix comment in tee_ree_fs.c" (no need for more details in the commit message), and add your `Signed-off-by:`? (see third bullet at https://github.com/OP-TEE/optee_os/blob/master/documentation/github.md#contributing-1).
You should use `git push -f` to force-push a single patch to this PR.

**Comment by wellsleep** [comment]
It's my first time to PR a public repo. Thanks for your help. @jforissier

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
@wellsleep thank you, last step is to add the Reviewed-by: tag given by @jenswi-linaro, and to squash/rebase into one single commit. Then I can merge.

**Comment by jforissier** [comment]
Thanks @wellsleep.

**Pull request merged**
