### PR TITLE
Import mbedtls 2.6.1

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Imports mbedtls 2.6.1 on a special import branch

### CODE REVIEW

**Comment by jforissier** [comment]
LGTM.
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

I think we need to document this new way of working with imported libraries. I will propose something to be added to `documentation/`.

**Comment by jforissier** [comment]
Ah, one question I forgot to ask: why 2.6.1? Latest seems to be 2.9.0.

**Comment by jenswi-linaro** [comment]
> Ah, one question I forgot to ask: why 2.6.1? Latest seems to be 2.9.0.

It seems there has been some releases since this work was started

> I think we need to document this new way of working with imported libraries. I will propose something to be added to `documentation/`.

Sounds good, I was thinking of the same. I was just going to wait a little to have it tried first.

**Comment by jenswi-linaro** [comment]
Should I update to 2.9.0 or should we take that in next step, just to see that the process seems to work as intended? Looking at the dates of the tags, 2.6.1 isn't ancient it's just that a lot of releases has been pushed out lately.

**Comment by jforissier** [comment]
> Should I update to 2.9.0 or should we take that in next step [...]

Up to you. I'm fine with both ways.

**Comment by jenswi-linaro** [comment]
OK, let's keep it as it is.

**Comment by jenswi-linaro** [comment]
Tag applied

**Comment by jforissier** [comment]
@jenswi-linaro it looks like we forgot two things:
- Exclude `lib/libmbedtls` in `scripts/checkpatch_inc.sh` 
- Reformat the SPDX identifiers to follow https://github.com/OP-TEE/optee_os/blob/master/documentation/copyright_and_license_headers.rst#pre-existing-or-imported-files

**Comment by jenswi-linaro** [comment]
Sorry, I'll fix that in new pull requests

**Comment by jenswi-linaro** [comment]
For license headers https://github.com/OP-TEE/optee_os/pull/2344

**Comment by jenswi-linaro** [comment]
`lib/libmbedtls` is excluded in `scripts/checkpatch_inc.sh`, done in
66666258c64d ("checkpatch_inc.sh: ignore lib/libmbedtls")

**Comment by jforissier** [comment]
> For license headers #2344

Thanks

> `lib/libmbedtls` is excluded in `scripts/checkpatch_inc.sh`, done in
6666625 ("checkpatch_inc.sh: ignore lib/libmbedtls")

Right, that's good. Having it in this PR would have allowed CI to complete successfully although we don't care much since it's just the import branch.

**Pull request merged**
