### PR TITLE
Misc

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Some small changes preparing for Trusted UI

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
`session_is_cancelled` used to be a generic function, not a arm-specific one.

**Comment by jenswi-linaro** [comment]
Yes, but I don't know where else to put it. It relates closely to the other functions in `core/arch/arm/kernel/tee_ta_manager.c`, that entire file is almost architecture neutral now. It looks like it's only `tee_ta_verify_param()` that is questionable unless I'm missing something. Perhaps it's time to move `tee_ta_manager.c` out of `arch/arm`

**Comment by pascal-brand-st-dev** [comment]
Yes, I think so. Is it an issue to move `tee_ta_manager.c` out of `arch/arm` before this pull-request?
Can you work on it, or do you want me to work on it?

**Comment by jenswi-linaro** [comment]
I can work on it.

**Comment by jenswi-linaro** [comment]
https://github.com/OP-TEE/optee_os/pull/769 created

**Comment by jenswi-linaro** [comment]
I'll rebase this when we're done with https://github.com/OP-TEE/optee_os/pull/769

**Comment by jenswi-linaro** [comment]
Rebased.

**Comment by pascal-brand-st-dev** [comment]
`Reviewed-by: Pascal Brand <pascal.brand@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tag applied

**Pull request merged**
