### PR TITLE
plat-mediatek: add support for MT8175 SoC

### PR DESCRIPTION
**Pull request by Fabo**
Add OP-TEE support for MT8175 SoC.

Signed-off-by: Fabien Parent <fparent@baylibre.com>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Looks good. Would you mind adding something to the documentation about the Mediatek platforms, and about MT8175 in particular?
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by Fabo** [comment]
> Looks good. Would you mind adding something to the documentation about the Mediatek platforms, and about MT8175 in particular?

Sure

**Comment by jforissier** [comment]
@Fabo please rebase onto master and add Jens' tag then I will merge this. Thanks.

**Comment by Fabo** [comment]
> @Fabo please rebase onto master and add Jens' tag then I will merge this. Thanks.

Done. Thanks

**Pull request merged**
