### PR TITLE
Multiple fixes CAAM and Crypto driver

### PR DESCRIPTION
**Pull request by clementfaure**
Hello!

This patch set:
- Fixes suspend/resume issue in the CAAM driver.
- Fixes compilation warning in CAAM driver.
- Fixes compilation error and warning in crypto driver introduced in the recent RSA pull-request (my bad ...)

Thanks!

### CODE REVIEW

**Comment by jforissier** [comment]
> Fixes compilation error and warning in crypto driver introduced in the recent RSA pull-request (my bad ...)

Is there a way we could improve the CI coverage for your use case? If so, please do not hesitate to propose changes to `.shippable.yml`.

**Comment by clementfaure** [comment]
Good idea, so we can avoid doing mistakes like I did during the review of the RSA ..
I will add the compilation of few imx platforms but with `CFG_NXP_CAAM=y`.
We should have a 100% coverage of the CAAM driver code by adding the compilation of
- mx6ulevk
- mx6sxsabresd
- mx6qsabreauto
- mx7dsabresd
- mx7ulpevk
- mx8mmevk

I will add the `.shippable` patch to this PR

**Comment by jforissier** [comment]
For the fixes:
`Acked-by: Jerome Forissier <jerome@forissier.org>`

One minor thing though: one should normally not wrap compiler messages. They should not trigger checkpatch warnings.

**Comment by clementfaure** [comment]
> One minor thing though: one should normally not wrap compiler messages. They should not trigger checkpatch warnings.

Alright, I will do better next time

**Comment by clementfaure** [comment]
@jforissier Are you OK with the `.shippable.yml` patch?

**Comment by jforissier** [comment]
> @jforissier Are you OK with the `.shippable.yml` patch?

Yes:
`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by clementfaure** [comment]
@jforissier Thanks!
Tag applied

**Pull request merged**
