### PR TITLE
symbolize.py: translate TA panic codes

### PR DESCRIPTION
**Pull request by jforissier**
When a TA panics, the TEE core shows the panic code as follows:

 E/TC:? 0 TA panicked with code 0xffff000f

The value is whatever was passed to TEE_Panic() by the TA or the library
that caused the panic; typically, the TEE Intenal Core API functions
implemented in libutee. It quite often happens that this value is a
TEE_Result code. Therefore it is convenient to translate the hexadecimal
value to a symbolic name (TEE_ERROR_*). With this commit, if a match is
found, the name is shown in parentheses like so:

 E/TC:? 0 TA panicked with code 0xffff000f (TEE_ERROR_SECURITY)

If the code doesn't correspond to a known TEE_Result value however
nothing is appended to the output.

Suggested-by: Peter Griffin <peter.griffin@linaro.org>
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
CC @petegriffin

**Comment by petegriffin** [comment]
IMO that is a very helpful additional feature to the script :) As I often find myself having to grep what the error code is not being a every day optee developer.

Acked-by: Peter Griffin <peter.griffin@linaro.org>

**Comment by jenswi-linaro** [comment]
Nice. We could perhaps decode ESR too? Example https://esr.arm64.dev/?#0x623a0400

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
> Nice. We could perhaps decode ESR too? Example https://esr.arm64.dev/?#0x623a0400

Good idea, ESR is quite painful to decode manually. I'm adding that to my to-do list :)

**Pull request merged**
