### PR TITLE
core: user_ta: fix missing dereference of freed EXIDX memory

### PR DESCRIPTION
**Pull request by etienne-lms**

### CODE REVIEW

**Comment by etienne-lms** [comment]
Updated with a commit description.

**Comment by etienne-lms** [comment]
Jens synthesized it the best. 

Reproducing: it occurs when running `xtest 1006`  on very constraint RAM (i.e pager + high log level). I reproduced it (obviously on a arm32 arch) with around 20kB of heap. An init session in `xtest 1006` runs out of heap in `set_exidx()`: [`alloc_ta_mem(exidx_sz)` /line 914/](https://github.com/OP-TEE/optee_os/pull/2572/files#diff-c652d2fb2b5ee316c89da6b1697ff8bcR914) succeeds, a mobj is allocated, but [`vm_map()`/line 917/](https://github.com/OP-TEE/optee_os/pull/2572/files#diff-c652d2fb2b5ee316c89da6b1697ff8bcR917) runs out of heap, hence `goto err;` and call to `mobj_free()` without nullifying `utc->mobj_exidx`. 

Note: TAs can run into the issue even if they have no exception index tables but at least 2 elf segments (xtest 1006 case).
where there are several elf segments, `set_exidx()` accumulates (a zeroed) exception index table size `exidx_size` [/line 912/](https://github.com/OP-TEE/optee_os/pull/2572/files#diff-c652d2fb2b5ee316c89da6b1697ff8bcR912) and we go through `alloc_ta_mem()`, `vm_map()` and the loop below with null sized references. I saw no bug in the sequence (but the fixed `mobj_free()`). It happedn that even if the map area is null, the entry of `vm_map()`  allocates a `struct vm_region`. It is this allocation out of heap in the description above.

Note again: regarding the sequence, since `exidx_size` is `0` [at at line 912](https://github.com/OP-TEE/optee_os/pull/2572/files#diff-c652d2fb2b5ee316c89da6b1697ff8bcR912), I wonder if we should better set `utc->exidx_start = NULL; utc->exidx_size = 0;` and `return TEE_SUCCESS;` instead of calling `alloc_ta_mem()`.

**Comment by jforissier** [comment]
@jenswi-linaro @etienne-lms thanks for the detailed explanations, now I got it. I think the fix you're proposing is perfectly fine, and I would suggest we do any optimization for the no-exception table case in a later patch.
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jforissier** [comment]
@etienne-lms BTW I don't think dereference is used properly in the commit subject; how about `core: user_ta: set freed EXIDX pointer to NULL`?

**Comment by etienne-lms** [comment]
commit comment updated. tag applied.

**Pull request merged**
