### PR TITLE
Secshm fix

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Fixes https://github.com/OP-TEE/optee_os/issues/1323 (hopefully)

### CODE REVIEW

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey/pager)`

**Comment by etienne-lms** [comment]
Sorry for this late feedback but i faced an issue and tested over and over to make sure it did not come from my setup: GP tests 8040 is successful but test 1006 (Test Basic OS features) fails: core panics in in "test_mem_access_right": translation fault in `flush_ctx_range_from_list()`. Jerome, could you check on your side ?

Actually almost all tests are OK (standard & GP), but 1006 and some GP 9xxx (at least 9083) do panic in core due to translation faults.

**Comment by jforissier** [comment]
@etienne-lms all good here on HiKey...
```
INFO:    TEE-CORE: Pager is enabled. Hashes: 960 bytes
INFO:    TEE-CORE: Initializing (2.3.0-36-g61b1868 #1 Tue Feb  7 14:59:19 UTC 2017 arm)
INFO:    TEE-CORE: Initialized
[...]
root@HiKey:/ xtest 1006 8040 9083
[...]
regression_1006 OK
regression_8040 OK
regression_9083 OK
+-----------------------------------------------------
38 subtests of which 0 failed
3 test cases of which 0 failed
712 test cases was skipped
TEE test application done!
```

**Comment by etienne-lms** [comment]
gosh, i must dig a bit to understand what's happening...

**Comment by etienne-lms** [comment]
Hi, I reproduce the core panic described above on qemu_virt with `CFG_WITH_PAGER=y`.
Panic occurs when `pgt_flush_ctx_range()` calls `flush_ctx_range_from_list()` on `pgt_cache_list`.

Issue seems fixed with patch below. I don't really catch the first loop in this routine. It seems it empties the `pgt_cache_list` before second loop is reached.

```
static void flush_ctx_range_from_list(struct pgt_cache *pgt_cache, void *ctx,
				      vaddr_t begin, vaddr_t last)
{
	struct pgt *p;
	struct pgt *next_p;

	p = SLIST_FIRST(pgt_cache);
	while (pgt_entry_matches(p, ctx, begin, last)) {
		flush_pgt_entry(p);
		SLIST_REMOVE_HEAD(pgt_cache, link);
		push_to_free_list(p);
		p = SLIST_FIRST(pgt_cache);
	}

	p = SLIST_FIRST(pgt_cache);
+	if (!p)
+		return;
	while (true) {
		next_p = SLIST_NEXT(p, link);
		if (!next_p)
			break;
		if (pgt_entry_matches(next_p, ctx, begin, last)) {
			flush_pgt_entry(next_p);
			SLIST_REMOVE_AFTER(p, link);
			push_to_free_list(next_p);
			continue;
		}

		p = SLIST_NEXT(p, link);
	}
}
```

**Comment by jenswi-linaro** [comment]
Thanks @etienne-lms . Since it's a singly linked list the parent pointer is needed to remove the element, this makes the first entry in the list a special case which is dealt with in the first loop. I'll push a patch based in this.

**Comment by jenswi-linaro** [comment]
Update

**Comment by etienne-lms** [comment]
@jenswi-linaro, thanks for the explanation. crystal clear.

**Comment by jenswi-linaro** [comment]
Update

**Comment by jforissier** [comment]
@etienne-lms on HiKey 9068 is OK but it's GP test 9122 that is failing (commit 6700f38):
```
* regression_9122 50-03-6c
ERROR:   TEE-CORE: 
ERROR:   TEE-CORE: user TA data-abort at address 0xffffdeb1 (alignment fault)
ERROR:   TEE-CORE:  fsr 0x00000001  ttbr0 0x3f01506a  ttbr1 0x3f01006a  cidr 0x1
ERROR:   TEE-CORE:  cpu #2          cpsr 0x20000030
ERROR:   TEE-CORE:  r0 0xffffdead      r4 0x00100f90    r8 0x00115ba0   r12 0x00100fb8
ERROR:   TEE-CORE:  r1 0x00200000      r5 0xffffdead    r9 0x00010012    sp 0x00100f00
ERROR:   TEE-CORE:  r2 0x00000020      r6 0x00100fb8   r10 0x3f046f64    lr 0x00101729
ERROR:   TEE-CORE:  r3 0x00000040      r7 0x00000000   r11 0x3f00eee8    pc 0x00104244
ERROR:   TEE-CORE: Status of TA 534d4152-5443-534c-5443-525950544f31 (0x3f00eff8) (active)
ERROR:   TEE-CORE: - load addr : 0x101000    ctx-idr: 1
ERROR:   TEE-CORE: - stack: 0x100000 4096
ERROR:   TEE-CORE: sect 0 : va 0x100000 pa 0 0x1000
ERROR:   TEE-CORE: sect 1 : va 0x101000 pa 0 0x9000
ERROR:   TEE-CORE: sect 2 : va 0x10a000 pa 0 0x2000
ERROR:   TEE-CORE: sect 3 : va 0x10c000 pa 0 0xb000
ERROR:   TEE-CORE: 
ERROR:   TEE-CORE: core prefetch-abort at address 0x3f029ca0 (translation fault)
ERROR:   TEE-CORE:  fsr 0x00000007  ttbr0 0x3f01506a  ttbr1 0x3f01006a  cidr 0x1
ERROR:   TEE-CORE:  cpu #2          cpsr 0x600001b7
ERROR:   TEE-CORE:  r0 0x3f00f1f8      r4 0x00000004    r8 0x00000000   r12 0x3f029ca1
ERROR:   TEE-CORE:  r1 0x00001000      r5 0x3f00eea0    r9 0x00010012    sp 0x3f018d58
ERROR:   TEE-CORE:  r2 0x00000000      r6 0x00000014   r10 0x3f046f64    lr 0x3f001220
ERROR:   TEE-CORE:  r3 0x3f018e14      r7 0x3f006b79   r11 0x3f00eee8    pc 0x3f029ca0
ERROR:   TEE-CORE: Panic
```
Tried setting CFG_TEE_CORE_DEBUG=y to get a backtrace but then it's OK:
```
* regression_9122 50-03-6c
ERROR:   TEE-CORE: 
ERROR:   TEE-CORE: user TA data-abort at address 0xffffdeb1 (alignment fault)
ERROR:   TEE-CORE:  fsr 0x00000001  ttbr0 0x3f01906a  ttbr1 0x3f01406a  cidr 0x1
ERROR:   TEE-CORE:  cpu #4          cpsr 0x20000030
ERROR:   TEE-CORE:  r0 0xffffdead      r4 0x00100f90    r8 0x00115ba0   r12 0x00100fb8
ERROR:   TEE-CORE:  r1 0x00200000      r5 0xffffdead    r9 0x00010012    sp 0x00100f00
ERROR:   TEE-CORE:  r2 0x00000020      r6 0x00100fb8   r10 0x3f04cf64    lr 0x00101729
ERROR:   TEE-CORE:  r3 0x00000040      r7 0x00000000   r11 0x3f012f68    pc 0x00104244
ERROR:   TEE-CORE: Status of TA 534d4152-5443-534c-5443-525950544f31 (0x3f013078) (active)
ERROR:   TEE-CORE: - load addr : 0x101000    ctx-idr: 1
ERROR:   TEE-CORE: - stack: 0x100000 4096
ERROR:   TEE-CORE: sect 0 : va 0x100000 pa 0 0x1000
ERROR:   TEE-CORE: sect 1 : va 0x101000 pa 0 0x9000
ERROR:   TEE-CORE: sect 2 : va 0x10a000 pa 0 0x2000
ERROR:   TEE-CORE: sect 3 : va 0x10c000 pa 0 0xb000
ERROR:   TEE-CORE: sect 4 : va 0x200000 pa 0x3ee01000 0x1000
ERROR:   TEE-CORE: sect 5 : va 0 pa 0 0
ERROR:   TEE-CORE: sect 6 : va 0 pa 0 0
ERROR:   TEE-CORE: sect 7 : va 0 pa 0 0
  regression_9122 OK
```

Same situation with parent commit (61b1868), but OK on master (928468c), with or without CFG_TEE_CORE_DEBUG.

**Comment by jforissier** [comment]
Hmmmm...
`core/arch/arm/kernel/link.mk` has `entries-unpaged += mobj_phys_get_pa` but `mobj_phys_get_pa` is in section `.text_pageable`:
```
$ grep mobj_phys_get_pa out/arm-plat-hikey/core/tee.dmp | head -1
3f029ca0 l     F .text_pageable	00000028 mobj_phys_get_pa
```
That's unexpected, isn't it?

**Comment by jenswi-linaro** [comment]
Aha, that's it. Yes, unexpected.

**Comment by jenswi-linaro** [comment]
Hmm, perhaps this is because those two functions are static?

**Comment by etienne-lms** [comment]
can't we use `KEEP_PAGER()` for the routines loaded in the several `struct mobj_ops`?
From build tests, it works ok.

**Comment by jenswi-linaro** [comment]
We should use them, unfortunately the AArch64 linker asserts on something then. But surrounding the `KEEP_PAGER()` with `#ifndef ARM64` or something could be a temporary workaround.

**Comment by etienne-lms** [comment]
What would be the diff with, for example `user_ta_dump_state()` that seems to be used in the same scope: `static` routine, stored in a `__unpaged_rodata` structure, and registered through `KEEP_PAGER()` ?

**Comment by jforissier** [comment]
Both options work for me (making the two functions static, or using `KEEP_PAGER()` instead of `entries-unpaged`).

Since pager is not supported with AArch64, I wouldn't mind adding `#ifndef ARM64` directly in the definition of `KEEP_PAGER()` (with the proper comment of course). Who knows, by the time we choose to enable pager on AArch64, the toolchain may be fixed (might be the case with GCC6.2 already?)

**Comment by jenswi-linaro** [comment]
You mean what's the difference in the ELF? Last time I looked at it the linker was unhappy with some index in the ELF. Since KEEP_PAGER sometime works and sometimes doesn't I guess it's just some bug in the linker. If we could make an isolated case highlighting the problem we could probably get some toolchain guy to try to fix it.

**Comment by jenswi-linaro** [comment]
Update

**Comment by jforissier** [comment]
For "core: arm: pager: bugfix linking": please note: `s/iwth/with/` in the commit message, other than that:
```
Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>
Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey)
```

This commit passes the whole xtest suite with GP on HiKey (with pager enabled of course).

**Comment by etienne-lms** [comment]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (qemu_virt, b2260, GP)`

**Comment by jenswi-linaro** [comment]
Rebased, squashed, tags applied.
Note that I modified the test-by tags a little to better reflect what (I assume in Etienne's case) was tested.

**Comment by etienne-lms** [comment]
@jenswi-linaro, feel free to do so.
note that it tends to make long commit comment lines...

minor: I think the "tested-by" tags could apply to each of these commits.
actually, several unrelated (but pager related) issues were fixed.

**Comment by jforissier** [comment]
@etienne-lms about the long lines due to T-b: you're right it's a bit annoying. We should try to shorten them, possibly by using several lines when several platforms are tested (that may help a bit). But, in any case it is not a big issue, let's just let Travis complain and ignore it ;)

About which commit to apply the T-b: again you're mostly right, in principle T-b means that a particular commit does fix an issue or adds a feature, and that this fact was verified by the tester. In contrast, the T-b I have given is more like "at this point in the commit history, *all* regression tests pass" (i.e., it's not just testing the feature/bugfix introduced by that very commit). For this meaning, I think it's best to add the tag to the latest commit, the closest to the code that was actually tested. Now it's true that there is some ambiguity...

**Comment by jenswi-linaro** [comment]
Rebased

**Pull request merged**
