### PR TITLE
MAINTAINERS: update etienne's e-mail address

### PR DESCRIPTION
**Pull request by etienne-lms**
Updates etienne-lms e-mail address.

### CODE REVIEW

**Review by jforissier — APPROVED** [review]
```
Signed-off-by: Etienne Carriere <etienne.carriere@foss.st.com>
Signed-off-by: Etienne Carriere <etienne.carriere@linaro>
```
I think the first sign-off is enough.
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by etienne-lms** [comment]
Removed 2nd S-o-b tag and applied review tag.

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
review tag applied.
thanks.

**Pull request merged**
