### PR TITLE
imx8qm: configure for virtualization support

### PR DESCRIPTION
**Pull request by lorc**
This PR contains various patches, mostly for core/arm/plat-imx to enable virtualization support on iMX8QM SOC. 

This PR was tested on iMXQ8QM MEK-like board.

OP-TEE core maintainers would be interested in patch to interrupt.c. I believe, this fixes issue with virtualization porting to Raspberry platform.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jenswi-linaro** [comment]
Please fix the checkpatch error.

**Comment by jforissier** [comment]
@jbech-linaro @jenswi-linaro should we temporarily disable CFG_LOCKDEP in IBART? This is about the error:
```
  2670:  E/TC:3 0 unw_get_kernel_stack:170 Out of memory
  2671:  E/TC:3 0 lockdep_lock_acquire:88 lockdep: error 0xffff000c
  2672:  E/TC:3 0 Panic at core/include/kernel/lockdep.h:89 <lockdep_lock_acquire>
```
My understanding of the issue is, heap usage has slowly been increasing in OP-TEE as new features were added, and now HiKey620 can't handle it with pager etc. and lockdep enabled. Lockdep uses quite a bit of memory because it records call stacks whenever a mutex is taken or released. Not normally an issue because it is a debugging thing, can be enabled with specific configurations etc. but here it is a problem obviously.

Here is what I propose:
- We temporarily disable lockdep in IBART
- I propose a PR to disable call stack recording in lockdep (the tool would still detect potential deadlocks but print less detailed information)
- We re-enable lockdep in IBART without call stacks

What do you think?

(@lorc sorry for hijacking the discussion :wink:)

**Comment by jbech-linaro** [comment]
> * We temporarily disable lockdep in IBART
> * I propose a PR to disable call stack recording in lockdep (the tool would still detect potential deadlocks but print less detailed information)
> * We re-enable lockdep in IBART without call stacks

Fine with me, let me know **when** you want to have it disabled.

**Comment by jenswi-linaro** [comment]
Sounds like a good plan.

**Comment by jforissier** [comment]
> Fine with me, let me know **when** you want to have it disabled.

Well, ASAP... (so that people currently working on PRs can have meaningful test results). Thanks!

**Comment by jbech-linaro** [comment]
> Well, ASAP... (so that people currently working on PRs can have meaningful test results). Thanks!

Done! I've just changed it locally, didn't commit, since it's a temporary thing. But hopefully all flags should be seen at the top of the build (even though I know there has been issues with that).

```diff
$ git diff
diff --git a/jobdefs/examples/hikey6220.yaml b/jobdefs/examples/hikey6220.yaml
index 3ce662a..56cac07 100644
--- a/jobdefs/examples/hikey6220.yaml
+++ b/jobdefs/examples/hikey6220.yaml
@@ -35,7 +35,7 @@ pre_build:
 
 build:
         # Default flags
-        - cmd: make -j8 CFG_DRAM_SIZE_GB=1 CFG_FLASH_SIZE=4 CFG_RPMB_WRITE_KEY=y CFG_RPMB_FS=y CFG_SECURE_DATA_PATH=y CFG_WITH_PAGER=y CFG_TEE_CORE_LOG_LEVEL=2 CFG_LOCKDEP=y CFG_CORE_MBEDTLS_MPI=y CFG_ENCRYPT_TA=y
+        - cmd: make -j8 CFG_DRAM_SIZE_GB=1 CFG_FLASH_SIZE=4 CFG_RPMB_WRITE_KEY=y CFG_RPMB_FS=y CFG_SECURE_DATA_PATH=y CFG_WITH_PAGER=y CFG_TEE_CORE_LOG_LEVEL=2 CFG_LOCKDEP=n CFG_CORE_MBEDTLS_MPI=y CFG_ENCRYPT_TA=y
           timeout: 1500
 
 pre_flash:
```

**Comment by lorc** [comment]
Thank you for review. I'll fix the checkpatch error and prepare PR for merge bit later, after I'll finish my current project activity.

**Comment by jforissier** [comment]
@jbech-linaro now that https://github.com/OP-TEE/optee_os/pull/3728 is merged, could you please add `CFG_LOCKDEP=y `**`CFG_LOCKDEP_RECORD_STACK=n`** to the IBART build?

**Comment by jbech-linaro** [comment]
> @jbech-linaro now that #3728 is merged, could you please add `CFG_LOCKDEP=y `**`CFG_LOCKDEP_RECORD_STACK=n`** to the IBART build?

Done, current command line.
```bash
make -j8 CFG_DRAM_SIZE_GB=1 CFG_FLASH_SIZE=4 CFG_RPMB_WRITE_KEY=y CFG_RPMB_FS=y CFG_SECURE_DATA_PATH=y CFG_WITH_PAGER=y CFG_TEE_CORE_LOG_LEVEL=2 CFG_LOCKDEP=y CFG_LOCKDEP_RECORD_STACK=n CFG_CORE_MBEDTLS_MPI=y CFG_ENCRYPT_TA=y
```

Only the Hikey build have this. Lockdep for the QEMU build isn't relevant? I..e, good to have it enabled on one and disabled on another.

**Comment by jforissier** [comment]
> Only the Hikey build have this. Lockdep for the QEMU build isn't relevant? I..e, good to have it enabled on one and disabled on another.

IBART is still failing on HiKey with `CFG_LOCKDEP=y CFG_LOCKDEP_RECORD_STACK=n` :cry: let's disable lockdep on HiKey and enable it on QEMU instead, OK? (I have tried, it works fine).

**Comment by jbech-linaro** [comment]
> > Only the Hikey build have this. Lockdep for the QEMU build isn't relevant? I..e, good to have it enabled on one and disabled on another.
> 
> IBART is still failing on HiKey with `CFG_LOCKDEP=y CFG_LOCKDEP_RECORD_STACK=n`  let's disable lockdep on HiKey and enable it on QEMU instead, OK? (I have tried, it works fine).

Ok, current configs are now:
```bash
$ grep "make -j8" *.yaml
01-hikey6220.yaml:        - cmd: make -j8 CFG_DRAM_SIZE_GB=1 CFG_FLASH_SIZE=4 CFG_RPMB_WRITE_KEY=y CFG_RPMB_FS=y CFG_SECURE_DATA_PATH=y CFG_WITH_PAGER=y CFG_TEE_CORE_LOG_LEVEL=2 CFG_LOCKDEP=n CFG_LOCKDEP_RECORD_STACK=n CFG_CORE_MBEDTLS_MPI=y CFG_ENCRYPT_TA=y
02-qemu-v7.yaml:        - cmd: make -j8 CFG_LOCKDEP=y CFG_LOCKDEP_RECORD_STACK=n
```
I guess this is what you're suggesting? You can re-run the relevant jobs in the IBART-interface to see if things are working.

**Comment by jforissier** [comment]
@jbech-linaro looks good, now the failure is because this PR needs rebasing.
For simplicity, you could remove `CFG_LOCKDEP=n CFG_LOCKDEP_RECORD_STACK=n` on HiKey, since disabled is the default setting.
Thanks!

**Comment by jbech-linaro** [comment]
> For simplicity, you could remove `CFG_LOCKDEP=n CFG_LOCKDEP_RECORD_STACK=n` on HiKey, since disabled is the default setting.

Done!

**Comment by lorc** [comment]
Addressed the checkpatch warnings.

**Comment by jforissier** [comment]
- For "core: move static IRQC data to nexus memory":
`Acked-by: Jerome Forissier <jerome@forissier.org>`
- `s/ixm/imx/` in the last patch

For the `plat-imx` patches, could we have some feedback from i.MX reviewers please? @OP-TEE/plat-imx @MrVan @cneveux @sdininno @clementfaure @bryanodonoghue Thanks!

**Comment by lorc** [comment]
Updated tags. 
@jenswi-linaro, is your Acked-by tag for certain commit or for the whole series?

**Comment by jenswi-linaro** [comment]
@lorc, it is for the whole series.

**Comment by MrVan** [comment]
@lorc wow! Is this patchset runs on XEN on i.MX8QM? with Dual Linux OSes using OP-TEE?

**Comment by lorc** [comment]
@MrVan,

> @lorc wow! Is this patchset runs on XEN on i.MX8QM? with Dual Linux OSes using OP-TEE?

Yep. We made it working :) Actually, this patch is all what you need. But, CAAM will not work in this case, of course.

@jenswi-linaro, thanks. I added your tag to all patches.

**Comment by MrVan** [comment]
@lorc Just wonder, have you ever also managed Trusty working also?
Anyway great done on the OP-TEE part. `Acked-by: Peng Fan <peng.fan@nxp.com>`

**Comment by lorc** [comment]
> @lorc Just wonder, have you ever also managed Trusty working also?

No, we never tried it. It seems that Android is happy with OP-TEE, so there is no need to use Trusty.

> Anyway great done on the OP-TEE part. Acked-by: Peng Fan <peng.fan@nxp.com>
Thanks. Added your tag as well.

**Pull request merged**
