### PR TITLE
ta: pkcs11: remove unnecessary code

### PR DESCRIPTION
**Pull request by ldts**
Remove unecessary assignment.

Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

### CODE REVIEW

**Comment by etienne-lms** [comment]
checkpatch report:
```
>> checkpatch ffb89655e8849909ce92158eda01f2bee5fbf14b
ffb89655 ta: pkcs11: remove unncessary code
WARNING: 'unecessary' may be misspelled - perhaps 'unnecessary'?
#6: 
Remove unecessary assignment.
       ^^^^^^^^^^
```
With that fixed: 
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`.

**Comment by ldts** [comment]
um thanks (sorry, should have checked). btw does PKCS11 store all created keys in memory after creation?  I am running out of space after creating 15 keys (TEE_Realloc fails in tee2pkcs_add_attribute)....shouldnt it just write the keys to storage and free the memory?

**Comment by etienne-lms** [comment]
You should set `CFG_PKCS11_TA_HEAP_SIZE` to the targeted size. Default is 16kB, not much. We could grow a bit. Enough to pass `xtest`.

**Comment by etienne-lms** [comment]
> btw does the PKCS#11 TA implementation store all created keys in volatile memory after creation?

Yes it does. As soon has a persistent object is exposed once to client, it remains in volatile memory (unless it's destroyed of course). There is room for improvement here, to relax memory pressure.

**Comment by ldts** [comment]
> You should set `CFG_PKCS11_TA_HEAP_SIZE` to the targeted size. Default is 16kB, not much. We could grow a bit. Enough to pass `xtest`.

thanks

**Comment by ldts** [comment]
@jforissier is anything else pending on this? just cleaning up my repos before vacation

**Comment by jforissier** [comment]
@ldts no this can be merged I just missed it ;-)

**Pull request merged**
