### PR TITLE
arm: Update SHA-256 32-bit CE implementation to process multiple blocks

### PR DESCRIPTION
**Pull request by jforissier**
~~The first two commits are from https://github.com/OP-TEE/optee_os/pull/418 so please focus on the last one.~~ Edit: PR rebased on latest master.

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
I'm a little bit confused with this PR. Is it possible to push #418, and then have #421, before checking this one?

**Comment by jforissier** [comment]
@pascal-brand-st-dev no problem, I'll rebase once #418 and #421 are merged. Basically, only the last commit will remain.

**Comment by jforissier** [comment]
Rebased on top of master.

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jforissier** [comment]
Review tags applied.

**Pull request merged**
