### PR TITLE
AES using ARMv8-A Cryptographic Extensions (AArch32)

### PR DESCRIPTION
**Pull request by jforissier**
Adds the missing code to provide AES acceleration to 32-bit builds of OP-TEE.

### CODE REVIEW

**Comment by d3zd3z** [comment]
What platform are you testing this on? Does qemu support these instructions?

**Comment by jforissier** [comment]
I'm testing on HiKey primarily. It works fine on D02 too. I don't think that QEMU supports these instructions. Just try to force `CFG_AES_ARM32_CE` and you will see, I bet you'll get an undefined instructions abort.

**Comment by jforissier** [comment]
Sorry I meant `CFG_CRYPTO_AES_ARM32_CE=y`.

**Comment by jforissier** [comment]
Wait! I think was wrong... It looks like QEMU *does* emulate the AES instructions in both the AArch32 and AArch64 states: http://git.qemu.org/?p=qemu.git&a=search&h=HEAD&st=grep&s=ARM_FEATURE_V8_AES

Same for SHA1/SHA256: http://git.qemu.org/?p=qemu.git&a=search&h=HEAD&st=grep&s=ARM_FEATURE_V8_SHA

@d3zd3z would you try adding `CFG_CRYPTO_WITH_CE ?= y` in this block of code: https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-vexpress/conf.mk#L60-L65 and see how `xtest` runs?

**Comment by d3zd3z** [comment]
Initial test shows it failing to boot at all with `CFG_CRYPTO_WITH_CE` enabled. I'll continue investigating.

```
ERROR:   TEE-CORE: undef-abort at 0x7df00b80
FSR 0x0 PC 0x7df00b80 TTBR0 0x7DF4006A CONTEXIDR 0x0
CPUID 0x80000000 CPSR 0x1d3 (read from SPSR)
ERROR:   TEE-CORE: [abort] undefined abort (trap CPU)
ERROR:   TEE-CORE: PANIC: get_fault_type core/arch/arm/kernel/abort.c:507
```

**Comment by d3zd3z** [comment]
The problem seems to be that there aren't any V8 CPUs available to pick when running Aarch32 mode. So, this does fail expectedly.

**Comment by jforissier** [comment]
Ah, right, `qemu_virt` is ARMv7. Maybe build with `PLATFORM=vexpress-qemu_armv8a` (for 32 bits) and `PLATFORM=vexpress-qemu_armv8a CFG_ARM64_core=y` (for 64 bits) would work? With `qemu-system-aarch64` that is.

**Comment by d3zd3z** [comment]
Trying to run with an a53, fails to boot (nothing ever prints anything), I'm guessing it is starting in 64-bit mode, and we'd at least have to make some change to be able to run in 32-bit mode on a v8 CPU. Running the a15 emulator on aarch64's emulator does work, though.

But, trying to test the 32-bit crypto code in Qemu is probably a little challenging.

**Comment by jforissier** [comment]
The 64-bit CE code runs fine in our qemu_v8 environment (https://github.com/OP-TEE/manifest/blob/master/qemu_v8.xml), tested with `make -j9 run CFG_CRYPTO_WITH_CE=y`. As for the 32-bit code, you're right it's not easy to test because the Makefile forces 64 bits (https://github.com/OP-TEE/build/blob/master/qemu_v8.mk#L9). I suppose there must be a reason for that.

**Comment by d3zd3z** [comment]
```
Reviewed-by: David Brown <david.brown@linaro.org>
```
We'll have to decide if it is worth figuring out a way to make this run in 32-bit mode on qemu.

**Comment by jforissier** [comment]
The CE code is enabled by default on HiKey, so it is tested quite often (and for each release in any case). Therefore, enabling CE in qemu is not really needed IMO.

**Comment by jforissier** [comment]
@ardbiesheuvel FYI.

**Comment by ardbiesheuvel** [comment]
QEMU does implement the 32-bit instructions, but currently, does not enable them for any of the 32-bit CPUs it emulates.

For my local QEMU build, I have been using the following patch for a while now:

diff --git a/target-arm/cpu.c b/target-arm/cpu.c
index 986f04cfd62f..be372488ac53 100644
--- a/target-arm/cpu.c
+++ b/target-arm/cpu.c
@@ -952,6 +952,13 @@ static void cortex_a15_initfn(Object *obj)
     cpu->ccsidr[0] = 0x701fe00a; /* 32K L1 dcache */
     cpu->ccsidr[1] = 0x201fe00a; /* 32K L1 icache */
     cpu->ccsidr[2] = 0x711fe07a; /* 4096K L2 unified cache */
+
+    cpu->id_isar5 = 0x00001120; /* enable crypto extensions */
+    set_feature(&cpu->env, ARM_FEATURE_V8_AES);
+    set_feature(&cpu->env, ARM_FEATURE_V8_SHA1);
+    set_feature(&cpu->env, ARM_FEATURE_V8_SHA256);
+    set_feature(&cpu->env, ARM_FEATURE_V8_PMULL);
+
     define_arm_cp_regs(cpu, cortexa15_cp_reginfo);
 }
 
This enables the crypto instructions for the emulated Cortex-A15 CPU

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Pull request closed without merging**
