### PR TITLE
ftrace improvements

### PR DESCRIPTION
**Pull request by jforissier**
Some ftrace improvements to better handle TAs that invoke long-running system calls.

### CODE REVIEW

**Comment by b49020** [comment]
Thanks @jforissier for these enhancements.

Reviewing "ftrace: use wall clock time":

I think completely relying on wall clock time would overestimate TA execution time especially in case of foreign interrupts as that time is not spent during actual TA function execution.

To take care of syscall time, actually I have added a flag `bool syscall` for `tee_ta_update_session_utime_suspend` and `tee_ta_update_session_utime_suspend` APIs, so that we don't exclude syscall time. Please have a look at change here: https://github.com/OP-TEE/optee_os/pull/3225/files#diff-1a25b2e89a0fb603b204778d62577b2fR966

**Comment by b49020** [comment]
For "ftrace: allow tracing of syscall wrappers only":

`Reviewed-by: Sumit Garg <sumit.garg@linaro.org>`

**Comment by b49020** [comment]
For "ftrace: allow display of larger durations":

This is nice enhancement especially to take care of larger syscall durations. So:
`Reviewed-by: Sumit Garg <sumit.garg@linaro.org>`

**Comment by jforissier** [comment]
@b49020 thanks for the review tags. Now regarding the controversial patch...

> I think completely relying on wall clock time would overestimate TA execution time especially in case of foreign interrupts as that time is not spent during actual TA function execution.

Well, I disagree. ftrace is a tracing framework, contrary to gprof which is statistical and computes average time, percentage of time spent executing actual function code etc. So, for gprof it makes sense to consider only user mode CPU time, and doing otherwise would be misleading. That's how gprof works in normal world too.

But for ftrace you basically show what happened for a particular invocation of a function and I see no strong reason to "hide" non-user time. If it entered at time A and exited at time B, then the user can expect B-A elapsed time to be reported for the function. Using wall clock time can help find out issues that could not be diagnosed otherwise, like if the TA keeps being interrupted it will actually not be doing much work and in this case it's nice to see that functions take longer than expected.

But, to be more practical let's consider an example. When I mentioned your upcoming syscall tracing patch (which is quite nice actually ;-)) and said "I suspect it will not work", I was thinking about inconsistencies. Please consider the following example.

```
- All tests with my "milliseconds" patch ("ftrace: allow display of larger durations").
- Showing only the TEE_Wait(2000) part in xtest 1009.

1. Without my "ftrace: use wall clock time" patch.

1.a. Tracing user space and syscalls
   make -j10 CFG_TA_FTRACE_SUPPORT=y CFG_CORE_SYSCALL_FTRACE=y CFG_ULIBS_MCOUNT=y CFG_FTRACE_BUF_SIZE=32768 CFLAGS_ta_arm32="-O0 -pg" run

              |      TEE_Wait() {
              |       utee_wait() {
              |        syscall_wait() {
     8.208 us |         tee_ta_get_current_session();
              |         tee_time_get_sys_time() {
    15.024 us |          arm_cntpct_get_sys_time();
    37.728 us |         }
              |         tee_time_get_sys_time() {
    13.392 us |          arm_cntpct_get_sys_time();
    35.600 us |         }
    30.896 us |         tee_ta_session_is_cancelled();
              |         tee_time_wait() {
              |          thread_rpc_cmd() {
     8.032 us |           plat_prng_add_jitter_entropy();
              |           get_rpc_arg() {
     6.832 us |            memset();
              |            mobj_get_cookie() {
              |             mobj_reg_shm_get_cookie() {
     6.176 us |              to_mobj_reg_shm();
    27.760 us |             }
    50.496 us |            }
    97.552 us |           }
     6.256 us |           reg_pair_from_64();
    33.952 us |           get_rpc_arg_res();
  2065.195 ms |          }
  2065.482 ms |         }
              |         tee_time_get_sys_time() {
    62.912 us |          arm_cntpct_get_sys_time();
   159.424 us |         }
    26.640 us |         tee_ta_session_is_cancelled();
  2066.178 ms |        }
    26.208 us |        set_svc_retval();
  2066.581 ms |       }
  2067.213 ms |      }


1.b. Tracing user space only
   make -j10 CFG_TA_FTRACE_SUPPORT=y CFG_CORE_SYSCALL_FTRACE=n CFG_ULIBS_MCOUNT=y CFG_FTRACE_BUF_SIZE=32768 CFLAGS_ta_arm32="-O0 -pg" run

              |      TEE_Wait() {
   111.936 us |       utee_wait();
   435.792 us |      }

2. With my "ftrace: use wall clock time" patch.

2.a. Tracing user space and syscalls: same as (1.a) basically (with minor variations
in reported times).

2.b. Tracing user space only

              |      TEE_Wait() {
  2073.673 ms |       utee_wait();
  2073.999 ms |      }
 ```

Which do you prefer, 1.b or 2.b? (considering 1.a). I am saying 2.b is better because 1.b is inconsistent: `TEE_Wait()` is charged a different duration depending on which parts of the code are being traced (user space only or user space + syscalls).

**Comment by b49020** [comment]
> But for ftrace you basically show what happened for a particular invocation of a function and I see no strong reason to "hide" non-user time. If it entered at time A and exited at time B, then the user can expect B-A elapsed time to be reported for the function.

I understand your point and following change in syscall patch-set should make `case 1` behave as expected:

```
diff --git a/core/kernel/tee_ta_manager.c b/core/kernel/tee_ta_manager.c
index 673bb59..8d8cd64 100644
--- a/core/kernel/tee_ta_manager.c
+++ b/core/kernel/tee_ta_manager.c
@@ -962,10 +962,8 @@ static void tee_ta_update_session_utime(bool suspend,
        gprof_update_session_utime(suspend, s, now);
 #endif
 #if defined(CFG_TA_FTRACE_SUPPORT)
-#if defined(CFG_CORE_SYSCALL_FTRACE)
        if (syscall)
                return;
-#endif
        ftrace_update_session_utime(suspend, s, now);
 #endif
 }
```

> Using wall clock time can help find out issues that could not be diagnosed otherwise, like if the TA keeps being interrupted it will actually not be doing much work and in this case it's nice to see that functions take longer than expected.

How about if TA is executing a simple `DMSG` and interrupted by normal world and not scheduled back for longer duration especially on a loaded system?

And user won't get a consistent timing graph using wall clock time during multiple runs as one could never be sure which TA function would be interrupted.

**Comment by jforissier** [comment]
> following change in syscall patch-set should make case 1 behave as expected:

It does.
Since it fixes to code that is not yet upstream, perhaps it should come first instead as a fixup on top of syscall tracing support.

> How about if TA is executing a simple DMSG and interrupted by normal world and not scheduled back for longer duration especially on a loaded system?

With my proposal, the user has an opportunity to wonder why the time is larger than expected and figure out that maybe too many interrupts are coming etc. But I guess it depends on the use case.

> And user won't get a consistent timing graph using wall clock time during multiple runs as one could never be sure which TA function would be interrupted.

True, but is this really an issue? If you're interested in global system behavior, you want to see the raw time. If you're optimizing TA code, it may be different. Perhaps this should be made configurable. But I'd rather keep things simple.

Frankly I'm not sure what is best. Note Linux uses raw timestamps it seems so no difference between types of CPU time (but it's all kernel anyway, not application).

**Comment by b49020** [comment]
> Since it fixes to code that is not yet upstream, perhaps it should come first instead as a fixup on top of syscall tracing support.

Agree, will create a separate PR for this fixup.

> Note Linux uses raw timestamps it seems so no difference between types of CPU time (but it's all kernel anyway, not application).

Following is an example trace of Linux function graph:

```
    #
    #      TIME       CPU  DURATION                  FUNCTION CALLS
    #       |         |     |   |                     |   |   |   |
    360.774522 |   1)   0.541 us    |                                          }
    360.774522 |   1)   4.663 us    |                                        }
    360.774523 |   1)   0.541 us    |                                        __wake_up_bit();
    360.774524 |   1)   6.796 us    |                                      }
    360.774524 |   1)   7.952 us    |                                    }
    360.774525 |   1)   9.063 us    |                                  }
    360.774525 |   1)   0.615 us    |                                  journal_mark_dirty();
    360.774527 |   1)   0.578 us    |                                  __brelse();
    360.774528 |   1)               |                                  reiserfs_prepare_for_journal() {
    360.774528 |   1)               |                                    unlock_buffer() {
    360.774529 |   1)               |                                      wake_up_bit() {
    360.774529 |   1)               |                                        bit_waitqueue() {
    360.774530 |   1)   0.594 us    |                                          __phys_addr();
```

It seems the use-cases you are referring to matches with optional absolute time field in above function graph. So definitely we can add this optional field in ftrace graph for TAs too. But I think duration for a specific TA function should represent actual execution time only rather than incorporating time spent serving foreign interrupts.

**Comment by b49020** [comment]
> will create a separate PR for this fixup.

https://github.com/OP-TEE/optee_os/pull/3232

**Comment by jforissier** [comment]
Closing since the first two commits was merged in #3241 and the last one is controversial -- a less drastic solution was merged in #3232.

**Pull request closed without merging**
