### PR TITLE
core: add ELF identifier after memory region when dumping TA state

### PR DESCRIPTION
**Pull request by jforissier**
Update the TA exception/panic dump to add an identifier after each memory
region used to map an ELF section. Here is an example with a TA linked
against two dynamic libraries ("E/TC:0" prefix removed):
```
 TA panicked with code 0x0
 Status of TA 93038f64-871d-4773-b1f5-878697745eee (0xe17fdf0) (active)
  arch: arm  load address: 0x103000 ctx-idr: 2
  stack: 0x102000 4096
  region 0: va 0x100000 pa 0xe100000 size 0x1000 flags ---R-X
  region 1: va 0x102000 pa 0xe319000 size 0x1000 flags rw-RW-
  region 2: va 0x103000 pa 0xe300000 size 0xe000 flags r-x--- [0]
  region 3: va 0x111000 pa 0xe30e000 size 0xb000 flags rw---- [0]
  region 4: va 0x11c000 pa 0xe31a000 size 0x1000 flags r-x--- [1]
  region 5: va 0x11d000 pa 0xe32b000 size 0x1000 flags r-x--- [2]
  region 6: va 0x11e000 pa 0xe33c000 size 0x1000 flags r-----
  region 7: va 0x12c000 pa 0xe32a000 size 0x1000 flags rw---- [1]
  region 8: va 0x12d000 pa 0xe33b000 size 0x1000 flags rw---- [2]
  [0] 93038f64-871d-4773-b1f5-878697745eee @ 0x103000
  [1] 7814a949-e967-421c-8838-04f7ee1c5744 @ 0x11c000
  [2] 14c7f8d4-0202-4bfe-b4ca-ab6eca303169 @ 0x11d000
 Call stack:
  0x00103628
  0x00109bed
  0x0011c36d
  0x00103041
  0x00103245
  0x0010334d
  0x0010348b
  0x001035df
```
Index [0] points to the main executable while higher values identify
libraries.

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Seems very useful.

How come the loaded libraries seems to be interleaved?

**Comment by jforissier** [comment]
> How come the loaded libraries seems to be interleaved?

That's a very good question, and I would have expected you to tell me ;-)
Well, I need to take a closer look but it might be a matter of size and similar permissions. The physical addresses are in the "expected" order though (ELF number 0, 1, 2 then the combined EXIDX table).

**Comment by jforissier** [comment]
@jenswi-linaro weird mapping fixed in https://github.com/OP-TEE/optee_os/pull/2329.

With that I get the following dump:
```
E/TC:0 TA panicked with code 0x0
E/TC:0 Status of TA 93038f64-871d-4773-b1f5-878697745eee (0xe17fe00) (active)
E/TC:0  arch: arm  load address: 0x103000 ctx-idr: 2
E/TC:0  stack: 0x102000 4096
E/TC:0  region 0: va 0x100000 pa 0xe100000 size 0x1000 flags ---R-X 
E/TC:0  region 1: va 0x102000 pa 0xe318000 size 0x1000 flags rw-RW- 
E/TC:0  region 2: va 0x103000 pa 0xe300000 size 0xd000 flags r-x--- [0]
E/TC:0  region 3: va 0x110000 pa 0xe30d000 size 0xb000 flags rw---- [0]
E/TC:0  region 4: va 0x11b000 pa 0xe319000 size 0x1000 flags r-x--- [1]
E/TC:0  region 5: va 0x12b000 pa 0xe329000 size 0x1000 flags rw---- [1]
E/TC:0  region 6: va 0x12c000 pa 0xe32a000 size 0x1000 flags r-x--- [2]
E/TC:0  region 7: va 0x13c000 pa 0xe33a000 size 0x1000 flags rw---- [2]
E/TC:0  region 8: va 0x13d000 pa 0xe33b000 size 0x1000 flags r----- 
E/TC:0  [0] 93038f64-871d-4773-b1f5-878697745eee @ 0x103000
E/TC:0  [1] 7814a949-e967-421c-8838-04f7ee1c5744 @ 0x11b000
E/TC:0  [2] 14c7f8d4-0202-4bfe-b4ca-ab6eca303169 @ 0x12c000
E/TC:0 Call stack:
E/TC:0  0x00103628
E/TC:0  0x00109591
E/TC:0  0x0011b36d
E/TC:0  0x00103041
E/TC:0  0x00103245
E/TC:0  0x0010334d
E/TC:0  0x0010348b
E/TC:0  0x001035df
```

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Pull request merged**
