### PR TITLE
core: mobj: MOBJ is abstract pull it from arch folder

### PR DESCRIPTION
**Pull request by maroueneboubakri**
This commit moves mobj.h and mobj.c from arch folder to top core folder
to be able to reuse it when porting OP-TEE OS to another architecture.

Signed-off-by: Marouene Boubakri <marouene.boubakri@nxp.com>

### CODE REVIEW

**Comment by etienne-lms** [comment]
mobj relies on arch/.../core_mmu.h for some configurations, IDs, ... as SMALL_PAGE_SIZE, CORE_MMU_PGDIR_SIZE, CORE_MMU_USER_PARAM_MASK,  CORE_MEM_{SDP_MEM|NON_SEC|NSEC_SHM|...}, OPTEE_SMC_SHM_CACHED.
Also few arch/.../kernel/ things as VCORE_UNPG_RW_SZ.
These are all meaninful in your architecture?

**Comment by maroueneboubakri** [comment]
> mobj relies on arch/.../core_mmu.h for some configurations, IDs, ... as SMALL_PAGE_SIZE, CORE_MMU_PGDIR_SIZE, CORE_MMU_USER_PARAM_MASK, CORE_MEM_{SDP_MEM|NON_SEC|NSEC_SHM|...}, OPTEE_SMC_SHM_CACHED.
> Also few arch/.../kernel/ things as VCORE_UNPG_RW_SZ.
> These are all meaninful in your architecture?

The architecture should define these values.  Let's say we don't make big changes on` core_mmu.h`. However, The `core_mmu.c` implementation is changed to consider the architecture specificities.

**Comment by jenswi-linaro** [comment]
I assume that `core_mmu.h` is going to be broken up in architecture dependent and architecture independent parts.
Perhaps it's better to instead start with `core_mmu.h` so we can get a better view of what we're about to agree on.

**Comment by maroueneboubakri** [comment]
> I assume that `core_mmu.h` is going to be broken up in architecture dependent and architecture independent parts.
> Perhaps it's better to instead start with `core_mmu.h` so we can get a better view of what we're about to agree on.

Yes, the same applies for `thread.c` .

**Pull request closed without merging**
