### PR TITLE
Refactor ta man2

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Breakout initial commits of https://github.com/OP-TEE/optee_os/pull/592 with review comments addressed.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Fix plat-stm build error and a checkpatch warning

**Comment by pascal-brand-st-dev** [comment]
About the commits on tee_ta_manager.c refactoring:

    Reviewed-by: Pascal Brand <pascal.brand@linaro.org>
    Tested-by: Pascal Brand <pascal.brand@linaro.org> (STM platform)

**Comment by jenswi-linaro** [comment]
@pascal-brand-st-dev  Does the RB-tag cover all the commits here?

**Comment by pascal-brand-st-dev** [comment]
Not the first 2 ones, related to the linker

**Comment by jenswi-linaro** [comment]
Tags applied

**Pull request merged**
