### PR TITLE
Add imx93 support

### PR DESCRIPTION
**Pull request by clementfaure**

### CODE REVIEW

**Review by jforissier — APPROVED** [review]
Hello @clementfaure,

- "core: imx: simplify the error macro message"
  "ci: add imx93evk build"
  
  `Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`
 
- "core: imx: add imx93 registers"
  "core: imx: add imx93 SoC ID"
  "core: imx: add support imx93evk platform"
  
  `Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by clementfaure** [comment]
Tags applied. Thanks for the quick ack

**Comment by clementfaure** [comment]
👍🏻

**Pull request merged**
