### PR TITLE
ta: pkcs11: fix TEE identity authentication token reference

### PR DESCRIPTION
**Pull request by etienne-lms**
Correct token reference pass to verify client credentials.

Fixes: 1a27b197 ("ta: pkcs11: Add TEE Identity based authentication support")
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

### CODE REVIEW

**Comment by etienne-lms** [comment]
Issue reported by https://github.com/OP-TEE/optee_os/commit/1a27b197d8b16ef2d4dab8d205f359627b6f0232#r46677828.

**Comment by ruchi393** [comment]
` Acked-by: Ruchika Gupta <ruchika.gupta@linaro.org>`

**Comment by jforissier** [comment]
@etienne-lms please remember to also rebase when applying Ruchika's tag so that the IBART build is fixed and we have a clean status. Thanks.

**Comment by etienne-lms** [comment]
rebased to master and tag applied.

**Pull request merged**
