### PR TITLE
Update CHANGELOG.md for 3.5.0

### PR DESCRIPTION
**Pull request by jforissier**
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
As usual, let's use this PR to collect Tested-bys.

**Comment by jbech-linaro** [comment]
I don't think we have an `rc1` tag yet, but I have the RPi3 a try today using latest and with that:
```bash
NOTICE:  BL1: v2.0(debug):v2.0-580-g023bc019
NOTICE:  BL1: Built : 09:49:16, Apr 16 2019
...
NOTICE:  BL2: v2.0(debug):v2.0-580-g023bc019
NOTICE:  BL2: Built : 09:49:16, Apr 16 2019
...
NOTICE:  BL31: v2.0(debug):v2.0-580-g023bc019
NOTICE:  BL31: Built : 09:49:16, Apr 16 2019
...
I/TC: OP-TEE version: 3.4.0-210-g13e224aa #1 Tue Apr 16 07:48:35 UTC 2019 aarch64
...
U-Boot 2019.01-00093-gaac0c29d4b (Apr 16 2019 - 09:47:25 +0200)
...
[    0.000000] Linux version 4.14.56-v8 (jbech@debby) (gcc version 8.2.1 20180802 (GNU Toolchain for the A-profile Architecture 8.2-2018-08 (arm-rel-8.23))) #1 SMP PREEMPT Tue Apr 16 09:59:52 CEST 2019
...
# xtest -l15
...
+-----------------------------------------------------
44034 subtests of which 0 failed
93 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```
`Tested-by: Joakim Bech <joakim.bech@linaro.org>` (RPi3B)

**Comment by jforissier** [comment]
@jbech-linaro indeed, no -rc1 yet but it's good to know that things are working on master.

I, too, have run various configurations on HiKey960, and with https://github.com/OP-TEE/optee_test/pull/343:

`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey960, GP)`

(that is with master at commit bccaa84).

**Comment by MrVan** [comment]
@jforissier 
"o regression_5006.3 Allocate_out_of_memory
  regression_5006.3 OK
o regression_5006.4 OpenSession_error_notExistingTA
it stops here for some time.. any idea?
"

**Comment by etienne-lms** [comment]
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (b2260, GP)` 
on optee_os 13e224a / optee_test [68936ba](https://github.com/OP-TEE/optee_test/commit/68936baf18d0a1650728907f8f03c376776c933d) / optee_client [16c8f54](https://github.com/OP-TEE/optee_client/commit/16c8f548786c70df04d3a1e61bf89abce9b92389)
```
root@sti:~# xtest -t regression -l15
(...)
44039 subtests of which 0 failed
93 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
root@sti:~# xtest -t gp
(...)
4488 subtests of which 0 failed
644 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
root@sti:~#

**Comment by MrVan** [comment]
`Tested-by: Peng Fan <peng.fan@nxp.com> (imx6q-sabresd, imx8mm-evk)`

```
xtest -t regression -l15
44033 subtests of which 0 failed
93 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by sandeepbrcm** [comment]
`Tested-by: Sandeep Tripathy <sandeep.tripathy@broadcom.com> (bcm-ns3)`

```
xtest -t regression -l15
44034 subtests of which 0 failed
93 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by jbech-linaro** [comment]
I have just now pushed a release candidate tag `3.5.0-rc1`. If you haven't already added a `Tested-by`, then please use`3.5.0-rc1` tag when testing.

**Comment by igoropaniuk** [comment]
For `3.5.0-rc1`:
```
+-----------------------------------------------------
44038 subtests of which 0 failed
94 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

`Tested-by: Igor Opaniuk <igor.opaniuk@gmail.com> (Poplar)`

**Comment by lorc** [comment]
For `3.5.0-rc1`:

> 24045 subtests of which 0 failed
> 93 test cases of which 0 failed
> 0 test cases were skipped
> TEE test application done!

`Tested-by: Volodymyr Babchuk <vlad.babchuk@gmail.com> (RCAR H3)`
`Tested-by: Volodymyr Babchuk <vlad.babchuk@gmail.com> (RCAR H3/virtualization)`

**Comment by nodeax** [comment]
`Tested-by: Akshay Bhat <akshay.bhat@timesys.com> (Atmel SAM)`
```
# xtest -t regression -l15
44034 subtests of which 0 failed
93 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by b49020** [comment]
For `3.5.0-rc1`:
```
$ xtest -l 15
+-----------------------------------------------------
44034 subtests of which 0 failed
93 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```
`Tested-by: Sumit Garg <sumit.garg@linaro.org> (Developerbox)`

**Comment by vchong** [comment]
For `3.5.0-rc1`:

`Tested-by: Victor Chong <victor.chong@linaro.org> (HiKey AOSP, HiKey960 AOSP)`

**Comment by jforissier** [comment]
For `3.5.0-rc1`:

`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey960)`

(details [here](https://docs.google.com/document/d/1TNEfvNCVPWd4wTwcX8hL0Frc0PW50f9qk6Nm0rSg0Ik)).

**Comment by jenswi-linaro** [comment]
For `3.5.0-rc1`:
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU v8)`

**Comment by jbech-linaro** [comment]
Using `3.5.0-rc1`
`Tested-by: Joakim Bech <joakim.bech@linaro.org>` (QEMU v7)

```
44034 subtests of which 0 failed
93 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by jbech-linaro** [comment]
Using `3.5.0-rc1`:
`Tested-by: Joakim Bech <joakim.bech@linaro.org>` (FVP)

```
+-----------------------------------------------------
24045 subtests of which 0 failed
93 test cases of which 0 failed
0 test cases were skipped
```

**Comment by jenswi-linaro** [comment]
@jbech-linaro, which combinations did you do on FVP?

**Comment by jbech-linaro** [comment]
> @jbech-linaro, which combinations did you do on FVP?

Only plain `# xtest`, no special build flags and not using the `-l15`.

**Comment by jenswi-linaro** [comment]
OK, I'm currently running the four combinations, 32/64-bit and with and without pager. I'll post the result when I'm done.

**Comment by jenswi-linaro** [comment]
For `3.5.0-rc1`:
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Hikey)`
The four combinations  `AArch{32,64}` and `CFG_WITH_PAGER={y,n}` has been tested.

**Comment by jbech-linaro** [comment]
> Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Hikey)

HiKey? .. or FVP?

**Comment by jenswi-linaro** [comment]
Hikey, I'm doing things simultaneously. :-)

**Comment by glneo** [comment]
For 3.5.0-rc1:
```
Tested-by: Andrew F. Davis <afd@ti.com> (DRA7xx, AM43xx, AM57xx, AM65x)
```

**Comment by jenswi-linaro** [comment]
For `3.5.0-rc1`:
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (FVP)`
The four combinations `AArch{32,64}` and `CFG_WITH_PAGER={y,n}` has been tested.

**Comment by bryanodonoghue** [comment]
For `3.5.0-rc1`
`Tested-by: Bryan O'Donoghue <bryan.odonoghue@linaro.org> (WaRP7)`

**Comment by jenswi-linaro** [comment]
For `3.5.0-rc1`:
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)`
The four combinations `AArch{32,64}` and `CFG_WITH_PAGER={y,n}` has been tested.

**Comment by Emantor** [comment]
For `3.5.0-rc1`:
`Tested-by: Rouven Czerwinski <r.czerwinski@pengutronix.de> (imx6qsabresd)` with `CFG_TZC380=y` and bootloader disabled bypass.

**Comment by etienne-lms** [comment]
For both 3.5.0-rc1 and latest master branches:
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (b2120, b2260, stm32mp1)`.

**Comment by jbech-linaro** [comment]
OP-TEE 3.5.0 has been released!
This [changelog](https://github.com/OP-TEE/optee_os/blob/master/CHANGELOG.md) has been [pushed manually](https://github.com/OP-TEE/optee_os/commit/5df2a985b2ffd0b6f1107f12ca2a88203bf31328#diff-4ac32a78649ca5bdd8e0ba38b7006a1e), all gits are tagged with 3.5.0 and [stable manifests has been created](https://github.com/OP-TEE/manifest/tree/3.5.0) (where I've test built for QEMU v7 and RPi3). Closing the PR.

Thanks everyone for being part of the OP-TEE 3.5.0 release!

**Pull request closed without merging**
