### PR TITLE
Update CHANGELOG for 3.11.0

### PR DESCRIPTION
**Pull request by jforissier**
Update CHANGELOG for 3.11.0 and collect Tested-by tags.

Signed-off-by: Jerome Forissier <jerome@forissier.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)`

**Comment by jforissier** [comment]
master @ 037c8a70 + #4133:
`Tested-by: Jerome Forissier <jerome@forissier.org> (QEMU)`

**Comment by jforissier** [comment]
master @ aad807b4:
`Tested-by: Jerome Forissier <jerome@forissier.org> (QEMUv8)`

**Comment by clementfaure** [comment]
Hello!

Master@ aad807b403b
```
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6dlsabreauto)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6dlsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6qpsabreauto)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6ulevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6ullevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6ulzevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6sllevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx7dsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx7ulpevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx8mmevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx8mnevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx8mqevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx8qmmek)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx8qxpmek)
```

**Comment by jforissier** [comment]
master @ 589a4941
`Tested-by: Jerome Forissier <jerome@forissier.org> (HiKey)`

**Comment by jforissier** [comment]
master @ 589a4941
`Tested-by: Jerome Forissier <jerome@forissier.org> (HiKey960)`

**Comment by Emantor** [comment]
```
+-----------------------------------------------------
12481 subtests of which 55 failed
91 test cases of which 12 failed
0 test cases were skipped
TEE test application done!
```
All logs are collected in #4139.

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Hikey GP v1.1)`

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (FVP)`

**Comment by nodeax** [comment]
I am seeing some failures on SAMA5 platform (I did not test the last 2 releases, so not sure if this is necessarily associated with the changes in this release).

```
+-----------------------------------------------------
24530 subtests of which 12 failed
91 test cases of which 5 failed
0 test cases were skipped
TEE test application done!
```

All logs are collected in https://github.com/OP-TEE/optee_os/issues/4153

**Comment by ricardosalveti** [comment]
Also seeing some failures on zynqmp-zcu102, but this is the first time I'm testing against this target, so not sure if regressions or not yet.

With https://github.com/OP-TEE/optee_client/commit/2de7f2531b704b83f9a44429cbab282df9b984a4 (3.11.0-rc1):
```
+-----------------------------------------------------
12800 subtests of which 57 failed
91 test cases of which 14 failed
0 test cases were skipped
TEE test application done!
```
With https://github.com/OP-TEE/optee_client/commit/f12384882afb75a29e8a44b5091bd04228bce9e3:
```
+-----------------------------------------------------
24740 subtests of which 2 failed
91 test cases of which 2 failed
0 test cases were skipped
TEE test application done!
```
Logs collected at #4155.

**Comment by jbech-linaro** [comment]
Seems to be mixed results this time, should we push the release +1 week to give people time to do some debugging? @ricardosalveti @Emantor @nodeax , if we push it another week would you time have to do debug a bit more on your end for the issue that you're facing?

**Comment by Emantor** [comment]
Looks @jenswi-linaro pinned this down to https://github.com/linaro-swg/linux/commit/1149e7d06a009e5dacf6aaa29bd087da64bfbed2 not being included in upstream kernels. @ruchi393 is working on a patch for the client, depending on when the patch is available I don't think that an extension of the release time is required. On the other hand an extension removes pressure from @ruchi393 to deliver this week.

**Comment by jforissier** [comment]
@Emantor what you said applies to #4139 and #4155. #4153 looks different.

**Comment by jbech-linaro** [comment]
> Looks @jenswi-linaro pinned this down to [linaro-swg/linux@1149e7d](https://github.com/linaro-swg/linux/commit/1149e7d06a009e5dacf6aaa29bd087da64bfbed2) not being included in upstream kernels

Which brings back a question we've touched a couple of times and that is whether to make a change to start using the upstream kernel tree/branch as the default tree/branch? I fully aware of patches in linaro-swg/linux that are not found upstream. But maybe an exercise like this would be an incentive to try to push that stuff upstream to the official upstream kernel tree instead of keeping it downstream forever?

**Comment by Emantor** [comment]
@jforissier You are right, I should have mentioned that my comment only applies to #4139.

**Comment by jenswi-linaro** [comment]
The two patches "tee: client UUID: Skip REE kernel login method as well" and "driver: tee: Handle NULL pointer indication from client" are in flight. I expect them to be merged during this merge window, at least the latter patch.

**Comment by igoropaniuk** [comment]
```
I/TC: OP-TEE version: 3.11.0-rc1-12-gae85b831 (gcc version 9.2.1 20191025 (GNU Toolchain for the A-profile Architecture 9.2-2019.12 (arm-9.10))) #1 Wed Oct 14 09:23:58 UTC 2020 aarch64

...
# xtest -l20
+-----------------------------------------------------
44591 subtests of which 0 failed
92 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

`Tested-by: Igor Opaniuk <igor.opaniuk@gmail.com> (Poplar)`

**Comment by ricardosalveti** [comment]
With "driver: tee: Handle NULL pointer indication from client" I'm able to get it to pass without any issues.

```
I/TC: OP-TEE version: 3.11.0-rc1-110-gae2b65fc (gcc version 10.2.0 (GCC)) #1 Thu Jan  1 00:00:00 UTC 1970 aarch64

+-----------------------------------------------------
24745 subtests of which 0 failed
91 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

Tested-by: Ricardo Salveti <ricardo@foundries.io> (ZynqMP)

**Comment by lorc** [comment]
For 3.11.0-rc1 tag with "driver: tee: Handle NULL pointer indication from client"  kernel patch:

`Tested-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com> (Rcar H3)`
`Tested-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com> (Rcar H3/virtualization)`

**Comment by Emantor** [comment]
With latest optee-client:
`Tested-by: Rouven Czerwinski <r.czerwinski@pengutronix.de> (ccimx6ulsbcpro)`
`Tested-by: Rouven Czerwinski <r.czerwinski@pengutronix.de> (STM32MP157DK2)`

**Comment by clementfaure** [comment]
For ```3.11.0-rc1```
```
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6dlsabreauto)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6dlsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6qpsabreauto)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6ulevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6ullevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6ulzevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6sllevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx7dsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx7ulpevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx8mmevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx8mnevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx8mqevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx8qmmek)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx8qxpmek)
```

**Comment by etienne-lms** [comment]
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1)`  on 3.11.0-rc1 and latest optee_os master.

**Pull request merged**
