### PR TITLE
Update CHANGELOG for 3.17.0

### PR DESCRIPTION
**Pull request by jforissier**
Update CHANGELOG for 3.17.0 and collect Tested-by tags.

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

### CODE REVIEW

**Comment by Neal-liu** [comment]
I met kernel panic during platform initialization on Aspeed ast2600 platform.

The problem is system cannot get gicd_base virtual address at core/drivers/gic.c gic:255
Due to Aspeed design, we only have 4KB address space mapping for GICD & GICC. And we register it only size SMALL_PAGE_SIZE(4KB). As the results, core_mmu_get_va() cannot get va for size GIC_DIST_REG_SIZE(64KB).

After I revised to register gicd & gicc to the corresponding physical memory size, it can boot up successfully.
But the memory map overlaps warning will show up.

```
D/TC:0   add_phys_mem:554 GIC_BASE + GICC_OFFSET type IO_SEC 0x40462000 size 0x00010000
D/TC:0   add_phys_mem:554 GIC_BASE + GICD_OFFSET type IO_SEC 0x40461000 size 0x00010000
D/TC:0   add_phys_mem:568 Physical mem map overlaps 0x40461000
```

I'm wondering if hardcode gicd & gicc memory mapping size is reasonable and
the memory map overlaps warning is acceptable or not?

**Comment by jenswi-linaro** [comment]
The "Physical mem map overlaps" debug print can be safely ignored.
With "Aspeed design", do you mean the code here in optee_os or limits in the physical SoC?

**Comment by Neal-liu** [comment]
"Aspeed design" means hardware limits in the physical SoC. Each of them have 4KB address space.

**Comment by jenswi-linaro** [comment]
Please create a PR fixing the problem. We can continue the discussion there.

**Comment by Neal-liu** [comment]
> Please create a PR fixing the problem. We can continue the discussion there.

PR #5241 is already created.

**Comment by jbech-linaro** [comment]
```
NOTICE:  BL1: v2.6(debug):v2.6
NOTICE:  BL1: Built : 17:49:25, Mar 29 2022
NOTICE:  BL2: v2.6(debug):v2.6
NOTICE:  BL2: Built : 17:49:25, Mar 29 2022
NOTICE:  BL31: v2.6(debug):v2.6
NOTICE:  BL31: Built : 17:49:25, Mar 29 2022
I/TC: OP-TEE version: 3.16.0-155-g023aecc6 (gcc version 10.2.1 20201103 (GNU Toolchain for the A-profile Architecture 10.2-2020.11 (arm-10.16))) #1 Tue 29 Mar 2022 03:49:05 PM UTC aarch64
U-Boot 2021.10 (Mar 29 2022 - 17:48:55 +0200)
[    0.000000] Linux version 5.4.83-v8 (jyx@tuxedo) (gcc version 10.2.1 20201103 (GNU Toolchain for the A-profile Architecture 10.2-2020.11 (arm-10.16))) #1 SMP PREEMPT Tue Mar 29 17:49:06 CEST 2022
# xtest -l 15
+-----------------------------------------------------
46198 subtests of which 0 failed
95 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```
`Tested-by: Joakim Bech <joakim.bech@linaro.org>` (RPi3B)


```
# xtest
....
+-----------------------------------------------------
26263 subtests of which 0 failed
95 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```
`Tested-by: Joakim Bech <joakim.bech@linaro.org>` (RPi3B-NFS)

**Comment by Neal-liu** [comment]
with #5241:
`Tested-by: Neal Liu <neal_liu@aspeedtech.com>` (ast2600)

**Comment by clementfaure** [comment]
Hi!

With `bb75092f2f898c3b65863671133324c5deddf23b`
```
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6dlsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6qsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6sllevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6sxsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6ulevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6ullevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6ulzevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx7dsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx7ulpevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mmevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mnevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mqevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mpevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8qmmek)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8qxpmek)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8dxlevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8ulpevk)
```

**Comment by jforissier** [comment]
Commit 145035ff:

`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (vexpress-qemu_armv8a)`

**Comment by jforissier** [comment]
Commit a9edcef3:

`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (hikey-hikey)`

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (imx-mx8mqevk)`

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)`

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (FVP)`

**Comment by lorc** [comment]
`Tested-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com> (rcar-salvator_m3_2x4g / virt)`
`Tested-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com> (rcar-salvator_m3_2x4g)`

**Comment by sahilnxp** [comment]
With commit id: 497dbec867958eb665743a90f4e7bdf5774f0653
```
Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS1012A-RDB)
Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS1028A-RDB)
Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS1088A-RDB)
Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS2088A-RDB)
Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS1046A-RDB)
Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS1043A-RDB)
Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS2160A-RDB)
Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS2162A-QDS)
```

**Comment by etienne-lms** [comment]
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1, gp pkcs11)`

**Comment by etienne-lms** [comment]
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (vexpress-qemu_virt, gp pkcs11 pager)`

**Pull request merged**
