### PR TITLE
Fix tee_ta_rpc_load in case of out of memory

### PR DESCRIPTION
**Pull request by pascal-brand-st-dev**
Signed-off-by: Pascal Brand <pascal.brand@st.com>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by jforissier** [comment]
This is essentially a cosmetic fix, right? Because `thread_rpc_free_payload(payload)` does nothing when `payload == NULL`.
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by pascal-brand-st-dev** [comment]
Well, it is not obvious. For sure, `thread_rpc_free_payload` is calling the linux driver whatever the payload is. Then the linux driver is searching for the related shm,...

As everything is useless, it is better and safer to return directly.

**Comment by jforissier** [comment]
@pascal-brand-st-dev 
Huh ?! I see a pointer check [here](https://github.com/OP-TEE/optee_os/blob/80ddeac77bdb13ada0a2289c7b83187aa94e7ff0/core/arch/arm/kernel/thread.c#L1067-L1075) ;-)

**Comment by pascal-brand-st-dev** [comment]
Indeed, this is `thread_optee_rpc_free_payload` which is called, not `thread_rpc_free_payload`. `thread_optee_rpc_free_payload` does not contain the if. Cf https://github.com/OP-TEE/optee_os/blob/80ddeac77bdb13ada0a2289c7b83187aa94e7ff0/core/arch/arm/kernel/thread.c#L1139

**Comment by jforissier** [comment]
Ah, this is confusing :( Your fix is fine. Sorry for the noise.

**Pull request merged**
