### PR TITLE
Minor fixes i.MX platforms

### PR DESCRIPTION
**Pull request by clementfaure**
Hello,

Here are small fixes for i.MX platforms.

Thanks,
Clement

### CODE REVIEW

**Review by jforissier — COMMENTED** [review]
- For commit " core: imx: remove useless header include":
  `Reviewed-by: Jerome Forissier <jerome@forissier.org>`
- All other commits:
  `Acked-by: Jerome Forissier <jerome@forissier.org>`

Question: is mx6sll OK regarding the errata? If I understand your comment correctly I think it is (but it mentions SL not SLL specifically). But if it is not the case then two commits should preferably be swapped.

**Comment by clementfaure** [comment]
Hi @jforissier,
Yes, the mx6sl and the mx6sll are not concerned by the errata.
Only platforms imx6d/6q/6dp/6qp are affected by the PL310 issue because these platforms might feature faulty PL310 controllers.

Do you want me to add the link to the errata in the commit message ? https://www.nxp.com/docs/en/errata/IMX6DQCE.pdf

**Comment by jforissier** [comment]
@clementfaure
>  Yes, the mx6sl and the mx6sll are not concerned by the errata.

Cool, then this series is fine in that order.

> Do you want me to add the link to the errata in the commit message ? https://www.nxp.com/docs/en/errata/IMX6DQCE.pdf

Yep good idea, the more information the better (well... up to a certain point!)

**Comment by clementfaure** [comment]
Force-push:
* Link to the PL310 errata added
* Tags applied
* Rebase

**Pull request merged**
