### PR TITLE
core: pager: initialize vabase in core pager tables

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Initialize the vabase in each struct pgt used to page OP-TEE core.

Fixes: 5ca851ec83ba ("core: pager: add struct tblidx")
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome@forissier.org>`
`Tested-by: Jerome Forissier <jerome@forissier.org> (HiKey960)`

**Comment by jbech-linaro** [comment]
FYI, I'm unable to access IBART remotely. Need to drive to the office to sort it out. So now you know in case you wondered about it.

**Comment by jenswi-linaro** [comment]
Tags applied

**Comment by jforissier** [comment]
@jbech-linaro OK thanks.

**Pull request merged**
