### PR TITLE
plat-stm32mp1: remove duplicate config

### PR DESCRIPTION
**Pull request by gagachang**
There are two lines of "CFG_STM32_RNG ?= y" in `plat-stm32mp1/conf.mk`.
Remove a duplicate one.

Signed-off-by: gagachang <vivahavey@gmail.com>

### CODE REVIEW

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome@forissier.org>`

Thanks!

**Comment by gagachang** [comment]
@etienne-lms @jforissier , Thanks for reviewing!
Sorry, gagachang is my nickname.
Should I commit another PR about fixing this or just fix the commit message?
I just added my real name "Che-Chia Chang" of Github.

**Comment by etienne-lms** [comment]
Just force push an updated commit in your branch.
You can also add the review tags in your commit message, Jérôme's and my 
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`.

**Comment by etienne-lms** [comment]
Also: CI complains on checkpatch (see Travis report).
You should update your gitconfig so that s-o-b tag and author description matches (the author part still uses your nickname) before commiting your change.

**Comment by jforissier** [comment]
All good thanks.

**Pull request merged**
