### PR TITLE
Overflow2

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jforissier** [comment]
Just a quick comment before I really look into this: I find the variable names really painful to read!
Could `__intofa_a_signed` just be called `__a_s` for instance? (and `__intofa_a` could be `__a` etc.).

**Comment by jenswi-linaro** [comment]
The variables are prefixed in order to minimize the risk of conflicts. I agree that the names of the variables makes it difficult to read, but I don't see any way around it.

**Comment by jenswi-linaro** [comment]
Update

**Comment by etienne-lms** [comment]
Good tests could balance the code hard reading.
The `ADD_OVERFLOW` tests look nice: positive/negative tests at overflow bound and saturation cases.
Maybe the `SUB_OVERFLOW` would deserve some more negative test.

From my side, `Acked-by: Etienne Carriere <etienne.carriere@linaro.org>` and thanks.

**Comment by jforissier** [comment]
The `util:` patches LGTM:
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

For the `core_self_tests.c:` patches:
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Pull request merged**
