### PR TITLE
Update CHANGELOG for 3.19.0 and collect Tested-by tags.

### PR DESCRIPTION
**Pull request by jforissier**
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

### CODE REVIEW

**Comment by clementfaure** [comment]
Hello @jforissier !

For `4b46e0e8`

```
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6dlsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6qsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6sllevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6sxsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6ulevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6ullevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6ulzevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx7dsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx7ulpevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mmevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mnevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mqevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mpevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8qmmek)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8qxpmek)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8dxlevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8ulpevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx93evk)
```

**Comment by jforissier** [comment]
For `4b46e0e81`:

`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (vexpress-qemu_armv8a, GP, PKCS#11)`

With one known issue: https://github.com/OP-TEE/optee_os/issues/5418

**Comment by jforissier** [comment]
For `4b46e0e81`:

`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (vexpress-qemu_virt, GP, PKCS#11)`

**Comment by manorit2001** [comment]
For `4b46e0e81`

`Tested-by: Manorit Chawdhry <m-chawdhry@ti.com> (k3-j721e)`

**Comment by sahilnxp** [comment]
Hello

For `4b46e0e81`

Tested-by: Sahil Malhotra [sahil.malhotra@nxp.com](mailto:sahil.malhotra@nxp.com) (LS1012A-RDB)
Tested-by: Sahil Malhotra [sahil.malhotra@nxp.com](mailto:sahil.malhotra@nxp.com) (LS1028A-RDB)
Tested-by: Sahil Malhotra [sahil.malhotra@nxp.com](mailto:sahil.malhotra@nxp.com) (LS1088A-RDB)
Tested-by: Sahil Malhotra [sahil.malhotra@nxp.com](mailto:sahil.malhotra@nxp.com) (LS2088A-RDB)
Tested-by: Sahil Malhotra [sahil.malhotra@nxp.com](mailto:sahil.malhotra@nxp.com) (LS1046A-RDB)
Tested-by: Sahil Malhotra [sahil.malhotra@nxp.com](mailto:sahil.malhotra@nxp.com) (LS1043A-RDB)
Tested-by: Sahil Malhotra [sahil.malhotra@nxp.com](mailto:sahil.malhotra@nxp.com) (LX2160A-RDB)
Tested-by: Sahil Malhotra [sahil.malhotra@nxp.com](mailto:sahil.malhotra@nxp.com) (LX2160A-QDS)

**Comment by jforissier** [comment]
For `b7563bab0`:

`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (hikey-hikey, GP, PKCS#11)`

**Comment by jenswi-linaro** [comment]
For b0ba0031ff2b89e15722914c395879946f9caf9c:
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)`

**Comment by jenswi-linaro** [comment]
For 3.19.0-rc1
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (imx-mx8mqevk)`

**Comment by igoropaniuk** [comment]
For 3.19.0-rc1
Tested-by: Igor Opaniuk <igor.opaniuk@foundries.io> (Poplar)

```
+-----------------------------------------------------
26307 subtests of which 0 failed
98 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

There is unrelated to OP-TEE OS (rather to Poplar builroot setup) problem, at some point kernel increased in size, so now hitting this issue in U-Boot:

```
Device 0: unknown device
switch to partitions #0, OK
mmc0(part 0) is current device
Scanning mmc 0:2...
Found /extlinux/extlinux.conf
Retrieving file: /extlinux/extlinux.conf
180 bytes read in 2 ms (87.9 KiB/s)
1:	Buildroot
Retrieving file: /extlinux/../Image
36440576 bytes read in 1614 ms (21.5 MiB/s)
append: mem=1G root=/dev/mmcblk0p3 rootfstype=ext4 rootwait rw earlycon=pl011,0xf8b00000 mmz=ddr,0,0,60M
Retrieving file: /extlinux/../hisilicon/hi3798cv200-poplar.dtb
14390 bytes read in 4 ms (3.4 MiB/s)
## Flattened Device Tree blob at 32200000
   Booting using the fdt blob at 0x32200000
ERROR: FDT image overlaps OS image (OS=0x30000000..0x32360000)
SCRIPT FAILED: continuing...
14390 bytes read in 4 ms (3.4 MiB/s)
BOOTP broadcast 1
DHCP client bound to address 1
```

Adjusting `fdt_addr_r` in U-Boot obviously fixes the problem, but as poplar manifest points to mainline U-Boot, tbh I'm not sure how that can be addressed properly:
1. U-Boot fork (v2021.07 + `fdt_addr_r` patch) + poplar.xml pointing to that fork
2. Play with `build/kconfigs/poplar.conf`, unsetting unneeded Kconfig symbols to decrease Linux image in size

**Comment by jenswi-linaro** [comment]
For ecd7f426fb4f7b5f15cab37fe20df8c76ededcc4
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (FVP)`

**Comment by jenswi-linaro** [comment]
@igoropaniuk, this isn't the first time I've seen this kind of error in U-Boot. The solution is often to change the FDT address until things work again, but given that this occurs again and again it would be nice if this was handled automatically by U-Boot instead. Regardless, it seems that the fix should be done in the upstream U-Boot.

OP-TEE itself works and that's most important, so the tested by is good and I guess that's enough for this release. We could if needed add a note of the problem somewhere.

**Comment by balint-dobszay-arm** [comment]
For 3.19.0-rc1:
`Tested-by: Balint Dobszay <balint.dobszay@arm.com> (fvp-ts)`

**Comment by ricardosalveti** [comment]
For ecd7f426fb:

```
Tested-by: Ricardo Salveti <ricardo@foundries.io> (imx-mx8mmevk, plug-and-trust v0.4.0)
Tested-by: Ricardo Salveti <ricardo@foundries.io> (ZynqMP, GP, PKCS#11)
```

While xtest works on imx-mx8mmevk with plug-and-trust (SE05X), it can fail when running in loop, which is fixed by https://github.com/OP-TEE/optee_os/pull/5541.

**Comment by etienne-lms** [comment]
Thanks @jforissier. sorry for that.

Tag fixup (to show which flavors were tested):
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1-157C_DK2, gp, pkcs11)`
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1-157C_DK2, gp, pkcs11)`

**Comment by etienne-lms** [comment]
right!
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1-157C_DK2, gp, pkcs11)`
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1-157C_EV1, gp, pkcs11)`

**Pull request merged**
