### PR TITLE
Master+warp7 mbl

### PR DESCRIPTION
**Pull request by bryanodonoghue**
This PR adds a new platform based on the WaRP7 "WaRP7_mbl".

The Kernel DTB is contained in a u-boot FIT image so a DTB overlay as is provided for in f41e7926 is used to allow u-boot to extract a verified kernel DTB from a FIT image and apply an overlay, before handing off to Linux.

Given the DTB is loaded after OPTEE it is necessary to make a small modification to the i.MX watchdog code to make sure we can tell it how to reboot the system.

This separate config allows for easy differentiation between the existing WaRP7 bootflow and the MBL specific bootlfow.

If this format is acceptable, then other A7 ATF/OPTEE ports for the MBL project will follow a similar bootflow and similar naming convention.

The u-boot changes that accompany this are here:
https://git.linaro.org/landing-teams/working/mbl/u-boot.git/log/?h=master_warp7_bl33%2bfit-development%2bintegrated_kernel_fit-overlay

ATF here:
https://git.linaro.org/landing-teams/working/mbl/arm-trusted-firmware.git/log/?h=integration%2bwarp7_tbb%2bdtb_change

### CODE REVIEW

**Comment by bryanodonoghue** [comment]
@MrVan

**Comment by jforissier** [comment]
Minor comment: the build command in the third patch:
```
make CROSS_COMPILE=arm-linux-gnueabihf- PLATFORM=imx \
     PLATFORM_FLAVOR=mx7swarp7_mbl ARCH=arm CFG_PAGEABLE_ADDR=0 \
     CFG_TEE_CORE_NB_CORE=1
```
...could be simplified to:
```
make PLATFORM=imx-mx7swarp7_mbl
```
...because:
- `arm-linux-gnueabihf-` is the default compiler prefix for arm32
- `ARCH` is forced to `arm` in `Makefile`
- `PLATFORM_FLAVOR` can always be combined with the main platform name using syntax: platform dash flavor
- `CFG_PAGEABLE_ADDR` and `CFG_TEE_CORE_NB_CORE` default to the values you give anyway

**Comment by MrVan** [comment]
With @jforissier 's comments addressed: `Reviewed-by: Peng Fan <peng.fan@nxp.com>`

**Comment by bryanodonoghue** [comment]
Hmm.
Not understanding that error. I'll do a force update push to see if it goes away.

**Pull request merged**
