### PR TITLE
Fix RNG and HUK ELE API

### PR DESCRIPTION
**Pull request by clementfaure**
Hello,
Two patches to fix ELE RNG and HUK API calls. This is related to a recent firmware change.

Thanks!

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Are these changes backward compatible or will OP-TEE have to be updated in sync with the firmware?

**Comment by clementfaure** [comment]
Hello @jenswi-linaro ,
This change is not backward compatible. For now, the support for imx93 is labelled as pre-production support, so breaking changes are expected.

**Comment by jenswi-linaro** [comment]
OK, it might be worth mentioning something about that in the commit message.

**Comment by clementfaure** [comment]
Force-push
* Commit re-word
* Rebase

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Pull request merged**
