### PR TITLE
Added 64-bit RISC-V ta compilation

### PR DESCRIPTION
**Pull request by liushiwei007**

### CODE REVIEW

**Comment by jforissier** [comment]
Hello @liushiwei007,

In commit "ta: support RISC-V", about 99% of the code should be common with Arm. On the other hand you're keeping a few lines related to BTI and memtag stuff which are clearly Arm-specific. So that's not how it should be done.

**Comment by liushiwei007** [comment]
> 



> Hello @liushiwei007,
> 
> In commit "ta: support RISC-V", about 99% of the code should be common with Arm. On the other hand you're keeping a few lines related to BTI and memtag stuff which are clearly Arm-specific. So that's not how it should be done.

Then what should I do better, delete BTI and memtag, or find a way to make this part public.
on the other hand,  the following code seems no longer allowed 
   34 extern uint8_t ta_heap[];
   35 extern const size_t ta_heap_size;
   36 extern struct ta_head ta_head;
Can you put them in user_ta_header.h?

**Comment by jforissier** [comment]
@liushiwei007 I would first try to move `user_ta_entry.c` and `user_ta_header.c` outside `arch/arm` and see if that works for RISC-V too. Then maybe split `link.mk` into a common part and an arch-specific part (`ta/devkit/link.mk`, `ta/devkit/arch/arm/link_arm.mk`).

> on the other hand, the following code seems no longer allowed
> 34 extern uint8_t ta_heap[];
> 35 extern const size_t ta_heap_size;
> 36 extern struct ta_head ta_head;
> Can I put them in user_ta_header.h?

The `extern` keyword should be avoided but I don't think we can avoid it for these variables.

**Comment by liushiwei007** [comment]
ok，Then I will wait for you to finish this part first, and I will submit the other parts first.

**Comment by jforissier** [comment]
@liushiwei007 there is a misunderstanding, I do not intend to refactor the code myself, I was just saying "if I were you I would..." :wink: please propose something.

**Comment by liushiwei007** [comment]
> @liushiwei007 there is a misunderstanding, I do not intend to refactor the code myself, I was just saying "if I were you I would..." 😉 please propose something.

Ok, I will try to modify the parts with less impact first

**Comment by liushiwei007** [comment]
@jforissier hi, Did I do something wrong? I think that these error messages have nothing to do with my submission.
Like the following:
/root/optee_repo_qemu_v8/out-br/build/optee_test_ext-1.0/host/xtest/xtest_helpers.h:13:10: fatal error: tee_api_compat.h: No such file or directory
   13 | #include <tee_api_compat.h>
WARNING: IS_ENABLED(_CFG_TA_STACK_PROTECTOR) is normally used as IS_ENABLED(CFG__CFG_TA_STACK_PROTECTOR)
#8388: FILE: ta/arch/arm/user_ta_header.c:55:
+	if (IS_ENABLED(_CFG_TA_STACK_PROTECTOR) && !stack_canary_inited) {

**Comment by jforissier** [comment]
> Did I do something wrong? I think that these error messages have nothing to do with my submission.

Indeed, please rebase onto the `master` branch and CI should pass.

**Comment by jenswi-linaro** [comment]
There's a strange merge commit, please remove that.

**Comment by liushiwei007** [comment]
Thanks for the help. I took care of the CI. It was resubmitted to #5693

**Pull request closed without merging**
