### PR TITLE
MAINTAINERS: Update Corstone1000 maintainer

### PR DESCRIPTION
**Pull request by xueliang-zhong-arm**
Update maintainer of ARM Corstone1000 to Emekcan Aras.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
@vishnu-banavath, OK with you?
BTW, why isn't the new maintainer doing this PR?

**Comment by xueliang-zhong-arm** [comment]
Emekcan Aras is currently active developer of ARM Corstone-1000 board in various projects, including supporting Corstone-1000 optee recipes & patches in Yocto meta-arm, e.g.:
https://git.yoctoproject.org/meta-arm/log/?qt=grep&q=Emekcan+Aras

If the OP-TEE maintainers require Emekcan himself to raise such PR, that is fine, we'll raise a new PR. Please confirm.

**Comment by jforissier** [comment]
I suppose we could do with an `Acked-by:` from both @ememarar and @vishnu-banavath

**Comment by ememarar** [comment]
Sorry, we talked to Xueliang about this, but I was a bit busy, so he helped :) looks good to me.

**Comment by xueliang-zhong-arm** [comment]
Vishnu is on vacation this week, I'll ask him to `ack` this PR next week. Thanks all.

**Comment by vishnu-banavath** [comment]
I'm ok with this change and sorry for the delayed response.

Thanks

**Review by vishnu-banavath — APPROVED** [review]

**Comment by jforissier** [comment]
Thanks @vishnu-banavath 
@xueliang-zhong-arm can you please add `Acked-by: Vishnu Banavath <vishnu.banavath@arm.com>`? Thanks!

**Comment by xueliang-zhong-arm** [comment]
Hi, I've just added
`Acked-by: Vishnu Banavath <vishnu.banavath@arm.com>`
in the comment message.

**Comment by jforissier** [comment]
I have added Emeckan's Acked-by too. Merged, thanks.

**Pull request closed without merging**
