### PR TITLE
plat-hikey: define DRAM1_BASE for defining the size of TA's secure memory when building OP-TEE

### PR DESCRIPTION
**Pull request by TaihuLight**
plat-hikey: make DRAM1_BASE configurable
Adds CFG_DRAM1_BASE configuration switch in the platform to allow one to tune DRAM1_SIZE.

#5146
#4768
#6160

Signed-off-by: Loonloon <cloudiot@126.com>

### CODE REVIEW

**Review by etienne-lms — COMMENTED** [review]
Please fix the commit message:
```
plat-hikey: define DRAM1 and CPU count for HiKey-960
...
```

The changes apply for both `hikey` and `hikey960`. Should use `ifeq ($(PLATFORM_FLAVOR),hikey960)`?

**Comment by TaihuLight** [comment]
@etienne-lms Thank you for your review. I fixed the commit, the define could work for both Hikey 960 and HiKey.

**Review by jenswi-linaro — COMMENTED** [review]
Please add a sentence in the commit message describing the purpose of this change. The two links are good references, but it's good to have something directly in the commit message too.

**Review by etienne-lms — COMMENTED** [review]
The change looks good to me but the commit message should be updated to something like:
```
plat-hikey: make DRAM1_BASE configurable

Adds CFG_DRAM1_BASE configuration switch in the platform to allow
one to tune DRAM1_SIZE.

Signed-off-by: ...
```
Please use your full name in your Signed-off-by tag.

**Comment by TaihuLight** [comment]
@etienne-lms I have fixed the commit message.

**Pull request closed without merging**
