### PR TITLE
core: allow CFG_TEE_LOAD_ADDR to not be page aligned

### PR DESCRIPTION
**Pull request by etienne-lms**
Fixes https://github.com/OP-TEE/optee_os/issues/1556

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
It's better to point out the commit that is fixed because that's part of the history while the pull request is less specific and also not part of the history. With that fixed:
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
@jenswi-linaro I agree. @etienne-lms please add the commit reference, but also keep the GitHub since it is somewhat useful when writing release notes.

**Comment by etienne-lms** [comment]
Ok, i'll keep both reference.

**Comment by jforissier** [comment]
Missing Acked-by added and patch merged.

**Pull request closed without merging**
