### PR TITLE
core: replace REGISTER_TIME_SOURCE()

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Remove REGISTER_TIME_SOURCE() and implement tee_time_get_sys_time() and tee_time_get_sys_time_protection_level() directly in the file where REGISTER_TIME_SOURCE() was used previously.

### CODE REVIEW

**Review by etienne-lms — COMMENTED** [review]
`Reviewed-by: Etienne Carriere <etienne.carriere@foss.st.com>`

**Review by jforissier — COMMENTED** [review]
Perhaps mention why.

`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by etienne-lms** [comment]
> Perhaps mention why.

Simplification I guess.

**Comment by jenswi-linaro** [comment]
Tags applied. I've added one more paragraph to the commit message.

**Pull request merged**
