### PR TITLE
GP Internal Core API v1.1 : generic object functions

### PR DESCRIPTION
**Pull request by cedric-chaumont-st-dev**
Signed-off-by: Cedric Chaumont <cedric.chaumont@st.com>

Vote: For testing use optee_test dev/gp11_generic_obj branch

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
Apart from an open question on issue tracking,

    Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by cedric-chaumont-st-dev** [comment]
Rebased

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by cedric-chaumont-st-dev** [comment]
Rebased.  Verified.
Tested-by: Cedric Chaumont <cedric.chaumont@linaro.org> (STM boards)
Tested-by: Cedric Chaumont <cedric.chaumont@linaro.org> (ARM Juno board)

**Pull request merged**
