### PR TITLE
clk: stm32mp25: fix some error cases management

### PR DESCRIPTION
**Pull request by etienne-lms**

### CODE REVIEW

**Comment by etienne-lms** [comment]
@Gabriel-Fernandz, could you have a look at these changes?

**Comment by GseoC** [comment]
Keep alive

**Comment by etienne-lms** [comment]
Please, keep alive.

**Comment by etienne-lms** [comment]
@Gabriel-Fernandez could you have a look at this change?

**Review by Gabriel-Fernandz — APPROVED** [review]
Hi you can add my Reviewed-by: Gabriel Fernandez gabriel.fernandez@foss.st.com

**Review by Gabriel-Fernandz — APPROVED** [review]

**Review by Gabriel-Fernandz — APPROVED** [review]
Hi you can add my Reviewed-by: Gabriel Fernandez gabriel.fernandez@foss.st.com

**Comment by etienne-lms** [comment]
Review tag applied. Thanks.

**Pull request merged**
