### PR TITLE
Update CHANGELOG for 3.8.0

### PR DESCRIPTION
**Pull request by jforissier**
Update CHANGELOG for 3.8.0 and collect Tested-by tags.

Signed-off-by: Jerome Forissier <jerome@forissier.org>

### CODE REVIEW

**Comment by jbech-linaro** [comment]
Tested with RPi3b using latest as of today. Will try once more when we have the RC-tag ready.

`Tested-by: Joakim Bech <joakim.bech@linaro.org>` (RPi3b)
```bash
24352 subtests of which 0 failed
96 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by igoropaniuk** [comment]
Poplar with the latest `91fc6bd893("core: crypto: add support for SM2 PKE")`:

```
# xtest -l20
+-----------------------------------------------------
44345 subtests of which 0 failed
97 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by glneo** [comment]
With latest:
```Tested-by: Andrew F. Davis <afd@ti.com>``` (plat-ti)

**Comment by jenswi-linaro** [comment]
Trouble on Juno, see https://github.com/OP-TEE/optee_os/issues/3529

**Comment by jforissier** [comment]
With latest:
`Tested-by: Jerome Forissier <jerome@forissier.org> (HiKey)`

**Comment by jenswi-linaro** [comment]
With https://github.com/OP-TEE/optee_os/pull/3535 on top of latest:
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)`

**Comment by jforissier** [comment]
Latest master (67283c27):

`Tested-by: Jerome Forissier <jerome@forissier.org> (HiKey960, GP)`
```
$ xtest
...
28707 subtests of which 0 failed
742 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by lorc** [comment]
Hi @jforissier, will be there tag/release branch? IIRC there were tags for previous releases.
Or should  I test the master branch?

**Comment by jforissier** [comment]
@lorc yes, the plan is to create the 3.8.0-rc1 tag tomorrow.

**Comment by b49020** [comment]
With release tag: `3.8.0-rc1`:

`Tested-by: Sumit Garg <sumit.garg@linaro.org> (Developerbox)`

```
$ xtest -l 15
...
+-----------------------------------------------------
44526 subtests of which 0 failed
96 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by igoropaniuk** [comment]
Poplar retested with release tag `3.8.0-rc1`:

```
# xtest -l20
+-----------------------------------------------------
44345 subtests of which 0 failed
97 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

`Tested-by: Igor Opaniuk <igor.opaniuk@gmail.com> (Poplar)`

**Comment by jforissier** [comment]
HiKey960 tested with release tag `3.8.0-rc1`, `xtest` with GlobalPlatform tests:

```
# xtest
...
28707 subtests of which 0 failed
742 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

`Tested-by: Jerome Forissier <jerome@forissier.org> (HiKey960, GP)`

**Comment by jforissier** [comment]
QEMUv8 with `3.8.0-rc1` is:

`Tested-by: Jerome Forissier <jerome@forissier.org> (QEMUv8)`

**Comment by bryanodonoghue** [comment]
```
# xtest
...
24078 subtests of which 0 failed
95 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

`Tested-by: Bryan O'Donoghue <bryan.odonoghue@linaro.org> WaRP7`

**Comment by jforissier** [comment]
Tag `3.8.0-rc1`:
`Tested-by: Jerome Forissier <jerome@forissier.org> (HiKey)`

**Comment by lorc** [comment]
With #3546:

`Tested-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com> (Rcar H3)`

Virtualization is still broken, thought. See #3543.

**Comment by jforissier** [comment]
I believe all known problems have been fixed, it is time to tag the release.
Thanks everybody :+1:

**Comment by jenswi-linaro** [comment]
Thank you @jforissier !

**Comment by jforissier** [comment]
For the record, I have updated the LibTomCrypt branch `import/libtomcrypt-1.18.2-develop-20180819`, that is:
- cherry-picked the LTC commits present in master but not yet in the import branch,
- merged master into the import branch so that it is in a useable state for further developments (build, CI... shippable log [here](https://app.shippable.com/github/OP-TEE/optee_os/runs/4232/1/console)).

**Pull request merged**
