### PR TITLE
Update travis for gcc5

### PR DESCRIPTION
**Pull request by jbech-linaro**
Signed-off-by: Joakim Bech <joakim.bech@linaro.org>

### CODE REVIEW

**Comment by jbech-linaro** [comment]
This should be merged after:
https://github.com/OP-TEE/build/pull/65
has been merged.

**Comment by pascal-brand-st-dev** [comment]
`Reviewed-by: Pascal Brand <pascal.brand@linaro.org>`

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jbech-linaro** [comment]
I'm puzzled why `wget` failed in Travis, the previous job 5 days ago was working. I tried copy/paste the failing line in a console here and it works here? Change it to `curl -L` to ensure it follows redirections?

Otherwise, patch rebased, tags applied and ready for merge.

**Comment by jforissier** [comment]
The Travis error is not related to redirection it seems, probably a temporary error with the Linaro release server.

**Comment by jbech-linaro** [comment]
I could try force push once more just to see if it was a temporary hickup?

**Comment by jforissier** [comment]
Yes or you can just click on the relaunch button if you are an admin of the project I think.

**Comment by jbech-linaro** [comment]
I'm not admin there I think, the re-launch didn't work there. But I've started it on the branch for the pull request (the branch I own).
https://travis-ci.org/jbech-linaro/optee_os/builds/132858278

**Comment by jbech-linaro** [comment]
It seems like it was happy when I just re-triggered the build on my local branch, so probably just a temporary hick-up. @pascal-brand-st-dev do you want me to force push again, to trigger travis here again? The PR is coming from the branch that worked after re-trigger the build.

**Pull request merged**
