### PR TITLE
ta: pkcs11: PKCS11_CKM_AES_CBC_PAD is not supported

### PR DESCRIPTION
**Pull request by etienne-lms**
Remove PKCS11_CKM_AES_CBC_PAD from the list of the supported mechanism
as it is not implemented by the TA.

Fixes: https://github.com/OP-TEE/optee_os/issues/5142
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

### CODE REVIEW

**Comment by cmcgcc** [comment]
Would it be better just add some comments to mark it unfinished? The patch will eventually be reverted.
In terms of the cr itself, these two places also need removal.
https://github.com/OP-TEE/optee_os/blob/e42199d0ac15b260f35fb1a3d076fd5313b292ea/ta/pkcs11/src/token_capabilities.c#L73
https://github.com/OP-TEE/optee_os/blob/e42199d0ac15b260f35fb1a3d076fd5313b292ea/ta/pkcs11/src/token_capabilities.c#L374

**Comment by etienne-lms** [comment]
Thanks for the feedback.

`MECHANISM(PKCS11_CKM_AES_CBC_PAD, ...)` defines the mechanism in array `pkcs11_modes[]` ([token_capabilities.c](https://github.com/OP-TEE/optee_os/blob/e42199d0ac15b260f35fb1a3d076fd5313b292ea/ta/pkcs11/src/token_capabilities.c#L69)) that lists the PKCS#11 mechanism properties as per the specification, for reference. So we should keep AES_CBC_PAD reference here.

My change removes the AES_CBC_PAD entry from `token_mechanism[]` (`TA_MECHANISM(...)`) which lists the mechanisms/operations supported by the TA, hence to be removed.

I agree  `case PKCS11_CKM_AES_CBC_PAD:` could be removed from `pkcs11_mechanism_supported_key_sizes()`. I'll update this P-R.

**Comment by vesajaaskelainen** [comment]
Hmm :grin: https://github.com/vesajaaskelainen/optee_os/commit/b06bf1901b54140aad869dcd2995e7caa4339b07

Wondering should we polish that instead?

**Comment by cmcgcc** [comment]
We are implementing one internally for encryption. We can probably share it if no one is working on it.

**Comment by etienne-lms** [comment]
@vesajaaskelainen and @cmcgcc: are you ok we merge the current P-R as is, to reflect current implementation?

**Comment by cmcgcc** [comment]
We have a proposal for encryption padding. It is under internal reviewing process for oss publishing. Would you like to wait a day or two?

**Comment by vesajaaskelainen** [comment]
> We have a proposal for encryption padding. It is under internal reviewing process for oss publishing. Would you like to wait a day or two?

I don't think we are that hurry. Waiting to see updated PR with the support.

**Comment by etienne-lms** [comment]
No real hurry. Let's at least target an update before next 3.17.0 tag ([planned mid April](https://optee.readthedocs.io/en/latest/general/releases.html?highlight=3.17.0)).

**Comment by etienne-lms** [comment]
@vesajaaskelainen, @cmcgcc, do you ack this change for 3.17.0 tag?

**Comment by vesajaaskelainen** [comment]
Sure.

`Acked-by: Vesa Jääskeläinen <vesa.jaaskelainen@vaisala.com>`

**Comment by etienne-lms** [comment]
tag applied

**Pull request merged**
