### PR TITLE
core: fix weakness in shm registration

### PR DESCRIPTION
**Pull request by etienne-lms**
When core needs to validate content before it is used, core must first
move the data in secure memory, then validate it (or not), then access
validated data from secure memory only, not from original shared memory
location.

This change fixes mobj_reg_shm_alloc() so that it checks the validity
of the registered reference after the references are copied into the
secure memory.

This change fixes mobj_mapped_shm_alloc() to use the shm buffer reference
instead of the initial description still located in shared memory.

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

### CODE REVIEW

**Comment by etienne-lms** [comment]
tag applied

**Comment by lorc** [comment]
Guys, looks I missed this PR. 

Actually, you didn't fixed anything, as there was no issue.

`pages` parameter for `mobj_reg_shm_alloc()` and `mobj_mapped_shm_alloc()` is an array allocated inside OP-TEE. It is secure memory. This array is filled inside `msg_param.c` by function `msg_param_extract_pages()`. 

This change causes no harm (except that new code is harder to read), so it is okay. But I will be very grateful, if you'll invite me next time to review such changes.

**Comment by etienne-lms** [comment]
hello @lorc.  I had I new look at the change.

From my view, at the time, i understood the apis `mobj_reg/mapped_shm_alloc()` were designed to handle shm reference passed through the shm. So the change proposed. As apis do not check if parameter `vaddr_t *params` is pointing to secure or non secure memory.
Looking back, you could argue that one should assume these apis targets secure data references only. That's true. This is the case with the coming changes you are referring to.

About notifying you, I understand I could have pinged you during the review to get your feedback since your merge was quite recent. My apologies. On the other hand, there will be other changes coming and I can't promise to notify for all those that are related to the mobj or some shared memory handling.
With all due respect.

**Comment by lorc** [comment]
@etienne-lms, excuse me, no offense meant. I was just surprised to see this patch.

Probably I had to mention somewhere that input parameters to those functions are considered secure. 

Maybe it is good idea to introduce special attribute like

**Comment by etienne-lms** [comment]
Good morning @lorc. There is no offense.
The attribute idea may be a good idea. How it's used and asserted might be quite intrusive but why not. Indeed manipulating data from the non secure memory is a specific operation in the TEE scope.

**Pull request merged**
