### PR TITLE
Fix OPTEE startup on RCAR H3 platform.

### PR DESCRIPTION
**Pull request by lorc**
There are two patches that together fix https://github.com/OP-TEE/optee_os/issues/1460

One of them is RCAR-specific. Another one is more general, as it applicable to all platforms.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
In the first commit message `s/Never/Newer/`

**Comment by lorc** [comment]
@jenswi-linaro done.

**Comment by jenswi-linaro** [comment]
With commit message fixed:
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by lorc** [comment]
Should we wait for another review?

**Comment by jenswi-linaro** [comment]
It has to be tested in some different configurations, LPAE, non-LPAE, pager, no pager.
Perhaps @etienne-lms can take a look also.

**Comment by etienne-lms** [comment]
This change is fine and indeed useful. There are few ROUNDDOWN/ROUNDUP in platform code that could be cleaned once this change merged.

I have tested this on qemu_virt (for ARMv7) with/without pager and with/without LPAE, with some extra mapping requests to exercise various cases. Everything was fine.
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (qemu_virt)`

Sole minor comment: i think we try to not add references to OPTEE issues/PR in commit message as they may be meaningless in the future. @lorc, I think you can remove it from the 2nd commit message, your description is clear enough.

**Comment by lorc** [comment]
Removed reference to GH, added `Reviewed-by` and `Tested-by` tags.

**Comment by jbech-linaro** [comment]
There was an error in Travis, but I think that also was related to Jens last patch in xtest. I've just triggered a re-run och Travis for the patches here. When that is done I'll merge the fixes here.

**Comment by etienne-lms** [comment]
travis failure is due the the htree and will be fixed through https://github.com/OP-TEE/optee_os/pull/1463.

**Comment by jbech-linaro** [comment]
@lorc, I think your patch is fine as such, would you mind just rebase it on top of latest and then I can just merge it.

**Comment by lorc** [comment]
@jbech-linaro, I have rebased it a few seconds ago.

**Comment by jbech-linaro** [comment]
Thanks for the contribution @lorc! I did a quick test (QEMU) before merging  and all worked fine.

**Pull request merged**
