### PR TITLE
plat-rpi3: Fix compile when CFG_DT=y

### PR DESCRIPTION
**Pull request by bryanodonoghue**
commit e9495e2a350d ('generic_boot: reserve optee_tzdram memory') adds a
dependency on CFG_TZDRAM_START and CFG_TZDRAM_SIZE respectively. For the
rpi3 though which usually is not compiled with CFG_DT=y the lack of
definition of these two defines is not apparent.

This patch fixes the omission by defining both missing symbols.

### CODE REVIEW

**Comment by bryanodonoghue** [comment]
ping @grandpaul

**Comment by bryanodonoghue** [comment]
Fixes compile error for me with the following command line

make CROSS_COMPILE=/opt/linaro/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf- CFG_DT=y CFG_TEE_CORE_LOG_LEVEL=1 LDFLAGS= NOWERROR=1 PLATFORM=rpi3 CROSS_COMPILE_ta_arm32=arm-oe-linux-gnueabi- CROSS_COMPILE_core=aarch64-linux-gnu- CFG_DT_ADDR=0x03000000 CFG_ARM64_core=y all CFG_TEE_TA_LOG_LEVEL=0

**Comment by Emantor** [comment]
`Reviewed-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>`

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
If i'm not mistaking, maybe consider using **generic_memory_layout.h** as done in https://github.com/OP-TEE/optee_os/pull/2915.

**Comment by etienne-lms** [comment]
Also, as this fix a build with specific config, maybe add into the commit comment the failing build command and related error traces you get before this change is applied. This could help others to find this change when facing the same situation.

**Comment by bryanodonoghue** [comment]
I think @grandpaul already had the fix in #2915 in his tree - lets use that instead.

**Pull request closed without merging**
