### PR TITLE
Update rpi3.md

### PR DESCRIPTION
**Pull request by aj700**
It seems such a manifest file is missing in the manifest git. I can only see a rpi3.xml and a rpi3_stable.xml. Is that right?

### CODE REVIEW

**Comment by jbech-linaro** [comment]
Thanks @aj700 , I missed this when we did the release last week.
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
@aj700 please reword your commit message, we don't want a question there. And add Joakim's R-b tag. And rebase on top of latest optee_os/master. Thanks!

**Comment by aj700** [comment]
I have uploaded a new pull request after reabse.
https://github.com/OP-TEE/optee_os/pull/1126

**Comment by aj700** [comment]
Not a github ninja, and didnt really understand what R-b tag meant(now I know :D). Hope the new pull request helps you.

**Comment by jforissier** [comment]
You could (should) have force-pushed to the same branch, hence the same PR. No need to open a new one. Not a big deal though.

**Pull request closed without merging**
