### PR TITLE
Concurrent pager

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Checkpatch complains about a long line, other that travis is happy.

**Comment by jbech-linaro** [comment]
Just a few minor comments. The name change from `thread` to `thr` in one of the patches could have been done separately to make it easier to actually see the differences. The last patch was rather complicated, I hope I understood it. For this patch set I don't want you to squash the patches. It is quite nice to have them as you have done here.

Even with the comments:
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jenswi-linaro** [comment]
Added a bugfix affecting Juno and presumably Hikey.

**Comment by jenswi-linaro** [comment]
Comments address. Please have a look at "pager: bug fix boot time moving of hashes" too.

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey)`

I can confirm HiKey is affected by the bug fixed in the last commit. With all patches in this PR:

```
root@HiKey:/ xtest -l 15
[...]
48300 subtests of which 0 failed
702 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```

**Comment by jenswi-linaro** [comment]
Rebased and tags applied. Note that there's no review tag (yet) for "pager: bug fix boot time moving of hashes"

**Comment by jenswi-linaro** [comment]
Review tag added for "pager: bug fix boot time moving of hashes", thanks Jerome!
Now all commits have one review tag each.

**Pull request merged**
