### PR TITLE
TEE file format and key manager data structure refactoring

### PR DESCRIPTION
**Pull request by jamescfkung**
Signed-off-by: James Kung james.kung@linaro.org
Tested-by: James Kung james.kung@linaro.org (QEMU)

### CODE REVIEW

**Comment by jamescfkung** [comment]
Compiling optee_test failed due to optee_test depends on tee_fs_key_manager.h in optee_os.
In this patch, I modified the data structures in tee_fs_key_manager.h in order to solve some security issues.
If Travis CI cannot handle the dependency automatically, we should do the xtest manaully.

**Comment by jforissier** [comment]
On Fri, Jan 22, 2016 at 2:38 AM, James Kung <notifications@github.com>
wrote:

If Travis CI cannot handle the dependency automatically, we should do the
> xtest manaully.
>

I hope it's a joke.

**Comment by jamescfkung** [comment]
The secure storage design change is documented in the [presentation file] (https://docs.google.com/presentation/d/1mnXQ4Lp-8wl3zTMuQHBEVNPE0Lpmicvn44Q-2whSD5M/edit?usp=sharing) (marked with red color)

**Comment by jamescfkung** [comment]
Rebased

**Comment by d3zd3z** [comment]
This is a really big change. Glancing through it, it at least looks like it is mostly refactoring, but there also seems to be a change of unlink to force unlink. Ideally, the steps of the refactoring would be broken down into separate commits and good descriptions of the change should be in the commit text. A good test is if you need to say "also..." in the commit text, the part after that probably belongs in a separate commit. It should be possible to look at the commit text, and the diff of the patch and see that it is just a refactor. It'd also be nice if each step could build (this also helps when doing the refactoring).

It's probably too late to break this down now, since it is all squashed into a single commit, but something to keep in mind in the future.

**Comment by d3zd3z** [comment]
Also, note that `core/tee/tee_fs_common.c` is too large to show in the github gui. There are two spurious blank lines at the end of this file.

**Comment by jbech-linaro** [comment]
@jforissier , do you agree with me that this PR has become outdated and isn't relevant any longer? I.e, I'd like to close it.

**Comment by jforissier** [comment]
@jbech-linaro yes, unless there is more to it than code cleaning. Well, actually I think there is: https://github.com/OP-TEE/optee_os/pull/624#issuecomment-173772216 mentions "security issues". Unfortunately the document link in https://github.com/OP-TEE/optee_os/pull/624#issuecomment-174861783 does not work anymore :( but I think this PR was also addressing the TA storage separation issues by including the TA UUID in the encryption. Since this has been addressed differently in https://github.com/OP-TEE/optee_os/commit/fde4a756bfc837d36bae74853194f0f6646e7b36 I think this one can be closed.

@jamescfkung: feel free to chime in ;)

**Comment by jbech-optee-adm** [comment]
I'm closing this PR, since it's no longer valid.

**Pull request closed without merging**
