### PR TITLE
plat-vexpress: Change UART1_BASE and IT_UART1

### PR DESCRIPTION
**Pull request by vchong**
This is required to move OP-TEE to upstream QEMU.

Signed-off-by: Victor Chong <victor.chong@linaro.org>
Suggested-by: Peter Maydell <peter.maydell@linaro.org>
Tested-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by vchong** [comment]
Depends on https://github.com/linaro-swg/bios_qemu_tz_arm/pull/1.

+-----------------------------------------------------------------------------------------
Results of testsuite XTEST_TEE_TEST:
+-----------------------------------------------------------------------------------------
27277 subtests of which 0 failed
59 test cases of which 0 failed
0 test case was skipped
TEE test application done!

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jbech-linaro** [comment]
Reviewed-by: Joakim Bech <joakim.bech@linaro.org>

**Comment by vchong** [comment]
Tags applied. Please merge. Thanks!

**Pull request merged**
