### PR TITLE
plat-stm32mp1: fix clock, scmi channel IDs and disable BGET tests

### PR DESCRIPTION
**Pull request by etienne-lms**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
tag applied

**Comment by jforissier** [comment]
@etienne-lms should this be considered fixes that need to be picked in 3.13.0?

**Comment by etienne-lms** [comment]
yes please, these are needed in 3.13.0, definitely.

**Pull request merged**
