### PR TITLE
core: arm: imx: Support psci feature query

### PR DESCRIPTION
**Pull request by niej**
Add psci features list for query. The list is based on
current implemented psci functions.

Signed-off-by: Jun Nie <jun.nie@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Please expand the commit message. It's at least not clear to me what the purpose is.

**Comment by niej** [comment]
@jenswi-linaro OK. Do you think below information is enough to explain the patch?

Support PSCI call to query features list. So that non-secure world knows what features are supported by ATF. The feature list is based on current implemented iMX psci functions.

**Comment by jenswi-linaro** [comment]
Sounds good. With that:
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

We'll need an ack from @mrvan too.

**Comment by MrVan** [comment]
Acked-by: Peng Fan <peng.fan@nxp.com>

**Comment by niej** [comment]
@jenswi-linaro @MrVan 
Thanks for your review! The branch for pull requested has been updated with new commit message and act tag.

**Comment by jforissier** [comment]
Thanks @niej!

**Pull request merged**
