### PR TITLE
Rpmb fix

### PR DESCRIPTION
**Pull request by jenswi-linaro**
For all tests to pass https://github.com/OP-TEE/optee_os/pull/1919 is needed too, please ignore
"core: fix access conflict status in rpmb fs that panics TA" while reviewing this PR

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Fixes https://github.com/OP-TEE/optee_os/issues/1780

**Comment by jforissier** [comment]
For "core: RPMB_FS: remember owner uuid", with the proper 12-character SHA1 prefix in the commit description:
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
FYI, "core: RPMB_FS: remember owner uuid" has a proper 12-character SHA1 prefix in the commit description, it's just github mangling the commit message.

**Comment by jforissier** [comment]
Ah, yes indeed, but checkpatch expects "commit 078f18f82eeb ..." (the word "commit" has to be there).

**Comment by jenswi-linaro** [comment]
Message updated, tag applied

**Comment by etienne-lms** [comment]
https://github.com/OP-TEE/optee_os/pull/1919 is updated (tag applied)

**Comment by jforissier** [comment]
@jenswi-linaro can you please rebase now that 1919 is merged? Thanks.

**Comment by jenswi-linaro** [comment]
Rebased

**Pull request merged**
