### PR TITLE
nist p521 - fix key size

### PR DESCRIPTION
**Pull request by ldts**

### CODE REVIEW

**Comment by clementfaure** [comment]
For 7d80c2a949812c65ce3744d9a4e246b3644f5af2,
`Acked-by: Clement Faure <clement.faure@nxp.com>`

**Comment by jforissier** [comment]
For "crypto_api: acipher: ecc NIST-P521", with the below comment addressed:
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

Please reverse the order of the two commits to preserve bisectability ("In preparation for key_size being changed from 528 to 521 for ECC NIST-P521..."). Also in the commit subject ECC should be spelled `ECC` not `ecc`.

**Comment by ldts** [comment]
updated and tags applied.

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Pull request merged**
