### PR TITLE
Fix the occasional AArch64 linker problem

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
The travis error is checkpatch complaining over some assembly macros.

**Comment by lorc** [comment]
Hi. I reviewed it (including python script). Looks good.
`Reviewed-by: Volodymyr Babchuk <vlad.babchuk@gmail.com>`

**Comment by jforissier** [comment]
For the first patch ("core: avoid incremental linking with -gc"):
Nice workaround ;) Could you please add a typical error message in the commit log, as well as references to the bug reports? (https://bugs.linaro.org/show_bug.cgi?id=3006 and https://sourceware.org/bugzilla/show_bug.cgi?id=21524).
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`.

**Comment by jenswi-linaro** [comment]
Commit message update, tags applied.

**Comment by jforissier** [comment]
Thanks, merged.

**Pull request merged**
