### PR TITLE
Remove big lock take 2

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Replaces #533

Addressed review comments and added review tags for reviewed patches.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Squashed https://github.com/jforissier/optee_os/commit/f54c2e2435988f5899432f69d110e44323519263 into "core: ltc: add lock for memory pool"

**Comment by jenswi-linaro** [comment]
Commits `core: arm: thread-safe sessions` and `arm: mutex: Add file and line to debuginfo` doesn't have a review tag yet. Anything more I can/should do?

**Comment by jforissier** [comment]
For `arm: mutex: Add file and line to debuginfo`:
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Thanks Jerome! Any volunteers to review `core: arm: thread-safe sessions`?

**Comment by jbech-linaro** [comment]
I've reviewed all individual patches and there are just a few minor comments. Please address those and then this is ready to be merged.

**Comment by jenswi-linaro** [comment]
Update, please check `libutils: make malloc thread-safe` as the solution was a bit different than what was suggested (function `raw_realloc()`).

**Comment by jbech-linaro** [comment]
That should work.
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jbech-linaro** [comment]
There's a compiler error (a colon instead of semi-colon in one location), see Travis, please fix and re-upload a fix.

**Comment by jenswi-linaro** [comment]
Updated

**Comment by jbech-linaro** [comment]
I've talked to Jens, but FYI for other following this, Travis most likely fails on the expect script and we suspect it does so because of `rcu_sched detected stalls`. I will merge this patch, since we have seen this from time to time and it's not a problem with the patch itself. But we should fix this as soon as possible so we don't get errors from Travis. Jens suggested that we build the kernel with `CONFIG_PREEMPT` set (Preemptible Kernel (Low-Latency Desktop)).

**Comment by jforissier** [comment]
@jbech-linaro agreed with your analysis. About `CONFIG_PREEMPT`: I can give it a try, its sounds like a good lead. It should not hurt in any case.

**Pull request merged**
