### PR TITLE
Miscellaneous patches

### PR DESCRIPTION
**Pull request by sahilnxp**
This pull request enable support for Attestation PTA and OTP DIE ID by default for i.MX platforms

### CODE REVIEW

**Review by jforissier — APPROVED** [review]
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by etienne-lms** [comment]
@sahilnxp, could you add your S-o-b tag to these changes?

**Comment by sahilnxp** [comment]
Thanks @jforissier 
Tags updated.

**Comment by sahilnxp** [comment]
Thanks @jenswi-linaro 
Tags updated.

**Comment by sahilnxp** [comment]
May I know if there is any other comment on this ?

**Comment by jforissier** [comment]
@sahilnxp all good, thanks!

**Pull request merged**
