### PR TITLE
core: remove unused CORE_MEM_EXTRAM

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU)
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by etienne-lms** [comment]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

Maybe you should remove the 2 occurrences of `DRAM1_BASE` that are now unused?

**Comment by etienne-lms** [comment]
I think even the `DRAM0_BASE` defined by each platforms could be removed.
I guess you would rather ask each maintainer whether they want to remove them or not for some private purpose. Those `DRAMx_BASE` were mandate by the generic code since this old `CORE_MEM_EXTRAM` support.

**Comment by jenswi-linaro** [comment]
I think we should wait a little with removing those `DRAMx_BASE` as we'll need those after https://github.com/OP-TEE/optee_os/pull/1232

**Comment by jenswi-linaro** [comment]
Tags applied

**Pull request merged**
