### PR TITLE
ta: pkcs11: fix comment stating no mechanism is supported

### PR DESCRIPTION
**Pull request by etienne-lms**
Remove the inline comment that states the implementation does not yet
support any mechanism as is it not true.

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

### CODE REVIEW

**Review by Emantor — APPROVED** [review]

**Comment by Emantor** [comment]
`Acked-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>`

**Comment by ruchi393** [comment]
`Reviewed-by: Ruchika Gupta <ruchika.gupta@linaro.org>`

**Comment by etienne-lms** [comment]
tags applied

**Comment by etienne-lms** [comment]
that was a tuff one :)

**Pull request merged**
