### PR TITLE
qemu: update computation of TZDRAM_SIZE

### PR DESCRIPTION
**Pull request by pascal-brand-st-dev**
TZDRAM_SIZE is computed from DRAM0_TEERES_SIZE, CFG_TEE_RAM_VA_SIZE
and CFG_SHMEM_SIZE, instead of using hard-coded values.

Signed-off-by: Pascal Brand <pascal.brand@st.com>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by pascal-brand-st-dev** [comment]
Tags applied

**Comment by cedric-chaumont-st** [comment]
@pascal-brand-st-dev : I assume that TEERES stand s for TEE reserved. In that case, I would prefer TEE_RSVD instead.

**Comment by jenswi-linaro** [comment]
@cedric-chaumont-st this define was there even before this patch.

**Comment by cedric-chaumont-st** [comment]
@jenswi-linaro : FMI, Why TZDRAM_SIZE has changed with the pager ?

**Comment by jenswi-linaro** [comment]
@cedric-chaumont-st it's because we're faking TZSRAM with a portion of the memory reserved as TZDRAM.

**Comment by cedric-chaumont-st** [comment]
Manually merged.

**Pull request closed without merging**
