### PR TITLE
ARM Juno GCC5 support note.

### LINKED ISSUE #822: ramdisk.img size
Hi,

I recently tried to update my OP-TEE files using `repo sync` and in the end it showed that the current `ramdisk.img` size was `29.15 MB` as shown below:
```
Image Type:   AArch64 Linux RAMDisk Image (gzip compressed)
Data Size:    30563157 Bytes = 29846.83 kB = 29.15 MB
Load Address: 00000000
Entry Point:  00000000
```

As the `/JUNO/SITE1/HBI0262B/images.txt` limits it to `8.3 MB` I am guessing that I should update `NOR4ADDRESS` , is that right? 

The increased size comes from the lib folder, could it be because of the use of gcc5?

Note: I tried in downloading all files again but got the same thing. I compiled for the juno board.

### PR DESCRIPTION
**Pull request by Miraje**
It fixes #822 (ramdisk.img size)

Signed-off-by: Miraje Gentilal <miraje.gentilal@hotmail.com>

### CODE REVIEW

**Comment by Miraje** [comment]
Tested-by: Miraje Gentilal <miraje.gentilal@hotmail.com> (Juno-r2)

**Comment by jbech-linaro** [comment]
Perfect @Miraje , thanks a lot!

`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by Miraje** [comment]
@jbech-linaro I tried to squash the commits but I tinhk I messed up I'm sorry. How should I proceed? Should I create a new request?

**Comment by Miraje** [comment]
@jbech-linaro  tags applied

**Comment by jbech-linaro** [comment]
Patch has been merged, thanks a lot for the contribution!

**Comment by Miraje** [comment]
@jbech-linaro Sure, no problem at all :)

**Pull request merged**
