### PR TITLE
mk: aosp_optee.mk: Fix check for 2nd toolchain

### PR DESCRIPTION
**Pull request by vchong**
Set CROSS_COMPILE32 and append to CROSS_COMPILE_LINE if
$($(combo_2nd_arch_prefix)TARGET_TOOLS_PREFIX) is NOT empty.

Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by vchong** [comment]
@liuyq or @vishalbhoj Please ack if ok! Thanks!

**Comment by liuyq** [comment]
how about changing to like this:
 TOP_ROOT_ABS := $(realpath $(TOP))
+ifeq ($(TARGET_IS_64_BIT),true)
+## only support 64bit TAs on 64bit platform
+## 32bit TAs on 64bit platform are not supported
 CROSS_COMPILE64 := $(TOP_ROOT_ABS)/$(TARGET_TOOLS_PREFIX)
 CROSS_COMPILE_LINE += CROSS_COMPILE64="$(CROSS_COMPILE64)"
-ifeq ($(strip $($(combo_2nd_arch_prefix)TARGET_TOOLS_PREFIX)),)
+else
+## only support 32bit TAs on 32bit platform
 CROSS_COMPILE32 := $(TOP_ROOT_ABS)/$($(combo_2nd_arch_prefix)TARGET_TOOLS_PREFIX)
 CROSS_COMPILE_LINE += CROSS_COMPILE32="$(CROSS_COMPILE32)"
 endif

Your change will have 
     CROSS_COMPILE_LINE := CROSS_COMPILE64="$(CROSS_COMPILE64)"
for 32bit platform as well, where CROSS_COMPILE64 will be 32bit toolchian, which will still work but not looks good.

**Comment by vchong** [comment]
@liuyq 

> +## 32bit TAs on 64bit platform are not supported

But this is supported by OP-TEE.

> Your change will have
> CROSS_COMPILE_LINE := CROSS_COMPILE64="$(CROSS_COMPILE64)"
> for 32bit platform as well, where CROSS_COMPILE64 will be 32bit toolchian, which will still work but not looks good.

Are you sure about this? I tried a build and optee_test seems to be able to parse the flags properly, i.e. even with CROSS_COMPILE64 in CROSS_COMPILE_LINE, the file generated was 32bit.

**Comment by liuyq** [comment]
On 19 July 2017 at 00:17, vchong <notifications@github.com> wrote:

> @liuyq <https://github.com/liuyq>
>
> +## 32bit TAs on 64bit platform are not supported
>
> But this is supported by OP-TEE.
>
> Your change will have
> CROSS_COMPILE_LINE := CROSS_COMPILE64="$(CROSS_COMPILE64)"
> for 32bit platform as well, where CROSS_COMPILE64 will be 32bit toolchian,
> which will still work but not looks good.
>
> Are you sure about this? I tried a build and optee_test seems to be able
> to parse the flags properly, i.e. even with CROSS_COMPILE64 in
> CROSS_COMPILE_LINE, the file generated was 32bit.
>

did not check the details how optee_os side does, but guess,
 CROSS_COMPILE64 not used for the 32bit platform, and CROSS_COMPILE32 not
used for 64 bit platform.

-- 
Best Regards,
Yongqin Liu
---------------------------------------------------------------
#mailing list
linaro-android@lists.linaro.org <linaro-dev@lists.linaro.org>
http://lists.linaro.org/mailman/listinfo/linaro-android

**Comment by liuyq** [comment]
Acked-by: Yongqin Liu <yongqin.liu@linaro.org>

**Comment by vchong** [comment]
Tag added. Thanks!

**Pull request merged**
