### PR TITLE
gpio framework: add a put operator

### PR DESCRIPTION
**Pull request by etienne-lms**
Adds a `.put` operation handler in `struct gpio_ops` for a GPIO consumer driver to be able to release the GPIO resources it has allocated when getting its GPIO using a DT drvier GPIO provider (`gpio_dt_alloc_pin()`). This is needed for example, when such a consumer driver must defer its probe sequence hence release resources as it will be probed again later and will request again its GPIO resources.

### CODE REVIEW

**Comment by etienne-lms** [comment]
@tprrt, could you have a look at this P-R?

**Comment by tprrt** [comment]
Hello @etienne-lms,

It looks good to me.

Kind regards,
Thomas

**Comment by etienne-lms** [comment]
@tprrt, do I understand I can apply you `Acked-by` review tag on both commits?

**Comment by tprrt** [comment]
> @tprrt, do I understand I can apply you `Acked-by` review tag on both commits?

Yes, you can.

**Comment by etienne-lms** [comment]
A-b review tag applied.

**Pull request merged**
