### PR TITLE
core: remove mem_map_inited and fix the SHM_VASPACE_SIZE

### PR DESCRIPTION
**Pull request by prime-zeng**
The mem_map_inited is useless,so remove it.
The MEM_AREA_SHM_VASPACE vapsace should have the size of
SHM_VASPACE_SIZE, fix it here.

Signed-off-by: Zeng Tao <prime.zeng@hisilicon.com>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
The two changes in the commit is completely unrelated except that I guess you noticed the `mem_map_inited` variable while fixing the other problem. Please split into two commits. Generally, if you use the word "and" like this in a commit it's a sign that the commit should perhaps be split.

From the description it's not really clear what happens to MEM_AREA_SHM_VASPACE, explain what it was initialized with before and the usefulness of this patch will be obvious for more.

**Comment by prime-zeng** [comment]
@jenswi-linaro  OK , update with your comment.

**Comment by jenswi-linaro** [comment]
Please add something like:
*Prior to this patch MEM_AREA_SHM_VASPACE was initialized with RES_VASPACE_SIZE, which is wrong. With this patch MEM_AREA_SHM_VASPACE is initialized with SHM_VASPACE_SIZE instead.*
to the "core: fix the size of dynamic shared memory buffers" 

With that added:
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by prime-zeng** [comment]
Tags applied, commit message updated as suggested.

**Pull request merged**
