### PR TITLE
ci: zynqmp: Add compilation for optional drivers

### PR DESCRIPTION
**Pull request by vesajaaskelainen**
Test compile optional Xiphera TRNG and HUK drivers (and its related
drivers).

Signed-off-by: Vesa Jääskeläinen <vesa.jaaskelainen@vaisala.com>

---

Depends on:
- https://github.com/OP-TEE/optee_os/pull/5460

### CODE REVIEW

**Comment by vesajaaskelainen** [comment]
Currently gives warning:
```
_make PLATFORM=zynqmp-zcu102 CFG_ARM64_core=y CFG_WITH_SOFTWARE_PRNG=n CFG_XIPHERA_TRNG=y CFG_ZYNQMP_HUK=y
core/drivers/xiphera_trng.c: In function 'xiphera_trng_read32':
core/drivers/xiphera_trng.c:43:18: error: unused variable 'exceptions' [-Werror=unused-variable]
   43 |         uint32_t exceptions = 0;
      |                  ^~~~~~~~~~
core/drivers/xiphera_trng.c: At top level:
cc1: note: unrecognized command-line option '-Wno-c2x-extensions' may have been intended to silence earlier diagnostics
cc1: all warnings being treated as errors
make: *** [mk/compile.mk:163: out/core/drivers/xiphera_trng.o] Error 1
make: *** Waiting for unfinished jobs....
```

As depending PR is merged.

**Comment by vesajaaskelainen** [comment]
@jforissier side effect of that CI pipeline transition is that now they also start to execute on personal forks too ;)

So I could test the change beforehand in here:
https://github.com/vesajaaskelainen/optee_os/runs/7579901612?check_suite_focus=true#step:5:416

**Comment by jforissier** [comment]
> @jforissier side effect of that CI pipeline transition is that now they also start to execute on personal forks too ;)

Absolutely. Note that the CI in your fork runs on your branch, and the CI here (in the PR) runs on the merge of your branch into master. So it's not exactly a duplicate.

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by vesajaaskelainen** [comment]
> `Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

Thanks! Applied tag.

Please wait for depending PR to be merged first.

**Comment by vesajaaskelainen** [comment]
keep-alive

**Comment by vesajaaskelainen** [comment]
Only rebased to trigger new build with latest master.

**Comment by vesajaaskelainen** [comment]
Yei... the test build is now green :grin:

**Pull request merged**
