### PR TITLE
Stmm preparations

### PR DESCRIPTION
**Pull request by jenswi-linaro**
This pull request contains a few patches that later will be needed with OP-TEE running StMM.
Instead of sitting on them until they are really needed I'm pushing them now to avoid time consuming and error prone rebasing.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
And now are the trinity happy too! :-)

**Comment by jforissier** [comment]
What is StMM?

**Comment by jbech-linaro** [comment]
> What is StMM?

Standalone Management Mode, you'll find a bit about it [here](https://uefi.org/sites/default/files/resources/UEFI%20updates%20and%20Secure%20Software%20Isolation%20on%20Arm_final.pdf). The "Single Partition Use-case" slide gives the high level overview. Basically OP-TEE needs to be able to run the StMM module.

**Comment by jenswi-linaro** [comment]
Here's some TF-A documentation too https://github.com/ARM-software/arm-trusted-firmware/blob/master/docs/components/secure-partition-manager-design.rst which we try to emulate partially.

**Comment by jenswi-linaro** [comment]
update

**Comment by jenswi-linaro** [comment]
Rebased on master, added two more commits "core: vm_set_prot() and friends works across VM regions" and "core: move vfp state into struct user_ta_ctx ".

**Comment by FulcronZ** [comment]
Hi. I have been using this code to test [StMM][pipat_optee_spm]. The code works fine. `vm_set_prot()` can split mm regions, and StMM can resume from system call because of PC and SP are saved. 

I will ack after the style error in Travis fixed. 

A little bit of StMM background
--------------------------------

EFI Management Mode (MM) handles system-critical operations and configurations e.g. setting uefi variables. Standalone MM (StMM) is a complete firmware image which can provide MM service. For Arm architecture, it is loaded and runs in secure world. A few years ago, StMM has been loaded by TF-A SPM_MM service. UEFI in non-secure world talks with StMM in secure world using SMC with ARM MM protocol. There is only one Arm StMM implementation at the moment provided in EDK2. 

Since many SoCs are still using Armv8.0-A, they can run only one secure application, because it doesn't have S-EL2 to launch secure world hypervisor. This is where OP-TEE comes in. OP-TEE can launch multiple TEE TAs. So why can't it host an StMM too? This makes Armv8.0-A can run both TEE TAs and StMM, without much StMM porting effort. 

[pipat_optee_spm]: https://git.linaro.org/people/pipat.methavanitpong/optee_os.git/log/?h=pipat/stmm2

**Comment by jforissier** [comment]
@FulcronZ thanks for the explanations and the link to the `stmm` branch.

About the style error in Travis: it's how we have always written KEEP_PAGER() everywhere in the code, so ignoring the warning sounds acceptable to me, on the other hand it is an easy fix and and it would not look too bad to have a blank line, so we may as well want to change. @jenswi-linaro it's up to you ;-)

I'll try to spend some time reviewing this, too.

**Comment by jenswi-linaro** [comment]
I'd rather keep the `KEEP_PAGER()` where they are, compare with `EXPORT_SYMBOL_GPL()` in the kernel. There's actually special treatment for `EXPORT_SYMBOL_GPL()` and friends in `checkpatch.pl`. Perhaps we can rename `KEEP_PAGER()` to something that still makes sense and match those rules at the same time. I suspect that for instance `DECLARE_KEEP_PAGER()` would be OK with `checkpatch.pl`.

**Comment by jforissier** [comment]
- For commits:
  - "core: thread_enter_user_mode(): avoid leaking register content"
  - "core: add struct user_mode_ctx"

  `Acked-by: Jerome Forissier <jerome@forissier.org>`

- For commits:
  - "core: move struct thread_ctx_regs to thread.h"
  - "core: add common user_mode_ctx_print_mappings()"

  `Reviewed-by: Jerome Forissier <jerome@forissier.org>`

- For commit "core: system_pta: refuse changing kernel mappings"
  There is a typo in the commit description (jsystem).

  `Reviewed-by: Jerome Forissier <jerome@forissier.org>`

- For commit "core: move vfp state into struct user_ta_ctx"
  In the commit description `s/vfp/VFP/` and `s/ i / a /`.

  `Reviewed-by: Jerome Forissier <jerome@forissier.org>`

**Comment by FulcronZ** [comment]
Ok. I prefer the style in the kernel too. 

For all commits:
`Acked-by: Pipat Methavanitpong <pipat.methavanitpong@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tag applied, commit messages updated, rebased on master

**Pull request merged**
