### PR TITLE
plat-marvell: Add support for Marvell OcteonTX2 SoC family

### PR DESCRIPTION
**Pull request by anilreddy3**
Support for Marvell OcteonTX2 CN96xx, CN98xx and CNF95xx SoCs.
   Tested 64-bit mode with default configurations:
    1. Build commands
            make PLATFORM=marvell-otx2t96
            make PLATFORM=marvell-otx2f95
            make PLATFORM=marvell-otx2t98
    2. Passed xtest

### CODE REVIEW

**Comment by jforissier** [comment]
Hi @anilreddy3, thanks for the patches.

How can the first commit ("plat-marvell: Add support for OcteonTX2 CN96xx SoC") work without the second one ("plat-marvell: Implement core position for OcteonTX2 platforms")?

**Comment by anilreddy3** [comment]
> Hi @anilreddy3, thanks for the patches.
> 
> How can the first commit ("plat-marvell: Add support for OcteonTX2 CN96xx SoC") work without the second one ("plat-marvell: Implement core position for OcteonTX2 platforms")?

Thanks for quick response.
Agree, always tried the both the patches together, do you want me commit "plat-marvell: Implement core position for OcteonTX2 platforms" first?

**Comment by jforissier** [comment]
> > Hi @anilreddy3, thanks for the patches.
> > How can the first commit ("plat-marvell: Add support for OcteonTX2 CN96xx SoC") work without the second one ("plat-marvell: Implement core position for OcteonTX2 platforms")?
> 
> Thanks for quick response.
> Agree, always tried the both the patches together, 

OK.

> do you want me commit "plat-marvell: Implement core position for OcteonTX2 platforms" first?

No, please fold the second patch into the first. One cannot go without the other really.

**Comment by anilreddy3** [comment]
> > > Hi @anilreddy3, thanks for the patches.
> > > How can the first commit ("plat-marvell: Add support for OcteonTX2 CN96xx SoC") work without the second one ("plat-marvell: Implement core position for OcteonTX2 platforms")?
> > 
> > 
> > Thanks for quick response.
> > Agree, always tried the both the patches together,
> 
> OK.
> 
> > do you want me commit "plat-marvell: Implement core position for OcteonTX2 platforms" first?
> 
> No, please fold the second patch into the first. One cannot go without the other really.

that's a good suggestion, I thought of adding magic number in place of CFG_CLUSTERS_PER_NODE and submitting first.

**Comment by jforissier** [comment]
> > do you want me commit "plat-marvell: Implement core position for OcteonTX2 platforms" first?
> 
> No, please fold the second patch into the first. One cannot go without the other really.

...and with that done:
`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by jforissier** [comment]
> that's a good suggestion, I thought of adding magic number in place of CFG_CLUSTERS_PER_NODE and submitting first.

It doesn't make sense to add a file called `plat-marvell/otx2/core_pos.S` before support for `otx2` is introduced.

**Comment by anilreddy3** [comment]
> > that's a good suggestion, I thought of adding magic number in place of CFG_CLUSTERS_PER_NODE and submitting first.
> 
> It doesn't make sense to add a file called `plat-marvell/otx2/core_pos.S` before support for `otx2` is introduced.

agree.

**Comment by anilreddy3** [comment]
> Acked-by: Jerome Forissier <jerome@forissier.org>
Thanks @jforissier for the ACK.
folded second patch into the first and also updated the Tag.

**Pull request merged**
