### PR TITLE
Request for comments: Signed ta

### PR DESCRIPTION
**Pull request by jenswi-linaro**
This is a PR with the result of the signed TA investigation, it's not intended to be merged as it looks today but rather to be used to decide which direction we should take on this. This PR replaces #302. 

To test this please use https://github.com/jenswi-linaro/optee_test/tree/signed_ta for optee_test

The first patch is the old "TA as ELF" which includes the first proposal for signing TAs.
The second patch replaces the sign header with the complete ELF copied into an ASN.1 structure as defined by RFC4108.

There's some rough edges in these patches, but it should be good enough to decide if we should continue in this track or look for other options.

### CODE REVIEW

**Comment by neil1899** [comment]
Dear @jenswi-linaro 
I have read your signed_TA branch that decrypt the TAs.
but i don't know how can i encrypt the TAs of optee_test.
do you achieve some tools that encrypt the TAs.

**Comment by neil1899** [comment]
Dear @jenswi-linaro 
if you have achieve the tools, can you tell me how can i use it to encrypt my ta

**Comment by paswan-ms** [comment]
Adding a link to the potentially related issue around supporting ABS32 relocation entries: https://github.com/OP-TEE/optee_os/issues/435
Paul.

**Comment by paswan-ms** [comment]
Some bug fixes that cause sign.py to fail when building on Windows because the 'b' binary mode flag is missing:

`sign.py: Line 47: f = open(args.key, 'rb')`
`sign.py: Line 51: f = open(args.inf, 'rb')`
`sign.py: Line 72: f = open(args.out, 'wb');`

(note the latter has a ';' on also).
Thanks,
Paul.

**Comment by jenswi-linaro** [comment]
Thanks Paul. I'll include that when rebasing.

/Jens

**Comment by paswan-ms** [comment]
The original TA binary format compiled our TA that includes OpenSSL into a TA binary of ~850Kb. With this change the TA binary is ~3.5Mb. Are there any redundant sections that can be culled from the TA image?
Thanks,
Paul.

**Comment by jenswi-linaro** [comment]
Yes, all the .debug_* sections are good candidates. In principle it should be enough to only keep what's in the program headers.

Note that even TA binary is larger it shouldn't use significantly more secure memory once it's loaded.

/Jens

**Comment by jenswi-linaro** [comment]
Replaced by #445

**Pull request closed without merging**
