### PR TITLE
plat-totalcompute: remap console logs

### PR DESCRIPTION
**Pull request by annsai01**
Remapping console logs from soc uart1 (s0 termial) to css secure (uart1_ap terminal)

Change-Id: I5e790dcbe345405cdfaa0f2697d8cba27afb3df4

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Didn't we just have a PR about this? Anyway, please drop the `Change-Id` from the commit message and apply:
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jenswi-linaro** [comment]
A real name on the signed-off line instead of `annsai01` would be nice too even if I suppose it can be deduced from the email address.

**Comment by annsai01** [comment]
> Didn't we just have a PR about this? Anyway, please drop the `Change-Id` from the commit message and apply:
> `Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

I have amended ack by and my full name in the commit msg

**Comment by annsai01** [comment]
I am waiting for the  change to get merged if everything is appropriate

**Comment by jforissier** [comment]
> I am waiting for the change to get merged if everything is appropriate

I can take care of replacing `annsai01` with `Annam Saimanisha` if you're OK with that. Then I'll merge the commit manually.

**Comment by annsai01** [comment]
> > I am waiting for the change to get merged if everything is appropriate
> 
> I can take care of replacing `annsai01` with `Annam Saimanisha` if you're OK with that. Then I'll merge the commit manually.

I have force pushed and changed that to Annam Sai Manisha ..Can you check on that and change if needed.. Thanks

**Comment by jforissier** [comment]
Author updated and commit pushed to master, thanks!

**Pull request closed without merging**
