### PR TITLE
Remove legacy tee_common_unpg.h

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Removes legacy file core/include/kernel/tee_common_unpg.h
and updates with new types etc as needed.

Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU)
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by etienne-lms** [comment]
few missing changes:
- tee_svc_cache.c line 54: `tee_uaddr_t` => `uaddr_t`
- tee_pager.c: line 1079: `tee_vaddr_t` => `vaddr_t`
- core_mmu_v7.c: add `#include <string.h>`

**Comment by jenswi-linaro** [comment]
Thanks, updated

**Comment by etienne-lms** [comment]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (b2260)`

**Comment by jenswi-linaro** [comment]
Squashed and tags applied.

**Pull request merged**
