### PR TITLE
plat-zynq7k: fix a code typo introduced in 3.5.0-rc1 which prevented zynq7k to switch to NS

### PR DESCRIPTION
**Pull request by yanyan-wrs**
A defect was introduced in a commit in 3.5.0: https://github.com/OP-TEE/optee_os/commit/af4c7f4b3ad2480a078cd54de909280af5924256, where the register value and address is switched and it prevented OPTEE to successfully switch back to NS. The fix is obvious and trivial and testing on real hardware has been carried out to ensure it now correctly boots.

Signed-off-by: yan.yan@windriver.com
Tested-by: yan.yan@windriver.com

### CODE REVIEW

**Review by etienne-lms — COMMENTED** [review]
Could you update the commit log with the description you added in the P-R and your real name in the s-o-b and t-b tags. Something like the below:
```
plat-zynq7k: fix a typo in NS work unlocking

A defect was introduced in 3.5.0 where the register value and address
are switched, preventing OPTEE to successfully switch back to non-secure
world. The fix is obvious and trivial and testing on real hardware has
been carried out to ensure it now correctly boots.

Fixes: af4c7f4b3ad2 ("zynq7k: upgrade from write32() to io_write32() and friends")
Signed-off-by: **Your real name** <yan.yan@windriver.com>
Tested-by: **Your real name** <yan.yan@windriver.com> (zynq7k)
```

My apologies for the bug introduced by the referred commit.
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by jforissier** [comment]
I would hardly call the bug a "typo". How about `plat-synq7k: fix wrong argument order in NS world unlocking`?

**Comment by vesajaaskelainen** [comment]
It seems that we have done similar fix while determining what kind of work it is to get OP-TEE running on Zynq7k.

We have been observing that there needs to be additional changes in `smc` interface in order to boot u-boot -- we are not yet in kernel side so cannot comment on that yet. 

Our current flow is SPL->FIT image (bitstream->OP-TEE->u-boot proper) -> FIT image (kernel).

@yanyan-wrs what kind of system are you testing this with? Do you have some non-upstreamed changes for optee / u-boot / kernel?

**Comment by yanyan-wrs** [comment]
> It seems that we have done similar fix while determining what kind of work it is to get OP-TEE running on Zynq7k.
> 
> We have been observing that there needs to be additional changes in `smc` interface in order to boot u-boot -- we are not yet in kernel side so cannot comment on that yet.
> 
> Our current flow is SPL->FIT image (bitstream->OP-TEE->u-boot proper) -> FIT image (kernel).
> 
> @yanyan-wrs what kind of system are you testing this with? Do you have some non-upstreamed changes for optee / u-boot / kernel?

I tested it on Xilinx Zynq7K ZC702 Evaluation Board. The boot flow I used is FSBL->U-boot->Optee->Rich OS. If U-boot is chained after OPTEE, i.e., running in NS, it will not be able to access certain resource only accessible in Secure World, such as the system control register and friends. I haven't tried the latter boot flow but one of my clients report he tried and encountered the exact access right problem above. Thus a fix in u-boot is need to maybe introduce a new configuration that replaces direct privileged register access with SMC calls. In any case the change of U-boot and FIT image is out of scope of this pull request.

**Comment by jforissier** [comment]
@yanyan-wrs please apply Etienne's R-b, thanks!

**Comment by yanyan-wrs** [comment]
> @yanyan-wrs please apply Etienne's R-b, thanks!

Hi would you please elaborate what R-b needs to be applied? I've updated the commit message to include the fixed issue and all corrected sign-offs.

**Comment by etienne-lms** [comment]
R-b stands for `Reviewed-by:` tag.
As I posted a comment with my R-B tag (`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`), you are expected to finalize your P-R by updating the commit log adding `Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>` next to your `Signed-of-by:` (S-o-b) tag.
See [finalizing-your-contribution](https://optee.readthedocs.io/en/latest/general/contribute.html#finalizing-your-contribution) in the documentation.

**Comment by jforissier** [comment]
Review tag applied, merge manually.

**Pull request closed without merging**
