### PR TITLE
GP Internal Core API v1.1 : update data stream functions

### PR DESCRIPTION
**Pull request by cedric-chaumont-st-dev**
update return code/panic reasons

Signed-off-by: Cedric Chaumont <cedric.chaumont@st.com>

### CODE REVIEW

**Comment by cedric-chaumont-st-dev** [comment]
@pbrand: I updated using out flag (instead of err because only one flag implemented). Is it what you meant ?

**Comment by pascal-brand-st-dev** [comment]
My fault. I read the wrong version.

    Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by cedric-chaumont-st-dev** [comment]
Rebased. Squashed.

**Pull request merged**
