### PR TITLE
arm64: SHA-224/SHA-256 using ARMv8-A cryptographic extensions

### PR DESCRIPTION
**Pull request by jforissier**
The first 3 commits are from https://github.com/OP-TEE/optee_os/pull/423, please consider the 4th commit.

### CODE REVIEW

**Comment by ardbiesheuvel** [comment]
Reviewed-by: Ard Biesheuvel <ard.biesheuvel@linaro.org>

**Comment by pascal-brand-st-dev** [comment]
Can you rebase on top of #423 once merged? Thanks.

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jforissier** [comment]
Rebased and review tags added.

**Pull request merged**
