### PR TITLE
Some small fixes

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Review by jforissier — COMMENTED** [review]
For "core: fix offset calculation in param_mem_to_user_va()":

`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Review by jforissier — COMMENTED** [review]
For "core: syscall_storage_obj_create(): check that the attributes object is initialized":

`Reviewed-by: Jerome Forissier <jerome@forissier.org>`

**Review by jforissier — COMMENTED** [review]
For "libutee: fix TEE_BigIntDiv(): dest_q or dest_r may be NULL":

`Reviewed-by: Jerome Forissier <jerome@forissier.org>`

**Comment by jenswi-linaro** [comment]
Tags applied

**Pull request merged**
