### PR TITLE
ci: add build with Mbed TLS and crypto extensions

### PR DESCRIPTION
**Pull request by jforissier**
Build for the Juno platform with Mbed TLS as the core crypto library. This would have caught the issue fixed in commit 021fee0affe5 ("core: mbedtls: Fix build").

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Why Juno? Wouldn't it work with QEMU?

**Comment by jforissier** [comment]
For some reason the build doesn't fail on QEMUv8, I need to check why.

**Comment by jforissier** [comment]
> For some reason the build doesn't fail on QEMUv8, I need to check why.

Ah, the reason is `CFG_CRYPTO_WITH_CE`. PLATFORM=vexpress-qemu_armv8a` will fail in the same way when `CFG_CRYPTO_WITH_CE=y`. @jenswi-linaro would you prefer I add a QEMU build instead of Juno?

**Comment by jenswi-linaro** [comment]
> > For some reason the build doesn't fail on QEMUv8, I need to check why.
> 
> Ah, the reason is `CFG_CRYPTO_WITH_CE`. `PLATFORM=vexpress-qemu_armv8a` will fail in the same way when `CFG_CRYPTO_WITH_CE=y`. @jenswi-linaro would you prefer I add a QEMU build instead of Juno?

Yes, please. :-)

**Comment by jforissier** [comment]
Update

**Review by jenswi-linaro — COMMENTED** [review]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Pull request merged**
