### PR TITLE
pkcs11: Fix return value when trying to open parallel session

### PR DESCRIPTION
**Pull request by vesajaaskelainen**
It is mandatory to have CKF_SERIAL_SESSION set when invoking
C_OpenSession(). Return value CKR_SESSION_PARALLEL_NOT_SUPPORTED must be
returned.

Specified in:
PKCS #11 Cryptographic Token Interface Base Specification Version 2.40
Plus Errata 01
5.6 Session management functions
C_OpenSession

Signed-off-by: Vesa Jääskeläinen <vesa.jaaskelainen@vaisala.com>

### CODE REVIEW

**Comment by vesajaaskelainen** [comment]
Goes with https://github.com/OP-TEE/optee_client/pull/245 and https://github.com/OP-TEE/optee_test/pull/476.

**Review by etienne-lms — COMMENTED** [review]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`.
In commit log, i suggest a minor rephrasing, the 2nd sentence looks unfinished to me (but I'm not an English native speaker):
> It is mandatory to have CKF_SERIAL_SESSION set when invoking
C_OpenSession() unless what the function shall return CKR_SESSION_PARALLEL_NOT_SUPPORTED.

**Comment by vesajaaskelainen** [comment]
> `Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`.
> In commit log, i suggest a minor rephrasing, the 2nd sentence looks unfinished to me (but I'm not an English native speaker):
> 
> > It is mandatory to have CKF_SERIAL_SESSION set when invoking
> > C_OpenSession() unless what the function shall return CKR_SESSION_PARALLEL_NOT_SUPPORTED.

Reworded a bit differently, please check that you are still happy with that.

Applied tags.

**Comment by vesajaaskelainen** [comment]
I will add "ta: " keyword to subject line of commits.

**Review by etienne-lms — APPROVED** [review]

**Pull request merged**
