### PR TITLE
drivers: sam: use header file "platform_config.h" instead of "sama5d2.h" 

### PR DESCRIPTION
**Pull request by TonyHan11**

### CODE REVIEW

**Review by jforissier — COMMENTED** [review]
LGTM

`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by TonyHan11** [comment]
rebased on the latest `master` branch and update `sama5d2.h` in `core/drivers/nvmem/atmel_sfc.c` too.

**Comment by jforissier** [comment]
@TonyHan11 please add my `Acked-by:` tag, thanks!

**Comment by TonyHan11** [comment]
@jforissier `Acked-by:` added, thanks.

**Pull request merged**
