### PR TITLE
Npcm 3 21

### PR DESCRIPTION
**Pull request by rutigl**
feat(plat): added support to Nuvoton npcm845x chip

initial version

Signed-off-by: Margarita Glushkin <rutigl@gmail.com>

### CODE REVIEW

**Comment by jforissier** [comment]
:cry: :cry: :sob:

**Comment by jenswi-linaro** [comment]
There's no need to create new PRs with this kind of messy commits. Please try to follow the instructions at https://optee.readthedocs.io/en/latest/general/contribute.html. We can't review it in the current state, please let us know when you think it's ready for review with proper commit messages and so on.

**Comment by rutigl** [comment]
Hi,
I thinks it's ready

2023-05-11 21:45 GMT+03:00, Jens Wiklander ***@***.***>:

**Comment by rutigl** [comment]
Yes, I removed all the commits from the history.
Thank you.

2023-05-14 22:13 GMT+03:00, Etienne Carriere ***@***.***>:

**Pull request closed without merging**
