### PR TITLE
[RFC] Icons for telling the status of our platforms

### PR DESCRIPTION
**Pull request by jbech-linaro**
Since there are some platforms where we haven't heard from the maintainers for a while. I think it would be good to indicate what the current status is on our platforms. This could also be used for releases also. I.e., instead of writing a [Tested On](https://github.com/OP-TEE/optee_os/blob/master/CHANGELOG.md#tested-on) section in CHANGELOG.md we could just refer to the readme.md with a link pointing to a tagged (release tagged) version.

The review tool in GitHub doesn't seem to render the icons in the preview. So if you want to see the rendered version correctly, then head to my branch instead.
https://github.com/jbech-linaro/optee_os/blob/maintenance_icons/README.md

### CODE REVIEW

**Comment by jforissier** [comment]
I'm fine with the idea, but I don't like the icons ;-) They look like configuration switches.

**Comment by jbech-linaro** [comment]
Same type of icon as we have in build.git from Travis, just without text
https://github.com/OP-TEE/build#op-tee-buildgit

**Comment by jforissier** [comment]
> Same type of icon as we have in build.git from Travis, [...]
> https://github.com/OP-TEE/build#op-tee-buildgit

>  just without text

That's the problem. How about removing the grey part (essentially keeping just a colored square), and writing the latest version that was tested next to the icon? That would be easy to understand and to update, as new versions are released.

**Comment by jbech-linaro** [comment]
So, I've made some changes now ... but what about ignore writing the version for the green ones? Wouldn't that make is less cluttered? Also ... If we do that, then we only have to update the platforms not being maintained.

**Comment by jforissier** [comment]
> what about ignore writing the version for the green ones? 

Agreed, I think it would look pretty good. Maybe also add some explanation? Something like:

====

The 'Maintained' column shows:
- a green dot if the platform is actively maintained: either tested successfully with the latest release (N), or is a newly supported platform
- an orange dot if the platform was last tested successfully with release N-1
- a red dot if the last successful test report is older

====

(feel free to re-word of course)

**Comment by etienne-lms** [comment]
+1 looks nice!

For the details, I would only tell that the triplet is the last op-tee tested version. I think the colour code is self explanatory. We can change version offset threshold without needing explanations.

**Comment by jbech-linaro** [comment]
@etienne-lms @jforissier I did add the suggested text by Jerome. But I'm not sure I follow Etiennes' suggestion. You are saying that we shall not add all text proposed by Jerome and just simply state, something like: 
`Version shown in column "Maintained?" reflects the latest tested version. If it is green it has been tested successfully on that current version`?
That works for me.

**Comment by jbech-linaro** [comment]
Update everything to latest. If we are happy with this, I would like to squash them all to a single commit.

**Comment by jforissier** [comment]
LGTM.
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jbech-linaro** [comment]
Squashed, rebased and tag(s) applied (should be) ready for merge! Thanks!

**Pull request merged**
