### PR TITLE
GICv3 interrupt handling fix

### PR DESCRIPTION
**Pull request by b49020**
This pull request also includes patch to set default number of threads to 8 which has already been reviewed as part of https://github.com/OP-TEE/optee_os/pull/2564.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
For the 2nd patch ("drivers: gicv3: Handle group 1 secure interrupts"):
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (FVP)`

**Comment by b49020** [comment]
Updated PR with tags.

**Comment by jforissier** [comment]
s/foriegn/foreign/

And preferably:
s/gicv3/GICv3/
s/trustedOS/Trusted OS/

**Comment by b49020** [comment]
Ok will correct these.

**Comment by b49020** [comment]
Updated PR.

**Pull request merged**
