### PR TITLE
libutils: sys/queue.h: add LIST_FOREACH_SAFE()

### PR DESCRIPTION
**Pull request by ruchi393**
Import macro LIST_FOREACH_SAFE from FreeBSD.

Signed-off-by: Ruchika Gupta <ruchika.gupta@linaro.org>

### CODE REVIEW

**Comment by Emantor** [comment]
`Reviewed-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>`

**Comment by jenswi-linaro** [comment]
Which version of FreeBSD did you take this from? The latest FreeBSD version looks slightly different.

**Comment by ruchi393** [comment]
I picked it up from her which was probably not the right place.
https://ftp.netbsd.org/pub/NetBSD/NetBSD-current/src/sys/sys/queue.h

Should I change it to the one here -
https://github.com/freebsd/freebsd-src/blob/main/sys/sys/queue.h

They are almost similar except the use of LIST_END, but I think it would be better to maintain consistency.

**Comment by jenswi-linaro** [comment]
The two version are equivalent, but I'd prefer the FreeBSD version since our `sys/queue.h` is based on that. Sticking to FreeBSD should result in a smaller diff if we ever attempt a larger synch.

**Comment by ruchi393** [comment]
Changed it to FreeBSD code. I have forced pushed the commit to see if IBART still fails with this.

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Pull request merged**
