### PR TITLE
core: fix TA memory reference parameters mapping

### PR DESCRIPTION
**Pull request by etienne-lms**
This change fixes the TA buffer parameter mapping that gets clobbered
when a parameter of lower index relates to nonsecure memory while
a parameter of higher index relates to a secure memory area.

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

### CODE REVIEW

**Comment by etienne-lms** [comment]
fixes https://github.com/OP-TEE/optee_os/issues/1081

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
rebased, review tags applied.

**Pull request merged**
