### PR TITLE
pm: add a name identifier & refine suspend/resume ordering

### PR DESCRIPTION
**Pull request by etienne-lms**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
fixup commits squashed.
tag applied.

**Comment by etienne-lms** [comment]
@jforissier, are you ok to merge this P-R?

**Comment by jforissier** [comment]
@jforissier yep this one is ready, too!

**Pull request merged**
