### PR TITLE
Convert remaining CRLF files

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Converts the remaining CRLF files to LF, unix style.

Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tags applied

**Comment by jenswi-linaro** [comment]
Rebased

**Pull request merged**
