### PR TITLE
drivers/core/gic.c: Set priority mask to allow NS interrupts

### PR DESCRIPTION
**Pull request by pm215**
The non-secure world's view of interrupt priorities only allows it to set priorities between 0x80 and 0xff. This means that the secure world has to set the GICC_PMR (priority mask register) to a value that allows NS interrupts, otherwise the non-secure world will never see interrupts and has no way to set the priorities so that it will ever see them.

This wasn't causing problems for the version of QEMU OP-TEE is currently using, because that has a GIC which does not support TrustZone. However it is essential for being able to move forward to a newer QEMU with a TZ-aware GIC. Otherwise the Non-secure OS hangs late in boot because of the lack of interrupts.

Patch 1 is just a coding style fix, since the function is short and patch 2 needs to modify it anyway.

WARNING: I have tested this with QEMU, but don't have any access to hardware for testing.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by pm215** [comment]
Hi; is this pull likely to be merged in the near future? I have a QEMU patchset nearly ready to send out, and it would be nicer to be able to say "works with upstream OP-TEE" rather than "upstream OP-TEE but then you need to apply this patch"...

**Comment by jenswi-linaro** [comment]
Hi,
I see no reason to delay merging this PR. It's currently only affecting the QEMU port and FIQ isn't working there any way. I've tested that this boots OK on the QEMU we're testing with.
```
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU)
```

**Comment by jbech-linaro** [comment]
@pm215 sorry for the delay, I've manually cherry-picked and merged your patches.

**Comment by pm215** [comment]
Thanks!

**Comment by jbech-optee-adm** [comment]
Manually merged.

**Pull request closed without merging**
