### PR TITLE
Remove git_cpu_init()

### PR DESCRIPTION
**Pull request by jenswi-linaro**
@Amit-Radur, @b49020, @ChiaweiW, @clementfaure, @ememarar, @etienne-lms, @glneo, @grandpaul, @GseoC, @lorc, @MrVan, @Neal-liu, @pangupta, @sahilnxp, @sdininno 

Please check and ack your platforms. One difference for many platforms is that we rely on TF-A or the previous boot stage to initialize the GIC. I assume some unintended copy & paste error has led most platforms to reinitialize the GIC. If I'm wrong in that assumption, we'll see how we can fix it.

### CODE REVIEW

**Review by etienne-lms — COMMENTED** [review]
`Reviewed-by: Etienne Carriere <etienne.carriere@foss.st.com>` for commits
"plat-stm: use gic_init_per_cpu()",
"plat-stm32mp1: use gic_init_per_cpu()",
"plat-stm32mp2: use gic_init_per_cpu()" and 
"core: remove unused deprecated gic_cpu_init()"
with imperative mode in commit messages :)

**Comment by glneo** [comment]
Seems fine, but while testing I ran into a panic() on plat-k3, seems to be caused by a different GIC cleanup:

https://github.com/OP-TEE/optee_os/pull/6394#discussion_r1409603707

**Comment by ChiaweiW** [comment]
For aspeed platform:

Reviewed-by: Chia-Wei Wang <chiawei_wang@aspeedtech.com>

**Comment by jenswi-linaro** [comment]
@glneo, I'm trying to address the issue you mention in https://github.com/OP-TEE/optee_os/pull/6516

**Comment by clementfaure** [comment]
I got a crash at boot on old ARMv7 platforms `imx-mx6qsabresd`
```
2023-11-30T15:30:43 E/TC:0 0 assertion 'vers == 2' failed at core/drivers/gic.c:469 <gic_init_base_addr>
2023-11-30T15:30:43 E/TC:0 0 Panic at core/kernel/assert.c:28 <_assert_break>
2023-11-30T15:30:43 E/TC:0 0 TEE load address @ 0x14000000
2023-11-30T15:30:43 E/TC:0 0 Call stack:
2023-11-30T15:30:43 E/TC:0 0  0x140039d9
2023-11-30T15:30:43 E/TC:0 0  0x1400c439
2023-11-30T15:30:43 E/TC:0 0  0x14009c03
2023-11-30T15:30:43 E/TC:0 0  0x14008b7b
2023-11-30T15:30:43 E/TC:0 0  0x14009001
2023-11-30T15:30:43 E/TC:0 0  0x14003683
2023-11-30T15:30:43 E/TC:0 0  0x140001fc
```
I will have a look at it tomorrow

**Comment by clementfaure** [comment]
@jenswi-linaro Yes, I can boot the board now.

**Comment by sahilnxp** [comment]
I was getting the panic while booting on LX2160A-RDB platforms with this pull request.
But after https://github.com/OP-TEE/optee_os/pull/6516 is merged, board is booting fine.

For commit: **plat-ls: use gic_init_per_cpu()**
`Reviewed-by: Sahil Malhotra <sahil.malhotra@nxp.com>`

**Comment by jenswi-linaro** [comment]
Rebased on master to get the fix from #6516, tags applied and commit messages updated to use imperative mood.

**Comment by glneo** [comment]
For `plat-k3`: `Tested-by: Andrew Davis <afd@ti.com>`

For the `plat-ti` it looks good (not sure if this actually changes anything, so not sure it could break anything), but I haven't gotten around to testing, only a visual code review: `Reviewed-by: Andrew Davis <afd@ti.com>`

**Comment by b49020** [comment]
For `plat-rzn1`: `Sumit Garg <sumit.garg@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tags applied. A few commits are still missing tags, but perhaps this is as good as it gets.

**Comment by clementfaure** [comment]
`Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6qsabresd, imx-mx6ulevk, imx-mx8qmmek, imx-mx8mnevk)`

**Comment by jenswi-linaro** [comment]
Tag applied.

**Comment by jenswi-linaro** [comment]
No more progress on tags now. Perhaps this is as good as it gets.

**Comment by jforissier** [comment]
> No more progress on tags now. Perhaps this is as good as it gets.

Yes, I am merging this now. Thanks.

**Pull request merged**
