### PR TITLE
Add SolidRun Hummingboard Edge Platform Flavors

### PR DESCRIPTION
**Pull request by jordanrh1**
Add platform flavors for [Solidrun HummingBoard Edge boards](https://www.solid-run.com/product-tag/hummingboard-edge/).

### CODE REVIEW

**Comment by MrVan** [comment]
This patches looks good to me. But there are too many i.mx boards will be added if following the current way to use platform_flavor_xxx. How about pass CFG_UART=xx CFG_DRAM_SIZE=xx to make and then no need to add more platform_flavor_xxx?

**Comment by jordanrh1** [comment]
Not a bad idea. Created #2435 with this proposal.

**Comment by jforissier** [comment]
Sorry guys I don't agree, but I'm listening to your arguments. What's the real downside with the current approach?

**Comment by jordanrh1** [comment]
I see the merits of both approaches and do not feel strongly either way. I would lean towards sticking with precedent and adding platform flavors.

**Comment by MrVan** [comment]
@jforissier @jordanrh1 There are many i.MX variants and i.MX boards. Current approach is platform_flavor_mx6qsabresd/mx6dlsabresd/mx6ulevk and etc.. I would like to change to platform_flavor_mx6q/mx6dl/mx6ul with generic macros. To support different boards, people only need to pass CFG_DRAM/CFG_UART and others CFG to makefile, need to hardcode the DRAM/UART in source code with saying platform_flavor_mx6qsabresd wrapped.

**Comment by jforissier** [comment]
@MrVan @jordanrh1 I'll let you come up with a solution that pleases both of you and I'll merge that, not problem.

**Comment by jordanrh1** [comment]
Alright … @MrVan , please take a look at #2435.

**Comment by jordanrh1** [comment]
Fixed checkpatch errors and added Reviewed-by tag.

**Comment by jforissier** [comment]
@jordanrh1 thanks

**Pull request merged**
