### PR TITLE
Fix signing in-tree TAs and libraries

### PR DESCRIPTION
**Pull request by jenswi-linaro**
```
With 1cdd95a2a46d ("Support offline signing of TAs.") the sign.py script
now expects the token "sign" first in the arguments in order to do its
original purpose. So effectively to sign a TA or a library the script
now has to be called as "./scripts/sign.py sign ..." or there's to be
errors like:
  SIGN    ../out-os-qemu/ta_arm32-lib/libutee/527f1a47-b92c-4a74-95bd-72f19f4a6f74.ta
usage:
   sign.py command [ arguments ]

   command:
     sign        Generate signed loadable TA image file.
                 Takes arguments --uuid, --in, --out and --key.
     digest      Generate loadable TA binary image digest for offline
                 signing. Takes arguments  --uuid, --in and --dig.
     stitch      Generate loadable signed TA binary image file from
                 TA raw image and its signature. Takes arguments
                 --uuid, --in, --out, and --sig.

   sign.py --help  show available commands and arguments
sign.py: error: argument command: invalid choice: '0' (choose from 'sign', 'digest', 'stitch', 'generate-digest', 'stitch-ta')
mk/lib.mk:83: recipe for target '../out-os-qemu/ta_arm32-lib/libutee/527f1a47-b92c-4a74-95bd-72f19f4a6f74.ta' failed
make: *** [../out-os-qemu/ta_arm32-lib/libutee/527f1a47-b92c-4a74-95bd-72f19f4a6f74.ta] Error 2

With this patch "sign" is added as needed in the different make files.
Also the "--version 0" argument is removed since it doesn't seem to be
supported any longer.

Fixes: 1cdd95a2a46d ("Support offline signing of TAs.")
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>
```

### CODE REVIEW

**Comment by jforissier** [comment]
`sign` is supposed to be the default command, and I have no issue building for QEMU. It seems to me the build error you mention is purely caused by the use of `--version`, and affects only `CFG_ULIBS_SHARED=y`.

**Comment by jenswi-linaro** [comment]
OK, the error message got me confused. Update the commit and message.

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tag applied

**Pull request merged**
