### PR TITLE
MAINTAINERS: fix Igor Opaniuk's email, make him a Poplar reviewer

### PR DESCRIPTION
**Pull request by jforissier**
~~Igor no longer works for Linaro and emails to igor.opaniuk@linaro.org~~
~~cannot be delivered. Remove him from the reviewers list.~~

~~Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>~~
[Patch description updated]

### CODE REVIEW

**Comment by jbech-linaro** [comment]
@igoropaniuk , do you still want to maintain the Poplar board? And in that case, should we use your gmail-address instead? Or your new company email?

**Comment by igoropaniuk** [comment]
@jbech-linaro Sure, just use my personal email `igor.opaniuk@gmail.com`.

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
@igoropaniuk care to Ack this?

**Comment by igoropaniuk** [comment]
`Acked-by: Igor Opaniuk <igor.opaniuk@gmail.com>`

**Pull request merged**
