### PR TITLE
SHA-3 acceleration 

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
There are a few checkpatch warnings in `sha3_armv8a_ce_a64.S` for long lines, but I'm not sure if it's worth it to fix those.

**Comment by jenswi-linaro** [comment]
> > There are a few checkpatch warnings in `sha3_armv8a_ce_a64.S` for long lines, but I'm not sure if it's worth it to fix those.
> 
> Isn't it just enough to split the lines with a line continuation character? (`\`) That would not look bad I believe.

Yeah, that was easier than expected. I thought that the `.irp` line would cause trouble.

**Review by jforissier — COMMENTED** [review]
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tag applied

**Comment by jenswi-linaro** [comment]
Good to merge?

**Comment by jforissier** [comment]
> Good to merge?

Yes!

**Pull request merged**
