### PR TITLE
scmi-msg: fixes

### PR DESCRIPTION
**Pull request by etienne-lms**

### CODE REVIEW

**Comment by jforissier** [comment]
For "drivers: scmi-msg: define CFG_SCMI_MSG_VOLTAGE_DOMAIN in mk/config.mk":
s/switch/switches/ in the commit description
`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by jforissier** [comment]
For commit "drivers: scmi-msg: rename agent_id to channel_id":
In the commit description: s/to identifier/to identify/ I suppose?

`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by jforissier** [comment]
For commit "drivers: scmi-msg: clean and fix header file":

Ideally should be 2 commits but I'm fine as is.
`Reviewed-by: Jerome Forissier <jerome@forissier.org>`

**Comment by etienne-lms** [comment]
Ok, thanks @jforissier.
Could you tell me why/where IBART failed? I can't find out.

**Comment by jforissier** [comment]
> Could you tell me why/where IBART failed? I can't find out.

Looks like a timeout because I see no build error.

**Comment by etienne-lms** [comment]
last commit split in 2 commits as suggested.
tags applied on each commit.

**Pull request merged**
