### PR TITLE
dts: add stm32mp15*-scmi.dts files for when RCC is secure [my proposal]

### PR DESCRIPTION
**Pull request by jforissier**
Alternative implementation of #6541.

### CODE REVIEW

**Review by etienne-lms — COMMENTED** [review]
This change mandates one to use a `PLATFORM_FLAVOR` config switch but one can configure its stm32mp1 platform providing `CFG_STM32MP{13|15}=y` and `CFG_EMBED_DTB_SOURCE_FILE=...`, possibly a custom DTS file.

This is why in current implementation, PLATFORM_FLAVOR is rather a alias for a target configuration including the DTS file.

**Comment by jforissier** [comment]
> This change mandates one to use a `PLATFORM_FLAVOR` config switch but one can configure its stm32mp1 platform providing `CFG_STM32MP{13|15}=y` and `CFG_EMBED_DTB_SOURCE_FILE=...`, possibly a custom DTS file.
> 
> This is why in current implementation, PLATFORM_FLAVOR is rather a alias for a target configuration including the DTS file.

I don't get it, you don't want to be able to provide a custom DTS file?

**Comment by etienne-lms** [comment]
> I don't get it, you don't want to be able to provide a custom DTS file?

Yes I do. When so, there is no pre-selected flavor. I mean I would like to set `CFG_EMBED_DTB_SOURCE_FILE=xxx.dts` without any flavor, or alternatively use `PLATFORM_FLAVOR` to pre-select a DTS and a config.

**Comment by jforissier** [comment]
OK. Configuring based on the DT file name seems a bit fragile to me (I believe should be able to override the DT with any temporary name for convenience [and even give a full path but that's another story]), but that works.

**Pull request closed without merging**
