### PR TITLE
MAINTAINERS: Change maintainer for Marvell Armada

### PR DESCRIPTION
**Pull request by taovcu**
Signed-off-by: Tao Lu <taolu@marvell.com>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Can we get an ack from @kevin-peng-hao?

**Comment by taovcu** [comment]
Sure. I have notified Kevin Peng by email, just waiting for his ACK.

**Comment by kevin-peng-hao** [comment]
`Acked-by Kevin Peng <kg-kevingarnett@hotmail.com>`

**Comment by jenswi-linaro** [comment]
Thanks, looks good to me.
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jenswi-linaro** [comment]
An automatic notification isn't always sent when updating a commit so if you want to make sure it's noticed type a short comment also. Just "updated" is enough if there's nothing more you'd like to say.

**Pull request merged**
