### PR TITLE
arm64: CFG_WITH_VFP

### PR DESCRIPTION
**Pull request by jforissier**
First commit is just code cleaning. Second one implements CFG_WITH_VFP on arm64.

### CODE REVIEW

**Comment by jforissier** [comment]
Updated.

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jforissier** [comment]
Rebased and review tags applied.

**Pull request merged**
