### PR TITLE
mm: core_memprot: align convenience macroses usage

### PR DESCRIPTION
**Pull request by ikhorn**
As the macroses exist, why not to use them.

Signed-off-by: Ivan Khoronzhuk <ivan.khoronzhuk@globallogic.com>

### CODE REVIEW

**Review by etienne-lms — COMMENTED** [review]
Should rephrase the commit log to state this change adds helper functions, extending existing tee_pbuf_is_*() and tee_vbuf_is_*().

Note also `tee_pbuf_is_nsec_shm()` can be misleading: it targets buffers in the static reserved shm area (`CFG_CORE_RESERVED_SHM=y`), not any shared memory buffer (e.g. dyn shm).

**Comment by jenswi-linaro** [comment]
You're introducing most of the macros you claim already existed. I'm not sure this is that useful, I'd rather address the bigger picture than add another set of macros.

**Comment by ikhorn** [comment]
> It not just adds macros, it tries to decrease misleading by using same style verification macros. The misleading between static reserved shm and dynamic shared memory added historically before and should be got used to already I guess, but deferentially not by this change.

**Comment by ikhorn** [comment]
> I'm not sure this is that useful, I'd rather address the bigger picture than add another set of macros.
Absolutely agree. But then better drop the existent macros and use same style everywhere.

**Comment by jenswi-linaro** [comment]
Sure, go ahead and remove the `tee_?buf_*()` macros. I've always found the cast in them troublesome.

**Pull request closed without merging**
