### PR TITLE
core: sm_a32: add missing isb after scr change

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
@etienne-lms it seems we've overlooked this for quite some time.

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by etienne-lms** [comment]
Agree this is highly recommended. I guess we did not found issues yet because we test aarch32 code that does not access secure/non-secure banked registers while in monitor mode.
Indeed `Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`.

**Comment by jenswi-linaro** [comment]
Tags applied

**Pull request merged**
