### PR TITLE
Optimize size

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Some easy size optimizations

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
With or without my comments

    Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jenswi-linaro** [comment]
Review comments addressed.
Need to be merged in sync with https://github.com/OP-TEE/optee_test/pull/16

**Comment by jenswi-linaro** [comment]
@pascal-brand-st-dev if you're still OK with the PR I'll rebase and add RV tag.

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jenswi-linaro** [comment]
Rebased and review tag applied

**Pull request merged**
