### PR TITLE
 VSCode : Enable Development inside Docker Container

### PR DESCRIPTION
**Pull request by embetrix**
This will enable seamless Development of **optee_os** Project with VSCode inside Docker container.

The VSCode Container provides:

* Automatic Mapping of the host user UID/GID inside the container
* GCC Cross-Compilers (aarch64/armhf/riscv64)
* GDB Multiarch for Debugging
* Remote SSH on the Target with seamless ssh mapping of the Host inside the container (Linux/Windows WSL)
* Git and Git Extensions to work and send Patches

Note: This require Docker installation for Linux/or Windows :
      [1] https://docs.docker.com/engine/install

      VSCode Extensions (extensions.json) will be recommended for the installation

For more Information :
[2] https://code.visualstudio.com/docs/devcontainers/containers 
[3] https://www.youtube.com/watch?v=C_5tDWsWSj0
[4] https://www.youtube.com/watch?v=b1RavPr_878

### CODE REVIEW

**Comment by embetrix** [comment]
Any updates on this MR?

**Comment by jforissier** [comment]
LGTM.

`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by embetrix** [comment]
done

**Comment by gagachang** [comment]
I encountered the following error when I build `optee_os` inside VS Code Dev Container:
```shell
GEN     out/riscv-plat-virt/core/ta_pub_key.c
Traceback (most recent call last):
  File "/workspaces/optee_os/scripts/pem_to_pub_c.py", line 34, in main
    key = serialization.load_pem_private_key(data, password=None,
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/serialization/base.py", line 20, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1218, in load_pem_private_key
    return self._load_key(
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1454, in _load_key
    self._handle_key_loading_error()
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1512, in _handle_key_loading_error
    raise ValueError(
ValueError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/optee_os/scripts/pem_to_pub_c.py", line 71, in <module>
    main()
  File "/workspaces/optee_os/scripts/pem_to_pub_c.py", line 38, in main
    key = serialization.load_pem_public_key(data,
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/serialization/base.py", line 25, in load_pem_public_key
    return backend.load_pem_public_key(data)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1248, in load_pem_public_key
    self._handle_key_loading_error()
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1512, in _handle_key_loading_error
    raise ValueError(
ValueError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.
make: *** [mk/subdir.mk:188: out/riscv-plat-virt/core/ta_pub_key.c] Error 1
```

Issue is solved after I copied the content of `default.pem` into `default_ta.pem`.
It seems symbolic link does not work inside Dev Container.

**Comment by embetrix** [comment]
@gagachang what kind of environment are you using vscode on ? Linux ? Windows WSL ? if WSL make sure you are checking out the project on ext4 FS maybe ?

**Comment by embetrix** [comment]
I have just checkout out the master and built using VSCode Container : no problems. If you have more details open a ticket in Issue and describe excactly what is your environment and how to reprodcue this issue. here is a closed Merge request !

**Comment by gagachang** [comment]
> @gagachang what kind of environment are you using vscode on ? Linux ? Windows WSL ? if WSL make sure you are checking out the project on ext4 FS maybe ?

Hi @embetrix I use VSCode on Windows so it should be WSL.
I just cloned the project into my Windows desktop so it should be on NTFS...
Do I need to clone the project on EXT4 FS?

**Pull request merged**
