### PR TITLE
scripts: port gen_ldelf_hex to python3

### PR DESCRIPTION
**Pull request by Emantor**
Simple port for gen_ldelf_hex to python3.

### CODE REVIEW

**Comment by jbech-linaro** [comment]
Looking good and I couldn't see any `pycodestyle` warnings/errors, so with that:
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by Emantor** [comment]
The required change for shippable to work is to switch from `python-pyelftools` to `python3-pyelftools`.

**Comment by Emantor** [comment]
Tag applied.

**Comment by jforissier** [comment]
@Emantor 

> The required change for shippable to work is to switch from python-pyelftools to python3-pyelftools.

I'll take care of updating the Docker image. Thanks!

**Comment by lorc** [comment]
@Emantor, thanks for the patch. I just stepped right into the same problem myself.

**Pull request merged**
