### PR TITLE
Fix handling of  CFG_{THREAD,TMP}_STACK_EXTRA

### PR DESCRIPTION
**Pull request by jforissier**
Fix issues with `CFG_THREAD_STACK_EXTRA` and `CFG_TMP_STACK_EXTRA` and improve diagnostics messages.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by ldts** [comment]
tested on stm32mp1 (pager enabled platform)

**Comment by jforissier** [comment]
> tested on stm32mp1 (pager enabled platform)

Good! May I convert this into a `Tested-by: Jorge Ramirez-Ortiz <jorge@foundries.io> (STM32MP1, pager)` tag?

**Comment by ldts** [comment]
> > tested on stm32mp1 (pager enabled platform)
> 
> Good! May I convert this into a `Tested-by: Jorge Ramirez-Ortiz <jorge@foundries.io> (STM32MP1, pager)` tag?

I run the xtests suite with the SE050 i2c device (which requires the extra stack)

**Comment by jforissier** [comment]
@jbech-linaro re. the IBART error: the tag 2021.11 does exist in buildroot and I could clone the HiKey repo with no issue, so I suspect a local issue, perhaps with the reference forest?

**Review by etienne-lms — COMMENTED** [review]
`Acked-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by jbech-linaro** [comment]
> @jbech-linaro re. the IBART error: the tag 2021.11 does exist in buildroot and I could clone the HiKey repo with no issue, so I suspect a local issue, perhaps with the reference forest?

Indeed, checked, seems to be a similar issue as we had with U-Boot the other week. I wiped buildroot from the local reference and resynced which seemed to get it back on track. I've restarted all affected jobs in IBART.

 I suspect that the disc is dying (it's been running 24/7 since 2013 more or less).

**Pull request merged**
