### PR TITLE
Update description files for RK322X

### PR DESCRIPTION
**Pull request by TonyXie06**
Update .travis.yml, MAINTAINERS.md and  README.md for RK322X #1666

### CODE REVIEW

**Comment by jforissier** [comment]
Minor comment: you should probably drop the word "description" from ".travis.yml: Add Rockchip RK322X description".
Thanks for the updates and for adding yourself as a maintainer.

`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by TonyXie06** [comment]
Agreed, I will drop it.

jforissier, I discussed with my teammates and come to an advice: may I use a public email account as maintainer ,  just like "Rockchip <rockchip-op-tee@rock-chips.com>" ?  Because there will be more Rockchip SoCs supported by me or my teammates in the future, many of us play different roles for porting and maintainance work.

**Comment by jforissier** [comment]
@TonyXie06 I think a "generic" maintainer address is fine. So, if it is more convenient for you please go ahead and update it.

**Comment by TonyXie06** [comment]
1. tags applied;
2. drop word "description" from ".travis.yml: Add Rockchip RK322X description";
3. update maintainer as "Rockchip <op-tee@rock-chips.com>".

**Pull request merged**
