### PR TITLE
ltc: ctr: improve performance

### PR DESCRIPTION
**Pull request by vchong**
When accel_ctr_encrypt() is not used, accel_ecb_encrypt() is used via
ecb_encrypt() instead. The accel_ecb_encrypt() is frequently called at
every single block process. VFP assembly code called from the
accel_ecb_encrypt() is protected by
tomcrypt_arm_neon_enable()/disable(). FIQ enable/disable and VFP
register save/restore (64bitx32 registers!) to/from memory are done in
the tomcrypt_arm_neon_enable()/disable(). These overhead exist in each
single block process cause the degradation of system performance
eventually. Cases where h/w accelerated AES-CTR did not show any effects
or showed less performance than pure software processing have been
observed.

This patch resolves the issue by increasing utilization rate of
accel_ctr_encrypt().

Signed-off-by: Tetsuya Yoshizaki <yoshizaki.tetsuya@socionext.com>

### CODE REVIEW

**Comment by jforissier** [comment]
4003.9 and 4003.10 fail on HiKey. Has the author run `xtest`?

**Comment by vchong** [comment]
Updated

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey960)`

Performance improvement verified with https://github.com/OP-TEE/optee_test/pull/264.

image

**Comment by jforissier** [comment]
@sjaeckel FYI, comments welcome!

**Comment by vchong** [comment]
Can this proceed if there are no comments from @sjaeckel?

**Comment by jforissier** [comment]
@vchong fine by me.
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by vchong** [comment]
@jforissier Rebased, squashed and tag added. Also https://github.com/libtom/libtomcrypt/pull/359. Thanks!

**Comment by jforissier** [comment]
You've got the author name wrong (S-o-b...), can you please fix it?

**Comment by vchong** [comment]
@jforissier Oops, so sorry. Fixed.

**Comment by jforissier** [comment]
Sorry to bother you again... but I think you should add your own S-o-b: after Testuya's, as per https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst?h=v4.16-rc5#n446.

**Comment by vchong** [comment]
No problem. S-o-b added. Thanks!

**Comment by jforissier** [comment]
Found an issue: https://github.com/OP-TEE/optee_os/pull/2235#issuecomment-379054576. Investigating.

**Comment by jforissier** [comment]
> Found an issue: https://github.com/OP-TEE/optee_os/pull/2235#issuecomment-379054576. Investigating.

I think this PR just reveals a bug in `core/lib/libtomcrypt/src/ciphers/aes_modes_armv8a_ce_a32.S`: the counter does not seem to be incremented as it should. This is consistent with the fact that I cannot reproduce the issue in AArch64.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/2243

**Pull request merged**
