### PR TITLE
core: pta: drop benchmark

### PR DESCRIPTION
**Pull request by igoropaniuk**
Drop Benchmark PTA as current implementation is non-function and obsolete, and it's not supported anymore.

### CODE REVIEW

**Comment by igoropaniuk** [comment]
Created in advance for the next merge window

**Review by jenswi-linaro — COMMENTED** [review]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by igoropaniuk** [comment]
@jenswi-linaro tag applied and rebased. thanks

**Comment by igoropaniuk** [comment]
@etienne-lms tag applied, thanks!

**Pull request merged**
