### PR TITLE
Platprop

### PR DESCRIPTION
**Pull request by pascal-brand-st-dev**
Only the last commit is relevant. This is an attempt to add platform specific properties, and is to be reviewed to know if we should go in that direction or not. The aim is not to merge the Microsoft specific properties, but is that any platform can support its own set of specific properties, without the need to change OP-TEE.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
The extended properties don't have anything to do with the platform. The extended properties are instead vendor specific or only optional. I think we should aim for having all extended properties optional (can be enabled/disabled independently) while still being binary compatible (TAs shouldn't need recompiling when disabling a property etc). The id number of the property should be fixed once assigned.

**Comment by paswan-ms** [comment]
Were there some reasons for having the property handling split between the TA libraries and TEE the way that it is? 

If the TA lib just handled the type conversions and didn't interpret the property strings it could make a single call to the Core passing the property string with a binary blob parameter for everything. The Core could then lookup the property string directly and handle it all in one place. No intermediate enums or stubs for every property would be needed and the change to implement extended properties would only be the platform call when the property wasn't found in the GP defined list. It'd be cleaner and less code for all the property handling and the TA would never need to change if new properties are added and removed (and to add a GP property would need only a single table entry and a single handler for it).

As it is now, adding a property needs a number of changes in several files to plumb it through end-to-end. I know it may be too late or too much work to redesign it, but I thought it was worth mentioning...

**Comment by pascal-brand-st-dev** [comment]
@paswan-ms We got internal discussions here, and we think you are right: adding a property is not that easy right now, and the split user/kernel is not straightforward.

What we should try to achieve is:
* add the possibility to add extended properties
* these properties could be part of OP-TEE
* they should be optional (by default not included), and could be selected in "simple" way one by one from the platform configuration.
* something to take care: ta specific properties that are part of `ta/arch/um/user_ta_header.c` (cf. `TA_CURRENT_TA_EXT_PROPERTIES`)

Paul, do you have any design in mind? Would you have time to propose something like this in OP-TEE?

@jenswi-linaro @jforissier @jbech-linaro Do not hesitate to add anything if I forgot some points.

**Comment by paswan-ms** [comment]
In terms of design, collapse "propset_implementation[]" into "tee_props_lut[]". Redefine "utee_get_property" to delete the "utee_property" parameter and add "char prop[PROP_STR_MAX]" to the "prop_val" struct to pass through the property string name (where PROP_STR_MAX is reasonable enough to hold a long property string name).
 
"propget_get_property" collapses into "tee_svc_sys_get_property" and the big "prop" case statement disappears because we'd use an optional handler function defined in "tee_props_lut[]" (similar to how "propset_implementation[]" did) that would only be needed for the complex (none-const) properties.
Paul.

**Comment by pascal-brand-st-dev** [comment]
Implemented in https://github.com/OP-TEE/optee_os/pull/648, https://github.com/OP-TEE/optee_os/pull/651 and https://github.com/OP-TEE/optee_os/pull/656

**Pull request closed without merging**
