### PR TITLE
ci: travis: delete toolchain binaries after download

### PR DESCRIPTION
**Pull request by jforissier**
Since build.git has been upgraded to GCC 8.2 [1], we are running out of
disk space when running the Travis CI script. This is because the GCC 8.2
binaries are much larger than 6.2:

 218M gcc-arm-8.2-2018.08-x86_64-aarch64-linux-gnu.tar.xz
 213M gcc-arm-8.2-2018.08-x86_64-arm-linux-gnueabihf.tar.xz
  94M gcc-linaro-6.2.1-2016.11-x86_64_aarch64-linux-gnu.tar.xz
  88M gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf.tar.xz

This commit makes some room by deleting the packages once they have been
extracted.

Link: [1] https://github.com/OP-TEE/build/commit/53119b77e9f2
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

### CODE REVIEW

**Comment by jbech-linaro** [comment]
We're living on the edge ;-)

`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
@jbech-linaro True... :-/ Hopefully by the time we need this space Travis will have increased the disk quota :D

**Comment by jforissier** [comment]
Update. Some more cleanup is needed apparently.

**Comment by jforissier** [comment]
Ping?

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Pull request merged**
