### PR TITLE
plat-vexpress: juno: add missing DRAM1

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Defines missing DRAM1 base 0x880000000 size 0x180000000 for Juno.

Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

Depends on https://github.com/OP-TEE/optee_os/pull/1860

### CODE REVIEW

**Comment by ken08liu14** [comment]
Hi Jens,
after register_nsec_ddr() is applied, adding SDP with CFG_TEE_SDP_MEM_BASE and the panic would appear on vexpress; and we have to do some hard code to skip SDP area in NSDDR to fix it.

I may comment this problem in other places so please just reply one is OK, sorry.

-Ken.

**Comment by jenswi-linaro** [comment]
Hi Ken,

I'll address that problem in a separate pull request.

Thanks,
Jens

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Rebased, tag applied

**Pull request merged**
