### PR TITLE
Copy additional header file to out dir

### PR DESCRIPTION
**Pull request by ashutoshksingh**
Added header is used by linaro test suite build

Signed-off-by: Ashutosh Singh <ashutosh.singh@arm.com>
Reviewed-by: James King <james.king@arm.com>

Change-Id: Ia5d1845e4dac75669169420becc8a5b1c72cef06
Signed-off-by: Ashutosh Singh <ashutosh.singh@arm.com>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Why do we need to include types_ext.h in xtest?

**Comment by ashutoshksingh** [comment]
types_ext.h is included by signed_hdr.h, which in turn is included by xtest.

**Comment by jenswi-linaro** [comment]
We changed `signed_hdr.h` to include `inttypes.h` instead of `types_ext.h` to avoid this.

**Comment by ashutoshksingh** [comment]
Okay, yes I see that in your oct 26 commit. thanks. I will withdraw this change then.

**Pull request closed without merging**
