### PR TITLE
4kta

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Enables mapping of TAs using 4k pages

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
FVP tests are fine, but it is not working with plat-stm.

**Comment by jenswi-linaro** [comment]
TAs are loaded at a new address with this, so if you do something special with relocation that could be something to look at.

**Comment by jbech-linaro** [comment]
@pascal-brand-st-dev , talked to Jens also, he will create a new pull request with the two first patches, sounds OK?

**Comment by jenswi-linaro** [comment]
The first two patches are copied to a new PR, https://github.com/OP-TEE/optee_os/pull/689

**Comment by jenswi-linaro** [comment]
Replaced by https://github.com/OP-TEE/optee_os/pull/740

**Pull request closed without merging**
