### PR TITLE
drivers: regulator: fix error case in regulator_supported_voltages() + split asserts

### PR DESCRIPTION
**Pull request by etienne-lms**
2 changes:
* Fix case when `.supported_voltages()` handler is supported to assert voltage description when the handler succeeds and to use pre-filled fallback description when the handler returns `TEE_ERROR_NOT_SUPPORTED` instead of asserting @*desc content while that pointer was likely not initialized with a valid address.
Fixes: af5b9881111c ("drivers: regulator: supported voltage consider levels bounds")
* Split assertions in `regulator_supported_voltages()` to ease debugging, providing a better indication of which condition is not fulfilled.

### CODE REVIEW

**Review by etienne-lms — COMMENTED** [review]
@gatien or @patrickdelaunay, may I ask you to have a look at these 2 changes?

**Comment by GseoC** [comment]
The commit description of `drivers: regulator: fix error case in regulator_supported_voltages()` commit is a bit unclear to me, would you mind rephrasing it? maybe something like:

```
Fix case when .supported_voltages() handler exists but reports TEE_ERROR_NOT_SUPPORTED.
In this case, the regulator should use the fallback values.
```

I let you mix my suggestion with whatever you esteem right.

With this changed:

`Acked-by: Gatien Chevallier <gatien.chevallier@foss.st.com>`

**Comment by patrickdelaunay** [comment]
For the series:

Acked-by: Patrick Delaunay <patrick.delaunay@foss.st.com>

**Comment by etienne-lms** [comment]
> The commit description of drivers: regulator: fix error case in regulator_supported_voltages() commit is a bit unclear to me, would you mind rephrasing it? maybe something like:

Thanks Gatien, indeed the sentence is far to long and not readable.

**Comment by etienne-lms** [comment]
I've rephrased in 1st commit message and applied the review patches to both.

**Review by GseoC — APPROVED** [review]

**Comment by GseoC** [comment]
Keep alive

**Pull request merged**
