### PR TITLE
ta: pkcs11 - Fixes for symmetric key and indirect templates

### PR DESCRIPTION
**Pull request by ruchi393**

### CODE REVIEW

**Review by etienne-lms — COMMENTED** [review]
for commit "ta: pkcs11: Modify optional attributes for symmetric key":
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

For commit "ta: pkcs11: Add sanitize function for symmetric keys":
missing S-o-b, LGTM otherwise (`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`)

For commit "ta: pkcs11: Remove class and key check for indirect attributes":
Really no issue in removing these tests? I'll give a 2nd look.

For commit "ta: pkcs11: Add restriction in C_GetAttributeValue()":
See comment. Using existing function: `Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by ruchi393** [comment]
Thanks for the review @etienne-lms .
Fixed  existing function in "ta: pkcs11: Add restriction in C_GetAttributeValue()". Tag added to the commit.
Tag also added to :
"ta: pkcs11: Modify optional attributes for symmetric key":
 "ta: pkcs11: Add sanitize function for symmetric keys":

For commit - "ta: pkcs11: Remove class and key check for indirect attributes":
I might have understood it wrong. So thought adding an example will help us brainstorm if my understanding is correct.

PKCS#11 specification doesn't mandate that indirect template have class and key specified. Imagine a case where an indirect template contains another indirect template. In this scenario parent indirect template may not have the class and key specified. We can pass the class and key hint of the parent. I tried that but that leads to the addition of this class and key attribute in the indirect template which is not correct.

eg 
a secret key can be used to wrap -> secret key/private key.
When unwrapping this wrapped secret key/private key, the unwrap template may specify class ot key if there is a restriction on which type of keys this secret key can unwrap or the unwrap template may just have attribute like sensitive, extractable etc.
Now the secret key created with this unwrapping may be further used for wrap/unwrap so may have an unwrapping template associated with it. It is not essential that this chain of unwrap templates will have the class and key attributes. Hence IIUC, this checking is not required.

**Comment by ruchi393** [comment]
The error shown by IBART in tests are expected. They are fixed by this PR - https://github.com/OP-TEE/optee_test/pull/497

**Comment by etienne-lms** [comment]
@ruchi393, would you agree creating a specific P-R for commit "ta: pkcs11: Remove class and key check for indirect attributes" so that the other reviewed patches can hit the mainline?

**Comment by ruchi393** [comment]
> @ruchi393, would you agree creating a specific P-R for commit "ta: pkcs11: Remove class and key check for indirect attributes" so that the other reviewed patches can hit the mainline?

Sure, I was thinking of doing the same.

**Comment by ruchi393** [comment]
New PR created for "ta: pkcs11: Remove class and key check for indirect attributes" - https://github.com/OP-TEE/optee_os/pull/4467

This PR has now 3 commits which are reviewed and have tags applied.

**Review by etienne-lms — APPROVED** [review]

**Pull request merged**
