### PR TITLE
core: cleanup tlb maintenance source files

### PR DESCRIPTION
**Pull request by etienne-lms**
Functions secure_get_cpu_id(), secure_mmu_datatlbinvall(), and
secure_mmu_disable() are not implemented. Remove their prototype.

ssvce_aXX.S and tz_ssvce.h now only provide TLB maintenance support.
This change renames the source and header files accordingly.

This P-R is just about file renaming and cleaning few minor deprecated things. It follows recently merged https://github.com/OP-TEE/optee_os/pull/1603.

### CODE REVIEW

**Comment by jforissier** [comment]
I would prefer this PR split in 3 commits:
1. core: arm: tz_ssvce.h: remove unused functions
2. core: arm: ssvce_a32.S, ssvce_a64.S: remove useless includes/comments
3. core: arm: rename TLB maintenance files

Other than that, it looks good.
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Copyright year should also be updated on tlb_helpers.h, tlb_helpers_a32.S and tlb_helpers_a64.S

with that:
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
Comments addressed (+ include sorting and comment indentation fixed)

**Comment by jenswi-linaro** [comment]
Copyright year for tlb_helpers.h should be updated also.

**Comment by etienne-lms** [comment]
squashed

**Pull request merged**
