### PR TITLE
Fixing issues around FF-A direct message handling in SPMC

### PR DESCRIPTION
**Pull request by imre-kis-arm**
There were multiple issues with FF-A direct message error handling in the SPMC component. This pull request introduces fixes in the following steps.
- Set initial SP state to busy which will prevent sending direct messages to uninitialized SPs.
- Clear MBZ registers of FFA_ERROR messages. This prevents sending back the reminiscence of the direct message in the error message.
- Cover all invalid cases in FF-A direct message request and response handlers. Also fix the logic behind determining the destination of the FFA_ERROR message.

I've extended the [SPMC test in trusted-services](https://review.trustedfirmware.org/c/TS/trusted-services/+/22959/1/components/service/spm_test/sp.c) by negative tests for covering all the error handler branches of FF-A direct message handlers.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by imre-kis-arm** [comment]
Could you please merge this pull request if there are no concerns with the change?

**Comment by jforissier** [comment]
@imre-kis-arm sure, sorry for the delay.

**Comment by imre-kis-arm** [comment]
No worries, thank you.

**Pull request merged**
