### PR TITLE
riscv: support page table cache

### PR DESCRIPTION
**Pull request by maroueneboubakri**
To support page table cache we re-use the original implementation. We move `pgt_cache.c` under `core/mm` and we set `CFG_WITH_LPAE ` if `CFG_CORE_LARGE_PHYS_ADDR` is set (which is the case for virt platform).
Flag names are kept as they are despite they are ARM related (EL0, LPAE).

### CODE REVIEW

**Comment by gagachang** [comment]
Maybe some comments could be added  into `riscv.mk` to describe the reuse of `CFG_WITH_LPAE`

**Comment by maroueneboubakri** [comment]
WIP

**Comment by jenswi-linaro** [comment]
For "core: mm: move pgt_cache.c to core/mm":
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
@gagachang does that looks OK to you?

**Comment by gagachang** [comment]
> @gagachang does that looks OK to you?

Yes, LGTM.

If any RISC-V guys' tag is needed, please apply
`Reviewed-by: Alvin Chang <alvinga@andestech.com>`

**Comment by maroueneboubakri** [comment]
@jforissier tags applied.

**Comment by jforissier** [comment]
> @jforissier tags applied.

I believe the tag is applicable to the 1st commit too.

**Pull request merged**
