### PR TITLE
core: mm: ensure all pager VA space is mapped with small pages

### PR DESCRIPTION
**Pull request by etienne-lms**
Fix can_map_at_level() to ensure all memory areas related the pager pageable virtual memory are mapped with small pages. This change fixes an issue found when the pager physical RAM ends on a section boundary (e.g. 512MB or 2MB on LPAE case) making the virtual memory mapping above that boundary to be prepared with pgdir or wider MMU tables while pager implementation expects 4kB page MMU tables.

### CODE REVIEW

**Comment by etienne-lms** [comment]
This fix is not urgent. No strong need to consider it for tomorrow 4.3.0 release.

**Review by jenswi-linaro — COMMENTED** [review]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
I have appended a commit for plat-stm32mp1 that leverage the fix from the first commit.
This appended commit is not yet reviewed.

**Review by jenswi-linaro — COMMENTED** [review]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
Review tags applied. Thanks.

**Pull request merged**
