### PR TITLE
crypto:add {cipher,hash,authenc,mac}{create,destroy,copy}

### PR DESCRIPTION
**Pull request by GuanchaoLiang**
The origin crypto operation as follow steps:
`crypto_ops.{cipher,hash,authenc,mac}.init`
`crypto_ops.{cipher,hash,authenc,mac}.update`
`...`
`crypto_ops.{cipher,hash,authenc,mac}.update`
`crypto_ops.{cipher,hash,authenc,mac}.final`

After the change, the crypto operation will like this:
`crypto_ops.{cipher,hash,authenc,mac}.create`
`crypto_ops.{cipher,hash,authenc,mac}.init`
`crypto_ops.{cipher,hash,authenc,mac}.update`
`...`
`crypto_ops.{cipher,hash,authenc,mac}.update`
`crypto_ops.{cipher,hash,authenc,mac}.final`
`crypto_ops.{cipher,hash,authenc,mac}.destroy`

Signed-off-by: Guanchao Liang <liang.guanchao@linaro.org>
Signed-off-by: Zeng Tao <prime.zeng@hisilicon.com>

### CODE REVIEW

**Comment by jforissier** [comment]
Hi @GuanchaoLiang @prime-zeng, thanks for submitting this PR.

Before doing a detailed review, I see several issues with this PR. I'm not saying it's bad, but I don't know what to think about it for the following reasons.
- Your commit message must describe what you are changing, and more importantly why you are changing it. You should copy what you added in your first comment and explain the reasons. Don't be afraid of long commit messages -- they are really useful IMO.
- You're changing a lot of things inside LibTomCrypt. Why is it needed? It is a problem because we periodically synchronize with upstream, and to make this as easy as possible we want to minimize the differences between our implementation and upstream. If you do have to change things inside LTC, then please make a separate commit and at the same time, also open a pull request on LTC so that the changes are discussed with the maintainers. They may have better ideas on how to achieve what you are trying to do.
- If you're proposing this change in order to implement some hardware-specific acceleration, then I think we need to have this code too. Because, even if we don't have the hardware to test it, at least it will greatly help understand the reason for the change, why you're doing it like this, and also ensure that future changes won't go against what you have done in your implementation. In other words, we're not very interested in adding framework code (create/destroy/copy) that is not used for anything meaningful in our branch.

**Comment by GuanchaoLiang** [comment]
@jforissier Sorry about this PR, I will close it then and take the action as you comment.

**Comment by jforissier** [comment]
@GuanchaoLiang don't be sorry ;) maintainers and reviewers are here to help, so everything you're submitting here for review is good. That is how we discuss and come up with a good implementation in the end. Thanks!

**Comment by GuanchaoLiang** [comment]
Thanks, Jerome!! Happy to see your so nice reply. But I don't know why I
just receive this email, I see the time you reply is 4 days ago :)

Thanks again,
Liang

**Pull request closed without merging**
