### PR TITLE
core: add missing include of arm.h in arm32.h

### PR DESCRIPTION
**Pull request by etienne-lms**
minor fix...

### CODE REVIEW

**Comment by etienne-lms** [comment]
Updated commit with a nice description for the dear CI.

**Comment by jforissier** [comment]
Not needed I think, you should include `arm.h|` instead (`arm.h` includes `arm32.h`)

**Comment by etienne-lms** [comment]
You mean it is a better practice to `#include <arm.h>` rather than `<arm32.h>`?
Should **arm.h** include this code? 
```h 
#ifdef ARM32_H
#error include arm.h rather than arm32.h
#endif
```

I don't mean being nitpicking but I made a change in my platform **reset.S** source that requires `CPSR_MODE_MON` from **arm32.h** hence I included **arm32.h** and I got this build error log:
```
core/arch/arm/plat-stm32mp1/reset.S: Assembler messages:
core/arch/arm/plat-stm32mp1/reset.S:38: Error: constant expression required -- `cps #ARM32_CPSR_MODE_MON'
```
Not obvious the fix is to replace `#inculde <arm32.h>` with `#include <arm.h>` in my source file even if indeed a nice correction. There are few platform source files that currently straightly include **arm32.h**. Should we fix them all?

**Comment by jenswi-linaro** [comment]
I agree with Jerome, it's generally preferable to include arm.h over arm32.h.

A check like that would be nice too, but perhaps after the release and also I think the check belongs in arm32.h and arm64.h instead.

**Comment by etienne-lms** [comment]
Ok, fine with me. I close this PR.

**Pull request closed without merging**
