### PR TITLE
Update CHANGELOG.md for 3.14.0

### PR DESCRIPTION
**Pull request by jforissier**
Update CHANGELOG for 3.14.0 and collect Tested-by tags.

Signed-off-by: Jerome Forissier <jerome@forissier.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)`

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome@forissier.org> (HiKey960 GP)`

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (imx-mx8mqevk)`

**Comment by sahilnxp** [comment]
On commit ID: `1d88c0c03f3bed5776739e459a598a011baa5207 core: clear temporary stack flag before entering boot_init_primary_late()`

`Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS1012A-RDB)`
`Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS1043A-RDB)`
`Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS1046A-RDB)`
`Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS1088A-RDB)`
`Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS2088A-RDB)`
`Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LX2160A-RDB)`

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome@forissier.org> (QEMUv8 GP PKCS#11)`

**Comment by jforissier** [comment]
Tested-by: Jerome Forissier <jerome@forissier.org> (QEMU GP PKCS#11)

**Comment by clementfaure** [comment]
Hello!
Same boards as usual but with the recently added mx8mpevk platform.
I will align with @jenswi-linaro and designate boards like so `$PLATFORM-$PLATFORM_FLAVOR`

```
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6dlsabreauto)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6dlsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6qpsabreauto)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6sllevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6ulevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6ullevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6ulzevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx7dsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx7ulpevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mmevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mnevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mqevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mpevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8qmmek)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8qxpmek)
```

**Comment by jforissier** [comment]
>  will align with @jenswi-linaro and designate boards like so `$PLATFORM-$PLATFORM_FLAVOR`

Good idea :+1: I'll do that next time!

**Comment by b49020** [comment]
For 3.14.0-rc1:

`Tested-by: Sumit Garg <sumit.garg@linaro.org> (Developerbox)`

**Comment by jforissier** [comment]
For 3.14.0-rc1:

`Tested-by: Jerome Forissier <jerome@forissier.org> (hikey)`

**Comment by vchong** [comment]
For 3.14.0-rc1:

`Tested-by: Victor Chong <victor.chong@linaro.org> (QEMUv8 AOSP)`

`pkcs11_1014.1` is failing but don't know why yet.

**Comment by lorc** [comment]
For 3.14.0-rc1:

`Tested-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com> (rcar-salvator_m3_2x4g)`
`Tested-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com> (rcar-salvator_m3_2x4g / virt)`

```
26166 subtests of which 0 failed
93 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by etienne-lms** [comment]
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1-157_DK2, pkcs11, gp)`
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1-157_ED1)`
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1-157_EV1)`

**Comment by ricardosalveti** [comment]
With default config + CFG_PKCS11_TA=y CFG_ENABLE_EMBEDDED_TESTS=y:

```
I/TC: OP-TEE version: 3.14.0-rc1-dev (gcc version 10.2.0 (GCC)) #1 Fri 09 Jul 2021 03:47:53 PM UTC aarch64
+-----------------------------------------------------
28809 subtests of which 0 failed
114 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

`Tested-by: Ricardo Salveti <ricardo@foundries.io> (ZynqMP)`

**Comment by clementfaure** [comment]
For `3.14.0-rc1`:

```
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6dlsabreauto)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6dlsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6qpsabreauto)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6sllevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6ulevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6ullevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6ulzevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx7dsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx7ulpevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mmevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mnevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mqevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mpevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8qmmek)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8qxpmek)
```

**Pull request merged**
