### PR TITLE
GP11 : TEE Arithmetical API fix/panic reason

### PR DESCRIPTION
**Pull request by cedric-chaumont-st-dev**
Signed-off-by: Cedric Chaumont <cedric.chaumont@st.com>

### CODE REVIEW

**Comment by cedric-chaumont-st-dev** [comment]
Test: Use optee_test branch dev/gp11_arith_func

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

Let's try to merge the PR that are already reviewed by 2 people before adding new ones.

Could you add a PR on OP-TEE/optee_test about the test change?

**Comment by cedric-chaumont-st-dev** [comment]
Done.

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by cedric-chaumont-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
Tested-by: Cedric Chaumont <cedric.chaumont@linaro.org> (STM boards)
Tested-by: Cedric Chaumont <cedric.chaumont@linaro.org> (ARM Juno board)
28716 subtests of which 0 failed
687 test cases of which 0 failed
0 test case was skipped
TEE test application done!
Note : optee_os PR #394 ,  optee_test PR #6 and #7 required

**Pull request merged**
