### PR TITLE
Rounding fix

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Fixes problem with upper 32-bit of a 64-bit address being zeroed out when rounding the address.

### CODE REVIEW

**Comment by etienne-lms** [comment]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by jenswi-linaro** [comment]
@zhizhouzh is it OK if I add:
```
Reported-by: Zhizhou Zhang <zhizhouzhang@asrmicro.com>
Tested-by: Zhizhou Zhang <zhizhouzhang@asrmicro.com>
```
to the commits?

**Comment by zhizhouzh** [comment]
@jenswi-linaro Sure, no problem.

**Comment by jenswi-linaro** [comment]
Rebased tags applied.

**Pull request merged**
