### PR TITLE
plat-stm32mp1: default enable CFG_ENABLE_EMBEDDED_TESTS

### PR DESCRIPTION
**Pull request by etienne-lms**
Changes platform stm32m1 to default enable CFG_ENABLE_EMBEDDED_TESTS
rather than CFG_TEE_CORE_EMBED_INTERNAL_TESTS to get all embedded tests
support including the test interface PTAs.

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jenswi-linaro** [comment]
This looks safe to merge.

**Comment by jforissier** [comment]
> This looks safe to merge.

Agreed, sorry for not doing it earlier.

**Comment by etienne-lms** [comment]
no worry. thanks.

**Pull request merged**
