### PR TITLE
core: tee_mm.c: Pull architecture-independent code from arch folder

### PR DESCRIPTION
**Pull request by maroueneboubakri**
When porting OP-TEE OS to another architecture we end up with a huge amount
of code being duplicated. The purpose of this commit is to check the
feasibility of re-factoring the project tree to sort out
architecture-independent code to ease the portability and the maintenance
for other archs.
I started with tee_mm.c, I would move it to tee folder core/tee/ rather
than core/mm considering the tee_ prefix.

Signed-off-by: Marouene Boubakri <marouene.boubakri@nxp.com>

### CODE REVIEW

**Comment by etienne-lms** [comment]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by jenswi-linaro** [comment]
The `tee_` prefix is there for historical reasons, `core/mm` is a better place.

**Comment by jforissier** [comment]
@maroueneboubakri FYI, you are not supposed to keep any `Reviewed-by:` tags whenever you're making significant changes. No need to force-push now however -- let's proceed with the review.

**Comment by etienne-lms** [comment]
> The `tee_` prefix is there for historical reasons, **core/mm** is a better place.

All exported function names are `tee_mm_xxx()` so having the source file named **tee_mmc.c** is quite convenient.

**Comment by maroueneboubakri** [comment]
Request for merging

**Comment by jforissier** [comment]
> Request for merging

A bit too soon don't you think? :wink:

**Comment by maroueneboubakri** [comment]
> > Request for merging
> 
> A bit too soon don't you think? 😉

I would close this and open a new one to handle the other components also (mmu, pager, mobj ..) in one shot ?

**Comment by jforissier** [comment]
@maroueneboubakri as you see fit. In any case you need to leave some time for reviewing, as you can see some decisions require some discussions and incremental changes so we can reach an agreement on what's best.

**Comment by jenswi-linaro** [comment]
> > The `tee_` prefix is there for historical reasons, **core/mm** is a better place.
> 
> All exported function names are `tee_mm_xxx()` so having the source file named **tee_mm.c** is quite convenient.

Yeah. With `tee_` prefix I meant both the files and what's in them.

**Pull request closed without merging**
