### PR TITLE
GP Internal Core API v1.1 : update TEE_AllocateOperation ECC

### PR DESCRIPTION
**Pull request by cedric-chaumont-st-dev**
add TEE_ALG_ECDSA_Pxxx/TEE_ALG_ECDH_Pxxx

Signed-off-by: Cedric Chaumont <cedric.chaumont@st.com>

### CODE REVIEW

**Comment by cedric-chaumont-st-dev** [comment]
Update

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by cedric-chaumont-st-dev** [comment]
Rebase.

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by cedric-chaumont-st-dev** [comment]
Squashed. Rebased. Tested.

**Pull request merged**
