### PR TITLE
Use core_mmu_get_va whenever possible

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
The changes in plat-hikey are good, but for the others it's actually changed behavior since the result from `phys_to_virt()` was cached.

**Comment by vchong** [comment]
Ok. I'll remove the changes for the other plats. Thanks!

**Comment by vchong** [comment]
Comment addressed.

**Comment by jenswi-linaro** [comment]
The commit message could describe the commit a bit more, and also please put a pair of `()` after the function name to make it stand out better.

With that:
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by vchong** [comment]
Commit message updated and tag added. Ready for merge. Thanks!

**Pull request merged**
