### PR TITLE
crypto API: make sure TEE_Attribute parameters are readable

### PR DESCRIPTION
**Pull request by jforissier**
Fixes https://github.com/OP-TEE/optee_os/issues/161.

Services that take a TEE_Attribute array for input must check that the
memory is readable before using it. This is accomplished by
check_attr_read_access(), which is either called directly by the system
service or by tee_svc_cryp_check_attr(). Buffers pointed to by 'reference'
attributes are also validated.
Then, it is no longer necessary to check accessibility in other
functions such as tee_svc_cryp_obj_store_attr_raw().

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
A bug has been entered in GP. In the meantime, I propose to accept this patch if the XML test file is fixed with respect to this.

@jforissier Could you send me and Cedric the patch of the XML file to that the tests run ok?

    Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jforissier** [comment]
I have updated optee_test to take into account the new behavior introduced
by this PR. Please check branch optee-pr-167.

* XTEST_TEE_7537 9d-5c-6a
ERR [629] TEEC:TEEC_InvokeCommand:402: Function returns with [-53212]
  XTEST_TEE_7537 OK

**Comment by jforissier** [comment]
Rebased with tags applied.

**Comment by pascal-brand-st-dev** [comment]
@jforissier can you rebase?

**Pull request merged**
