### PR TITLE
Remove TEE_OPERATION_EXTENSION

### PR DESCRIPTION
**Pull request by jforissier**
Commit 6a2e0a9fe2b9 ("utee: support prehashed RSA sign/ver without
ASN.1") has introduced TEE_OPERATION_EXTENSION in tee_api_defines.h with
value 0xF. This poses a couple of minor issues:

1. Values 0x00000009-0x7FFFFFFF are "Reserved for future use" according
to the TEE Internal Core API specification v1.2.1 (Table 5-6),

2. The meaning of this #define is not clear: "extension" is not a
kind of operation like "cipher", "MAC", "asymmetric signature" etc.
The algorithm added by the above commit is TEE_ALG_RSASSA_PKCS1_V1_5
which is an asymmetric signature and should therefore be associated with
TEE_OPERATION_ASYMMETRIC_SIGNATURE.

I suppose the operation value was added in a attempt to keep the
structure of algorithm identifiers as defined in the GP v1.1
specification, where some particular bits indicate some attributes of
the algorithm. This scheme has since been abandoned by GlobalPlatform so
there is no reason to keep it.

Therefore, this commit removes the TEE_OPERATION_EXTENSION macro and
makes a special case in the TEE_GET_CLASS() macro so that algorithm
TEE_ALG_RSASSA_PKCS1_V1_5 is associated with
TEE_OPERATION_ASYMMETRIC_SIGNATURE.

Signed-off-by: Jerome Forissier <jerome@forissier.org>

### CODE REVIEW

**Comment by jforissier** [comment]
CC @EDVTAZ.

**Comment by jforissier** [comment]
@EDVTAZ I'll take your "thumbs up" as an Acked-by: if you don't mind, thanks!

**Comment by EDVTAZ** [comment]
Yes, it looks good to me, sorry for being unclear.

**Comment by jenswi-linaro** [comment]
This is an ABI change, quite small though.

**Comment by jforissier** [comment]
> This is an ABI change, quite small though.

The interface between TA and TEE core is unchanged. Only the "return value" of the `TEE_GET_CLASS()` macro is changed; but since it is a macro, pre-compiled applications won't break. Only new TAs, or re-compiled TAs would need to adjust for the different return value. So it is more of an API change, no?

**Comment by jenswi-linaro** [comment]
You're right.
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Pull request merged**
