### PR TITLE
drivers: caam: update return type of caam_sm_free()

### PR DESCRIPTION
**Pull request by sahilnxp**
Update return type of caam_sm_free() from TEE_Result to enum caam_status.

### CODE REVIEW

**Comment by sahilnxp** [comment]
Sorry, There is some error in this patch formatting I am correcting it.

**Comment by sahilnxp** [comment]
> Sorry, There is some error in this patch formatting I am correcting it.

Done.

**Comment by clementfaure** [comment]
`Acked-by: Clement Faure <clement.faure@nxp.com>`

**Comment by sahilnxp** [comment]
Tags applied.

**Pull request merged**
