### PR TITLE
core: lib: scmi-server: drop CFG_CROSS_COMPILE when compiling SCP firmware

### PR DESCRIPTION
**Pull request by GseoC**
Remove unused build directive

### CODE REVIEW

**Comment by GseoC** [comment]
Hi @etienne-lms , @vingu-linaro , can you check this P-R please?
Thx

**Comment by GseoC** [comment]
@jforissier, CI is down for the QEMUV8, Xen build I guess?

**Comment by jforissier** [comment]
@GseoC https://github.com/OP-TEE/build/pull/757 introduced this regression. I was able to reproduce the error in my build environment with `make -k clean; make -j$(nproc) check XEN_BOOT=y` and reverting 757 makes it work again. @jenswi-linaro

**Comment by jenswi-linaro** [comment]
I'm looking at the Xen problem.

**Review by etienne-lms — COMMENTED** [review]
All good to me.
`Reviewed-by: Etienne Carriere <etienne.carriere@foss.st.com>`

**Comment by GseoC** [comment]
Tag applied

**Comment by GseoC** [comment]
@jforissier I think TF-A repo was down or something, can you relaunch the failed build please? (If that's an issue for merging)

**Pull request merged**
