### PR TITLE
Update CHANGELOG for 3.12.0

### PR DESCRIPTION
**Pull request by jbech-linaro**
Update CHANGELOG for 3.12.0 and collect Tested-by tags for the next release.

Signed-off-by: Joakim Bech <joakim.bech@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)`

**Comment by Emantor** [comment]
Is there going to be an RC tag for the release? I can't find it yet.

**Comment by jbech-linaro** [comment]
> Is there going to be an RC tag for the release? I can't find it yet.

Yes, I'm going to send it out today (I think I mentioned that in the email that went out).

**Comment by jbech-linaro** [comment]
Tag `3.12.0-rc1` has been created on `build, manifest, optee_benchmark, optee_client, optee_docs, optee_examples, optee_os, 
 optee_test`, so please continue with your release testing.

**Comment by igoropaniuk** [comment]
In case some one of SDP test fails (`regression_1014.3 SDP: SDP TA invokes a SDP pTA`):

```
o regression_1014.3 SDP: SDP TA invokes a SDP pTA
D/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA 12345678-5b69-11e4-9dbb-101f74f00099
D/TC:? 0 ldelf_load_ldelf:91 ldelf load address 0x40006000
D/LD:  ldelf:134 Loading TA 12345678-5b69-11e4-9dbb-101f74f00099
D/TC:? 0 ldelf_syscall_open_bin:140 Lookup user TA ELF 12345678-5b69-11e4-9dbb-101f74f00099 (Secure Storage TA)
D/TC:? 0 ldelf_syscall_open_bin:144 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:140 Lookup user TA ELF 12345678-5b69-11e4-9dbb-101f74f00099 (REE)
D/TC:? 0 ldelf_syscall_open_bin:144 res=0
D/LD:  ldelf:168 ELF (12345678-5b69-11e4-9dbb-101f74f00099) at 0x40031000
D/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA d96a5b40-c3e5-21e3-8794-1002a5d5c61b
D/TC:? 0 ldelf_load_ldelf:91 ldelf load address 0x40006000
D/LD:  ldelf:134 Loading TA d96a5b40-c3e5-21e3-8794-1002a5d5c61b
D/TC:? 0 ldelf_syscall_open_bin:140 Lookup user TA ELF d96a5b40-c3e5-21e3-8794-1002a5d5c61b (Secure Storage TA)
D/TC:? 0 ldelf_syscall_open_bin:144 res=0xffff0008
D/TC:? 0 ldelf_syscall_open_bin:140 Lookup user TA ELF d96a5b40-c3e5-21e3-8794-1002a5d5c61b (REE)
D/TC:? 0 ldelf_syscall_open_bin:144 res=0xffff0008
E/LD:  init_elf:437 sys_open_ta_bin(d96a5b40-c3e5-21e3-8794-1002a5d5c61b)
E/TC:? 0 ldelf_init_with_ldelf:126 ldelf failed with res: 0xffff0008
D/TC:? 0 tee_ta_open_session:720 init session failed 0xffff0008
E/TA:  cmd_invoke_pta:293 SDP basic test TA: TEE_OpenTASession() FAILED 
D/TC:? 0 tee_ta_invoke_command:825 Error: ffff0008 of 4
Error: invoke SDP test TA (inject) failed ffff0008 4
D/TC:? 0 tee_ta_close_session:514 csess 0x306cac0 id 9
D/TC:? 0 tee_ta_close_session:533 Destroy session
D/TC:? 0 destroy_context:310 Destroy TA ctx (0x306ca60)
regression_1000.c:1243: ret has an unexpected value: 0x1, expected 0x0
  regression_1014.3 FAILED

```

**Comment by igoropaniuk** [comment]
Looks like `CFG_SECURE_DATA_PATH=y` is enabled in `out/arm/conf.mk`, but it doesn't imply `CFG_SDP_PTA`  needed to compile-in SDP PTA.

**Comment by igoropaniuk** [comment]
Looks like `CFG_SECURE_DATA_PATH=y `is enabled in `out/arm/conf.mk`, but it doesn't imply `CFG_SDP_PTA` needed to compile-in SDP PTA. However I see that PTA is being compiled with errors, when I manually set `CFG_SDP_PTA=y` (I assume that it's just dead piece of code and it's not used anymore?).

So maybe should 1014.3 be dropped?

@etienne-lms correct me if I'm wrong. Thanks!

**Comment by etienne-lms** [comment]
I don't remember enabling or modifying around `CFG_SDP_PTA` since... ever. No change around this switch since 3.11.0. It there a regression somewhere? I thought SDP tests were enabled in CI through Qemu but not relying on SDP PTA.

**Comment by igoropaniuk** [comment]
I've cross-checked the code, in https://github.com/OP-TEE/optee_test/blob/master/ta/sdp_basic/ta_sdp_basic.c#L280,  pTA uuid (`PTA_INVOKE_TESTS_UUID`) which used for this particular test points to `invokes_tests.pta`, not `sdp.pta`:
```                                                                                  
#define PTA_INVOKE_TESTS_UUID \                                                 
                 { 0xd96a5b40, 0xc3e5, 0x21e3, \                                 
                         { 0x87, 0x94, 0x10, 0x02, 0xa5, 0xd5, 0xc6, 0x1b } }
```

This pTA isn't compiled, as `CFG_TEE_CORE_EMBED_INTERNAL_TESTS=y` isn't set for Poplar.
PR:
https://github.com/OP-TEE/optee_os/pull/4314
https://github.com/OP-TEE/optee_test/pull/477

With these changes:
```
+-----------------------------------------------------
25551 subtests of which 0 failed
92 test cases of which 0 failed
0 test cases were skipped
TEE test application done!

```

**Comment by Emantor** [comment]
`xtest -l 15`on `imx-mx6qsabrelite` with `CFG_TEE_CORE_EMBED_INTERNAL_TESTS=y`:
```
45474 subtests of which 0 failed
91 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```
`Tested-by: Rouven Czerwinski <r.czerwinski@pengutronix.de> (imx-mx6qsabrelite)`

**Comment by Emantor** [comment]
`xtest -l 15`on `imx-ccimx6ulsbcpro` with `CFG_TEE_CORE_EMBED_INTERNAL_TESTS=y`:
```
45474 subtests of which 0 failed
91 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```
`Tested-by: Rouven Czerwinski <r.czerwinski@pengutronix.de> (imx-ccimx6ulsbcpro)`

**Comment by jforissier** [comment]
3.12.0-rc1 with #4312 and #4317:

`Tested-by: Jerome Forissier <jerome@forissier.org> (QEMUv8)`

**Comment by jbech-linaro** [comment]
```
45481 subtests of which 0 failed
91 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

`Tested-by: Joakim Bech <joakim.bech@linaro.org>` (RPi3B)

**Comment by jforissier** [comment]
3.12.0-rc1 with #4312 and #4317 on QEMU:

```
+++++ []
Status: PASS (578 test cases)
+++++ [CFG_WITH_PAGER=y]
Status: PASS (553 test cases)
+++++ [CFG_RPMB_FS=y CFG_RPMB_WRITE_KEY=y]
Status: PASS (611 test cases)
+++++ [CFG_REE_FS=n CFG_RPMB_FS=y CFG_RPMB_WRITE_KEY=y]
Status: PASS (578 test cases)
+++++ [CFG_CORE_DYN_SHM=n]
Status: PASS (578 test cases)
+++++ [CFG_WITH_PAGER=y CFG_RPMB_FS=y CFG_RPMB_WRITE_KEY=y]
Status: PASS (586 test cases)
+++++ [CFG_ULIBS_SHARED=y]
Status: PASS (578 test cases)
+++++ [CFG_ULIBS_SHARED=y CFG_WITH_PAGER=y]
Status: PASS (553 test cases)
+++++ [CFG_FTRACE_SUPPORT=y CFLAGS_ta_arm32=-pg CFLAGS_ta_arm64=-pg]
Status: PASS (578 test cases)
+++++ [COMPILER=clang]
Status: PASS (578 test cases)
```
`Tested-by: Jerome Forissier <jerome@forissier.org> (QEMU)`

**Comment by jbech-linaro** [comment]
```
# xtest
...
25546 subtests of which 0 failed
91 test cases of which 0 failed
0 test cases were skipped
```

`Tested-by: Joakim Bech <joakim.bech@linaro.org>` (RPi3B-NFS)

**Comment by etienne-lms** [comment]
```
# xtest -l 15
...
44833 subtests of which 0 failed
91 test cases of which 0 failed
0 test cases were skipped
```

`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1)`

**Comment by lorc** [comment]
`Tested-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com> (Rcar H3)`
 `Tested-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com> (Rcar H3/virtualization)`

> +-----------------------------------------------------
> 25506 subtests of which 2 failed
> 91 test cases of which 2 failed
> 0 test cases were skipped
> TEE test application done!

Two tests failed because my kernel does not support user and group login

**Comment by ricardosalveti** [comment]
```
I/TC: OP-TEE version: 3.12.0-rc1-dev (gcc version 10.2.0 (GCC)) #1 Thu 01 Jan 1970 12:00:00 AM UTC aarch64

# xtest
+-----------------------------------------------------
25509 subtests of which 0 failed
91 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

`Tested-by: Ricardo Salveti <ricardo@foundries.io> (ZynqMP)
`

**Comment by jforissier** [comment]
My testing on HiKey found two problematic configurations, see #4323 and #4324. All the other tests were successful.

**Comment by lorc** [comment]
I managed to boot kernel 5.10 on my board and now all tests are passing.
 
But looks like I have found another issue: second run of `xtest` fails in test 1008 with `TEEC_ERROR_OUT_OF_MEMORY`.
The more I run `xtest` the more test fail with the same error. So it is looks like memory leak.

I already tried with `CFG_VIRTUALIZATION` off. This excluded the potential memleak in the hypervisor. 

May I ask other maintainers to run `xtest` 10-15 times without rebooting?

**Comment by jenswi-linaro** [comment]
> I managed to boot kernel 5.10 on my board and now all tests are passing.
> 
> But looks like I have found another issue: second run of `xtest` fails in test 1008 with `TEEC_ERROR_OUT_OF_MEMORY`.
> The more I run `xtest` the more test fail with the same error. So it is looks like memory leak.
> 
> I already tried with `CFG_VIRTUALIZATION` off. This excluded the potential memleak in the hypervisor.
> 
> May I ask other maintainers to run `xtest` 10-15 times without rebooting?

I can see something like this on QEMU v7 too. It looks like we may be leaking sessions. I'll try to find the cause.

**Comment by lorc** [comment]
@jenswi-linaro, I think I nailed it in #4326. I'll take a deeper look in this, but I am not very familiar with storage code, so it can take some time.

**Comment by jbech-linaro** [comment]
I see a couple issues being investigated and fixes created and tested. We can move the release date to the beginning of next week if needed. Thoughts?

**Comment by jenswi-linaro** [comment]
Yes, it looks like we need a bit more time.

**Comment by jforissier** [comment]
I agree, we're not far I think but today is definitely too short.

**Comment by jbech-linaro** [comment]
Ok, so I will hold off with finalizing the release and instead doing it tomorrow Friday let's have Wednesday next week (20/1) as the new release day/date.

**Comment by b49020** [comment]
`Tested-by: Sumit Garg <sumit.garg@linaro.org> (Developerbox)`

```
$ xtest -l 15
+-----------------------------------------------------
45444 subtests of which 0 failed
91 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome@forissier.org> (HiKey, GP) # issue 4324`

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome@forissier.org> (HiKey960, GP) # issue 4324`

**Comment by vchong** [comment]
I'm testing on HiKey960 AOSP P with a 4.14 kernel [1] and getting below error for xtest 1014. Is 4.14 too old to work with the current xtest?

```
heap_data[0].type = 4
heap_data[1].type = 4
heap_data[2].type = 1
heap_data[3].type = 0
Error: target heap type 5 not found
query_data.cnt=4
```
[1] https://github.com/vchong/linux/tree/android-hikey-linaro-4.14_optee

**Comment by vchong** [comment]
> I'm testing on HiKey960 AOSP P with a 4.14 kernel [1] and getting below error for xtest 1014. Is 4.14 too old to work with the current xtest?
> 
> ```
> heap_data[0].type = 4
> heap_data[1].type = 4
> heap_data[2].type = 1
> heap_data[3].type = 0
> Error: target heap type 5 not found
> query_data.cnt=4
> ```
> 
> [1] https://github.com/vchong/linux/tree/android-hikey-linaro-4.14_optee

Found some issues with the defconfig. Will try again and update.

**Comment by vchong** [comment]
`Tested-by: Victor Chong <victor.chong@linaro.org> (HiKey960 AOSP P)`

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (FVP)`

**Comment by clementfaure** [comment]
Hello,

```Tested-by: Clement Faure <clement.faure@nxp.com> (mx6dlsabreauto)```
```Tested-by: Clement Faure <clement.faure@nxp.com> (mx6dlsabresd)```
```Tested-by: Clement Faure <clement.faure@nxp.com> (mx6qpsabreauto)```
```Tested-by: Clement Faure <clement.faure@nxp.com> (mx6ulevk)```
```Tested-by: Clement Faure <clement.faure@nxp.com> (mx6ullevk)```
```Tested-by: Clement Faure <clement.faure@nxp.com> (mx6ulzevk)```
```Tested-by: Clement Faure <clement.faure@nxp.com> (mx6sllevk)```
```Tested-by: Clement Faure <clement.faure@nxp.com> (mx7dsabresd)```
```Tested-by: Clement Faure <clement.faure@nxp.com> (mx7ulpevk)```
```Tested-by: Clement Faure <clement.faure@nxp.com> (mx8mmevk)```
```Tested-by: Clement Faure <clement.faure@nxp.com> (mx8mnevk)```
```Tested-by: Clement Faure <clement.faure@nxp.com> (mx8mqevk)```
```Tested-by: Clement Faure <clement.faure@nxp.com> (mx8qmmek)```
```Tested-by: Clement Faure <clement.faure@nxp.com> (mx8qxpmek)```

**Comment by jbech-linaro** [comment]
Last bid for people helping out with the release. If you have anything left pending that is needed for this particular release, then please ping me here in this thread. If I hear nothing, then I'll finalize the release today (EOD).

**Comment by jbech-linaro** [comment]
Thanks everyone for the contributions, I'm wrapping up this now by merging and closing this issue, tags will be created in a few minutes from now. Thanks!

**Comment by etienne-lms** [comment]
Thanks @jbech-linaro, @jforissier and all for the release.

**Pull request merged**
