### PR TITLE
plat-stm32mp1: fixes for 3.20.0 related to SCMI

### PR DESCRIPTION
**Pull request by etienne-lms**

### CODE REVIEW

**Comment by jforissier** [comment]
Didi you forget something in the commit description for "plat-stm32mp1: don't register SYSRAM twice when scmi-msg are enabled"?

```
when scmi-msg driver are enable () and SCP firmware SCMI library
```

Other than that:

`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by GseoC** [comment]
In `plat-stm32mp1: don't register SYSRAM twice when scmi-msg are enabled` commit message : 
`was moved in main.c but no removed` => `was moved in main.c but not removed`

IMO (same commit message): `the below debug trace` => `the debug trace below`

Reviewed-by: Gatien Chevallier <gatien.chevallier@foss.st.com>

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
> Didi you forget something in the commit description...

Indeed, I forgot to add the config switch names.

**Comment by etienne-lms** [comment]
Commit message fixed for "plat-stm32mp1: don't register SYSRAM twice when scmi-msg are enabled".
Tags applied.
Thanks for the review.

**Pull request merged**
