### PR TITLE
core: configure for a single user mode architecture

### PR DESCRIPTION
**Pull request by etienne-lms**
This change introduces `CFG_USER_TA_TARGET` to allow a configuration to select a unique user TA execution architecture even if the platform supports several (Aarch32/Aarch64).

`CFG_USER_TA_TARGET` shall be set to either `ta_arm32` or `ta_arm64`.

This feature can be used in build environments that do not support several cross compilation toolchains when building a single target. Buildroot (at least up to 2018.11) is such of an environment. The environment will likely use an Aarch64 toolchain for the TEE/REE which toolchain may not be able to compile Aarch32 targets and build to fail with a error message like:
```shell
    CC      out/ta_arm32-lib/libmbedtls/mbedtls/library/aes.o
  aarch64-linux-gnu-gcc: error: unrecognized command line option ‘-mthumb’
```

This change adds a bit of documentation on this configuration, in file **mk/config.mk** and adds few info about the related `CFG_USER_TA_TARGET_<ta-name>`.

### CODE REVIEW

**Comment by jforissier** [comment]
You can already do: `make ... ta-targets=ta_arm32` or `make ... ta-targets=ta_arm64`. What's wrong with that?

**Comment by etienne-lms** [comment]
Ok, works nice `make (...) ta-targets=ta_arm{32|64}` works nice.
Note that using `ta-target=ta_arm{32|64}` (no 's' after ta-target) build ok but with few warnings.
Wouldn't it be easier to rely on `CFG_xxx` directive for that?

**Comment by etienne-lms** [comment]
This `CFG_USER_TA_TARGETS` would be fine.
* As it is a list, value supporting `n` would mislead one to believe it could set to `y`.
* If undefined, I think the default behavior  should build for all targets supported by the platform.
* If defined to an empty string: should it not build user binaries or should it build all platform's supported.

`CFG_WITH_USER_TA` is about user TA support in core.
`CFG_USER_TA_TARGETS` would cover builds for targets architectures TAs: covers intree TAs, early TAs? and devkit (libs, devkit export).

**Comment by jforissier** [comment]
> As it is a list, value supporting `n` would mislead one to believe it could set to `y`.

Agreed. Let's not associate a special meaning to `n`.

> If undefined, I think the default behavior should build for all targets supported by the platform.

Agreed (certainly more convenient). We can always add support for a special value (`none`) later if needed.

> If defined to an empty string: should it not build user binaries or should it build all platform's supported ?

I'm not favorable to making a difference between "undefined" and "defined, but empty" for `CFG_` variables. It would make things needlessly complex. For instance, there are several ways you can set an empty value to override the default value set in a Makefile with `?=`. Consider we have `CFG_FOO=foo` in `mk/config.mk` for instance, then you can do `CFG_FOO= make` or `make CFG_FOO=` to clear the value. If it is an undefined variable that you want, you cannot do it.

Therefore, I'd rather we build all the supported user binaries if `CFG_USER_TA_TARGETS` is *undefined or empty*.

**Comment by etienne-lms** [comment]
@jforissier, I have pushed a proposal for `CFG_USER_TA_TARGETS`.
Maybe i did not do it the best way :), feel free to tell if so.

Zut! IBART complains... Strange. Fails on **bget.c**.

**Comment by etienne-lms** [comment]
Well, indeed this version is bugged...

**Comment by etienne-lms** [comment]
ok, I'll close this P-R.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/2703

**Pull request closed without merging**
