### PR TITLE
core: pta: drop SDP pTA

### PR DESCRIPTION
**Pull request by igoropaniuk**
```
Drop SDP pTA as it is not used anywhere and looks like isn't
maintained. When is CFG_SDP_PTA=y the build fails with
compile errors:

error: implicit declaration of function ‘tee_ta_get_calling_session’;
did you mean ‘ts_get_calling_session’?
[-Werror=implicit-function-declaration]
...
error: ‘struct tee_ta_session’ has no member named ‘ctx’

Signed-off-by: Igor Opaniuk <igor.opaniuk@gmail.com>
```

### CODE REVIEW

**Review by etienne-lms — COMMENTED** [review]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by igoropaniuk** [comment]
@etienne-lms R-b tag added, thanks

**Comment by igoropaniuk** [comment]
rebased on top of latest master

**Comment by jforissier** [comment]
Thanks Igor, could you please s/pTA/PTA/ in the commit subject and description? See commit bb80916b8c85 ("core: use PTA as acronym for pseudo TA").

**Comment by igoropaniuk** [comment]
@jforissier done and rebased, thanks!

**Pull request merged**
