### PR TITLE
scripts/pem_to_pub.py: use Cryptodome module instead of Crypto

### PR DESCRIPTION
**Pull request by etienne-lms**
Upgrade scripts/pem_to_pub.py to use module Cryptodome instead of
module Crypto for consistency with the other helper Python scripts
of OP-TEE OS package.

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
tag applied

**Comment by jforissier** [comment]
@etienne-lms 

> WARNING: Missing Signed-off-by: line by nominal patch author 'Etienne Carriere <etienne.carriere@st.com>'

**Comment by etienne-lms** [comment]
sorry, i'll fix that.

**Comment by etienne-lms** [comment]
fixed

**Pull request merged**
