### PR TITLE
batch typo fixes in documentation/comments

### PR DESCRIPTION
**Pull request by wamserma**
a input -> an input
Optinally -> Optionally
the the -> if the, the, by the, to the (guessed from context)

(typos inherited from upstream are kept)

Signed-off-by: Markus S. Wamser <github-dev@mail2013.wamser.eu>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Please split up in at least two separate patches, divided as:
- ta/pkcs11
- core

With a short and tidy description of what's done.

**Comment by wamserma** [comment]
@jenswi-linaro I split this up in a set of commits and detailed the changes in each commit message.

I just saw a common typo (duplicate "the") and then grepped across the source for a few more typo patterns. Matches in inherited libs (such as libtomcrypt) were ignored. Maybe we can still sneak this into 3.9.

**Comment by etienne-lms** [comment]
Despite would prefer header lines below:
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

```patch
-simple typo fixes in comments in core/arch tree …
+core: simple typo fixes in comments in core/arch tree
 
-simple typo fix in comments in core/drivers tree
+core: simple typo fix in comments in core/drivers tree
 
-simple typo fixes in comments in core/include tree
+core: simple typo fixes in comments in core/include tree
 
-simple typo fixes in comments in ta/pkcs11 tree
+ta: simple typo fixes in comments in ta/pkcs11 tree
```

**Comment by jenswi-linaro** [comment]
Thanks @wamserma, I think we should manage that.

With the updates requested by @etienne-lms, please apply:
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by wamserma** [comment]
@etienne-lms @jenswi-linaro Done.

**Pull request merged**
