### PR TITLE
plat-mediatek: generate new TA dev kit for ARM64

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>
Tested-by: Victor Chong <victor.chong@linaro.org> (mediatek build only)

### CODE REVIEW

**Comment by vchong** [comment]
All the other v8 boards were done separately.
plat-vexpress (fvp and juno) in https://github.com/OP-TEE/optee_os/pull/566.
plat-hikey in https://github.com/OP-TEE/optee_os/pull/575.
The only v8 board left is plat-mediatek here.
There weren't any PRs for any of the v7 boards, so not sure if I should include them here also?

**Comment by jenswi-linaro** [comment]
@pascal-brand-st-dev I agree. It would be preferable to not have any `user_ta`, only `ta_arm64` and `ta_arm32`.

**Comment by vchong** [comment]
Ok. Would you guys prefer to include the changes here or in another PR for the rest of the platforms?

**Comment by pascal-brand-st-dev** [comment]
Either way is fine with me.

    Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by vchong** [comment]
In that case, let's do it in another PR. Can I rebase and tag, or do I need another RB?

**Comment by vchong** [comment]
Created https://github.com/OP-TEE/optee_os/pull/583.

**Comment by pascal-brand-st** [comment]
Manually merged

**Pull request closed without merging**
