### PR TITLE
Update CHANGELOG for 3.6.0

### PR DESCRIPTION
**Pull request by jforissier**
Update CHANGELOG for 3.6.0.

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
OP-TEE 3.6.0 is planned for July 4th. I will create a -rc1 tag on Monday 1st. As usual, let's use this PR to collect Tested-by:s and discuss any issue.

**Comment by jenswi-linaro** [comment]
I will not be able to test this tag on Juno, however I tested the ldelf and cache optimization pull requests on Juno in the four common configurations (with and without pager, Aarch32 and Aarch64) last Friday as I suspected I wouldn't be able to do it later.

If you think it's close enough the please add:
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)`

**Comment by jforissier** [comment]
@jenswi-linaro thanks. What you have tested is certainly very close to 3.6.0-rc1 so I will add your tag. Enjoy your vacation ;-)

**Comment by nodeax** [comment]
Trying to build optee_os I get the below error:
Traceback (most recent call last):
  File "scripts/gen_ldelf_hex.py", line 12, in <module>
    from elftools.elf.elffile import ELFFile
ImportError: No module named elftools.elf.elffile
mk/subdir.mk:158: recipe for target 'out/arm-plat-sam/core/ldelf_hex.c' failed

Trying to install ELFFile on Ubuntu 16.04, get the below error (both with Python 2.7 and 3.5):
      File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 403: SSL is required

Manually downloaded ELFFile package:(https://files.pythonhosted.org/packages/aa/e4/331249716119b80564509aa759f0c4f1856fc074d63beb325e812b829b88/elffile-0.005.tar.gz) and modifying distribute_setup.py:
DEFAULT_URL = "http://pypi.python.org/packages/source/d/distribute/"
to
DEFAULT_URL = "https://pypi.python.org/packages/source/d/distribute/"

Now I get the error:
pip3 install ~/Downloads/elffile-0.005 --user
      File "/tmp/pip-req-build-wj69z9qi/distribute_setup.py", line 467, in _extractall
        self.chown(tarinfo, dirpath)
    TypeError: chown() missing 1 required positional argument: 'numeric_owner'

Seems like I am going down a rabbit hole and elffile package has not been updated since 2011. Am I missing something obvious here?

**Comment by jforissier** [comment]
Hi @nodeax,

What is your distribution? Have you tried `apt get python-pyelftools`?

**Comment by nodeax** [comment]
> What is your distribution? Have you tried `apt install python-pyelftools`?

Installing python-pyelftools resolved the issue, using Ubuntu 16.04. Thanks!

**Comment by b49020** [comment]
`Tested-by: Sumit Garg <sumit.garg@linaro.org> (Developerbox)`

```
$ xtest -l 15
+-----------------------------------------------------
44067 subtests of which 0 failed
95 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey960, GP)`

```
root@HiKey960:/ xtest -t regression+gp
[...]
+-----------------------------------------------------
28246 subtests of which 0 failed
741 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by Emantor** [comment]
3.6.0-rc1:
`Tested-by: Rouven Czerwinski <r.czerwinski@pengutronix.de> (mx6qsabresd)`
```
root@DistroKit:~ optee-xtest -l 15
[…]
+-----------------------------------------------------
44067 subtests of which 0 failed
95 test cases of which 0 failed
0 test cases were skipped
TEE test application done!                                                                                                                                                                                                                                                                                                   
```

**Comment by etienne-lms** [comment]
3.6.0-rc1:
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (b2120, b2260, GP)`

**Comment by lorc** [comment]
For 3.6.0-r1 with #3112 

```
Tested-by: Volodymyr Babchuk <vlad.babchuk@gmail.com> (RCAR H3)
Tested-by: Volodymyr Babchuk <vlad.babchuk@gmail.com> (RCAR H3/virtualization)
```

**Comment by Emantor** [comment]
3.6.0-rc1:
`Tested-by Rouven Czerwinski <r.czerwinski@pengutronix.de>` (ccimx6ulsbcpro)
```
root@DistroKit:~ optee-xtest -l 15
+-----------------------------------------------------
44067 subtests of which 0 failed
95 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

Though I see a lot of during RFC 6070 test case 4.
```
[ 1705.971228] rcu: INFO: rcu_sched detected stalls on CPUs/tasks:                                                                                                                                                                             
[ 1705.977195] rcu:     (detected by 0, t=2102 jiffies, g=51977, q=3)                                                                                                                                                                          
[ 1705.983152] rcu: All QSes seen, last rcu_sched kthread activity 2102 (140596-138494), jiffies_till_next_fqs=1, root ->qsmask 0x0                                                                                                            
[ 1705.994729] optee-xtest     R  running task        0   169    157 0x00000002                                                                                                                                                                
[ 1706.001806] Backtrace:                                                                                                                                                                                                                      
[ 1706.004302] [<c010dea0>] (dump_backtrace) from [<c010e0f8>] (show_stack+0x18/0x1c)                                                                                                                                                          
[ 1706.011900]  r7:c0b14700 r6:c0a63440 r5:c0b08c08 r4:c4432840                                                                                                                                                                                
[ 1706.017598] [<c010e0e0>] (show_stack) from [<c0151b48>] (sched_show_task.part.1+0xc0/0xf8)                                                                                                                                                  
[ 1706.025898] [<c0151a88>] (sched_show_task.part.1) from [<c014c210>] (sched_show_task+0x1c/0x20)                                                                                                                                             
[ 1706.034613]  r5:c4ca6000 r4:cdfbe440                                                                                                                                                                                                        
[ 1706.038221] [<c014c1f4>] (sched_show_task) from [<c0191d10>] (rcu_sched_clock_irq+0x7d0/0x854)                                                                                                                                              
[ 1706.046865] [<c0191540>] (rcu_sched_clock_irq) from [<c019a070>] (update_process_times+0x38/0x68)                                                                                                                                           
[ 1706.055765]  r10:cdfba690 r9:c01ae0c4 r8:cdfba540 r7:0000018d r6:00000000 r5:c4432840                                                                                                                                                       
[ 1706.063607]  r4:ffffe000                                                                                                                                                                                                                    
[ 1706.066174] [<c019a038>] (update_process_times) from [<c01addc0>] (tick_sched_handle+0x5c/0x60)                                                                                                                                             
[ 1706.074896]  r7:0000018d r6:33240b68 r5:c4ca7c90 r4:cdfba890                                                                                                                                                                                
[ 1706.080588] [<c01add64>] (tick_sched_handle) from [<c01ae114>] (tick_sched_timer+0x50/0xb0)                                                                                                                                                 
[ 1706.088968] [<c01ae0c4>] (tick_sched_timer) from [<c019ad10>] (__hrtimer_run_queues+0x178/0x3a0)                                                                                                                                            
[ 1706.097775]  r7:cdfba580 r6:00000000 r5:cdfba540 r4:cdfba890                                                                                                                                                                                
[ 1706.103465] [<c019ab98>] (__hrtimer_run_queues) from [<c019bce4>] (hrtimer_interrupt+0x128/0x2b8)                                                                                                                                           
[ 1706.112366]  r10:cdfba690 r9:cdfba6c0 r8:ffffffff r7:7fffffff r6:00000003 r5:20010193                                                                                                                                                       
[ 1706.120208]  r4:cdfba540                                                                                                                                                                                                                    
[ 1706.122776] [<c019bbbc>] (hrtimer_interrupt) from [<c05e684c>] (mxc_timer_interrupt+0x3c/0x44)                                                                                                                                              
[ 1706.131420]  r10:c0b387b0 r9:c4ca7bc0 r8:c401e000 r7:00000011 r6:00000000 r5:c401bb68                                                                                                                                                       
[ 1706.139261]  r4:c4008640                                                                                                                                                                                                                    
[ 1706.141830] [<c05e6810>] (mxc_timer_interrupt) from [<c017a990>] (__handle_irq_event_percpu+0x4c/0x234)                                                                                                                                     
[ 1706.151244]  r5:c401bb68 r4:c4008700                                                                                                                                                                                                        
[ 1706.154850] [<c017a944>] (__handle_irq_event_percpu) from [<c017aba8>] (handle_irq_event_percpu+0x30/0x88)                                                                                                                                  
[ 1706.164532]  r10:c0b387b0 r9:c4ca7c90 r8:c401e000 r7:00000000 r6:c401bb00 r5:c401bb68                                                                                                                                                       
[ 1706.172373]  r4:c0b08c08                                                                                                                                                                                                                    
[ 1706.174938] [<c017ab78>] (handle_irq_event_percpu) from [<c017ac50>] (handle_irq_event+0x50/0x74)                                                                                                                                           
[ 1706.183830]  r6:00000001 r5:c401bb68 r4:c401bb00                                                                                                                                                                                            
[ 1706.188484] [<c017ac00>] (handle_irq_event) from [<c017f250>] (handle_fasteoi_irq+0xb8/0x178)                                                                                                                                               
[ 1706.197029]  r7:00000000 r6:00000001 r5:c0b0dbcc r4:c401bb00                                                                                                                                                                                
[ 1706.202720] [<c017f198>] (handle_fasteoi_irq) from [<c0179b14>] (generic_handle_irq+0x28/0x3c)                                                                                                                                              
[ 1706.211347]  r5:00000011 r4:c0a62870                                                                                                                                                                                                        
[ 1706.214952] [<c0179aec>] (generic_handle_irq) from [<c017a194>] (__handle_domain_irq+0x58/0xc0)                                                                                                                                             
[ 1706.223683] [<c017a13c>] (__handle_domain_irq) from [<c0440b9c>] (gic_handle_irq+0x60/0xc4)                                                                                                                                                 
[ 1706.232064]  r9:c4ca7c90 r8:c0b09294 r7:ce80a000 r6:000003ff r5:000003eb r4:ce80a00c                                                                                                                                                        
[ 1706.239836] [<c0440b3c>] (gic_handle_irq) from [<c0101aac>] (__irq_svc+0x6c/0x90)                                                                                                                                                           
[ 1706.247335] Exception stack(0xc4ca7c90 to 0xc4ca7cd8)                                                                                                                                                                                       
[ 1706.252411] 7c80:                                     ffff0004 00000000 00000000 00000000                                                                                                                                                   
[ 1706.260615] 7ca0: 00000000 00000000 00000000 00000000 c48fd440 c0b08c08 ffff0000 c4ca7d1c                                                                                                                                                   
[ 1706.268816] 7cc0: c4ca7cf0 c4ca7ce0 c05f7bd8 c0113a68 60010013 ffffffff                                                                                                                                                                     
[ 1706.275459]  r10:ffff0000 r9:c4ca6000 r8:c48fd440 r7:c4ca7cc4 r6:ffffffff r5:60010013                                                                                                                                                       
[ 1706.283300]  r4:c0113a68                                                                                                                                                                                                                    
[ 1706.285869] [<c05f7b98>] (optee_smccc_smc) from [<c05f8380>] (optee_do_call_with_arg+0xb0/0x150)                                                                                                                                            
[ 1706.294668]  r4:c05f7b98                                                                                                                                                                                                                    
[ 1706.297231] [<c05f82d0>] (optee_do_call_with_arg) from [<c05f8834>] (optee_invoke_func+0x100/0x180)                                                                                                                                         
[ 1706.306304]  r10:00000000 r9:00000000 r8:c4983980 r7:c0b08c08 r6:c48fd440 r5:c4ca7e70                                                                                                                                                       
[ 1706.314145]  r4:c4ce9440                                                                                                                                                                                                                    
[ 1706.316709] [<c05f8734>] (optee_invoke_func) from [<c05f655c>] (tee_ioctl+0xfb4/0x11b4)
[ 1706.324740]  r9:00000000 r8:00000098 r7:c48fd440 r6:be8f7158 r5:c4983980 r4:be8f7140
[ 1706.332517] [<c05f55a8>] (tee_ioctl) from [<c0284b3c>] (do_vfs_ioctl+0xa4/0x960)
[ 1706.339941]  r10:c44febd0 r9:c4ca6000 r8:be8f7208 r7:00000003 r6:c4bbee40 r5:be8f7208
[ 1706.347785]  r4:c0b08c08
[ 1706.350350] [<c0284a98>] (do_vfs_ioctl) from [<c0285434>] (ksys_ioctl+0x3c/0x68)
[ 1706.357773]  r10:00000036 r9:c4ca6000 r8:be8f7208 r7:8010a403 r6:00000003 r5:c4bbee40
[ 1706.365615]  r4:c4bbee40
[ 1706.368180] [<c02853f8>] (ksys_ioctl) from [<c0285470>] (sys_ioctl+0x10/0x14)
[ 1706.375342]  r9:c4ca6000 r8:c0101204 r7:00000036 r6:00000000 r5:be8f71d0 r4:b6d58f7c
[ 1706.383117] [<c0285460>] (sys_ioctl) from [<c0101000>] (ret_fast_syscall+0x0/0x54)
[ 1706.390702] Exception stack(0xc4ca7fa8 to 0xc4ca7ff0)
[ 1706.395779] 7fa0:                   b6d58f7c be8f71d0 00000003 8010a403 be8f7208 00000003
[ 1706.403987] 7fc0: b6d58f7c be8f71d0 00000000 00000036 00000000 00000000 004d7d78 0000009f
[ 1706.412184] 7fe0: b6d58fac be8f7134 b6d47a2f b6c44878
[ 1706.417264] rcu: rcu_sched kthread starved for 2102 jiffies! g51977 f0x2 RCU_GP_WAIT_FQS(5) ->state=0x0 ->cpu=0
[ 1706.427361] rcu: RCU grace-period kthread stack dump:
[ 1706.432422] rcu_sched       R  running task        0    10      2 0x00000000
[ 1706.439494] Backtrace:
[ 1706.441978] [<c076a100>] (__schedule) from [<c076a910>] (schedule+0x40/0x94)
[ 1706.449054]  r10:cdfb9440 r9:c0b03d00 r8:c0b08c08 r7:cdfb9440 r6:00000000 r5:c40b9edc
[ 1706.456897]  r4:ffffe000
[ 1706.459461] [<c076a8d0>] (schedule) from [<c076e724>] (schedule_timeout+0x1dc/0x468)
[ 1706.467220]  r5:c40b9edc r4:00021cff
[ 1706.470829] [<c076e548>] (schedule_timeout) from [<c0190128>] (rcu_gp_kthread+0x560/0x1070)
[ 1706.479207]  r10:c0b14700 r9:c0b14898 r8:c0b08cec r7:00000001 r6:c0b14a0c r5:cdfbe440
[ 1706.487048]  r4:00000000
[ 1706.489613] [<c018fbc8>] (rcu_gp_kthread) from [<c01440e0>] (kthread+0x14c/0x160)
[ 1706.497111]  r7:c40b8000
[ 1706.499673] [<c0143f94>] (kthread) from [<c01010e8>] (ret_from_fork+0x14/0x2c)
[ 1706.506910] Exception stack(0xc40b9fb0 to 0xc40b9ff8)
[ 1706.511981] 9fa0:                                     00000000 00000000 00000000 00000000
[ 1706.520186] 9fc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[ 1706.528385] 9fe0: 00000000 00000000 00000000 00000000 00000013 00000000
[ 1706.535025]  r10:00000000 r9:00000000 r8:00000000 r7:00000000 r6:00000000 r5:c0143f94
[ 1706.542867]  r4:c4087340

**Comment by nodeax** [comment]
3.6.0-rc1:
```
Tested-by: Akshay Bhat <akshay.bhat@timesys.com> (Atmel SAM)

# xtest -l 15
+-----------------------------------------------------
44067 subtests of which 0 failed
95 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by jbech-linaro** [comment]
`Tested-by: Joakim Bech <joakim.bech@linaro.org>` (Rpi3b)

**Comment by jforissier** [comment]
3.6.0-rc1:

`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (QEMU, GP)`

```
root@Vexpress:/ xtest
[...]
+-----------------------------------------------------
28568 subtests of which 0 failed
740 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

Found issue https://github.com/OP-TEE/optee_os/pull/3114.

**Comment by jforissier** [comment]
@Emantor 

> Though I see a lots of these kernel events during RFC 6070 test case 4:
> ```
> [ 1705.971228] rcu: INFO: rcu_sched detected stalls on CPUs/tasks:
> ```

This test is expected to take a long time (2 minutes on HiKey620 as documented in the source code), but it should not cause any stall message from the kernel. Is CONFIG_PREEMPT enabled on your platform?

**Comment by Emantor** [comment]
Currently `CONFIG_PREEMPT_VOLUNTARY=y`, I'll do a quick rerun with `CONFIG_PREEMPT=y`.

**Comment by Emantor** [comment]
@jforissier with `CONFIG_PREEMPT_VOLUNTARY` the OP-TEE kernel driver does seem to have no rescheduling point within the RPC code which will continously reenter OP-TEE after servicing the interrupt. I suspect we want a `might_sleep` in the RPC loop of the kernel driver.

**Comment by jforissier** [comment]
@Emantor makes sense, care to send a patch to the LKML?

**Comment by Emantor** [comment]
@jforissier Shortly after testing it locally :-)

**Comment by jforissier** [comment]
3.6.0-rc1:

`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (QEMUv8, GP)`

```
xtest
[...]
+-----------------------------------------------------
28568 subtests of which 0 failed
740 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by Emantor** [comment]
Patch submitted to [LKML](https://lore.kernel.org/patchwork/patch/1096873/).

**Comment by vchong** [comment]
`Tested-by: Victor Chong <victor.chong@linaro.org> (HiKey620 AOSP, HiKey960 AOSP)`

**Comment by grandpaul** [comment]
3.6.0-rc1:
```
Tested-by: Ying-Chun Liu (PaulLiu) <paul.liu@linaro.org> (bpi0)
```

**Comment by igoropaniuk** [comment]
3.6.0-rc1:
```
+-----------------------------------------------------
44071 subtests of which 0 failed
96 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```
`Tested-by: Igor Opaniuk <igor.opaniuk@gmail.com> (Poplar)`

**Comment by etienne-lms** [comment]
3.6.0-rc1 with https://github.com/OP-TEE/optee_os/pull/3106:
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1, GP)`

**Comment by jforissier** [comment]
All,
Thank you for testing and reporting back here. Tag 3.6.0 is now released.

**Pull request merged**
