### PR TITLE
Support compiling optee_ftpm

### PR DESCRIPTION
**Pull request by jenswi-linaro**
This pull request replaces https://github.com/OP-TEE/optee_os/pull/7054 now that we have decided to keep the fTPM TA in a separate git. The commits needed in optee_os from the previous PR are moved into this PR.

### CODE REVIEW

**Review by etienne-lms — COMMENTED** [review]
`Reviewed-by: Etienne Carriere <etienne.carriere@foss.st.com>` for commmits
"tee_api_types.h: default alignment for TEE_BigIntFMMContext",
"libmbedtls: mbedtls_config_uta.h: enable SHA-384 and SHA-512 support",
"mk/subdir.mk: introduce srcs_ext-y and srcs_ext_base-y"
and for the 2 fixup commits.

**Comment by jenswi-linaro** [comment]
Squashed and tags applied.

**Comment by jforissier** [comment]
@jenswi-linaro please fix the conflict and I will merge this. Thanks!

**Comment by jenswi-linaro** [comment]
Rebased to resolve conflict.

**Pull request merged**
