### PR TITLE
New mbed uta

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Repacing https://github.com/OP-TEE/optee_os/pull/2260
Applied tags from that pull request

Note that the squash commit is from https://github.com/jenswi-linaro/optee_os/tree/import/mbedtls-2.6.1
This should be pushed to the main optee_os.git as branch `import/mbedtls-2.6.1`
Please take a look at that branch and comment on the last three commits which. Once this branch is
pushed to the main optee_os.git I'll recreate the squash commits with fresh data.

Further updates to that branch will be via normal pull requests to that branch, followed by a squash merge to master.

Note that I've restructured the source code a little to minimize the needed updates in the imported code.

### CODE REVIEW

**Comment by jforissier** [comment]
This "squashed commit" approach looks reasonable to me.

Regarding the checkpatch errors: I'd rather have the commit log shortened quite a bit and formatted as expected by checkpatch, i.e. something like that:
```
Squash merging branch import/mbedtls-2.6.1

Commit 6c1097d5df8f ("mbedtls: configure mbedtls to reach for config")
Commit cf71c332be21 ("mbedtls: remove default include/mbedtls/config.h")
Commit 7cd016364667 ("Import mbedtls-2.6.1")

Signed-off-by: ...
```

**Comment by jenswi-linaro** [comment]
OK, I'll update the squashed commit once we're happy with  https://github.com/jenswi-linaro/optee_os/tree/import/mbedtls-2.6.1 (top 3 commits).

**Comment by jforissier** [comment]
> OK, I'll update the squashed commit once we're happy with https://github.com/jenswi-linaro/optee_os/tree/import/mbedtls-2.6.1 (top 3 commits).

How do we review this? How about I create branch `import/mbedtls-2.6.1` in `OP-TEE/optee_os` then you create a PR against it?

**Comment by jenswi-linaro** [comment]
> How do we review this? How about I create branch import/mbedtls-2.6.1 in OP-TEE/optee_os then you create a PR against it?

Sounds good

**Comment by jforissier** [comment]
> > How do we review this? How about I create branch import/mbedtls-2.6.1 in OP-TEE/optee_os then you create a PR against it?
>
> Sounds good

Done

**Comment by jenswi-linaro** [comment]
Pull request in https://github.com/OP-TEE/optee_os/pull/2338

**Comment by jenswi-linaro** [comment]
> Just a question, the defines in lib/libmbedtls/include/mbedtls_config_uta.h how did you come up with that list? Is there any thinking behind it or did you just take some default list more or less?

I started from one minimal TLS config file and modified it to suit my needs.

**Comment by jenswi-linaro** [comment]
Squashed and rebased. Updated the "Squashed commit importing mbedtls-2.6.1 source" with @jbech-linaro tag added.

**Comment by jenswi-linaro** [comment]
Updated description in first commit

**Pull request merged**
