### PR TITLE
Gp fixes

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tags applied

**Comment by jforissier** [comment]
Wait... commit https://github.com/OP-TEE/optee_os/pull/816/commits/e450de74386260670deefa0762a63f859fe964a0 breaks xtest 4007.20 (`xtest 4007 -l 15`).

**Comment by jbech-linaro** [comment]
@jforissier can you come back as soon as possible regarding the error you found, I'd like that we merge this asap since I just merged https://github.com/OP-TEE/optee_test/issues/97.

**Comment by jenswi-linaro** [comment]
It looks like some of the DH test cases are incorrect. Max key size specified is smaller than the actual key in many cases, wonder why.

**Comment by jenswi-linaro** [comment]
It seem that the key size is set to the actual key size when `keygen_dhxxx_private_bits` is 0 and the value of `keygen_dhxxx_private_bits` if not 0.

To me this looks like some confusion from the past. Does anyone understand how the values for `keygen_dhxxx_private_bits` are selected? Or are they just found out empirically based on the values of corresponding `_p` and `_g`?

**Comment by jforissier** [comment]
@jenswi-linaro I also think the `key_size` values need to be fixed, and also the check on the size of the generated private key attribute (TEE_ATTR_DH_PRIVATE_VALUE)  should be fixed also to use `key_size` if `_private_bits == 0` and the value of `_private_bits` otherwise. I don't know how these private bit value are selected however.

What do you think of https://github.com/OP-TEE/optee_test/pull/98?

**Comment by jenswi-linaro** [comment]
@jforissier, looks good. I was considering exactly the same solution. :-)

**Pull request merged**
