### PR TITLE
libutils: Fix malloc thread-safe

### PR DESCRIPTION
**Pull request by pascal-brand-st-dev**
Signed-off-by: Pascal Brand <pascal.brand@st.com>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by jforissier** [comment]
The `mdbg_` functions lack proper locking, no?

**Comment by pascal-brand-st-dev** [comment]
As far as I can see, `mdbg_` functions

* are using `raw_` functions, which are correctly locked
* are updating / checking the header / footer, which are private, and so does not need to be guarded.

Did I miss something?

**Comment by jenswi-linaro** [comment]
@pascal-brand-st-dev I agree, it should be OK.

**Comment by jforissier** [comment]
What happens if `mdbg_alloc()` or `mdbg_free()` is called while `mdbg_check()` is running?

**Comment by jenswi-linaro** [comment]
@jforissier yes, you're right.
The locking should not be done in the `raw_` functions, it's the responsibility of the caller.
All the `raw_` functions are static so the fix is straight forward.

**Comment by pascal-brand-st-dev** [comment]
I am abandoning this PR, and will create a new one with lock outside of the `raw_` functions

**Pull request closed without merging**
