### PR TITLE
Removing TPM driver from OP-TEE core

### PR DESCRIPTION
**Pull request by etienne-lms**
Using a TPM driver from OP-TEE prevent non-secure world to leverage TPM software stack and features.
For OP-TEE to use TPM for secure services, OP-TEE core will rather rely on a non-secure remote service on the same principles as the RPMB based secure storage. This change does not address this later case, it only removes code currently not used in OP-TEE core.

Comments are welcome of course if one needs such TPM driver from OP-TEE core and proposes some service integration.

### CODE REVIEW

**Review by jenswi-linaro — COMMENTED** [review]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
tag applied

**Comment by jforissier** [comment]
Is it not a problem to remove things before the alternative is implemented?

**Comment by jenswi-linaro** [comment]
This is as far as I know not used or complete.

**Comment by jenswi-linaro** [comment]
This is as far as I know not used or complete.

**Comment by jforissier** [comment]
> This is as far as I know not used or complete.

OK

**Pull request merged**
