### PR TITLE
Bug fixes for object type with attribute CKA_PRIVATE

### PR DESCRIPTION
**Pull request by ruchi393**

### CODE REVIEW

**Comment by vesajaaskelainen** [comment]
While at it I was wondering what other access control things might be missing:

- PKCS11_CMD_DESTROY_OBJECT

**Comment by vesajaaskelainen** [comment]
For commits:

https://github.com/OP-TEE/optee_os/pull/4286/commits/92573123c1fea666071210cad865c2438085a1d0
https://github.com/OP-TEE/optee_os/pull/4286/commits/ab87c4aef2b693538505ce817496cd58ea59dd5b

`Reviewed-by: Vesa Jääskeläinen <vesa.jaaskelainen@vaisala.com>`

**Comment by ruchi393** [comment]
> While at it I was wondering what other access control things might be missing:
> 
> * PKCS11_CMD_DESTROY_OBJECT

You are right @vesajaaskelainen . It should be worth checking that flow also. I will have a look.

**Comment by ruchi393** [comment]
> Reviewed-by: Vesa Jääskeläinen <vesa.jaaskelainen@vaisala.com>

Thanks @vesajaaskelainen

**Comment by ruchi393** [comment]
Tags applied

**Pull request merged**
