### PR TITLE
Libtomcrypt 1.18.2 develop 20240412

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Update libtomcrypt

Once we're happy with the commits here, the branch should be pushed to a new branch with the name `import/libtomcrypt-1.18.2-develop-20240412`. Then I'll create a squash commit for a new pull request to be merged to the master branch, as described at https://optee.readthedocs.io/en/latest/building/gits/optee_os.html#import-branches

### CODE REVIEW

**Comment by jforissier** [comment]
- For "core: ltc: update for libtomcrypt changes":
  `Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`
- It looks like 8d4ddb4cf is missing
- I ran some of my release test on QEMUv8 and found no issue.

**Comment by jenswi-linaro** [comment]
Cherry-picked "core: ltc: rsa_verify_hash: fix panic on hash mismatch" and tag applied.

**Comment by jenswi-linaro** [comment]
Is it OK to push this to `import/libtomcrypt-1.18.2-develop-20240412` now?

**Comment by jenswi-linaro** [comment]
I'll push this to `import/libtomcrypt-1.18.2-develop-20240412` if there are no further comments.

**Comment by jforissier** [comment]
@jenswi-linaro fine with me

**Comment by jenswi-linaro** [comment]
I've pushed this to `import/libtomcrypt-1.18.2-develop-20240412`.

**Pull request closed without merging**
