### PR TITLE
Update CHANGELOG for 4.4.0

### PR DESCRIPTION
**Pull request by jforissier**
Update CHANGELOG for 4.4.0 and collect Tested-by tags.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Hikey)`
I had to add this for edk2
``` diff
diff --git a/BaseTools/Source/C/LzmaCompress/GNUmakefile b/BaseTools/Source/C/LzmaCompress/GNUmakefile
index 63d7ee0bc343..1eaecfe8f895 100644
--- a/BaseTools/Source/C/LzmaCompress/GNUmakefile
+++ b/BaseTools/Source/C/LzmaCompress/GNUmakefile
@@ -29,4 +29,4 @@ OBJECTS = \
 
 include $(MAKEROOT)/Makefiles/app.makefile
 
-BUILD_CFLAGS += -D_7ZIP_ST
+BUILD_CFLAGS += -D_7ZIP_ST -Wno-dangling-pointer
```
and provide a python2 environment.

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (vexpress-qemu_armv8a)`

```
builder@d51a16fd38f1:~/optee$ repo forall -c 'V=$(git describe --tags --always --dirty); N=$(pwd | sed 's@.*/@@'); printf "%-21s %s\\n" $N $V'
SCP-firmware      	3d1b98e
build             	4.3.0-15-g3d4497c
buildroot         	2024.05
hafnium           	v2.10
linux             	a24278ea7
mbedtls           	mbedtls-2.26.0
optee_client      	4.3.0-4-gd221676
optee_examples    	4.3.0
optee_os          	4.3.0-179-gbaa90692e
optee_rust        	v0.2.0-76-gec3eefd
optee_test        	4.3.0-5-g695231e
qemu              	v8.1.2
trusted-firmware-a	v2.10
u-boot            	v2023.07.02
xen               	RELEASE-4.18.0
```

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (vexpress-qemu_virt)`

```
$ repo forall -c 'V=$(git describe --tags --always --dirty); N=$(pwd | sed 's@.*/@@'); printf "%-21s %s\\n" $N $V'
build             	4.3.0-15-g3d4497c
buildroot         	2024.05
linux             	a24278ea7
optee_client      	4.3.0-4-gd221676
optee_examples    	4.3.0
optee_os          	4.3.0-179-gbaa90692e
optee_test        	4.3.0-5-g695231e
qemu              	v7.0.0
trusted-firmware-a	v2.6
u-boot            	v2024.07
```

**Comment by gyuri-szing** [comment]
> `Tested-by: Imre Kis <imre.kis@arm.com> (fvp-ts)`

Please find
- SPMC change log here: https://github.com/Trusted-Services/trusted-services/wiki/OP-TEE-SPMC-status#important-changes-of-v440-release
- and test logs here: https://github.com/Trusted-Services/trusted-services/wiki/OP-TEE-SPMC-v4.4-test-results

**Comment by jforissier** [comment]
With 4.4.0-rc1:

`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (rockchip-rk3399) (Rockpi4B)`

**Comment by jbech-linaro** [comment]
```
# xtest -l 15
...
332756 subtests of which 0 failed                                                                                                                                                                                                                                                       
107 test cases of which 0 failed      
```
`Tested-by: Joakim Bech <joakim.bech@linaro.org> (RPi 3B v1.2)`

**Comment by jenswi-linaro** [comment]
With https://github.com/OP-TEE/build/pull/786
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (FVP)`

**Comment by etienne-lms** [comment]
For 4.4.0-rc1 with https://github.com/OP-TEE/optee_os/pull/7081:
`Tested-by: Etienne Carriere <etienne.carriere@foss.st.com> (stm32mp1-157C_DK2_SCMI)`
`Tested-by: Etienne Carriere <etienne.carriere@foss.st.com> (stm32mp1-157C_EV1_SCMI)`
`Tested-by: Etienne Carriere <etienne.carriere@foss.st.com> (stm32mp1-157C_DK2)`
`Tested-by: Etienne Carriere <etienne.carriere@foss.st.com> (stm32mp1-157C_EV1)`
`Tested-by: Etienne Carriere <etienne.carriere@foss.st.com> (stm32mp1-157C_ED1)`
`Tested-by: Etienne Carriere <etienne.carriere@foss.st.com> (stm32mp1-135F_DK)`

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (rockchip-rk3399, Rockpi4B)`

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (imx-mx8mqevk)`

**Comment by jforissier** [comment]
> `Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (rockchip-rk3399, Rockpi4B)`

So we both tested that one :wink:

**Comment by jforissier** [comment]
Merged manually.

**Pull request closed without merging**
