### PR TITLE
core: imx: add i.MX6SX Sabreauto support

### PR DESCRIPTION
**Pull request by MrVan**
Add i.MX6SX Sabreauto support.

Signed-off-by: Peng Fan <peng.fan@nxp.com>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by MrVan** [comment]
Tags applied with `.shippable.yml` and `MAINTAINERS.md` updated.

**Comment by jforissier** [comment]
@MrVan could you please rebase onto master? I'm sorry I merged 644dfaa5bedc ("ci: travis: run only code check and QEMU regression") before your patches, resulting in a conflict.

**Comment by MrVan** [comment]
@jforissier rebased

**Comment by jforissier** [comment]
@MrVan thanks!

**Pull request merged**
