### PR TITLE
GP Internal Core API v1.1 : TA configuration properties

### PR DESCRIPTION
**Pull request by cedric-chaumont-st-dev**
add gpd.ta.version and gpd.ta.description

Signed-off-by: Cedric Chaumont <cedric.chaumont@st.com>

Note: For testing use optee_test with dev/gp11_ta_prop branch

### CODE REVIEW

**Comment by cedric-chaumont-st-dev** [comment]
Done. I also add TA_DESCRIPTION. The description is optional and I would prefer to have a default declaration of TA_DESCRIPTION instead of having an "ifdef" within the ta_props{} structure.

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

Do not forget to remove the "dummy" TA_VERSION and descriptions from optee_tests.

**Comment by cedric-chaumont-st-dev** [comment]
optee_test updated. os_test.c modified only.

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by cedric-chaumont-st-dev** [comment]
Squashed

**Pull request merged**
