### PR TITLE
Make sure tee.elf .text section is not modified at runtime

### PR DESCRIPTION
**Pull request by jforissier**
A couple of patches to prevent the `.text` section of the TEE core from being modified on boot. With this, the content in memory remains identical to what is in the file and therefore it is much easier to implement code integrity verification mechanisms.

(Not for 3.11.0 since it is too late for that.)

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Does this really work with Core ASLR?

**Comment by jforissier** [comment]
It does ;-) tested on QEMU qnd QEMUv8.

**Comment by jforissier** [comment]
> It does ;-) tested on QEMU and QEMUv8.

Update: what's working is that the tests pass. I did not check whether or not `.text` gets modified however.

**Comment by jenswi-linaro** [comment]
ARMv7 crashes with paging enabled.

**Comment by jforissier** [comment]
> OK, I'm a bit surprised. I would have expected that `boot_mmu_config` has to be in the `.identity_map` section. Perhaps it has ended up at the same page.

No, it is quite far away actually:
```
$ egrep " (__identity_map|boot_mmu_config)" out/arm/core/tee.dmp
0e100288 l     O .text  00000004 boot_mmu_config_rel
0e1003cc g       .text  00000000 __identity_map_init_end
0e178d30 g     O .bss   00000018 boot_mmu_config
0e10009c g       .text  00000000 __identity_map_init_start
```
What is the purpose of this range?

**Comment by jforissier** [comment]
> ARMv7 crashes with paging enabled.

Huh, not for me (QEMU `make -j10 CFG_WITH_PAGER=y run`). :confused:

**Comment by jenswi-linaro** [comment]
If something goes bad here it will happen during boot. Once all CPUs are online we're safe.
I may miss some other detail. It's needed for memory coherency. When the secondary CPUs boot caches may not be enabled until MMU is enabled. Since the primary CPU modifies `boot_mmu_config` is needs to be cleaned. By having it in write protected memory it can't get dirty again.

**Comment by jenswi-linaro** [comment]
The failure I got was:
```
D/TC:0 0 init_runtime:460 hash pg_idx 7 hash 0x3d774418 page 0x40707000
E/TC:0 0 init_runtime:464 Hash failed for page 7 at 0x40707000: res 0xffff000f
E/TC:0 0 Panic at core/arch/arm/kernel/boot.c:465 <init_runtime>
E/TC:0 0 TEE load address @ 0x3d74d000
E/TC:0 0 Call stack:
E/TC:0 0  0x3d7528f5
E/TC:0 0  0x3d75c7f7
E/TC:0 0  0x3d78dc07
E/TC:0 0  0x3d78ded3
E/TC:0 0  0x3d78df0f
E/TC:0 0  0x3d74d1b0
```

**Comment by jforissier** [comment]
> Since the primary CPU modifies `boot_mmu_config` is needs to be cleaned.

It is modified before the primary CPU MMU is enabled so presumably with caching disabled too. So how could secondary CPUs not "see" the updated value?

> The failure I got was:
> ```
> D/TC:0 0 init_runtime:460 hash pg_idx 7 hash 0x3d774418 page 0x40707000
> E/TC:0 0 init_runtime:464 Hash failed for page 7 at 0x40707000: res 0xffff000f
> E/TC:0 0 Panic at core/arch/arm/kernel/boot.c:465 <init_runtime>
>```

Hmmm... so something was changed inside a hashed page. Do you still have the `tee.dmp` file?

**Comment by jenswi-linaro** [comment]
It's easy to reproduce with `CFG_CC_OPTIMIZE_FOR_SIZE=n`

**Comment by jenswi-linaro** [comment]
> It is modified before the primary CPU MMU is enabled so presumably with caching disabled too. So how could secondary CPUs not "see" the updated value?

Makes sense.

**Comment by jenswi-linaro** [comment]
Moving `boot_mmu_config` out of the `.text` section is only the tip of the iceberg. What are you planning to do with the relocation scattered through the binary?

The reason I chose to put `boot_mmu_config` right after `enable_mmu()` (in both AArch32 and AArch64 assembly) is that when the binary has been relocated it's a bit weird to execute from another address. When the secondary CPUs boot they are in this weird environment too. To make things easier to code I put almost everything needed in  `.identity_map`. The AArch32 assembly was a bit simplified by this also.

Everything in `.identity_map` is always mapped both as identity mapped and also at the new address. It seems that `boot_mmu_config` doesn't have to be part of this though.

**Comment by jforissier** [comment]
> Moving `boot_mmu_config` out of the `.text` section is only the tip of the iceberg. What are you planning to do with the relocation scattered through the binary?

Oh, right. I obviously missed a very big "detail" :cry:
Well, the .text relocations caused by C code are eliminated by `-fpie` but I completely missed the fact that hand-written assembly may produce relocatable literal pool entries (`ldr Rd, =symbol` typically will). That would need to be replaced with more complex relative addressing. I could not find a syntax to have the assembler do that automatically, which I find surprising.

So how to best address the code integrity use case? It seems the only reasonable option is to measure the section(s) to be protected immediately after the end of initialization (once `boot_mmu_config` etc. have been written to and relocations have been applied). After this point (and not sooner), the executable is not supposed to change in memory.

**Comment by jenswi-linaro** [comment]
`boot_init_primary()` is a good place to hook into.

**Comment by jforissier** [comment]
Wth ASLR disabled, I think the only thing that changes `.text` is `boot_mmu_config` so things are probably manageable in this case. But that would be a partial solution.

> `boot_init_primary()` is a good place to hook into.

Right. I'm closing this for now. Thanks for the feedback!

**Comment by jforissier** [comment]
I have written a simple Python script to print informations about relocations, I'm sharing in case it can be helpful: https://github.com/jforissier/misc/blob/master/print_relocations.py

```
$ print_relocations.py out/arm/core/tee.elf | grep text
0xe100098 in .text <__flatmap_unpg_rx_start + 152>
0xe1001dc in .text <cached_mem_start>
0xe10030c in .text <reset_secondary + 128>
0xe100310 in .text <reset_secondary + 132>
0xe100314 in .text <reset_secondary + 136>
0xe100318 in .text <reset_secondary + 140>
0xe10031c in .text <reset_secondary + 144>
0xe100320 in .text <reset_secondary + 148>
0xe100324 in .text <reset_secondary + 152>
0xe100328 in .text <stack_tmp_export>
0xe100394 in .text <vector_fiq_entry + 28>
0xe10039c in .text <vector_fiq_entry + 36>
0xe1003a0 in .text <vector_fiq_entry + 40>
0xe1009bc in .text <icache_inv_user_range + 180>
0xe1009c0 in .text <icache_inv_user_range + 184>
0xe1009c4 in .text <icache_inv_user_range + 188>
0xe1009c8 in .text <icache_inv_user_range + 192>
0xe1009cc in .text <icache_inv_user_range + 196>
0xe1009d0 in .text <icache_inv_user_range + 200>
0xe1009d4 in .text <icache_inv_user_range + 204>
0xe1009d8 in .text <icache_inv_user_range + 208>
0xe1009dc in .text <icache_inv_user_range + 212>
0xe1009e0 in .text <icache_inv_user_range + 216>
0xe100a60 in .text <sm_fiq_entry + 96>
0xe1051e0 in .text <.thread_rpc_return + 12>
0xe108180 in .text <relocate + 68>
0xe10ec3c in .text <tee_svc_do_call + 88>
0xe1100a8 in .text <sm_init + 108>
0xe1100ac in .text <sm_init + 112>
0xe1100b0 in .text <sm_init + 116>
```

**Pull request closed without merging**
