### PR TITLE
core: dt_driver: do not defer probe on skip phandler arguments

### PR DESCRIPTION
**Pull request by etienne-lms**
Prevent `dt_driver_device_from_node_idx_prop()` to request driver probe deferral when needing to skip phandle arguments cells related to providers not yet registered. When skipping these phandle argument cells we don't really need the skipped provider is registered, we can read the `#xxx-cells` property in the provider DT node straight.

For example, consider a driver which DT node defines:
```
  clocks = <&foo_clock 1 2 3>, <&bar_clock 2>;
  clock-names = "foo", "bar";
```
If driver calls `clk_get_by_name(fdt, node, "bar")`, it does not need to wait `&foo_clock` related driver to be already probed, it does not even need the driver to be ever probed.

Reported-by: Gatien Chevallier <gatien.chevallier@foss.st.com>
Link: https://github.com/OP-TEE/optee_os/pull/6491#discussion_r1404181813
Fixes: a22e85b25772 ("core: dt_driver: factorize clk_dt_get_from_provider")

### CODE REVIEW

**Comment by etienne-lms** [comment]
Sorry I forgot to test that with debug trace level.

**Comment by GseoC** [comment]
2 minors comments:

`Acked-by: Gatien Chevallier <gatien.chevallier@foss.st.com>`

**Comment by GseoC** [comment]
> 2 minors comments:
> 
> `Acked-by: Gatien Chevallier <gatien.chevallier@foss.st.com>`

Actually, forget the comments, the format is coherent with what's above

**Comment by etienne-lms** [comment]
Review tags applied and rebased to fix IBART test failure.

**Pull request merged**
