### PR TITLE
plat-vextpress: fvp: map tzcdram

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Map part of DRAM as TZCDRAM in sync with ARM-TF. This is needed to be able to
read pageable part supplied by ARM-TF when pager is enabled.

Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

Alternative for https://github.com/OP-TEE/optee_os/pull/1769 and https://github.com/OP-TEE/build/pull/176

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tag applied

**Comment by jforissier** [comment]
There's a checkpatch warning (I know it's easy to miss it since Travis keeps failing out due to timeouts).

**Comment by jenswi-linaro** [comment]
Thanks, updated commit message

**Pull request merged**
