### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jforissier** [comment]
For "libutils: fix range check in gen_malloc_add_pool()":

`Reviewed-by: Jerome Forissier <jerome@forissier.org>`

**Comment by jforissier** [comment]
For "core: arm32: update thread_smc() for SMCCC v1.2":

> but the normal function calling convention requires
> r4-r7 to be preserved so save a and restore them.

So this is more of a bug fix even with SMCCC < v1.2, isn't it? Why mention v1.2 at all?

**Comment by jenswi-linaro** [comment]
> For "core: arm32: update thread_smc() for SMCCC v1.2":
> 
> > but the normal function calling convention requires
> > r4-r7 to be preserved so save a and restore them.
> 
> So this is more of a bug fix even with SMCCC < v1.2, isn't it? Why mention v1.2 at all?

No, it's with the v1.2 calling convention that r3-r7 could be used to return values. But even then only for specific functions, notably the FF-A family of functions.

**Comment by jforissier** [comment]
I think I got it, it's the `smc #0` that would potentially (when SMCCC v1.2 is used) return a value in r4-r7 and thus change them which the caller of `thread_smc()` wouldn't expect so you're preserving them always.
Why push/pop r3-r7 and not r4-r7 though?

**Comment by jenswi-linaro** [comment]
I looks like you answered your own question there. :-) Let me know if anything is unclear. ;-)

**Comment by jenswi-linaro** [comment]
Updated the commit "core: arm32: update thread_smc() for SMCCC v1.2" with r4-r7 instead.

**Comment by jforissier** [comment]
And what about r8, (r9), r10 and r11? Don't they need preserving, too?

**Comment by jenswi-linaro** [comment]
> And what about r8, (r9), r10 and r11? Don't they need preserving, too?

No, they are required to be preserved together with `lr`.

**Comment by jforissier** [comment]
For "core: arm32: update thread_smc() for SMCCC v1.2":

`Reviewed-by: Jerome Forissier <jerome@forissier.org>`

(please fix typo in commit description: "so save ~~a~~ and restore")

**Comment by jenswi-linaro** [comment]
Tag applied. Typo fixed.

**Pull request merged**
