### PR TITLE
plat-nuvoton: update HUK reading

### PR DESCRIPTION
**Pull request by rutigl**
Reading HUK from UUID stored in two scratchpad registers

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Please rebase to get rid of the conflict and the merge commit. We don't do merge commits in pull requests.

**Comment by rutigl** [comment]
> rebase done

**Comment by jenswi-linaro** [comment]
Please fix the checkpatch errors.
"plat-nuvoton: added HUK reading" contains conflict markers that are then removed in "plat-nuvoton: update HUK reading".
Before force pushing an update fixing this, please take a look at the diffs using gitk or a similar tool, it helps a bit when trying to cleanup  the history.

**Comment by rutigl** [comment]
In Nuvoton GitHub checkpatch succeded,  all the files are fixed, what should I run to update it in PR?

**Comment by jenswi-linaro** [comment]
When you need to rewrite history the normal command sequence is:
``` bash
# may be needed if your branch is a bit old.
git fetch github
# fix up the commits as needed
git rebase -i github/master
# check that history and diffs looks OK
gitk --all&
# sync your changes to your github repository
git push -f mygithubrepo mybrach
```
You may need to adjust the remotes `github` and `mygithubrepo` and the name of the brach `mybranch` to what you're using. Note that what's in `mybranch` when you force push it, is exactly what we'll see, so inspect it carefully using gitk or equivalent. It's impossible for us to review your patches if you can't get this right.

**Comment by jenswi-linaro** [comment]
What do you mean by "Nuvoton GitHub"? I presume not https://github.com/Nuvoton-Israel/optee_os/tree/npcm_4_0_0 since that's what we're seeing here.

**Comment by rutigl** [comment]
I really mean https://github.com/Nuvoton-Israel/optee_os/tree/npcm_4_0_0 from where I did PR, and history shows now only one commit for PR without any garbage.

**Comment by jenswi-linaro** [comment]
No, I see three commits on top of our master branch, or as github puts it `This branch is 3 commits ahead of OP-TEE:master.`

**Comment by jenswi-linaro** [comment]
No, those two commits are not part of the upstream OP-TEE, that's why they are showing up here.

**Review by jenswi-linaro — COMMENTED** [review]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by rutigl** [comment]
Done, thank you for review

**Pull request merged**
