### PR TITLE
.fpu neon rather than -mfpu=neon

### PR DESCRIPTION
**Pull request by jforissier**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
I though we needed to change more .S files but obviously not.
It would be nice to have this tested in AArch32 with CE enabled and possibly the pager too, just to make sure that we didn't miss anything.

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (QEMU CFG_WITH_VFP=y)`
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey960 AArch32)`
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey960 AArch32 pager)`

**Comment by jforissier** [comment]
I'll fix the typo in the commit log of "Remove useless .section directive" when applying tags.

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Pull request merged**
