### PR TITLE
GP11 : TEE_GetOperationInfoMultiple

### PR DESCRIPTION
**Pull request by cedric-chaumont-st-dev**
Signed-off-by: Cedric Chaumont <cedric.chaumont@st.com>

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
Missing tests

**Comment by cedric-chaumont-st-dev** [comment]
Rebased. Note : test use optee_test branch dev/gp11_op_info_mult

**Comment by cedric-chaumont-st-dev** [comment]
Note Test use optee_test PR #10

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by cedric-chaumont-st-dev** [comment]
Update.

**Comment by pascal-brand-st-dev** [comment]
`Reviewed-by: Pascal Brand <pascal.brand@linaro.org>`

**Comment by cedric-chaumont-st-dev** [comment]
Rebased. Squashed. Tested (STM, ARM Juno).
29320 subtests of which 0 failed
687 test cases of which 0 failed
0 test case was skipped
TEE test application done!

**Comment by cedric-chaumont-st-dev** [comment]
Tested (STM, ARM Juno).
29320 subtests of which 0 failed
687 test cases of which 0 failed
0 test case was skipped
TEE test application done!

**Comment by cedric-chaumont-st-dev** [comment]
The variable operationState usage will be updated in the next PR.

**Comment by pascal-brand-st-dev** [comment]
Then remove it.
Next PR will not be merged before 2 weeks.

**Comment by cedric-chaumont-st-dev** [comment]
TEE_GetOperationInfoMultiple currently use it. I meant the "operationState handling". I would prefer to keep it.

**Comment by pascal-brand-st-dev** [comment]
Got it. I will merge.

**Comment by cedric-chaumont-st-dev** [comment]
Thank U

**Pull request merged**
