### PR TITLE
FVP fix

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by imre-kis-arm** [comment]
`Tested-by: Imre Kis <imre.kis@arm.com> (fvp-ts)`

**Comment by jenswi-linaro** [comment]
Tag applied

**Review by etienne-lms — COMMENTED** [review]
`Reviewed-by: Etienne Carriere <etienne.carriere@foss.st.com>` for commit
"core: arm: ffa: optionally use CFG_CORE_ASYNC_NOTIF_GIC_INTID".

`Acked-by: Etienne Carriere <etienne.carriere@foss.st.com>` for commits
"plat-vexpress: fvp: configure GIC redistributor base address" and
"plat-vexpress: configure CFG_CORE_ASYNC_NOTIF_GIC_INTID"
with comments on commit message: are the 2 `Fixes:` tags accurate?
1st commit seems not to fix referred patch but rather enable GIC redistributor on fvp as stated in the commit log.
2nd commit seems to rather fix commit 462028ede02d.

**Comment by jenswi-linaro** [comment]
Tags applied. Replace the fixes tags with:
```
Fixes: 462028ede02d ("qemu_armv8a: add GIC v3 redistributor base address")
```

**Comment by jforissier** [comment]
The IBART failure can be ignored (will go away on rebase).

**Pull request merged**
