### PR TITLE
core: Fix flags and tag check_retrieve_request()

### PR DESCRIPTION
**Pull request by jellesels-arm**
Inside check_retrieve_request() the flags and tag where swapped.
Store them in the correct variable.

Signed-off-by: Jelle Sels <jelle.sels@arm.com>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
It looks like we've merged untested code.
Please add a fixes tag for the original commit.
With that:
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jellesels-arm** [comment]
> It looks like we've merged untested code. Please add a fixes tag for the original commit. With that: `Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`
Added the fixes tag.
I will have a look why this was not catches by the tests, cause I ran the my tests. I assume that in my original tests the value of the flags and tag was the same.

**Comment by jenswi-linaro** [comment]
Please make the tag
`Fixes: de66193d9849 ("core: FF-A: ADD FFA_MEM_RETRIEVE for SPs")`

**Comment by jellesels-arm** [comment]
> Please make the tag `Fixes: de66193d9849 ("core: FF-A: ADD FFA_MEM_RETRIEVE for SPs")`

Done

**Comment by jforissier** [comment]
@jellesels-arm small nits for future commits: no need for a blank line between `Fixes:` and other tags (`Signed-off-by:`, etc.) and also it would be good to identify the affected "subsystem" more precisely in the subject line, for example by adding `ff-a:` or `spmc:` after `core:`.

**Pull request merged**
