### PR TITLE
Pl310

### PR DESCRIPTION
**Pull request by pascal-brand-st-dev**

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
Review comments taken into account

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by jforissier** [comment]
I have posted two comments in outdated commit https://github.com/pascal-brand-st-dev/optee_os/commit/055196841e6c761de41001717317a5f02f2721d9.
Anyways:
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by pascal-brand-st-dev** [comment]
Thanks Jérôme.
I'll address your comments in a further patch.

**Pull request merged**
