### PR TITLE
Release note of 0.3.0 and script updates

### PR DESCRIPTION
**Pull request by pascal-brand-st-dev**
Signed-off-by: Pascal Brand <pascal.brand@st.com>

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
Missing Stable Commit of optee_os on Juno script

**Comment by jenswi-linaro** [comment]
Since we have a fix for Juno, please wait for that to be merged. I can provoke pager faults on FVP too, which is fixed with the "fiq fix" patch.

**Comment by pascal-brand-st-dev** [comment]
Sure, I'll wait for everything. No special urge.

Also, the change log shows hikey was tested, but this is not true yet.

**Comment by jforissier** [comment]
Tested on HiKey at commit https://github.com/jenswi-linaro/optee_os/commit/a9fccca0a1f818c1b0b001c55d2ce2042b4889a1 with defaut configuration, and also with `CFG_WITH_PAGER=y`. I used "extended xtest" (bb7cd04):
```
+-----------------------------------------------------
28693 subtests of which 0 failed
685 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```
For HiKey 64-bit however, there are some failures with extended xtest (namely: tests 7501, 7502, 7529-7532, 7567, 7568, 7572, 7584, 7595, 7640, 7645, 7646, 7661-7669, 7671). Standard xtest is OK.

**Comment by m943040028** [comment]
Tested on MediaTek board, need to change xtest stable commit back to `origin/james_mt8173`, or merge it to master

```
+-----------------------------------------------------
24493 subtests of which 0 failed
44 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```

`Tested-by: SY Chiu <sy.chiu@linaro.org> (MT8173 EVB)`

**Comment by pascal-brand-st-dev** [comment]
optee_test and optee_os sha1 update

@jforissier Do HiKey 64bits failures prevent tag 0.3.0?

* If yes, I'll wait for a fix
* if not, I'll update the CHANGE log file

**Comment by jforissier** [comment]
@pascal-brand-st-dev I did not investigate further.
In any case, the extended xtest had never been run on HiKey previously so it can't be considered as a regression. I would suggest we release 0.3.0 as-is, saying that only standard xtest pass on HiKey and not mentioning extended xtest. Indeed, it is very well possible that I mixed things up when building extended xtests (like not having 100% up-to-date code wrt. GP 1.1 API?).

**Comment by pascal-brand-st-dev** [comment]
Fix wrong sha1 and update change log of HiKey board testing

**Pull request merged**
