### PR TITLE
docs(huk_subkey.h): fixed a typo

### PR DESCRIPTION
**Pull request by nkxxll**
- fixed a typo in `huk_subkey.h` comment where `TEE_SUCCES` should be `TEE_SUCCESS`

### CODE REVIEW

**Comment by nkxxll** [comment]
This PR refers to issue #6626

**Review by etienne-lms — COMMENTED** [review]
`Acked-by: Etienne Carriere <etienne.carriere@foss.st.com>` with commit message change to  a more standard layout: header line + add Signed-off-by tag, for example:
```
core: kernel: fix typo in huk_subkey.h inline comment

Fix a typo in `huk_subkey.h` inline comment where TEE_SUCCES should be
TEE_SUCCESS.

Signed-off-by: ...

**Review by etienne-lms — APPROVED** [review]

**Comment by etienne-lms** [comment]
@jforissier, this change needs CI tests to be triggered.

**Comment by nkxxll** [comment]
I am confused the CI test is telling me there is not signed-off-by tag but it is present in the commit message. What am I missing?

**Comment by etienne-lms** [comment]
Rebase your change. It should fix the CI tests issues.

**Comment by jforissier** [comment]
> I am confused the CI test is telling me there is not signed-off-by tag but it is present in the commit message. What am I missing?

`Author:` and first `Signed-off-by:` have to be identical and they're not:
```
$ git fetch github pull/6634/head
$ git show FETCH_HEAD | grep -E "(Author:|Signed-off-by:)"
Author: nkirschall <84667783+nkxxll@users.noreply.github.com>
    Signed-off-by: Niklas Kirschall <niki.nice1203@gmail.com>
```

This should fix the problem:
```
$ git config --global user.name "Niklas Kirschall"
$ git config --global user.email "niki.nice1203@gmail.com"
$ git commit --amend --reset-author
$ git push -f
```

**Comment by etienne-lms** [comment]
The change looks all good to me. 
@nkxxll, please rebase your change on latest master branch tip of optee_os and @jforissier will be able to run CI tests on this P-R. Once it successfully passes, your change will likely be merged.

**Comment by nkxxll** [comment]
rebase done!

**Pull request merged**
