### PR TITLE
Paged user TAs

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Adds support for paged user TAs

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Depends on https://github.com/OP-TEE/optee_test/pull/124

**Comment by d3zd3z** [comment]
There's quite a bit of code, so I wouldn't say my review has been exhaustive, but what I've seen looks good.

**Comment by jenswi-linaro** [comment]
The `xtest 1016 Storage concurrency` is a bit tricky. When I'm testing on latest on master branch with pager enabled it sometimes fails. I'm starting to suspect that the pager itself isn't the culprit, instead it just makes it easier for race conditions to be triggered as context switch are suddenly very likely at certain addresses in the code.

**Comment by jenswi-linaro** [comment]
Rebased on master, squashed the [review] commit. Added a Hikey commit.

**Comment by jforissier** [comment]
@jenswi-linaro it looks like HiKey needs 40 KiB of HEAP_SIZE to pass `xtest 6016` reliably when pager is enabled.
There's also the checkpatch error and warning to be addressed.

**Comment by jbech-linaro** [comment]
Am I'm the only one that get the feeling that we have been fiddling with increasing both stack and heap quite a few times the last year? Maybe time to do an overhaul for all devices we support and at the same time increase to something a bit bigger than we actually need? Also, it might be worth checking whether we really need all of it or if we're unnecessarily use too much of them?

**Comment by jenswi-linaro** [comment]
Rebased with the memory fiddling patches removed as it's already dealt with on master now.

**Comment by jforissier** [comment]
Working fine on HiKey.
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey)`

**Comment by d3zd3z** [comment]
```
Acked-by: David Brown <david.brown@linaro.org>
```

**Comment by jenswi-linaro** [comment]
Checkpatch warnings/errors fixed, rebased and tags applied.

**Pull request merged**
