### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tag applied

**Comment by jenswi-linaro** [comment]
Update

**Comment by jenswi-linaro** [comment]
Squashed and commit message updated

**Comment by jenswi-linaro** [comment]
@etienne-lms, do you want to give any tag?

**Comment by etienne-lms** [comment]
Yes, sure. `Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by jenswi-linaro** [comment]
Thanks, tag applied.

**Pull request merged**
