### PR TITLE
Use DT_HASH to lookup symbols faster

### PR DESCRIPTION
**Pull request by jforissier**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Nice. However, this is yet another feature that need to be re-implemented in (or after) https://github.com/OP-TEE/optee_os/pull/3036.

**Comment by jforissier** [comment]
True. I can try to propose a patch for #3036. Should not be too hard I guess.

**Comment by jenswi-linaro** [comment]
Thanks, it should be fairly straight forward.

**Comment by jforissier** [comment]
@jenswi-linaro as discussed offline I have updated the patch to use `uint32_t` rather than `Elf32_Word` (because strictly speaking we should have used `Elf32_Word` for 32-bit executables and `Elf64_Word` for 64-bit ones, but both types are actually 32-bit quantities so `in the end uint32_t` makes more sense).

**Pull request merged**
