### PR TITLE
RPMB: tee_rpmb_write_blk(): allocate buffers once

### PR DESCRIPTION
**Pull request by jforissier**
Allocate shared memory buffers once for the write loop instead of
repeatedly allocating and freeing them. The previous code was needed
due to a bug/limitation in optee_linudriver [1]. Now that we are using
the "generic driver", the code can be optimized.

[1] https://github.com/OP-TEE/optee_linuxdriver/issues/40

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey)

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by pascal-brand-st-dev** [comment]
`Reviewed-by: Pascal Brand <pascal.brand@linaro.org>`

**Comment by jforissier** [comment]
Rebased with tags applied.

**Comment by pascal-brand-st** [comment]
Closing as manually merged

**Pull request closed without merging**
