### PR TITLE
cleanup plat-imx/conf.mk

### PR DESCRIPTION
**Pull request by murasesyuka**
duplicate cfg. at "CFG_MMU_V7_TTB ?= y"

Signed-off-by: murase_syuka <murase.syuka@gmail.com>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

Please add the "reviewed-by" tags in the commit message, and rebase on master. Thanks for your contribution.

**Comment by cedric-chaumont-st** [comment]
@murasesyuka Could you rebase and update your commit message (Reviewed-by, Tested-by) please ? Thanks for your contribution.

**Comment by murasesyuka** [comment]
reviewed thank you.
I try rebase. but this matter already fixed #515

**Pull request closed without merging**
