### PR TITLE
[rfc] Sign TAs using pss

### PR DESCRIPTION
**Pull request by jenswi-linaro**
PKCS#1 v1.5 has some security issues, https://cryptosense.com/blog/why-pkcs1v1-5-encryption-should-be-put-out-of-our-misery/

In this PR I propose to switch to sign TAs using TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA256. However, it's not completely without issues. In the scripts/sign_encrypt.py script we'll add dependency to Cryptodome. Before this the was dependency to Cryptodome only if TAs where to be encrypted.

Perhaps we should have a way of passing the algorithm to the script instead of using a hard coded algorithm.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
I'll polish up the commit messages.

**Comment by jenswi-linaro** [comment]
Update, tag applied to "core: shdr_verify_signature() supply hash length for salt length"

**Comment by jforissier** [comment]
In the first commit: "supply the size of the hash as the size of the **salt**".

Otherwise looks fine to me. For all commits:
`Reviewed-by: Jerome Forissier <jerome@forissier.org>`

**Comment by jforissier** [comment]
Note: I will add `Cryptodome` to the Docker image used by Shippable.

**Comment by jenswi-linaro** [comment]
Tag applied

**Comment by jforissier** [comment]
With CI updated with Cryptodome, all is well.

@jenswi-linaro 
> Perhaps we should have a way of passing the algorithm to the script instead of using a hard coded algorithm.

Could be nice, but if someone needs to be able to use the older algorithm, or cannot depend on Cryptodome, then we can always add a parameter later. I think this is good as it is.

**Pull request merged**
