### PR TITLE
kern.ld.S improvements

### PR DESCRIPTION
**Pull request by jforissier**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
For "core: arm: kern.ld.S: use ABSOLUTE() in some assertions":
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jenswi-linaro** [comment]
The resulting ELF becomes a bit messier with this. The reason we're doing this is to avoid knowing the required alignment of the `.nozi` section inside the link script. I'd rather add an `#ifdef CFG_WITH_LPAE` to use a more relaxed alignment (4KiB instead of 16KiB) for the LPAE and keep the resulting ELF more accurate with regards to sections.

**Comment by jforissier** [comment]
> I'd rather add an `#ifdef CFG_WITH_LPAE`

Sounds reasonable. Patch updated.

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Pull request merged**
