### PR TITLE
core: fix pl310 shared mutex when pager is enable

### PR DESCRIPTION
**Pull request by etienne-lms**
old fix i forgot to push earlier....

### CODE REVIEW

**Comment by jforissier** [comment]
Why only when pager is enabled? (the code is not guarded by `CFG_WITH_PAGER`).

**Comment by etienne-lms** [comment]
when pager is disable, the mutex is located in a flat-mapped area. pa=va => no bug.
so the real bug occurred when pager is enable.

But from your question, i fell i should change the commit header...

**Comment by jforissier** [comment]
OK, understood. Yes, please update the commit description. Other than that:
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jforissier** [comment]
Actually, I would not mind a small comment in the commit text, such as: _"Fixes the boot when pager is enabled. When pager is disabled, the mutex is located in a flat-mapped area, so pa == va and the bug does not occur."_. I think it's useful information.

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
@jforissier: ok i do as you suggest.

**Comment by jforissier** [comment]
Rebased and merged, thanks.

**Pull request closed without merging**
