### PR TITLE
Fix pager warnings

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by etienne-lms** [comment]
I saw that i was the faulty folk on the `copy_init` part :( 
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tags applied

**Comment by jforissier** [comment]
Can you rebase please?

**Comment by jenswi-linaro** [comment]
Rebased

**Pull request merged**
