### PR TITLE
Caam fixes

### PR DESCRIPTION
**Pull request by ruchi393**

### CODE REVIEW

**Comment by ruchi393** [comment]
@clementfaure , please review

**Comment by clementfaure** [comment]
Hello @ruchi393 ,
Please fix typo in the commit header message
```drivers: caam: Fix bug in JR Flush``` instead of ```drivers: caan: Fix bug in JR Flush ```

**Comment by jforissier** [comment]
> `drivers: caam: fix endianness caam_desc_pop function`

`in caam_desc_pop() function` (use parentheses when citing function names)

**Comment by clementfaure** [comment]
@ruchi393 Please rebase your branch to fix the CI fail

**Comment by clementfaure** [comment]
```Acked-by: Clement Faure <clement.faure@nxp.com>```

**Comment by jforissier** [comment]
@ruchi393 would you please rebase again and add @clementfaure's Acked-by tag? Then this should be ready for merging. Thanks.

**Comment by ruchi393** [comment]
Rebased the PR and added Acked-by

**Pull request merged**
