### PR TITLE
Python modules

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jbech-linaro** [comment]
Can't we add all this Python stuff as a pre-requisite? Why do we actually need to have it in the git?

**Comment by jforissier** [comment]
For "mk/cleandirs.mk: avoid print spurious empty lines":

`Reviewed-by: Jerome Forissier <jerome@forissier.org>`

**Comment by jforissier** [comment]
Why would we want to import pyelftools rather than making it a prerequisite for building?

**Comment by jenswi-linaro** [comment]
I should have tagged this PR "RFC".

Yes, we can add it as a prerequisite instead. This was an attempt to avoid adding more dependencies for the AOSP builds.

**Comment by jenswi-linaro** [comment]
https://github.com/OP-TEE/optee_os/pull/3039 created with only "mk/cleandirs.mk: avoid print spurious empty lines"

**Comment by jenswi-linaro** [comment]
Closing PR as we're going to rely on external dependencies instead.

**Pull request closed without merging**
