### PR TITLE
Dependencies

### PR DESCRIPTION
**Pull request by jbech-linaro**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jbech-linaro** [comment]
Tags applied, ready to be merged.

**Comment by d3zd3z** [comment]
Not sure you want to bother adding, but:
```
Reviewed-by: David Brown <david.brown@linaro.org>
```
Also, "sorting" in the commit title should probably be just "sort". The simple present tense makes the commits slightly easier to read later. But, it isn't that big of a deal.

**Comment by jbech-linaro** [comment]
Thanks @d3zd3z , I've updated the commit message and added your RB tag.

**Comment by jforissier** [comment]
Rebased on top of master and merged manually.

**Pull request closed without merging**
