### PR TITLE
Fix the use of Unique Key in the DCP driver

### PR DESCRIPTION
**Pull request by clementfaure**

### CODE REVIEW

**Review by etienne-lms — COMMENTED** [review]
`Acked-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by clementfaure** [comment]
Thanks @etienne-lms, tag applied!

**Comment by ricardosalveti** [comment]
`Tested-by: Ricardo Salveti <ricardo@foundries.io>`

This is the correct fix for https://github.com/OP-TEE/optee_os/pull/5238 (@Emantor fyi).

**Comment by clementfaure** [comment]
Hello @ricardosalveti, on which platform did you run the tests? so I can add `Tested-by: Ricardo Salveti <ricardo@foundries.io> (imx-mx****)`

**Comment by ricardosalveti** [comment]
> Hello @ricardosalveti, on which platform did you run the tests? so I can add `Tested-by: Ricardo Salveti <ricardo@foundries.io> (imx-mx****)`

Sure, imx6ull-evk.

**Comment by clementfaure** [comment]
Thanks! Tag applied

**Pull request merged**
