### PR TITLE
Sort out headers in kernel folder which are architecture-independent

### PR DESCRIPTION
**Pull request by maroueneboubakri**
To ease the porting of OP-TEE to more architectures, generic headers and sources which are located in `core/arch/arm/include/`  maybe be moved to ` core/include/`. 
This PR starts with kernel headers to make sure that this is feasible and does not make an impact.

### CODE REVIEW

**Comment by etienne-lms** [comment]
LGTM, `Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`.
Yet prefer also wait for feedback from @jforissier and @jenswi-linaro.

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jenswi-linaro** [comment]
By the way, the title line of most of the commits could have been written as:
`core: move xxx.h to core/include/kernel` without losing any information.

**Comment by jforissier** [comment]
> LGTM, `Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`.
> Yet prefer also wait for feedback from @jforissier and @jenswi-linaro.

Fine by me.

**Pull request merged**
