### PR TITLE
ci: delete .shippable.yml

### PR DESCRIPTION
**Pull request by jforissier**
The Microsoft Azure DevOps Pipelines CI script (.azure-pipelines.yml)
has now been tested with GitHub pull requests for 12 days with no
issues, so it is time to retire Shippable which only slows down the CI
loop at this point.

Signed-off-by: Jerome Forissier <jerome@forissier.org>

### CODE REVIEW

**Comment by jforissier** [comment]
Hmmm... not good. Just when buildin the commit that says "Azure is running with no issues"... that's ironic :confused: 

image

**Comment by jforissier** [comment]
Opened a ticket at Microsoft: https://developercommunity.visualstudio.com/t/TF24668:-The-following-team-project-coll/1361137

**Comment by jforissier** [comment]
Azure finally ran successfully after two new attempts.

**Comment by jforissier** [comment]
So, it turned out to be a misbehaving abuse detection algorithm in Azure Pipelines that blocked the execution. Apparently some people create public project with CI pipelines to mine cryptocurrency... so MS had to put protections in place. In the private comment I received from the MS support, they pointed me to a blog which explains the situatioon and recommends using GitHub Actions instead! Oh, well...

Anyways the tech said things should be working fine now.

**Comment by etienne-lms** [comment]
in case it helps: `Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Pull request merged**
