### PR TITLE
core: REE_FS: fix dirfile handle refcount

### PR DESCRIPTION
**Pull request by jenswi-linaro**
The counter ree_fs_dirh_refcount is used to determine when ree_fs_dirh should be free, not as a guarantee that ree_fs_dirh is still valid. This wasn't the assumption in ree_fs_readdir_rpc(), ree_fs_closedir_rpc(), and ree_fs_opendir_rpc(). So fix that by using get_dirh() in ree_fs_readdir_rpc as needed.

Fixes: ace6039fd434 ("core: REE_FS: refcount dirfile handle")

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Added a comment for `ree_fs_dirh` and `ree_fs_dirh_refcount`.

**Comment by jenswi-linaro** [comment]
Adding @ZheTing815's Reported-by.

**Review by jforissier — COMMENTED** [review]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Comment addressed and tag applied.

**Pull request merged**
