### PR TITLE
[RFC] core: add deferred init calls

### PR DESCRIPTION
**Pull request by jenswi-linaro**
```
Introduces CFG_CORE_DEFERRED_INIT which when 'y' enables deferred init
calls.  Deferred init calls are registered as any other init/final call
except that these are called when a PTA is called after the Linux
tee-supplicant has been initialized.

Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>
```
Relates to https://github.com/OP-TEE/optee_os/pull/4247

### CODE REVIEW

**Comment by jforissier** [comment]
Where is `call_deferredcalls()` called?

**Comment by jenswi-linaro** [comment]
> Where is `call_deferredcalls()` called?

It isn't, I don't think we're completely done here, hence the [RFC]. This is meant as a supplement to the discussion in #4247.
In the end I suppose it will be called from a PTA invoked by tee-supplicant.

**Comment by jforissier** [comment]
> > Where is `call_deferredcalls()` called?
> 
> It isn't, I don't think we're completely done here, hence the [RFC]. This is meant as a supplement to the discussion in #4247.
> In the end I suppose it will be called from a PTA invoked by tee-supplicant.

OK, got it.

**Comment by etienne-lms** [comment]
I wonder if static registering as here is preferred over dynamic registering with some `register_deferrer_call()` helper function. Or maybe both?

**Comment by jenswi-linaro** [comment]
When would you need dynamic registering?

**Comment by etienne-lms** [comment]
When depending on some init time resource probing, on some FDT content, ... 
I didn't mean I think this change should propose a dynamic registering. I was rather wondering why sometime dynamic registering (console.h, pm.h, drvcrpyt_*.h), and why sometime static registering (initcalls, memory, these deferred calls).

**Comment by anisyanka** [comment]
I can imagine a situation, when we need dynamic registering.
Lets see this example:
```C
static uint32_t test_dw1(void)
{
	EMSG("1");
	return 0;
}
static uint32_t test_dw2(void)
{
	EMSG("2");
	return 0;	
}
static uint32_t test_dw3(void)
{
	EMSG("3");
	return 0;	
}
static uint32_t test_dw4(void)
{
	EMSG("4");
	return 0;	
}
static uint32_t test_dw5(void)
{
	EMSG("5");
	return 0;	
}
....

deferred_init(test_dw1);
deferred_init(test_dw2);
deferred_init(test_dw3);

/* Here may be any condition. For example: do we need to delete a keystore?  */
if (1) {
	deferred_init(test_dw4);
} else {
	deferred_init(test_dw5);
}
```

When I try to run this example in qemu I see that execution of the `test_dw` happens in reverse.
I think there are situations, when right order of execution is important.
For example if first we need to delete old keystor and then create a key, we must do it in  right order. 
In other words in TEE console I see:
```
E/TC:0 0 test_dw5: 5
E/TC:0 0 test_dw4: 4
E/TC:0 0 test_dw3: 3
E/TC:0 0 test_dw2: 2
E/TC:0 0 test_dw1: 1
```
And also the execution of some conditions is useless, because we've added defered inits in static style.
Seems, dynamic registering can help us in such situations.

Maybe we need `deferred_init()` for deferred initialization and `deferred_work_add()` to handle the situations described above ?

**Comment by jenswi-linaro** [comment]
What prevents you from implementing `test_dw4()` and `test_dw5()` as
``` C
static uint32_t test_dw4(void)
{
     if (1)
	EMSG("4");
     return 0;	
}
static uint32_t test_dw5(void)
{
     if (!1)
	EMSG("5");
     return 0;	
}
```

You should probably view these deferred inits as functions taking care of a subsystem, not a generic function doing some work.

The call order is undefined, but is always the same for the same build. If you change toolchain you may get a different order. If ordering is important then we'll need to add multiple deferred_init() levels, like the `early_init()`, `early_init_late()` and so on.

**Comment by jenswi-linaro** [comment]
Keeping this open for a while longer.

**Comment by anisyanka** [comment]
Hello, I'd like to resume our discussion.

> What prevents you from implementing `test_dw4()` and `test_dw5()` as
> 
> ```c
> static uint32_t test_dw4(void)
> {
>      if (1)
> 	EMSG("4");
>      return 0;	
> }
> static uint32_t test_dw5(void)
> {
>      if (!1)
> 	EMSG("5");
>      return 0;	
> }
> ```

My example really might be replaced by yours and it will work, but actually in real system we have more conditions to execute (or not) particular deferred work. Therefore replacing is not so easy.

>The call order is undefined, but is always the same for the same build. If you change toolchain you may get a different order. If ordering is important then we'll need to add multiple deferred_init() levels, like the early_init(), early_init_late() and so on.

Yes, you're right, but even inside `early_init()` or `early_init_late()` right order could be important.

I agree the deferred init calls are not generic functions doing some work, therefore I'd prefer to have both of them mechanisms (static and dynamic) in OP-TEE. 
I have some new ideas how to implement dynamic deferred calls: https://github.com/OP-TEE/optee_os/pull/4247#issuecomment-773984907

What do you thinks about it?

**Pull request closed without merging**
