### PR TITLE
Rename arm32 architecture to arm

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Since we soon are going to have both arm32 and arm64 code in the same architecture it's a logical step to rename the architecture to arm.

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
More changes are required:

- documentations
- optee_test with CFG_COMPILE_MODE... but that means the STABLE_OPTEE_TEST must be modified in the setup scripts

Also, I would like to merge this commit once #208 is merged as we have some arm32 reference in the new script. @cedric-chaumont-st can you confirm we're almost there with #208?

**Comment by jenswi-linaro** [comment]
OK, I'll update documentation.
I seems that optee_test doesn't need to be updated right now, I've tested OK without any updates there, but long term we should update.

**Comment by jenswi-linaro** [comment]
Documentation updated.

**Comment by pascal-brand-st-dev** [comment]
In setup scripts, the following must be used instead:
- STABLE_OPTEE_CLIENT_COMMIT=1b830c9ca51547cf90cb929a904caa57a5e42853
- STABLE_OPTEE_TEST_COMMIT=bdc720eb11d698dfc79d5acd0f8257c313d8a687

It has been successfully used on QEMU. The script has not been tested on FVP.

With this change:

    Reviewed-by: Pascal Brand <pascal.brand@linaro.org>
    Tested-by: Pascal Brand <pascal.brand@linaro.org> (QEMU platform)

**Comment by jenswi-linaro** [comment]
Rebased and tags applied.

**Pull request merged**
