### PR TITLE
Import zlib-1.2.8

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Imports zlib-1.2.8 from http://zlib.net/zlib-1.2.8.tar.xz
with MD5 checksum 28f1205d8dd2001f26fec1e8c2cebe37

Internal test files and other unused files are removed.

Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU)
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
Can you add in the commit message why you added this library?

**Comment by jforissier** [comment]
+1 with @pascal-brand-st-dev. Also please make it clear that it is built as a user-mode library, for TAs.
IMO you should also include the `FAQ` file because it is referenced in `Changelog` and has some information about licensing and versioning in case the source code is modified.

**Comment by jenswi-linaro** [comment]
Update

**Comment by pascal-brand-st-dev** [comment]
`Reviewed-by: Pascal Brand <pascal.brand@linaro.org>`

**Comment by jenswi-linaro** [comment]
Rebased, tag applied

**Pull request merged**
