### PR TITLE
ta: pkcs11: Add support for AES CMAC mechanisms

### PR DESCRIPTION
**Pull request by vchong**
Add support for CKM_AES_CMAC* mechanisms.

Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by vchong** [comment]
Depends on:
https://github.com/OP-TEE/optee_client/pull/286
https://github.com/OP-TEE/optee_test/pull/546

**Review by etienne-lms — COMMENTED** [review]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by ruchi393** [comment]
`Acked-by: Ruchika Gupta <ruchika.gupta@linaro.org>`

**Comment by vchong** [comment]
Rebased and tag added. Please merge along with:
OP-TEE/optee_client#286
OP-TEE/optee_test#546

**Pull request merged**
