### PR TITLE
[RFC] checkpatch: increase max line length to 100

### PR DESCRIPTION
**Pull request by vesajaaskelainen**
Match the limit to the Linux kernel change in:

commit bdc48fa11e46f867ea4d75fa59ee87a7f48be144

Signed-off-by: Vesa Jääskeläinen <vesa.jaaskelainen@vaisala.com>

### CODE REVIEW

**Comment by vesajaaskelainen** [comment]
Proposal to increase the limit to 100 characters as in example with pkcs11 TA there are lots of variables and functions that easily go quite long and it gets a bit tiresome to try to fit lines into 80 limit.

**Comment by jforissier** [comment]
A few things...

1. This would effectively revert 751083b65671 ("checkpatch: limit maximum line length to 80"). The patch should simply remove the `--max-line-length` parameter, not set it to 100.
2. You could add your explanation (about PKCS#11) in the commit description (it is always good to have some context and details about the "why" especially since this changes a previous decision)
3. Since you are referencing an external commit, to avoid a checkpatch warning (!) you may use a link like so:
```
(blah blah) Linux kernel change: "checkpatch/coding-style: deprecate 80-column warning" [1].

Link: [1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=bdc48fa11e46f867ea4d75fa59ee87a7f48be144
Signed-off-by: ...
```

I have no strong opinion on this, for me that is acceptable. @jenswi-linaro what do you think?

`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by jenswi-linaro** [comment]
I'm not so keen on this. If it only affected the PKCS#11 TA I wouldn't care, but now it's also the entire git.
I don't want longer lines that 80 character anywhere else.

**Comment by vesajaaskelainen** [comment]
> I'm not so keen on this. If it only affected the PKCS#11 TA I wouldn't care, but now it's also the entire git.
> I don't want longer lines that 80 character anywhere else.

Feel free to disagree on enlarging the limit and just close the ticket -- then we are done on the topic. Idea was to have discussion how you see the change.

I am also open on tuning the PR based on @jforissier's comments but if it does not fly then I don't want to use more time on it.

**Comment by jenswi-linaro** [comment]
OK, let's close this then.
Thanks for being cool about it.

**Pull request closed without merging**
