### PR TITLE
ci: hafnium: fix "no space left on device" error

### PR DESCRIPTION
**Pull request by jforissier**
Apply the same technique as commit 788069fa88ed ("ci: rust: fix "no space left in device" error") to avoid a similar issue with the Hafnium job.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Who's putting the stuff in /__t ?

**Review by etienne-lms — COMMENTED** [review]
`Acked-by: Etienne Carriere <etienne.carriere@foss.st.com>`

**Comment by jforissier** [comment]
> Who's putting the stuff in /__t ?

The files are in the host VM (the Github Actions runner, as it is called) and they are automatically added to the root directory (/) of the container image that is spawned by the host VM to run the actual job (i.e., jforissier/optee_os_ci:qemuv8_check2). The mapping happens via a Docker mount (`-v` option). If you check the "Initialize containers" step in the CI job, you will see:

> /usr/bin/docker create --name c545a075e8c84e00a76f4a9538301fb5_jforissieroptee_os_ciqemuv8_check2_fa9c54 --label 94351b --workdir /__w/optee_os/optee_os --network github_network_9780ec224d434de49818ed43b77f1127  -e "HOME=/github/home" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work":"/__w" -v "/home/runner/runners/2.309.0/externals":"/__e":ro -v "/home/runner/work/_temp":"/__w/_temp" -v "/home/runner/work/_actions":"/__w/_actions" -v "/opt/hostedtoolcache":"/__t" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" --entrypoint "tail" jforissier/optee_os_ci:qemuv8_check2 "-f" "/dev/null"

Note the `-v "/opt/hostedtoolcache":"/__t"`. This mapping adds quite a bit (11G) to the initial size of the `/` overlay FS in the container.

Of course there is no guarantee that removing files in there from inside the container is safe... but it works ;)

**Comment by jenswi-linaro** [comment]
Thanks for the explanation.
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Pull request merged**
