### PR TITLE
core: arm: rpc i2c: fix, REE processed bytes

### PR DESCRIPTION
**Pull request by ldts**
The number of bytes processed by the REE is returned in p[3] as
defined in the API.

Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

### CODE REVIEW

**Comment by ldts** [comment]
@jenswi-linaro 

Another issue that I have noticed now using the thread storage vs the preallocated buffer in the original driver (still dont know the root cause, might or might not be related to the i2c trampoline)

This is with the  the tip of optee - managed to rebase from OP-TEE 3.6.0)  and NMB_THREADS = 1.

It seems that mobj associated to the thread gets corrupted (at the bottom of the trace, mobj->ops is 0x71ed323cc969a700 instead of the original 0xbe05d140). Not sure if you have any thoughts on what could be happening.

**I/TC: tee_fs_rpc_write_init**                                                                                                                                                                                                                                                                                                                                                             
**I/TC: thread_rpc_shm_cache_alloc thread 0, type 0, bytes 68**                                                                                                                                                                                                                                                                                                                             
I/TC: get_rpc_arg 382                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 404                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 407                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 457                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 460                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 382                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 404                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 407                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 457                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 460                                                                                                                                                                                                                                                                                                                                                                   
I/TC: mobj_matches 74 mobj = 0xbe0914d0                                                                                                                                                                                                                                                                                                                                                 
I/TC: mobj_matches 76 ops = **0xbe05d140**                             <---------------- CORRECT                                                                                                                                                                                                                                                                                                                     
I/TC: mobj_matches 78 matches = 0xbe012724                                                                                                                                                                                                                                                                                                                                              
I/TC: mobj_matches 82                                                                                                                                                                                                                                                                                                                                                                   
I/TC: tee_fs_rpc_write_final                                                                                                                                                                                                                                                                                                                                                            
I/TC: operation_commit                                                                                                                                                                                                                                                                                                                                                                  
I/TC: get_rpc_arg 382                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 404                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 407                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 430                                                                                                                                                                                                                                                                                                                                                                   
I/TC: mobj_matches 74 mobj = 0xbe0914d0                                                                                                                                                                                                                                                                                                                                                 
I/TC: mobj_matches 76 ops = 0xbe05d140                                                                                                                                                                                                                                                                                                                                                  
I/TC: mobj_matches 78 matches = 0xbe012724                                                                                                                                                                                                                                                                                                                                              
I/TC: mobj_matches 82                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 433                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 457                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 460                                                                                                                                                                                                                                                                                                                                                                   
I/TC: tee_fs_rpc_write_init                                                                                                                                                                                                                                                                                                                                                             
I/TC: thread_rpc_shm_cache_alloc thread 0, type 0, bytes 68                                                                                                                                                                                                                                                                                                                             
I/TC: tee_fs_rpc_write_final                                                                                                                                                                                                                                                                                                                                                            
I/TC: operation_commit                                                                                                                                                                                                                                                                                                                                                                  
I/TC: get_rpc_arg 382                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 404                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 407                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 430                                                                                                                                                                                                                                                                                                                                                                   
I/TC: mobj_matches 74 mobj = 0xbe0914d0                                                                                                                                                                                                                                                                                                                                                 
I/TC: mobj_matches 76 ops = 0xbe05d140                                                                                                                                                                                                                                                                                                                                                  
I/TC: mobj_matches 78 matches = 0xbe012724                                                                                                                                                                                                                                                                                                                                              
I/TC: mobj_matches 82                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 433                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 457                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 460    
I/TC: tee_fs_htree_write_block 824                                                                                                                                                                                                                                                                                                                                                      
I/TC: tee_fs_htree_write_block 829                                                                                                                                                                                                                                                                                                                                                      
I/TC: tee_fs_htree_write_block 835                                                                                                                                                                                                                                                                                                                                                      
I/TC: tee_fs_rpc_write_init                                                                                                                                                                                                                                                                                                                                                             
I/TC: thread_rpc_shm_cache_alloc thread 0, type 0, bytes 4096                                                                                                                                                                                                                                                                                                                           
I/TC: tee_fs_htree_write_block 842                                                                                                                                                                                                                                                                                                                                                      
I/TC: rpc_io_i2c_transfer                                                                                                                                                                                                                                                                                                                                                               
I/TC: thread_rpc_shm_cache_alloc thread 0, type 1, bytes 38                                                                                                                                                                                                                                                                                                                             
I/TC: get_rpc_arg 382                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 404                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 407                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 457                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 460                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 382                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 404                                                                                                                                                                                                                                                                                                                                                                   
I/TC: get_rpc_arg 407
I/TC: get_rpc_arg 457
I/TC: get_rpc_arg 460
I/TC: mobj_matches 74 mobj = 0xbe091600
I/TC: mobj_matches 76 ops = 0xbe05d140
I/TC: mobj_matches 78 matches = 0xbe012724
I/TC: mobj_matches 82
I/TC: rpc_io_i2c_transfer done
I/TC: get_rpc_arg 382
I/TC: get_rpc_arg 404
I/TC: get_rpc_arg 407
I/TC: get_rpc_arg 430
I/TC: mobj_matches 74 mobj = 0xbe091600
I/TC: mobj_matches 76 ops = 0xbe05d140
I/TC: mobj_matches 78 matches = 0xbe012724
I/TC: mobj_matches 82
I/TC: get_rpc_arg 433
I/TC: get_rpc_arg 457
I/TC: get_rpc_arg 460
[   46.133767] kernel processed 44 bytes
**I/TC: rpc_io_i2c_transfer**
I/TC: thread_rpc_shm_cache_alloc thread 0, type 1, bytes 2
**I/TC: rpc_io_i2c_transfer done**
I/TC: get_rpc_arg 382
I/TC: get_rpc_arg 404
I/TC: get_rpc_arg 407
I/TC: get_rpc_arg 430
I/TC: mobj_matches 74 mobj = 0xbe091600
I/TC: mobj_matches 76 ops = 0xbe05d140
I/TC: mobj_matches 78 matches = 0xbe012724
I/TC: mobj_matches 82
I/TC: get_rpc_arg 433
I/TC: get_rpc_arg 457
I/TC: get_rpc_arg 460
[   46.376947] kernel processed 38 bytes
**I/TC: rpc_io_i2c_transfer**
I/TC: thread_rpc_shm_cache_alloc thread 0, type 1, bytes 1
**I/TC: rpc_io_i2c_transfer done**
I/TC: get_rpc_arg 382
I/TC: get_rpc_arg 404
I/TC: get_rpc_arg 407
I/TC: get_rpc_arg 430
I/TC: mobj_matches 74 mobj = 0xbe091600
I/TC: mobj_matches 76 ops = 0xbe05d140
I/TC: mobj_matches 78 matches = 0xbe012724
I/TC: mobj_matches 82
I/TC: get_rpc_arg 433
I/TC: get_rpc_arg 457
I/TC: get_rpc_arg 460
[   46.420157] kernel processed 2 bytes
**I/TC: rpc_io_i2c_transfer**
I/TC: thread_rpc_shm_cache_alloc thread 0, type 1, bytes 44
**I/TC: rpc_io_i2c_transfer done**
I/TC: get_rpc_arg 382
I/TC: get_rpc_arg 404
I/TC: get_rpc_arg 407
I/TC: get_rpc_arg 430
I/TC: mobj_matches 74 mobj = 0xbe091600
I/TC: mobj_matches 76 ops = 0xbe05d140
I/TC: mobj_matches 78 matches = 0xbe012724
I/TC: mobj_matches 82
I/TC: get_rpc_arg 433
I/TC: get_rpc_arg 457
I/TC: get_rpc_arg 460
[   46.461935] kernel processed 1 bytes
I/TC: tee_fs_htree_write_block 849
I/TC: tee_fs_htree_write_block 855
**I/TC: tee_fs_rpc_write_final**
**I/TC: operation_commit**
I/TC: get_rpc_arg 382
I/TC: get_rpc_arg 404
I/TC: get_rpc_arg 407
I/TC: get_rpc_arg 430
I/TC: mobj_matches 74 mobj = 0xbe0914d0
I/TC: mobj_matches 76 ops = **0x71ed323cc969a700**                < -------------- CORRUPTED
E/TC:1 0
E/TC:1 0 Core data-abort at address 0x71ed323cc969a720 (translation fault)
E/TC:1 0  esr 0x96000004  ttbr0 0x20000be0a0020   ttbr1 0x00000000   cidr 0x0
E/TC:1 0  cpu #1          cpsr 0x40000004
E/TC:1 0  x0  71ed323cc969a700 x1  0000000000000000
E/TC:1 0  x2  00000000be0181a0 x3  0000008000000100
E/TC:1 0  x4  0000000000000010 x5  0000000000000010
E/TC:1 0  x6  00000000ffffffef x7  00000000fffffff0
E/TC:1 0  x8  00000000be0a6328 x9  a812b0d320432193
E/TC:1 0  x10 0000000000000000 x11 00000000000000de
E/TC:1 0  x12 00000000be0a6298 x13 000000000000000a
E/TC:1 0  x14 00000000ffffffff x15 0000000000000020
E/TC:1 0  x16 00000000be0182d0 x17 0000000000000000
E/TC:1 0  x18 00000000000000f8 x19 00000000be0914d0
E/TC:1 0  x20 00000000be066000 x21 00000000be066f89
E/TC:1 0  x22 0000000000000001 x23 00000000be066000
E/TC:1 0  x24 00000000be080cc0 x25 00000000be0a6758
E/TC:1 0  x26 00000000b8800120 x27 00000000be066fbb
E/TC:1 0  x28 00000000be0a6630 x29 00000000be0a6570
E/TC:1 0  x30 00000000be0088ec elr 00000000be0088f4
E/TC:1 0  sp_el0 00000000be0a6570
E/TC:1 0 TEE load address @ 0xbe000000
E/TC:1 0 Call stack:
E/TC:1 0  0x00000000be0088f4
E/TC:1 0  0x00000000be008dc4
E/TC:1 0  0x00000000be009454
E/TC:1 0  0x00000000be027c8c
E/TC:1 0  0x00000000be0266cc
E/TC:1 0  0x00000000be028068
E/TC:1 0  0x00000000be028638
E/TC:1 0  0x00000000be026a38
E/TC:1 0  0x00000000be029bf4
E/TC:1 0  0x00000000be02a300
E/TC:1 0  0x00000000be005c14
E/TC:1 0  0x00000000be01bab4
E/TC:1 0  0x00000000be006230
E/TC:1 0  0x00000000be01a51c
E/TC:1 0  0x00000000be01fe20
E/TC:1 0  0x00000000be0133e0
E/TC:1 0  0x00000000be0085f4
E/TC:1 0  0x00000000be004410
E/TC:1 0 Panic 'unhandled pageable abort' at core/arch/arm/kernel/abort.c:546 <abort_handler>
E/TC:1 0 TEE load address @ 0xbe000000

**Comment by jenswi-linaro** [comment]
Please add a
```
Fixes: 30c53a724263 ("core: arm: rpc i2c trampoline driver")
```
in the commit message.

You could include a few words in the commit message explaining what's fixed.

**Comment by jenswi-linaro** [comment]
The log looks a bit strange. This cache is shared with the storage code. It looks like `tee_fs_rpc_write_final()` expects a previously retrieved buffer. Now this only happens during `tee_tadb_ta_write()` so the i2c code should not be able to interfere with that.

**Comment by ldts** [comment]
just for background, the i2c code is managing the cryptographic operations via SE,  so if there is a fs access + crypto access + fs access, and the cache is shared, crypto would have modified the cache. would that be an issue? crypto use kernel cache where us fs seem to use user cache is my understanding.

**Comment by jenswi-linaro** [comment]
> just for background, the i2c code is managing the cryptographic operations via SE, so if there is a fs access + crypto access + fs access, and the cache is shared, crypto would have modified the cache. would that be an issue?

It looks like we're seeing something like that. 

> crypto use kernel cache where us fs seem to use user cache is my understanding.

I'm sorry, I don't understand.

**Comment by ldts** [comment]
my bad, I meant that i2c allocates for shm_type THREAD_SHM_TYPE_KERNEL_PRIVATE while fs allocates for THREAD_SHM_TYPE_APPLICATION.

**Comment by jenswi-linaro** [comment]
> my bad, I meant that i2c allocates for shm_type THREAD_SHM_TYPE_KERNEL_PRIVATE while fs allocates for THREAD_SHM_TYPE_APPLICATION.

OK, thanks. When you're using `thread_rpc_shm_cache_alloc()` you need to be careful with which functions you call. Or you need to call `thread_rpc_shm_cache_alloc()` again.

**Comment by ldts** [comment]
right, and that is what might be happening somewhere in tee_fs you think?

**Comment by jenswi-linaro** [comment]
No idea. I don't see how that can happen inside `rpc_io_i2c_transfer()`.

**Comment by ldts** [comment]
yes I think this can not work. tee_fs_htree_write_block() initializes the enc_block data buffer from thread cache, then requests i2c operations (which also use the same cache) and then tries to access it for writing directly via de-referecing struct tee_fs_rpc_operation. 

Perhaps each thread could have a number of caches -at least two?...or maybe allow the i2c trampoline to have its own dedicated buffer to talk to the REE.

**Comment by ldts** [comment]
shall I open an "issue" aside from this PR?

**Comment by jenswi-linaro** [comment]
Thanks for the analysis. I'll create another PR to take care of that. I don't think we need an "issue" for this.

**Comment by jenswi-linaro** [comment]
Please test with https://github.com/OP-TEE/optee_os/pull/4039

**Comment by ldts** [comment]
> Please test with https://github.com/OP-TEE/optee_os/pull/4039

thanks Jen. I'll test and come back to you towards the end of the day (I am OOO today and far from my desk)

**Comment by ldts** [comment]
@jenswi-linaro yes #4039 works as long as we apply this PR on top.

**Comment by jenswi-linaro** [comment]
Thanks

**Comment by jforissier** [comment]
Should we take 4039 + 4033 in 3.10.0?

**Comment by jenswi-linaro** [comment]
> Should we take 4039 + 4033 in 3.10.0?

Yes, that's probably the best. 30c53a7 ("core: arm: rpc i2c trampoline driver") is broken and may be confusing for people looking at the release.

For the commit "core: arm: rpc i2c: fix, REE processed bytes":
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by ldts** [comment]
> `Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`
> 
> Minor: could simply the commit log:
> 
> ```diff
> -The number of bytes processed by the REE is returned in p[3] as
> -defined in the API.
> +Fix number of bytes processed by the REE that is returned in p[3] as
> +defined in the API, not in p[2].
> -
> -The code being fixed by this patch uses p[2] which was part of the
> -initial work before we added support for the 'flags' field to be able
> -to interface to 10 bit chip addresses. Since the flags value was
> -placed in p[1], p[2] should have become p[3].
> ```

sure I can change that. give me a minute.

out of curiosity and given that we spent nearly three months reviewing about 60 lines of code in 30c53a7 ,  are there any lessons learnt on the review process itself? is it possible that perhaps we were not paying enough attention to the functional aspects of the pull request during the review and maybe a little bit too much to lesser relevant bits? and that caused some distraction?

**Pull request merged**
