### PR TITLE
arm: bugfix compile error in tee_mmu_map()

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jforissier** [comment]
What error does it fix? On which platform? (the Travis build was not broken prior to this patch AFAICT).

**Comment by jenswi-linaro** [comment]
@jforissier FVP Aarch64 `aarch64-linux-gnu-gcc (Linaro GCC 2014.11) 4.9.3 20141031 (prerelease)`

It's clearly an error even if some compilers doesn't see it that way, a paddr_t is an integer not a pointer.

**Comment by jforissier** [comment]
@jenswi-linaro agreed, thanks.
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tags applied.

**Pull request merged**
