### PR TITLE
Mobj bugfix

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Problems discovered while testing the GP socket stuff.

### CODE REVIEW

**Comment by jforissier** [comment]
's/statis/static/' in the commit message of "core: static ta: bugfix copy_in_param()".

Also, could you please add references to the commit(s) that introduced the issue? ("Fixes: 0123456789ab "Blah blah"). It helps when writing release notes.

**Comment by jforissier** [comment]
Other than that:
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org`

**Comment by jenswi-linaro** [comment]
Updated commit messages, tag applied.

**Comment by jforissier** [comment]
Sorry for the missing `>` in my R-b... (it confuses checkpatch).
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

While you're at it, can you add parentheses and double quotes around the commit subject in the Fixes: tag? That should be:
`Fixes: 0dcfa5686d02 ("core: introduce MOBJ abstraction")`

**Comment by jenswi-linaro** [comment]
Update as requested.

**Pull request merged**
