### PR TITLE
mk/aosp_optee.mk: move ta files to vendor partition

### PR DESCRIPTION
**Pull request by liuyq**
to make it work with Treble enabled builds

Acked-by: Victor Chong <victor.chong@linaro.org>
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>

### CODE REVIEW

**Comment by vchong** [comment]
ack

**Comment by vchong** [comment]
@petegriffin fyi

**Comment by petegriffin** [comment]
Great!

**Comment by vchong** [comment]
related to:
https://github.com/OP-TEE/optee_client/pull/119 (2nd commit)
https://github.com/OP-TEE/optee_test/pull/293

**Comment by liuyq** [comment]
The changes to support Treble enabled builds are as following:
https://github.com/OP-TEE/optee_client/pull/119
https://github.com/OP-TEE/optee_test/pull/293
https://github.com/OP-TEE/optee_os/pull/2413
https://android-review.linaro.org/#/c/18404/ (this change is only for treble support, need to apply other old changes on hikey device repository as well)

tested with xtest command on  hikey + aosp master + 4.14 kernel build on local side.

Please help to check if it's OK to have them merged, thanks in advance!

**Comment by vchong** [comment]
@jforissier Can this and all related PRs below be merged now? Thanks!

OP-TEE/optee_client#119
OP-TEE/optee_test#293
linaro-swg/optee_examples/pull/27
linaro-swg/optee_examples/pull/28

**Comment by jforissier** [comment]
@vchong all merged

**Pull request merged**
