### PR TITLE
[v4] Squashed commit upgrading to mbedtls-3.4.0

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Squash merging branch import/mbedtls-3.4.0

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Depends on https://github.com/OP-TEE/optee_test/pull/697

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (vexpress-qemu_armv8a)`

Fot the record, the test command I used: `make -j$(nproc) check CFG_CRYPTOLIB_NAME=mbedtls CFG_CRYPTOLIB_DIR=lib/libmbedtls check XTEST_ARGS="-x pkcs11_1021 -x pkcs11_1022 -x pkcs11_1023 -x pkcs11_1026"`

Hopefully people interested in using the PKCS#11 TA with MBedTLS as the core crypto library will troubleshoot and fix the issues :wink: they are not new (#5418).

**Comment by jenswi-linaro** [comment]
Tags applied

**Comment by jforissier** [comment]
The CI error (in the `make (multi-platform)` job):
```
error: unknown warning option '-Wno-unused-functions'; did you mean '-Wno-unused-function'? [-Werror,-Wunknown-warning-option]
```
...is a valid error that should be fixed (and also in the import branch...)

**Comment by jenswi-linaro** [comment]
I'll push the supplied fix to the import branch if we're OK with it.

**Comment by jenswi-linaro** [comment]
Pushed "libmbedtls: fix unrecognized compiler option" to the import branch.

Updated the squashed merge to include "libmbedtls: fix unrecognized compiler option". Updated the commit message to see if checkpatch could be made a bit less unhappy.

**Pull request merged**
