### PR TITLE
ta: pkcs11: Remove dual crypto operations from token capability

### PR DESCRIPTION
**Pull request by ruchi393**

### CODE REVIEW

**Comment by Emantor** [comment]
HI, small nit: Typo in the commit message of ` ta: pkcs11: Remove dual crypto operations from token capability `, implemenetation has one e too many.

**Comment by ruchi393** [comment]
> HI, small nit: Typo in the commit message of `ta: pkcs11: Remove dual crypto operations from token capability`, implemenetation has one e too many.

Thanks will fix it

**Comment by vesajaaskelainen** [comment]
Fixes looks familiar here -- https://github.com/OP-TEE/optee_os/pull/4756

**Comment by vesajaaskelainen** [comment]
For commit:
- https://github.com/OP-TEE/optee_os/pull/4771/commits/76aa2c6d94e93fa30da60b22ac2646e2b4d81a7e ta: pkcs11: Remove dual crypto operations from token capability

`Reviewed-by: Vesa Jääskeläinen <vesa.jaaskelainen@vaisala.com>`

**Comment by ruchi393** [comment]
> Fixes looks familiar here -- #4756

Yes it is the same...Sorry, I missed that PR.

**Comment by ruchi393** [comment]
Tag applied. PR updated to keep only 1 commit related with dual crypto operation.

**Comment by vesajaaskelainen** [comment]
You may want to update this PR's title to match.

**Pull request merged**
