### PR TITLE
core: sp: fix FFA_MEM_RECLAIM checks

### PR DESCRIPTION
**Pull request by balint-dobszay-arm**
Currently it is assumed that a NS endpoint's ID is always 0. This is not true if multiple VMs are present in the NWd, so the check will fail when reclaiming shared memory from an SP. Fix this by removing the owner ID check if the reclaim call comes from NWd, in this case the necessary checks are done by the hypervisor.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by balint-dobszay-arm** [comment]
Can we get this merged please?

**Comment by balint-dobszay-arm** [comment]
Rebased on top of master

**Comment by jforissier** [comment]
> Can we get this merged please?

Sure. Thanks!

**Pull request merged**
