### PR TITLE
ltc: remove test related source files

### PR DESCRIPTION
**Pull request by matt2048**
Test related source files have not been built into OP-TEE image all the
time, so we remove them permanently.

Signed-off-by: Matt Ma <matt.ma@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jforissier** [comment]
@matt2048 sorry i didn't notice you had pushed a new commit. Can you please rebase, then I'll merge immediately.

**Comment by matt2048** [comment]
@jforissier OK, thank you, I have rebased.

**Pull request merged**
