### PR TITLE
Fix CFG_CRYPTO=n compilation on armv8 targets compiled in AArch32

### PR DESCRIPTION
**Pull request by pascal-brand-st-dev**
This fixes compilation with
    CFG_CRYPTO=n COMPILE_S_KERNEL=32 COMPILE_S_USER=32

Signed-off-by: Pascal Brand <pascal.brand@st.com>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jforissier** [comment]
Something I missed: you should not refer to `COMPILE_S_KERNEL=32 COMPILE_S_USER=32` in the commit comment because these variables are not known to `optee_os`. Also I suppose user mode is irrelevant, so the actual condition that would trigger the bug is `CFG_CRYPTO=n CFG_ARM64_core=n`.

**Comment by pascal-brand-st-dev** [comment]
Right. I'll rework the pull-request.

**Comment by pascal-brand-st-dev** [comment]
Updated. Final pull-request with rework the commit message according to @jforissier proposal.

@jforissier @jenswi-linaro Could you let me know if you leave your R-Bs

**Comment by jenswi-linaro** [comment]
OK with me.

**Comment by jforissier** [comment]
Yes, this is fine. Thanks for updating.

**Pull request merged**
