### PR TITLE
plat-stm: fix flavor 'cannes'

### PR DESCRIPTION
**Pull request by etienne-lms**
fix 2 bugs introduced during plat-stm: beautification.

### CODE REVIEW

**Comment by jforissier** [comment]
Could you add the following tag?
```
Fixes: 8cd89706f19c ("plat-stm: beautify platform config")
```

Obviously I can't provide a R-b since I have no idea about the platform registers, but feel free to add:
```
Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`
```

**Comment by etienne-lms** [comment]
ok, thanks.

**Comment by etienne-lms** [comment]
trailing character at end of your `Acked-by`...

**Comment by jforissier** [comment]
Oops, sorry, you can delete it of course.

**Comment by etienne-lms** [comment]
updated, tag applied

**Comment by jforissier** [comment]
Oops, sorry, you can delete it of course.

**Comment by jforissier** [comment]
Oops, sorry, you can delete it of course.

**Comment by jforissier** [comment]
Hum. Sorry for the spam, apparently my browser has decided to not show the update when I click comment ;)

**Pull request merged**
