### PR TITLE
libutils: Implement speculation barrier for RISC-V

### PR DESCRIPTION
**Pull request by gagachang**
Implement load_no_speculate() with implementation consists of RISC-V fence instructions which are used to preserve the memory order.

- Data barrier: fence rw, rw
- Instruction barrier: fence.i; fence r, r

### CODE REVIEW

**Comment by gagachang** [comment]
Hi @maroueneboubakri 
Please review this PR, thanks!

**Comment by gagachang** [comment]
Hi @maroueneboubakri 
Any update about this PR?
The compiler error of upstream OP-TEE for RISC-V might be fixed with this PR.
We can then plan to add RISC-V architecture into official CI.

**Comment by lyctw** [comment]
`Reviewed-by: Yu Chien Peter Lin <peterlin@andestech.com>`

**Comment by gagachang** [comment]
Tag applied

**Pull request merged**
