### PR TITLE
plat-imx: fix build when CFG_BOOT_SYNC_CPU=y

### PR DESCRIPTION
**Pull request by gsora**
Added a missing semicolon, removed an unknown macro prefix.

Just doing some cleaning 😄

### CODE REVIEW

**Comment by gsora** [comment]
Rebased with ack in commit message.

**Comment by clementfaure** [comment]
@gsora Do you use this option?

**Comment by gsora** [comment]
@clementfaure no, I was reading `plat-imx.c` and noticed there were some typos.

**Comment by clementfaure** [comment]
Since ```CFG_BOOT_SYNC_CPU``` is disabled by default on i.MX and obviously not used, I guess this option could be deleted.

**Comment by jforissier** [comment]
@gsora: I think @clementfaure's suggestion should be considered here (especially since he is an official reviewer for i.MX :wink:). Would you please replace your commit with a new one? Thanks!

**Comment by gsora** [comment]
Indeed.

I'll close this PR and submit a new one with `CFG_BOOT_SYNC_CPU` removed.

**Pull request closed without merging**
