### PR TITLE
Fix libmbedtls cipher_wrap.c function pointer assignments

### PR DESCRIPTION
**Pull request by smo4201**
In the mbedtls cipher_wrap.c adjustments in optee_os, there is a wrong function pointer assignment, as the *ctx_clone function and its assignment in mbedtls_cipher_base_t was forgotten for chacha20 and chachapoly ciphers in cipher_wrap.c. The first commit should fix this. 

The optee_os compilation only throws warnings, if those ciphers are enabled in the mbedtls configuration. The second commit enables the chacha20 and chachapoly ciphers for UTAs. I think it would be nice, to have these ciphers supported for TAs, as they are supported by common protocols (TLS 1.3, IPsec, WireGuard, ...).

### CODE REVIEW

**Comment by jforissier** [comment]
Hi @smo4201, thanks for the patches! They look good to me and would suggest only slight changes to the commit subjects/messages:

```
libmbedtls: fix cipher_wrap.c for chacha20 and chachapoly

For chacha20 and chachapoly, the *_ctx_clone() function is missing
and therefore the wrong function pointers are assigned to
.ctx_clone_func and .ctx_free_func when MBEDTLS_CHACHA20_C
or MBEDTLS_CHACHAPOLY_C is enabled.
```
...and:
```
libmbedtls: mbedtls_config_uta.h: enable chacha20 and chachapoly support
```
With that, both commits are:

`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jforissier** [comment]
> I think it would be nice, to have these ciphers supported for TAs, as they are supported by common protocols (TLS 1.3, IPsec, WireGuard, ...).

...and feel free to mention that in the second commit if you want, it's always good to have some context in the commit descriptions.

**Comment by smo4201** [comment]
> Hi @smo4201, thanks for the patches! They look good to me and would suggest only slight changes to the commit subjects/messages:
> 
> ```
> libmbedtls: fix cipher_wrap.c for chacha20 and chachapoly
> 
> For chacha20 and chachapoly, the *_ctx_clone() function is missing
> and therefore the wrong function pointers are assigned to
> .ctx_clone_func and .ctx_free_func when MBEDTLS_CHACHA20_C
> or MBEDTLS_CHACHAPOLY_C is enabled.
> ```
> 
> ...and:
> 
> ```
> libmbedtls: mbedtls_config_uta.h: enable chacha20 and chachapoly support
> ```
> 
> With that, both commits are:
> 
> `Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

Hi @jforissier, 
I changed the commit messages as suggested and updated the PR.

**Comment by smo4201** [comment]
> > I think it would be nice, to have these ciphers supported for TAs, as they are supported by common protocols (TLS 1.3, IPsec, WireGuard, ...).
> 
> ...and feel free to mention that in the second commit if you want, it's always good to have some context in the commit descriptions.

Hi @jforissier, 
Also mentioned the protocols in the commit description for context.

**Pull request merged**
