### PR TITLE
Rsa for 2.5.0

### PR DESCRIPTION
**Pull request by jbech-linaro**
Fixes for the security issues that we discussed a while ago. Note that patches has already been reviewed once before this PR, so that is the reason why you already find that in the patches.
```bash
root@Vexpress:/ xtest -l 15
...
+-----------------------------------------------------
47112 subtests of which 0 failed
78 test cases of which 0 failed
0 test case was skipped
TEE test application done!
root@Vexpress:/ 
```

### CODE REVIEW

**Comment by jforissier** [comment]
Thanks for creating the PR. I have 2 questions:

- Do we have CVE numbers for the security fixes? If we do, the numbers should be in the commit description, but if we don't it shouldn't stop us from merging the patches of course.

- The checkpatch warnings look easy enough to fix (long lines), can you address this please?

**Comment by jbech-linaro** [comment]
> Do we have CVE numbers for the security fixes? If we do, the numbers should be in the commit description, but if we don't it shouldn't stop us from merging the patches of course.

I've requested CVE's using [this](http://iwantacve.org) (it's actually quite a while ago), but I haven't got them yet. Compared to the first time, we got asked to accept a some legal stuff, which Rob Booth approved and I gave the information to them. But checking [this](https://github.com/distributedweaknessfiling/DWF-Legal-Acceptance/tree/master/Terms-Of-Use) page I still cannot find my own email address there. I can try to get hold of the Mitre people, but I don't think we will get any CVE's in time for the release. Instead I suggest that we update out [Security Advisories](https://www.op-tee.org/security-advisories) page instead when we've actually got the CVE's.

> The checkpatch warnings look easy enough to fix (long lines), can you address this please?

Of course, I will fix those.

**Comment by jforissier** [comment]
@jbech-linaro sounds good to me, thanks!

**Comment by jforissier** [comment]
All good, I think you can squash the fixup into the original patch and I'll merge everything.

**Comment by jbech-linaro** [comment]
Squashed, rebased and tag(s) applied (should be) ready for merge! Thanks!

(After rebasing to latest this morning I "Re-tested" with xtest -l 15 on `fe685824  msg_param.h: add `const` qualifier for read-only functions`, but when done I could see another commit has been merged from Etienne).

**Comment by jforissier** [comment]
Merged, thanks.

> when done I could see another commit has been merged from Etienne

It's OK. Now I use the "rebase and merge" button to merge the PRs into master, so rebasing to the very latest is not required.

**Comment by jbech-linaro** [comment]
> It's OK. Now I use the "rebase and merge" button to merge the PRs into master, so rebasing to the very latest is not required.

Thanks Jerome! I did rebase it on Etienne's patch, but I didn't test on his patch! But ... I hardly suspect it will matter. Yeah, the "rebase and merge" is pretty nifty!

**Pull request merged**
