### PR TITLE
MAINTAINERS: remove Victor (Linaro)

### PR DESCRIPTION
**Pull request by jforissier**
Victor is not with Linaro anymore, so remove him from MAINTAINERS.

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
CC @vchong

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by vchong** [comment]
> CC @vchong

Thanks! Hope all is well with everyone!

**Comment by jforissier** [comment]
> > CC @vchong
> 
> Thanks! Hope all is well with everyone!

Yes, thank you, and remember you're still welcome here in case you'd like to comment on some PR :wink:

**Pull request merged**
