### PR TITLE
Update CHANGELOG for 3.16.0

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Update CHANGELOG for 3.16.0 and collect Tested-by tags.

Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome@forissier.org> (vexpress-qemu_armv8a)`

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome@forissier.org> (vexpress-qemu_armv8a, aarch64 host)`

(that is `make check` with the default configuration on an Arm machine)

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome@forissier.org> (hikey-hikey)`

Found an issue with `CFG_CORE_DYN_SHM=n`, fixed by kernel patch: https://lkml.org/lkml/2022/1/13/539

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome@forissier.org> (hikey-hikey960)`

**Comment by igoropaniuk** [comment]
```
I/TC: OP-TEE version: 3.15.0-273-g27f5d377...
...
+-----------------------------------------------------
26212 subtests of which 0 failed
93 test cases of which 0 failed
0 test cases were skipped
TEE test application done!

```

`Tested-by: Igor Opaniuk <igor.opaniuk@gmail.com> (Poplar)`

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)`

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (imx-mx8mqevk)`

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (FVP)`

**Comment by sahilnxp** [comment]
With commit c78b2c660fd377556cd07e029d4c6bab5b61e267

`Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS1012A-RDB)`
`Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS1028A-RDB)`
`Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS1043A-RDB)`
`Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS1046A-RDB)`
`Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS1088A-RDB)`
`Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LS2088A-RDB)`
`Tested-by: Sahil Malhotra <sahil.malhotra@nxp.com> (LX2160A-RDB)`

**Comment by clementfaure** [comment]
With b18c00f4e666423afe51d5980a89c5cfb1e61ec5
```
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6dlsabreauto)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6dlsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6qpsabreauto)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6qsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6sllevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6ulevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6ullevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6ulzevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx6sxsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx7dsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx7ulpevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mmevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mnevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mqevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8mpevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8qmmek)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8qxpmek)
Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8dxlevk)
```

**Comment by clementfaure** [comment]
With the 0fd85dcdb600618119ba7a935dbe6ad589a30b0e
```Tested-by: Clement Faure <clement.faure@nxp.com> (imx-mx8ulpevk)```

**Comment by vesajaaskelainen** [comment]
Xilinx Zynq MPSoC seems to be broken at the moment.

Tested with zcu102 and then our own board and we seem to be getting
```
E/TC:0 0 std_smc_entry:183 Bad arg address 0x803989000
```

We were previously using 3.14.0. We will start bisecting a bit where to breakage happened.

**Comment by jenswi-linaro** [comment]
The log suggests that normal world is using some memory which OP-TEE doesn't recognize.

**Comment by vesajaaskelainen** [comment]
Seems that this commit causes the issue -- if we revert this then zcu102 once again boots:
https://github.com/OP-TEE/optee_os/commit/a7474d1d0b780fc4f8a93883ae3f21320b155998 - plat: zynqmp: register ddr for dyn shm support

**Comment by vesajaaskelainen** [comment]
> Seems that this commit causes the issue -- if we revert this then zcu102 once again boots: [a7474d1](https://github.com/OP-TEE/optee_os/commit/a7474d1d0b780fc4f8a93883ae3f21320b155998) - plat: zynqmp: register ddr for dyn shm support

Created ticket: https://github.com/OP-TEE/optee_os/issues/5144

**Comment by etienne-lms** [comment]
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1, gp pkcs11)`
with and without https://github.com/OP-TEE/optee_os/pull/5100 + https://github.com/OP-TEE/optee_os/pull/5120. I would happily see these 2 in the tag but this is not a must.

**Comment by ricardosalveti** [comment]
With default config + CFG_PKCS11_TA=y CFG_ENABLE_EMBEDDED_TESTS=y:

```
I/TC: OP-TEE version: 3.15.0-322-g9e8852d79 (gcc version 10.2.0 (GCC)) #1 Thu 27 Jan 2022 02:22:58 PM UTC aarch64
+-----------------------------------------------------
29755 subtests of which 0 failed
117 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

`Tested-by: Ricardo Salveti <ricardo@foundries.io> (ZynqMP)
`

**Comment by etienne-lms** [comment]
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (vexpress-qemu_virt, gp pkcs11)`

**Comment by b49020** [comment]
`Tested-by: Sumit Garg <sumit.garg@linaro.org> (Developerbox)`

**Pull request merged**
