### PR TITLE
Update CHANGELOG for 3.20.0

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Update CHANGELOG for 3.20.0 and collect Tested-by tags.

Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by jneuhauser** [comment]
I have tested our supported platforms `stm32mp1-157A_DHCOR_AVENGER96` and `stm32mp1-157C_DHCOM_PDK2` with xtest using the OP-TEE developer setup and all tests passed. The boot logs do not contain any notable errors.

`Tested-by: Johann Neuhauser <jneuhauser@dh-electronics.com> (stm32mp1-157A_DHCOR_AVENGER96)`
`Tested-by: Johann Neuhauser <jneuhauser@dh-electronics.com> (stm32mp1-157C_DHCOM_PDK2)`

**Comment by jbech-linaro** [comment]
```
...
[    0.000000] Linux version 5.17.14-v8 (jyx@tuxedo) (aarch64-linux-gnu-gcc (GNU Toolchain for the A-profile Architecture 10.2-2020.11 (arm-10.16)) 10.2.1 20201103, GNU ld (GNU Toolchain for the A-profile Architecture 10.2-2020.11 (arm-10.16)) 2.35.1.20201028) #1 SMP PREEMPT Tue Jan 10 13:35:30 CET 2023
[    2.537166] optee: revision 3.19 (10fb0d97)
# xtest -l 15
...
46345 subtests of which 0 failed
101 test cases of which 0 failed
0 test cases were skipped
```
`Tested-by: Joakim Bech <joakim.bech@linaro.org>` (RPi3)

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (vexpress-qemu_armv8a)`

With one issue found: #5759.

```
$ repo forall -c 'V=$(git describe --tags --always --dirty); N=$(pwd | sed 's@.*/@@'); printf "%-21s %s\\n" $N $V'
build             	3.19.0-13-gdddfd73
buildroot         	2021.11
edk2              	edk2-stable202202
berkeley-softfloat-3  b64af41
brotli            	v1.0.9-35-gf4153a0
openssl           	OpenSSL_1_1_1j
boringssl         	version_for_cocoapods_9.0-42-g2070f8ad9
krb5              	krb5-1.17.1-final
pyca-cryptography 	2.3-65-g09403100d
brotli            	v1.0.9-35-gf4153a0
oniguruma         	v6.9.4_mark1
jansson           	v2.13.1
cmocka            	cmocka-1.1.5-23-g1cc9cde
linux             	v6.2-rc3-17-gaed8040f4aca
mbedtls           	v2.26.0
optee_benchmark   	3.19.0
optee_client      	3.19.0-11-gdd2d39b
optee_examples    	3.19.0-2-ga98d01e
optee_os          	3.19.0-245-g7c1027426
optee_rust        	v0.2.0-18-g0c7d3a6
optee_test        	3.19.0-16-g5db8ab4
qemu              	v7.2.0
trusted-firmware-a	v2.6
u-boot            	v2021.04
$ env | grep -E '^(GP_PACKAGE|CFG_)'
CFG_TEE_CORE_LOG_LEVEL=2
GP_PACKAGE=/home/jerome/work/TEE_Initial_Configuration-Test_Suite_v2_0_0_2-2017_06_09.7z
CFG_PKCS11_TA=y
CFG_USER_TA_TARGET_pkcs11=ta_arm64
CFG_ENABLE_EMBEDDED_TESTS=y
```

```
+++++ []
Status: PASS (3424 test cases)
Status: keyctl tests successful
+++++ [COMPILE_S_USER=32 CFG_USER_TA_TARGET_pkcs11=ta_arm32]
Status: PASS (3424 test cases)
Status: keyctl tests successful
+++++ [CFG_WITH_PAGER=y]
Status: PASS (3424 test cases)
Status: keyctl tests successful
+++++ [CFG_WITH_PAGER=y COMPILE_S_USER=32 CFG_USER_TA_TARGET_pkcs11=ta_arm32]
Status: PASS (3424 test cases)
Status: keyctl tests successful
+++++ [CFG_RPMB_FS=y CFG_RPMB_WRITE_KEY=y]
Status: PASS (3457 test cases)
Status: keyctl tests successful
+++++ [CFG_REE_FS=n CFG_RPMB_FS=y CFG_RPMB_WRITE_KEY=y]
Status: PASS (3423 test cases)
Status: keyctl tests successful
+++++ [CFG_CORE_DYN_SHM=n]
Status: PASS (3421 test cases)
+++++ [CFG_WITH_PAGER=y CFG_RPMB_FS=y CFG_RPMB_WRITE_KEY=y]
Status: PASS (3457 test cases)
Status: keyctl tests successful
+++++ [CFG_ULIBS_SHARED=y]
Status: PASS (3424 test cases)
Status: keyctl tests successful
+++++ [CFG_ULIBS_SHARED=y CFG_WITH_PAGER=y]
Status: PASS (3424 test cases)
Status: keyctl tests successful
+++++ [CFG_FTRACE_SUPPORT=y CFLAGS_ta_arm32=-pg CFLAGS_ta_arm64=-pg]
Status: PASS (3424 test cases)
Status: keyctl tests successful
+++++ [CFG_LPAE_ADDR_SPACE_BITS=44]
Status: PASS (3424 test cases)
Status: keyctl tests successful
+++++ [CFG_LPAE_ADDR_SPACE_BITS=44 COMPILE_S_USER=32 CFG_USER_TA_TARGET_pkcs11=ta_arm32]
Status: PASS (3424 test cases)
Status: keyctl tests successful
+++++ [CFG_LPAE_ADDR_SPACE_BITS=44 CFG_WITH_PAGER=y]
Status: PASS (3424 test cases)
Status: keyctl tests successful
+++++ [CFG_LPAE_ADDR_SPACE_BITS=44 CFG_WITH_PAGER=y COMPILE_S_USER=32 CFG_USER_TA_TARGET_pkcs11=ta_arm32]
Status: PASS (3424 test cases)
Status: keyctl tests successful
+++++ [CFG_CORE_PREALLOC_EL0_TBLS=y]
Status: PASS (3424 test cases)
Status: keyctl tests successful
+++++ [COMPILER=clang]
Status: PASS (3420 test cases)
Status: keyctl tests successful
+++++ [CFG_CORE_BTI=y CFG_TA_BTI=y CFG_USER_TA_TARGETS=ta_arm64 AARCH64_CROSS_COMPILE=~/x-tools/aarch64-unknown-linux-gnu/bin/aarch64-unknown-linux-gnu-]
Status: PASS (3439 test cases)
Status: keyctl tests successful
+++++ [PAUTH=y]
Status: PASS (3425 test cases)
Status: keyctl tests successful
+++++ [XEN_BOOT=y]
Status: PASS (3424 test cases)
Status: PASS (3426 test cases)
Status: keyctl tests successful
```

**Comment by jenswi-linaro** [comment]
```
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (imx-mx8mqevk)
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Hikey)
```

**Comment by jenswi-linaro** [comment]
```
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)
```

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (RockPi4)`

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (vexpress-qemu_virt)`

**Comment by etienne-lms** [comment]
For 3.20.0-rc1 + (already merged) https://github.com/OP-TEE/optee_os/pull/5760 + https://github.com/OP-TEE/optee_os/pull/5768 :
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1-157C_DK2)`
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1-157C_EV1)`

**Comment by ricardosalveti** [comment]
```
Tested-by: Ricardo Salveti <ricardo@foundries.io> (k3-am64x)
Tested-by: Ricardo Salveti <ricardo@foundries.io> (ZynqMP)
```

**Comment by jenswi-linaro** [comment]
Rebased on master and test tags applied.

**Comment by manorit2001** [comment]
Not gonna come in the commit but the tests were done so..
```
Tested-by: Manorit Chawdhry <m-chawdhry@ti.com> (k3-j721e)
Tested-by: Manorit Chawdhry <m-chawdhry@ti.com> (k3-j784s4)
```

**Pull request merged**
