### PR TITLE
core: riscv: Fix logic of thread_{get/set}_exceptions()

### PR DESCRIPTION
**Pull request by gagachang**
In ARM, the bits in DAIF register are used to mask the interrupts. While in RISC-V, the bits in CSR XIE are used to enable(unmask) corresponding interrupt sources.

To not modify the function of thread_get_exceptions(), we invert the bits after reading the value of CSR XIE, as mask.

To not modify the function of thread_set_exceptions(), we invert the bits in given "exceptions" before writing "exceptions" into CSR XIE. Therefore, the intended masked exception bits will be cleared when we write the final value into CSR XIE to mask those interrupts.

### CODE REVIEW

**Review by etienne-lms — COMMENTED** [review]
`Acked-by: Etienne Carriere <etienne.carriere@foss.st.com>`

**Review by jenswi-linaro — COMMENTED** [review]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
@gagachang please rebase to resolve the conflict and add the Acked-by: tags, thanks!

**Comment by gagachang** [comment]
Hi @jforissier 
I rebased and applied tha tags, thanks!

**Pull request merged**
