### PR TITLE
zynqmp: fix UART1 base for zcu102, zc1751_dc1 and zc1751_dc2 flavors

### PR DESCRIPTION
**Pull request by mimok**
Fix UART1 base address in zcu102 flavor

### CODE REVIEW

**Comment by mimok** [comment]
Subject and commit updated.
I added a link to the zynqmp documentation (but Travis test fails as link is too long).

Flavor zcu102 is actually the same as flavors zcu104 and zcu106 would be.
Can I make a new commit in this pulls request adding these flavors?
By this way my new bb recipes for OP-TEE which handles both platform and flavor would work for any zynqmp board without any additional modification of this repository.

**Comment by jforissier** [comment]
To avoid the checkpatch error, use a Link: tag.
```
Link: [1] (URL here)
```

**Comment by jforissier** [comment]
Better create a new PR for the other boards otherwise the title is misleading.

**Comment by jforissier** [comment]
Link  updated, PR merged. Thanks @mimok.

**Pull request closed without merging**
