### PR TITLE
Overflow macro fixes

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Fixes problem highlighted in https://github.com/OP-TEE/optee_os/pull/2303

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
The `__INTOF_ADD()` and `__INTOF_SUB()` macros can be improved, but this at solves the immediate problem.

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (QEMU)`

Also fixes the issue observed with https://github.com/OP-TEE/optee_os/pull/2298, not surprisingly. Thanks :)

@jenswi-linaro I propose to take commit "core_self_tests.c: add SUB_OVERFLOW() test" in my other PR (https://github.com/OP-TEE/optee_os/pull/2303) so that we can merge this first, then properly refer to the final commit ID in the commit log of each test commit. OK?

**Comment by jenswi-linaro** [comment]
Tags applied.
I don't understand what you're proposing, but I trust it's good. :-)
By the way, I have improved these fallback macros to better deal with mixed types etc. But I think I'll take that in a separate PR to not block anything here.

**Comment by jforissier** [comment]
Sorry for not being clear ;) I meant remove the last commit from this PR. It's OK I'll take the first two only.

**Comment by jforissier** [comment]
Fixes merged.

**Pull request closed without merging**
