### PR TITLE
Documentation: Update ARM Trusted Firmware

### PR DESCRIPTION
**Pull request by oliviermartin**
Update the toolchain version and the ARM Trusted Firmware build flags.

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
I'm wondering if we should synchronize versions of the compilers and flags in this document, as it is hard to maintain, or if we should point to the https://github.com/OP-TEE/build repo, and more specifically https://github.com/OP-TEE/build/blob/master/fvp.mk, as these later ones should be always up-to-date.

@jbech-linaro what do you think?

**Comment by oliviermartin** [comment]
Or maybe just write the toolchain version(s) only once in the top README.md of OP-TEE repository and edit all the other documents to point to this toolchain requirement.

**Comment by jbech-linaro** [comment]
Sorry for the late reply, but in principle I think we should try to stick with the information we have here:
https://github.com/OP-TEE/optee_os#421-get-the-compiler

The only quirk is that we require a few different compilers the one on the URL above is only for compiling optee_os on a 32-bit environment. But again, better to mention all in one place and point to this from other documents.

**Comment by jbech-linaro** [comment]
Hi again,

I've created a patch that applies on top of your (@oliviermartin) two patches that shows how I'd like to update this pull request. You will find the [patch](https://github.com/jbech-linaro/optee_os/commit/6a6726211bfe2dba89c783a73f70723d275db735) on top of [this](https://github.com/jbech-linaro/optee_os/commits/pr597_armtf_doc) branch. If you're OK with this, then please apply my patch on top of yours, then squash and rebase the patches and apply review tags etc.

`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by pascal-brand-st-dev** [comment]
With Joakim's changes:

    Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by pascal-brand-st-dev** [comment]
@oliviermartin Joakim and I got a chat about this docs. Indeed, it looks the docs on how to compile ARM-TF is redundant looking at the instruction in the makefiles of https://github.com/OP-TEE/build, and is a bit out of our scope as ARM-TF is not owned by us.

So we would suggest to simply remove https://github.com/OP-TEE/optee_os/blob/master/documentation/arm_trusted_firmware.md

The proposed changes in https://github.com/OP-TEE/optee_os/blob/master/README.md should be kept.

Sorry for the noise,
Pascal.

**Comment by pascal-brand-st** [comment]
#613 has been merged

**Pull request closed without merging**
