### PR TITLE
Convert README.md to README.rst

### PR DESCRIPTION
**Pull request by d3zd3z**
This is a largely mechanical conversion of README.me to README.rst. I'm not really intending for us to merge this at this point, but I wanted people to have a chance to look at the differences, and give opinions. Unfortunately, the differences are frequent enough that git doesn't try doing a diff (and doesn't consider this a rename).

Some of the advantages of reStructuredText are:
- A slightly cleaner text format, especially when it comes to tables
- Better support for nested constructs
- Auto table of contents generation
- The sphynx tools can convert the whole docs into beautiful web pages or PDFs

It does have some things that are a little awkward about it (if you use named links, the text in the document has to be different if the links point somewhere different).

Thoughts?

### CODE REVIEW

**Comment by jforissier** [comment]
Looked weird to me for a couple of minutes, but in the end I think it's better than Markdown. Automatic ToC generation is a nice feature, too. So I wouldn't mind if we were to convert our `.md` to `.rst`. Would you recommend an editor with preview mode?

**Comment by d3zd3z** [comment]
Re the editor with preview. I haven't really found anything I was happy with for `.md`, and never really searched for `.rst`. The problem was that everything I found ended up not doing the same thing as Github would show. What I ended up doing was just pushing the changes to a branch on github, and viewing that. Rst has a little of an advantage of there primarily being just one implementation of it, even github uses the same code as the standalone rendering tools.

There are a few minor restrictions on `.rst` in Github's preview, for example the auto-toc seems to ignore the depth parameter, and only shows two levels.

The main advantage I find over Markdown is that they seem to have actually thought about how the different aspects interact. Nested lists, with multiple paragraphs on one item (or say a table in the middle of it), although they can get a little messy, do seem to work right.

**Comment by jbech-linaro** [comment]
I'm also OK with going ahead with this. But before merging this patch you would need to rebase again, since there has been some new "README.md" patches since you started this patch.

**Comment by gitfineon** [comment]
`.rst` is not bad, but don't use it if you just want to have auto generated TOCs.
@d3zd3z mentioned some more advantages, but are you gonna use them?

There is a big discussion on adding a AutoGenTOC Feature to GitHub flavored Markdown [1](https://github.com/isaacs/github/issues/215) [2](https://github.com/github/markup/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20TOC)
And it is possible to locally generate a TOC using [gh-md-toc](https://github.com/ekalinin/github-markdown-toc). 

Auto converting `.md` to `.rst` is possible but not without manual fixing. 

A lot of applications highlight or preview markdown files but not restructeredText. I prefer [grip](https://github.com/joeyespo/grip) to get a local html file. But it is not ready to handle `.rst` files ([grip-rst-issue](https://github.com/joeyespo/grip/issues/160)).

RestucturedText ist perfect for collaborative document generation if only a few of them are aware of LaTeX. Example for a perfect `.rst` usecase is [devicetree.org](https://github.com/devicetree-org/devicetree-specification)

**Comment by jbech-linaro** [comment]
@d3zd3z I think we should close this since most of this information has been moved to build.git.

**Comment by d3zd3z** [comment]
Closing as this is out of date now.

**Pull request closed without merging**
