### PR TITLE
Convert configuration variables to CFG_* name

### PR DESCRIPTION
**Pull request by jforissier**
Convert configuration variables to CFG_* name
    
- Rename configuration variables that do not follow the CFG_* convention
- Delete useless -D<VAR> compiler flags
- Slightly reformat mk/conf.mk, add comments
    
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

Note: this is not based on OP-TEE/optee_os master but rather on my previous 'UART cleaning' commit (PR#226) which already renames one variable.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by pascal-brand-st-dev** [comment]
I can't make up my mind with the commit "[Review] Restore use of CFG_TEE_CORE_LOG_LEVEL." 

- One one hand, we got many nasty side-effects around traces and legacy code in the past. As an example, we should at least update optee_test if we want this.
- on the other hand, I understand the point of removing CFG in CFG_TRACE_LEVEL

Can this wait early next week so that I have some advises from STM people?

**Comment by jforissier** [comment]
On Tue, Mar 24, 2015 at 5:11 PM, Pascal Brand (dev) <
notifications@github.com> wrote:

> I can't make up my mind with the commit "[Review] Restore use of
> CFG_TEE_CORE_LOG_LEVEL."
>
>    - One one hand, we got many nasty side-effects around traces and
>    legacy code in the past. As an example, we should at least update
>    optee_test if we want this.
>    - on the other hand, I understand the point of removing CFG in
>    CFG_TRACE_LEVEL
>
> Can this wait early next week so that I have some advises from STM people?
>

Yes, sure.

**Comment by pascal-brand-st-dev** [comment]
@jforissier CFG_TRACE_LEVEL --> TRACE_LEVEL is fine.

May I suggest to have the following commit order:
- UART cleaning (with asc.h could be moved in stm platform)
- CFG_TRACE_LEVEL --> TRACE_LEVEL
- Convert configuration variables to CFG_* name …
- plat-vexpress: delete unused defines

**Comment by jforissier** [comment]
Rebased on top of master with commits in the proper order. @pascal-brand-st-dev  let me know if I should add your R-B tag.

**Pull request merged**
