### PR TITLE
shippable: build stm32mp1-157C_DK2

### PR DESCRIPTION
**Pull request by etienne-lms**
Add build test for platform flavor stm32mp1-157C_DK2 to build stm32mp1
with an embedded DTB.

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

### CODE REVIEW

**Comment by etienne-lms** [comment]
tag applied

**Comment by jforissier** [comment]
I'll take care of the Shippable error. The docker image currently lacks the DT compiler, I will add it.

**Comment by etienne-lms** [comment]
Ok thanks. Good thing this is tested :)

**Comment by jforissier** [comment]
> Ok thanks. Good thing this is tested :)

Yeah :laughing:

The Docker images are updated now, was quite fast to do (a combination of Docker magic voodoo for smart re-builds and me having FTTH internet access!).

There was a small mishap however. We will likely experience a few build timeouts because as I re-built the image, the GCC compiler in Ubuntu 18.04 (the starting point for my Docker images) had been upgraded from 7.4.0 to 7.5.0 (usual OS updates). Using a different compiler makes the whole `ccache` cache invalid so build times increase a lot :cry: I have a hack in place to deal with that, which consists in pushing a reduced `.shippable.yml` to branch [`shippable-cache-create`](https://github.com/OP-TEE/optee_os/tree/shippable-cache-create) which will partially re-fill the cache. Then I'll take care of restarting the timed out PRs when the cache is ready.

**Comment by etienne-lms** [comment]
thanks @jforissier.

**Pull request merged**
