### PR TITLE
Fix ta panic race

### PR DESCRIPTION
**Pull request by jenswi-linaro**
This should fix the issue reported in https://github.com/OP-TEE/optee_os/issues/6226

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
> Having some test cases in `xtest` would be great, but probably not simple since we're talking race conditions here...

Sorry, forgot to make the test PR too. https://github.com/OP-TEE/optee_test/pull/693

**Review by etienne-lms — COMMENTED** [review]
`Acked-by: Etienne Carriere <etienne.carriere@foss.st.com>`  with minor comments.
Commit message for "core: add release_state to struct ts_ops" : s/release/released/
Commit message for "core: fix race in handling TA panic" message: s/where/were/

**Comment by jenswi-linaro** [comment]
Comments addressed and tags applied.

**Comment by jforissier** [comment]
Added Tested-by: tag from https://github.com/OP-TEE/optee_os/issues/6226#issuecomment-1709417774 and merged manually.

**Pull request closed without merging**
