### PR TITLE
TEE Core File Operation Abstraction Layer

### PR DESCRIPTION
**Pull request by jamescfkung**
Tested-by: James Kung <james.kung@linaro.org> (QEMU platform)
Signed-off-by: James Kung <james.kung@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jenswi-linaro** [comment]
What's the rationale behind this change? Is it part of some larger scheme?

**Comment by jamescfkung** [comment]
I would like to implement another set of file operations which can support file encryption/decryption. With the abstraction layer, it can help to support different file system implementation easily.

**Comment by jenswi-linaro** [comment]
OK, thanks.
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Comment by pascal-brand-st** [comment]
Merged manually on top of master

**Pull request closed without merging**
