### PR TITLE
Update CHANGELOG for 3.13.0

### PR DESCRIPTION
**Pull request by ruchi393**
Update CHANGELOG for 3.13.0 and collect Tested-by tags for
the next release.

Signed-off-by: Ruchika Gupta <ruchika.gupta@linaro.org>

### CODE REVIEW

**Comment by jbech-linaro** [comment]
I'm intentionally a bit verbose here and show all commits, snippets of the boot log and the result of xtest itself. This because there is almost always someone having an issue or another with RPi3 even shortly after a release, so this information might ... or might not be valuable.
```
build -- 55b3964 qemu_v8: Update the EDK2 toolchain
buildroot -- e2fba6457b Update for 2021.02
firmware -- f8939644f7b firmware: Bump firmware (but not kernel) to latest master
linux -- fe9d6e09663c tee: optee: Add support for session login client UUID generation
optee_benchmark -- 875be7f main: fix enum argument for init_emitter()
optee_client -- 2c812c5 libckteec: return CKR_CANT_LOCK if mutex fails at lib initialization
optee_examples -- 0607ed4 plugins: example of using the tee-supplicant plugin framework
optee_os -- 409c619b core: stmm: Remove pager constraint on stmm_sp_ops
optee_test -- ebe750b xtest: stats: fix trace on pager stats
trusted-firmware-a -- a04808c16 Merge "Update TF-A version to 2.2" into integration
u-boot -- aac0c29d4b Merge tag 'dm-pull-15jan19' of git://git.denx.de/u-boot-dm
```

```
NOTICE:  BL1: v2.2(debug):v2.2
NOTICE:  BL1: Built : 11:04:08, Apr 13 2021
NOTICE:  rpi3: Detected: Raspberry Pi 3 Model B (1GB, Sony, UK) [0x00a02082]
...
NOTICE:  BL2: v2.2(debug):v2.2
NOTICE:  BL2: Built : 11:04:08, Apr 13 2021
...
NOTICE:  BL31: v2.2(debug):v2.2
NOTICE:  BL31: Built : 11:04:08, Apr 13 2021
...
I/TC: OP-TEE version: 3.12.0-213-g409c619b (gcc version 9.2.1 20191025 (GNU Toolchain for the A-profile Architecture 9.2-2019.12 (arm-9.10))) #1 Tue 13 Apr 2021 09:03:53 AM UTC aarch64
...
U-Boot 2019.01-00093-gaac0c29d4b (Apr 13 2021 - 12:45:11 +0200)
...
[    0.000000] Linux version 5.4.83-v8 (jyx@tuxedo) (gcc version 9.2.1 20191025 (GNU Toolchain for the A-profile Architecture 9.2-2019.12 (arm-9.10))) #1 SMP PREEMPT Tue Apr 13 11:03:52 CEST 2021
[    0.000000] Machine model: Raspberry Pi 3 Model B Rev 1.2
```

```
# xtest -l15
...
+-----------------------------------------------------
45768 subtests of which 0 failed
92 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```
`Tested-by: Joakim Bech <joakim.bech@linaro.org>` (RPi3B)

**Comment by jforissier** [comment]
I have tested on QEMU and QEMUv8 with GP and PKCS#11 (optee_os at commit 02dbcc7e).
- Found https://github.com/OP-TEE/optee_os/issues/4560 and https://github.com/OP-TEE/optee_os/issues/4561.
- Known issues : https://github.com/OP-TEE/optee_os/issues/4324 (the Linux kernel patch is on its way, expected in kernel v5.13) and https://github.com/OP-TEE/optee_os/issues/3899 (minor).

**Comment by jforissier** [comment]
Tested on HiKey960 with GP and PKCS#11 (optee_os commit 756e0b09). The issues I found on QEMU/QEMUv8 are reproducible but no other issues found.

With default config and `CFG_PKCS11_TA=y CFG_ENABLE_EMBEDDED_TESTS=y`:
```
62602 subtests of which 0 failed
2298 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by Emantor** [comment]
Nitrogen6X (imx6q-sabrelite, Kernel 5.11.15)
OP-TEE/optee-os: 203ee23d005b2cec2f21b5de334c5a246be32599
OP-TEE/optee-test:  [5abbcdf](https://github.com/OP-TEE/optee_test/commit/5abbcdf62ec49ca5087fedbfe564270854a096fd)
OP-TEE/optee-client:  [0fe819f](https://github.com/OP-TEE/optee_client/commit/0fe819faf9113d7dd2e904d8cd4af2835b5c50ab")
```
+-----------------------------------------------------
45748 subtests of which 1 failed
92 test cases of which 1 failed
0 test cases were skipped
TEE test application done!
```

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)`

**Comment by jforissier** [comment]
With:
optee_client          3.12.0-27-g7e2063a
optee_os              3.12.0-229-g36905f94
optee_test            3.12.0-23-g6300673

`Tested-by: Jerome Forissier <jerome@forissier.org> (HiKey, GP, PKCS#11)`

**Comment by ruchi393** [comment]
Tag 3.13.0-rc1 has been created on build, optee_benchmark, optee_client, optee_examples, optee_os, optee_test, so please continue with your release testing.

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (imx-mx8mqevk)`

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (FVP)`

**Comment by etienne-lms** [comment]
I see an issue with test gp_40178.
Running `xtest -t gp` once succeeds but gp_40178 fails if `xtest -t gp` is run again. Tested on 32bit plat-stm32mp1.
Once 40178 has failed, running the test again fails in various ways: segfault, signal 11, target dead, even IOCTL error but test successful.
Anyone else facing this issue?

**Comment by jforissier** [comment]
@etienne-lms

> I see an issue with test gp_40178.

Reproducible with QEMUv8. If I run the full test suite, the status is OK although 40178 logs a TEE_IOC_INVOKE error (which does not look right for this test), but if I only run gp_40178 I always get a segfault.

**Comment by jforissier** [comment]
3.13.0-rc1:

`Tested-by: Jerome Forissier <jerome@forissier.org> (QEMUv8, GP, PKCS#11)`

```
+++++ []
Status: PASS (3246 test cases)
+++++ [CFG_WITH_PAGER=y]
Status: PASS (3221 test cases)
+++++ [CFG_RPMB_FS=y CFG_RPMB_WRITE_KEY=y]
Status: PASS (3279 test cases)
+++++ [CFG_REE_FS=n CFG_RPMB_FS=y CFG_RPMB_WRITE_KEY=y]
Status: PASS (3246 test cases)
+++++ [CFG_CORE_DYN_SHM=n]
Status: PASS (3246 test cases)
+++++ [CFG_WITH_PAGER=y CFG_RPMB_FS=y CFG_RPMB_WRITE_KEY=y]
Status: PASS (3254 test cases)
+++++ [CFG_ULIBS_SHARED=y]
Status: PASS (3246 test cases)
+++++ [CFG_ULIBS_SHARED=y CFG_WITH_PAGER=y]
Status: PASS (3221 test cases)
+++++ [CFG_FTRACE_SUPPORT=y CFLAGS_ta_arm32=-pg CFLAGS_ta_arm64=-pg]
Status: PASS (3246 test cases)
```

**Comment by jforissier** [comment]
3.13.0-rc1:

`Tested-by: Jerome Forissier <jerome@forissier.org> (QEMU, GP, PKCS#11)`

```
+++++ []
Status: PASS (3246 test cases)
+++++ [CFG_WITH_PAGER=y]
Status: PASS (3221 test cases)
+++++ [CFG_RPMB_FS=y CFG_RPMB_WRITE_KEY=y]
Status: PASS (3279 test cases)
+++++ [CFG_REE_FS=n CFG_RPMB_FS=y CFG_RPMB_WRITE_KEY=y]
Status: PASS (3246 test cases)
+++++ [CFG_CORE_DYN_SHM=n]
Status: PASS (3246 test cases)
+++++ [CFG_WITH_PAGER=y CFG_RPMB_FS=y CFG_RPMB_WRITE_KEY=y]
Status: PASS (3254 test cases)
+++++ [CFG_ULIBS_SHARED=y]
Status: PASS (3246 test cases)
+++++ [CFG_ULIBS_SHARED=y CFG_WITH_PAGER=y]
Status: PASS (3221 test cases)
+++++ [CFG_FTRACE_SUPPORT=y CFLAGS_ta_arm32=-pg CFLAGS_ta_arm64=-pg]
Status: PASS (3246 test cases)
```

**Comment by ricardosalveti** [comment]
```
I/TC: OP-TEE version: 3.13.0-rc1-dev (gcc version 10.2.0 (GCC)) #1 Thu 01 Jan 1970 12:00:00 AM UTC aarch64

+-----------------------------------------------------
25796 subtests of which 0 failed
92 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

`Tested-by: Ricardo Salveti <ricardo@foundries.io> (ZynqMP)
`

**Comment by lorc** [comment]
For `3.13-rc1` (with #4579) :

`Tested-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com> (RCAR M3)`
`Tested-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com> (RCAR M3/virtualization)`

**Comment by etienne-lms** [comment]
3.13.0-rc1 + the already merged commits in optee_os, optee_test, build & manifest:
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1-ev1/dk2, gp, pkcs11)`

**Comment by clementfaure** [comment]
Hello,
For ```3.13.0-rc1```,
```
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6dlsabreauto)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6dlsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6qpsabreauto)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6sllevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6ulevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6ullevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx6ulzevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx7dsabresd)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx7ulpevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx8mmevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx8mnevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx8mqevk)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx8qmmek)
Tested-by: Clement Faure <clement.faure@nxp.com> (mx8qxpmek)
```

**Comment by Emantor** [comment]
With OP-TEE/optee_client#268
Nitrogen6X (imx6q-sabrelite, Kernel 5.11.15)
OP-TEE/optee-os: 203ee23d005b2cec2f21b5de334c5a246be32599
OP-TEE/optee-test:  [5abbcdf](https://github.com/OP-TEE/optee_test/commit/5abbcdf62ec49ca5087fedbfe564270854a096fd)
OP-TEE/optee-client:  [0fe819f](https://github.com/OP-TEE/optee_client/commit/0fe819faf9113d7dd2e904d8cd4af2835b5c50ab")
```
+-----------------------------------------------------
45761 subtests of which 0 failed
92 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by jforissier** [comment]
With:
optee_client          3.13.0-rc1
optee_os              3.13.0-rc1-3-gd269f2ec
optee_test            3.13.0-rc1-1-g159cd4a

`Tested-by: Jerome Forissier <jerome@forissier.org> (HiKey960, GP, PKCS#11)`

**Comment by igoropaniuk** [comment]
optee-os: `e687029d2("plat: rcar: use new register_ddr() macro")`
optee-client: `7e2063acb("libckteec: Add signing support for ECDSA")`
optee-test: `159cd4ab("gp: disable test ce-7b-17 (gp_40178)")`
optee-examples: `0607ed407("plugins: example of using the tee-supplicant plugin framework")`

`Tested-by: Igor Opaniuk <igor.opaniuk@foundries.io> (Poplar)`


```
+-----------------------------------------------------
25838 subtests of which 0 failed
93 test cases of which 0 failed
0 test cases were skipped
TEE test application done!

```

**Pull request merged**
