### PR TITLE
Juno crypto

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jbech-linaro** [comment]
More spookiness with Travis?

**Comment by jenswi-linaro** [comment]
@jbech-linaro looks like it.

**Comment by jenswi-linaro** [comment]
Tags applied

**Comment by jforissier** [comment]
@jenswi-linaro @jbech-linaro I've seen this failure pattern occasionally, it looks like QEMU just silently exists, hence closing the stdin/stdout pipes with Expect. Not enough memory maybe?

**Comment by jenswi-linaro** [comment]
Adds missing 
```
ifeq ($(CFG_CRYPTO_SHA256_ARM64_CE),y)
$(call force,CFG_WITH_VFP,y)
endif
```

**Comment by jenswi-linaro** [comment]
@jforissier Yes that could be it.

**Pull request merged**
