### PR TITLE
[RFC] Scall layer

### PR DESCRIPTION
**Pull request by jenswi-linaro**
In response to https://github.com/OP-TEE/optee_os/pull/5700#issuecomment-1357454035 here's an attempt to add a generic scall layer to handle syscall routing.

### CODE REVIEW

**Comment by maroueneboubakri** [comment]
Updated [PR#5714](https://github.com/OP-TEE/optee_os/pull/5714) to use `scall`.

**Review by etienne-lms — COMMENTED** [review]
Minor issues only. `Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>` once addressed.

**Comment by maroueneboubakri** [comment]
> Comments addressed, tags applied.

@jenswi-linaro  core/kernel/scall.c still has arm.h included.

**Comment by jenswi-linaro** [comment]
> > Comments addressed, tags applied.
> 
> @jenswi-linaro core/kernel/scall.c still has arm.h included.

Thanks, fixed.

**Comment by jforissier** [comment]
LGTM too.

`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tag applied.

**Comment by jenswi-linaro** [comment]
Tag applied.

**Comment by jforissier** [comment]
@jenswi-linaro would you like this merged for 3.20.0?

**Comment by jenswi-linaro** [comment]
Please wait with this until after the release.

**Comment by jenswi-linaro** [comment]
Ready to merge?

**Comment by jforissier** [comment]
> Ready to merge?

I think so, but perhaps @maroueneboubakri has something to say?

**Comment by maroueneboubakri** [comment]
@jforissier nothing to add.

**Comment by jforissier** [comment]
@maroueneboubakri OK then I will merge this in a moment. If you want to give an Acked-by: or Reviewed-by: please do so, but no obligation.

**Comment by maroueneboubakri** [comment]
> @maroueneboubakri OK then I will merge this in a moment. If you want to give an Acked-by: or Reviewed-by: please do so, but no obligation.

That's fine @jforissier thank you !

**Pull request merged**
