### PR TITLE
Misc

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Preparing for 64bit

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
I think that `-DARM32=1` in platform_config.h is not possible as this file defines values for both the core and the user_ta.

Then I would say it is preferable to not use `-DARM32=1` at all. But I cannot figure out any good solution to avoid it :(

**Comment by jenswi-linaro** [comment]
Should we keep it as it is now? Or something different?

**Comment by jforissier** [comment]
Is this something you could derive from a compiler-defined macro perhaps? Such as `__aarch64__`.

**Comment by jenswi-linaro** [comment]
Yes perhaps, but those defines seems a bit compiler specific. I would prefer supplying the `-DARM32=1` in some CPPFLAGS because it's very straight forward. As long as it works, I don't care which way we take.

I'm using another some other similar flags too, `-DILP32=1` and `-DLP64=1`, but those should be easier to get rid of if it's a problem.

**Comment by jforissier** [comment]
Sure those #defines may be more or less compiler-specific, but I think we can assume we always use GCC which basically solves the problem. Regarding `-DILP32=1` and `-DLP64=`, again it would be redundant:
```
$ aarch64-linux-gnu-gcc -dM -E - </dev/null | grep -e ILP32 -e LP64 -e aarch64
#define __LP64__ 1
#define __aarch64__ 1
#define _LP64 1
$ aarch64-linux-gnu-gcc -mabi=ilp32 -dM -E - </dev/null | grep -e ILP32 -e LP64 -e aarch64
#define __aarch64__ 1
#define __ILP32__ 1
#define _ILP32 1
$ arm-linux-gnueabihf-gcc -dM -E - </dev/null | grep -e ILP32 -e LP64 -e aarch64
$ 
```

**Comment by pascal-brand-st-dev** [comment]
Should we keep it as it is now? Or something different?
I think that as of now does not work because platform_flags.mk is a common configuration for a given platform. So you cannot distinguish core and user_ta differences in this file. What would be ARM32 value if we want to compile the core in arm64 and the user_ta in arm32?
Or did I miss something?

I am not in favor of using non-standard flags from the compiler.

Looking at the modifications, it looks like it is used only in core files. Could not we use CFG_ARM32_core?... and see later if we need such a define in the user_ta?

**Comment by jenswi-linaro** [comment]
I have one solution in plat-vexpress/{conf.mk,platform_flags.mk}. It's a bit like:
```
arm32-platform-cppflags += -DARM32=1 -DILP32=1
arm64-platform-cppflags += -DARM64=1 -DLP64=1

ifeq ($(CFG_ARM64_core),y)
core-platform-cppflags += $(arm64-platform-cppflags)
else
core-platform-cppflags += $(arm32-platform-cppflags)
endif

user_ta-platform-cppflags += $(arm32-platform-cppflags)
```

**Comment by jenswi-linaro** [comment]
@jforissier, with your example we can detect the presence and absence of ARM64, but how do we detect the presence of ARM32? Consider when we're compiling for some other target than ARM.

**Comment by pascal-brand-st-dev** [comment]
+1 with the proposed solution.

**Comment by jforissier** [comment]
@jenswi-linaro not sure, probably `__ARM_ARCH == 7`. Linux seems to be using `__LINUX_ARM_ARCH__` which is a re-define of `__ARM_ARCH`. As far as I can tell, when this is define you are compiling for some variant of 32-bit ARM.

**Comment by jenswi-linaro** [comment]
@pascal-brand-st-dev, which did you +1, my proposal (which already is included in the PR) or Jeromes?

@jforissier, OK so we can basically do it either way. I guess we should have the generated `conf.h` to pull in some suitable .h if we go with your idea.

**Comment by jforissier** [comment]
On Tue, Mar 24, 2015 at 3:35 PM, Jens Wiklander <notifications@github.com>
wrote:

> @pascal-brand-st-dev <https://github.com/pascal-brand-st-dev>, which did
> you +1, my proposal (which already is included in the PR) or Jeromes?
>
> @jforissier <https://github.com/jforissier>, OK so we can basically do it
> either way. I guess we should have the generated conf.h to pull in some
> suitable .h if we go with your idea.
>
What .h? Can't you just replace #ifdef ARM32 with #if (__ARM_ARCH == 7)?

**Comment by jenswi-linaro** [comment]
It's possible but a bit messy, compare
`#if defined(__ARM_ARCH) && (__ARM_ARCH == 7)`
with
`#ifdef ARM32`
There's currently 27 places where this is needed.

**Comment by jforissier** [comment]
On Tue, Mar 24, 2015 at 4:32 PM, Jens Wiklander <notifications@github.com>
wrote:

> It's possible but a bit messy, compare
> #if defined(__ARM_ARCH) && (__ARM_ARCH == 7)
> with
> #ifdef ARM32
> There's currently 27 places where this is needed.
>
Mmm... right. Then I guess it would be  reasonable to have this in some
header file:

```
#if defined(__ARM_ARCH) && (__ARM_ARCH == 7)
#ifndef ARM32
#define ARM32
#endif
#endif
```

In lib/libutils/ext/include/compiler.h maybe? But it would pollute the
namespace of user TAs. We don't have a location to put include files that
are common to user and kernel code, but not specific to a library, do we?
What about creating $(SRCDIR)/include/arch.h and using it via -include?

**Comment by pascal-brand-st-dev** [comment]
@pascal-brand-st-dev, which did you +1, my proposal
    (which already is included in the PR) or Jeromes?

The one that is already in master (ifeq ($(CFG_ARM64_core),y) ...)
But is it possible to have it in common parts instead of conf.mk / platform_flags.mk? That would enable to set only once that we compile for "32 or 64" the "core or user_ta", as single time when setting the CFG_ARM32_core... and to derive automatically the other flags.

**Comment by jenswi-linaro** [comment]
OK, I'll fix.

**Comment by jenswi-linaro** [comment]
Moved:
```
ifeq ($(CFG_ARM64_xxx),y)
core-platform-cppflags += -DARM64=1
endif
ifeq ($(CFG_ARM32_xxx),y)
core-platform-cppflags += -DARM32=1
endif
```
into ta/arch/arm32/arm32.mk and core/arch/arm32/arm32.mk

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>
    Tested-by: Pascal Brand <pascal.brand@linaro.org> (STM platform)

**Comment by jenswi-linaro** [comment]
Rebased and tags applied.

**Pull request merged**
