### PR TITLE
ree_fs_truncate() sync

### PR DESCRIPTION
**Pull request by jforissier**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
Needs more investigation, it seems that the new size (new meta-data) is indeed written to disk but for some reason when the object is re-open, the wrong header index is used and the previous header is read (hence the older size is assumed).

**Comment by jenswi-linaro** [comment]
Please add https://github.com/jenswi-linaro/optee_os/commit/430eaf3b7cb72434b0220392e86cc9b2a4070afc

It fixes one error. I'm working on the remaining error.

**Comment by jenswi-linaro** [comment]
Please add https://github.com/jenswi-linaro/optee_os/commit/70ae450bfc9e29afdb280c0045ecd1dba1a9fcc9

It fixes the remaining error.

**Comment by jforissier** [comment]
Thanks @jenswi-linaro, works fine now.

**Comment by kevin-peng-hao** [comment]
Hi guys, with the xtest patch I provided in #2094, I got open error after close:

```
* regression_6007 Test TEE_TruncateObjectData
o regression_6007.1 Storage id: 00000001
o regression_6007.1.1 Test truncate file length
/media/kevinp/data_kevinp/kevinp_backup/workspace/op-tee/optee_test/host/xtest/regression_6000.c:493: fs_open(&sess, file_01, sizeof(file_01), 0x00000002 | 0x00000001 | 0x00000004, &obS
  regression_6007.1.1 FAILED
o regression_6007.1.2 Test extend file length
/media/kevinp/data_kevinp/kevinp_backup/workspace/op-tee/optee_test/host/xtest/regression_6000.c:565: fs_open(&sess, file_01, sizeof(file_01), 0x00000002 | 0x00000001 | 0x00000004, &obS
  regression_6007.1.2 FAILED
```

**Pull request merged**
