### PR TITLE
Update CHANGELOG.md for 3.1.0

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

This pull request is used to collect `Tested-by` tags for the `3.1.0` release

### CODE REVIEW

**Comment by lorc** [comment]
Hi @jenswi-linaro,

When release is scheduled? I.e. how much time we have to test it?

**Comment by jforissier** [comment]
Commit 628a9a1 ("ltc: ctr: improve performance") causes a regression in xtest 9159 (GP test) on HiKey960 32 bits. I'm continuing tests with this commit reverted.

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)`

**Comment by jforissier** [comment]
3.1.0-rc1 with commit 628a9a1 ("ltc: ctr: improve performance") reverted:

`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey960)`

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (FVP)`

**Comment by nodeax** [comment]
`Tested-by: Akshay Bhat <akshay.bhat@timesys.com> (Atmel SAM)`

```
# xtest
15787 subtests of which 0 failed
66 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```

**Comment by vchong** [comment]
3.1.0-rc1 with 2018-02-21 tee shm patches in https://android-git.linaro.org/kernel/hikey-linaro.git/log/?h=android-hikey-linaro-4.9&qt=grep&q=victor.chong reverted:

`Tested-by: Victor Chong <victor.chong@linaro.org> (HiKey AOSP)`

**Comment by igoropaniuk** [comment]
`Tested-by: Igor Opaniuk <igor.opaniuk@linaro.org> (RPi3)`

```
# xtest -l 15
+-----------------------------------------------------
35730 subtests of which 0 failed
66 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```

**Comment by kevin-peng-hao** [comment]
`Tested-by: Kevin Peng <kevinp@marvell.com> (Armada 7K, 8K, 3700)`

**Comment by etienne-lms** [comment]
for rc1: `Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (b2260/b2120, GP)`

**Comment by MrVan** [comment]
`Tested-by: Peng Fan <peng.fan@nxp.com> (mx6qsabresd mx6ul/ullevk mx7dsabresd)`

```
#xtest
15815 subtests of which 0 failed
66 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```

**Comment by jforissier** [comment]
Merged manually to discard the unwanted SDP commit (https://github.com/OP-TEE/optee_os/pull/2250#issuecomment-381127582).

@jenswi-linaro thanks for dealing with this during my vacations ;-)

**Pull request closed without merging**
