### PR TITLE
Misc small patches

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Review by jforissier — APPROVED** [review]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jforissier** [comment]
Preferably with `s/enough ram/enough RAM/` in the second commit

**Review by etienne-lms — COMMENTED** [review]
`Reviewed-by: Etienne Carriere <etienne.carriere@foss.st.com>`

**Comment by jenswi-linaro** [comment]
Tags applied.

**Pull request merged**
