### PR TITLE
tee.bin partitioning

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jforissier** [comment]
It looks like this breaks the 64-bit pager on HiKey (32 bits is OK though).
```
# HEAD = this PR [f2f628b]: panic

INFO:    TEE-CORE: No NSEC DDR memory area defined
INFO:    TEE-CORE:
INFO:    TEE-CORE: Pager is enabled. Hashes: 1728 bytes
ERROR:   [0x0] TEE-CORE:init_runtime:263: Hash failed for page 0 at 0x3b600000: res 0xffff000f
ERROR:   [0x0] TEE-CORE: Panic at core/arch/arm/kernel/generic_boot.c:264 <init_runtime>
ERROR:   [0x0] TEE-CORE: pc  0x000000003f0067e8

# HEAD~3: OK

INFO:    TEE-CORE: No NSEC DDR memory area defined
INFO:    TEE-CORE:
INFO:    TEE-CORE: Pager is enabled. Hashes: 1696 bytes
INFO:    TEE-CORE: OP-TEE version: 2.4.0-170-g0d6624c #2 Mon Jun 19 13:53:16 UTC 2017 aarch64
INFO:    TEE-CORE: Shared memory address range: 3dc00000, 3f000000
INFO:    TEE-CORE: Initialized
...
```

I'll take a closer look.

**Comment by jenswi-linaro** [comment]
Found the problem, a fix is added in this PR.

**Comment by jforissier** [comment]
Good catch, problem fixed indeed.

`Tested-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jforissier** [comment]
In "core: reduce init size", I suggest `s/LTC/LibTomCrypt/`, because it's not obvious why `__wq_rpc()` would call into that library, so it's better to avoid any doubt.
Anyway:
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tags applied, commit message updated as suggested.

**Pull request merged**
