### PR TITLE
Fix Clang12 warnings

### PR DESCRIPTION
**Pull request by jforissier**

### CODE REVIEW

**Review by etienne-lms — COMMENTED** [review]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by jenswi-linaro** [comment]
Any plans to upstream the "libmbedtls: address Clang 12 warning" commit? If not, perhaps it better to silent the warning for that file.

**Comment by jforissier** [comment]
> Any plans to upstream the "libmbedtls: address Clang 12 warning" commit? If not, perhaps it better to silent the warning for that file.

That's a good question, and in fact the issue has been fixed in a different way upstream: https://github.com/ARMmbed/mbedtls/commit/962e4ee4a6b3bc2f9a116358973fa7f991f60c65

I will cherry-pick that patch instead.

**Comment by jenswi-linaro** [comment]
> I will cherry-pick that patch instead.

With that done:
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
The Travis failure is a checkpatch complaint about an upstream patch so I am ignoring it. I am also not applying Review tags on upstream patches -- just adding my Sob with a reference to the upstream patch SHA1.

**Pull request merged**
