### PR TITLE
core: fix CFG_CORE_UNMAP_CORE_AT_EL0=y for non-default CFG_LPAE_ADDR_…

### PR DESCRIPTION
**Pull request by jenswi-linaro**
…SPACE_SIZE

Prior to this patch CORE_MMU_L1_TBL_OFFSET was calculated without taking
CFG_LPAE_ADDR_SPACE_SIZE into account. This leads to a
COMPILE_TIME_ASSERT() in case CFG_LPAE_ADDR_SPACE_SIZE is assigned
anything but (1ull << 32). Fix this by addign CFG_LPAE_ADDR_SPACE_SIZE
in the expression.

Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
Perhaps `CFG_LPAE_ADDR_SPACE_SIZE` should be deprecated and replaced by `CFG_LPAE_ADDR_SPACE_BITS` first. That would be easier to use, and avoid the issue found by Shippable.

**Comment by jenswi-linaro** [comment]
> Perhaps `CFG_LPAE_ADDR_SPACE_SIZE` should be deprecated and replaced by `CFG_LPAE_ADDR_SPACE_BITS` first. That would be easier to use, and avoid the issue found by Shippable.

Good idea. By deprecated you mean that it's replaced immediately?

**Comment by jforissier** [comment]
Yes, "deprecated" is not the right word since it would be a bit hard and pointless to keep compatibility. It should be OK to simply error out if the old config is set.

**Comment by jenswi-linaro** [comment]
Makes sense, I'll add such a patch here.

**Comment by ruchi393** [comment]
Minor  - In commit message : %s/addign/adding

Reviewed-by: Ruchika Gupta <ruchika.gupta@linaro.org>

**Comment by jenswi-linaro** [comment]
Comment addressed, tag applied.

**Pull request merged**
