### PR TITLE
Upgrade libtomcrypt to 1.18.2 branch develop 2022-09-13

### PR DESCRIPTION
**Pull request by jforissier**
Note: this PR targets a new import branch: https://github.com/OP-TEE/optee_os/tree/import/libtomcrypt-1.18.2-develop-20220913

Upgrade LibTomCrypt to the latest version. The steps I followed:
- Remove all files under `core/lib/libtomcrypt/src`
-  Import all files from upstream at the same place
- Cherry-pick all our local changes from the current import branch (https://github.com/OP-TEE/optee_os/commits/import/libtomcrypt-1.18.2-develop-20180819) and master
- Add commit "core: ltc: import sub.mk files from master and update" to restore the build files and adapt them to the new version
- Add two commits to fix build issues ("core: ltc: add missing <string_ext.h>" and "libtomcrypt: define LTC_MPI at the same time as LTC_DER")
- Fix a bug in the DSA signing code uncovered by a stricter check in the newer LTC ("core: ltc: fix .qord value in DSA sign and verify")

I expect a failure in the Rust check due to https://github.com/apache/incubator-teaclave-trustzone-sdk/pull/93.

### CODE REVIEW

**Review by etienne-lms — COMMENTED** [review]
Armv8 crypto extension (sha1, sh256, aes) impelmentations are duplicated files between existing (and built) _core/arch/arm/crypto/_ sources and sources added in LTC source tree (but not build with this series). Note many fixup commits in this series affect the later (LTC files).
_aes_armv8a_ce.c_, _aes_modes_armv8a_ce_a32.S_ and _aes_modes_armv8a_ce_a64.S_
from _core/lib/libtomcrypt/src/ciphers/aes/_, _core/lib/libtomcrypt/src/hashes/sha2/_, _core/lib/libtomcrypt/src/hashes/_.

For the first commits in the series, those without a well prefixed commit header line, maybe add such, e.g; `core: ltc:`?

No other comment.

**Comment by jforissier** [comment]
@etienne-lms good catch! The accelerated crypto files should not be under `core/lib/libtomcrypt/` anymore, they have been moved long ago. It looks like they were added back by mistake in branch `import/libtomcrypt-1.18.2-develop-20180819` already and thus I cherry-picked them here... I'll fix that.

**Comment by jenswi-linaro** [comment]
Would it make sense to identify patches to try to upstream?

**Comment by etienne-lms** [comment]
LGTM.

Checkpatch complains on commit message for commit "libtomcrypt: tomcrypt_private.h: add HASH_PROCESS_NBLOCKS".
The referenced commit could be de51851c5844 ("arm64: SHA-1 using ARMv8-A cryptographic extensions") that first introduced `HASH_PROCESS_NBLOCKS()` macro.

**Comment by jenswi-linaro** [comment]
Why is "libtomcrypt: apply BSD-2-Clause license" needed? Is an "Unlicense" license only a problem?

**Comment by jenswi-linaro** [comment]
In "core: ltc: add custom DH key generation function dh_make_key()" you could give some more details on the origin of `dh_make_key()`. It looks like this function was part of the initial OP-TEE commit.

**Comment by jenswi-linaro** [comment]
For the commits:
- libtomcrypt: tomcrypt_private.h: add HASH_PROCESS_NBLOCKS
- libtomcrypt: implement zeromem() with memzero_explicit()
- core: ltc: tomcrypt_custom.h: OP-TEE thread support
- core: ltc: fix 'switch case misses default'
- core: ltc: make key in accel_ecb_encrypt() and accel_ecb_decrypt() const
- core: ltc: add SM2 curve parameters
- core: ltc: import sub.mk files from master and update
- core: ltc: add missing <string_ext.h>
- libtomcrypt: define LTC_MPI at the same time as LTC_DER
- core: ltc: fix .qord value in DSA sign and verify
- ci: rust: apply upstream patch to fix failure in authentication-rs
 
Please apply:
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
> Why is "libtomcrypt: apply BSD-2-Clause license" needed? Is an "Unlicense" license only a problem?

Well you're right, it seems we could do without it. Let's see what we have:

```
(18) 731392162 Jerome Forissier libtomcrypt: define LTC_MPI at the same time as LTC_DER
(17) 80bc631fe Jerome Forissier core: ltc: import sub.mk files from master and update
(16) 3549ef81b Sohaib ul Hassan core: libtomcrypt: Remove prng_state* NULL pointer check from x25519_make_key()
(15) a6a77ae41 ycaibb core: ltc: fix missing mutex unlock
(14) 7f81781b4 Jerome Forissier core: ltc: add SM2 curve parameters
(13) 0ed547e08 Jerome Forissier core: ltc: make key in accel_ecb_encrypt() and accel_ecb_decrypt() const
(12) 6ededaa24 Jerome Forissier core: ltc: fix 'switch case misses default'
(11) 66b16576e Jerome Forissier core: ltc: add custom DH key generation function dh_make_key()
(10) afbc6a029 Jerome Forissier core: ltc: tomcrypt_custom.h: OP-TEE thread support
 (9) b3393b81c Jerome Forissier libtomcrypt: implement zeromem() with memzero_explicit()
 (8) 493d42cf0 Jens Wiklander core: LTC use only _CFG_CORE_LTC_ variables
 (7) 8c69618f4 Jerome Forissier libtomcrypt: apply BSD-2-Clause license
 (6) 9a08bc040 Jens Wiklander LTC: add GHASH acceleration
 (5) 3c00f89b1 Jens Wiklander ltc: make cipher_descriptor a pointer to descriptors
 (4) d6cdab20d Jens Wiklander ltc: make hash_descriptor a pointer to descriptors
 (3) 66e2f51f6 Jens Wiklander ltc: make prng_descriptor a pointer to descriptors
 (2) 4e11f1470 Jerome Forissier libtomcrypt: tomcrypt_private.h: add HASH_PROCESS_NBLOCKS
 (1) 4f6b32962 Pascal Brand ECC: optimize the pool of temporary variables
     955eced29 Jerome Forissier Import LibTomCrypt v1.18.2 branch "develop" (Sep 13, 2022)
     3717d7641 Jerome Forissier Remove LibTomCrypt
```
(1) was contributed 7 years ago under the original license; (15) and (16) are trivial fixes and all other commits are either from you or me, so if we both agree I can drop "libtomcrypt: apply BSD-2-Clause license".

**Comment by jforissier** [comment]
> In "core: ltc: add custom DH key generation function dh_make_key()" you could give some more details on the origin of `dh_make_key()`. It looks like this function was part of the initial OP-TEE commit.

Yes, part of the initial commit, LTC code modified to add the `xbits` rgument. I will update the commit description.

**Comment by jenswi-linaro** [comment]
> (1) was contributed 7 years ago under the original license; (15) and (16) are trivial fixes and all other commits are either from you or me, so if we both agree I can drop "libtomcrypt: apply BSD-2-Clause license".

Sounds good to me.

**Comment by jforissier** [comment]
@etienne-lms @jenswi-linaro thanks for your feedback. Hopefully next time will be easier if we manage to upstream more code and I also plan to consolidate the multiple `sub.mk` under `libtomcrypt/src/` into `libtomcrypt/sub.mk`, similar to what we have for MBed TLS.

**Pull request merged**
