### PR TITLE
Misc small patches from PR #3036

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by etienne-lms** [comment]
`Acked-by: Etienne Carriere <etienne.carriere@linaro.org>`:
* commit "core: vm_set_prot(): skip prot bits already set"
* commit "ta: link_shlib.mk: set linker max-page-size to 4K" 
(with typo to fix in commit message: s/max-pag-size/max-page-size/)

`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`:
* commit "core: handle_db: add ptr_destructor argument"
* commit "core: pager: check utc->areas before assigning tables"
* commit "Move reg_pair_*() to util.h"
* commit "core: provide struct user_ta_store_ops in public .h file"

`Acked-by: Etienne Carriere <etienne.carriere@linaro.org>`:
* commit "mk/lib.mk: link user libraries with 4K page size"

**Comment by jforissier** [comment]
About "ta: link_shlib.mk: set linker max-page-size to 4K": looks similar to ce0bad5535aa ("ta: link.mk: set linker max-page-size to 4K") except that there is no `ta_head` in a shared library, so what is the purpose? Is it still to save space by reducing alignment constraints? A comment and/or a reference to the other might be helpful.

How about squashing "mk/lib.mk: link user libraries with 4K page size" into the same commit? (same purpose obvioulsy).

**Comment by jenswi-linaro** [comment]
I'll squash and update the commit messages of "ta: link_shlib.mk: set linker max-page-size to 4K" and "mk/lib.mk: link user libraries with 4K page size" to make it more clear. The reason they where separate commits is that I discovered the problems at different stages.

**Comment by jenswi-linaro** [comment]
Tags applied

**Pull request merged**
