### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Fix arm64 build error and update travis.yml to build for arm64

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Sorry about the spamming here, I'm trying to get an aarch64 compiler into travis.

**Comment by jforissier** [comment]
No problem, but do you know that you can set up your own CI loop on https://travis-ci.org/? Then each time you push something to your GitHub repo, it will trigger a build.

**Comment by jenswi-linaro** [comment]
Thanks, I'll try that.

**Comment by jenswi-linaro** [comment]
I'm closing this now, I'll create a new PR when I have something that works.

**Pull request closed without merging**
