### PR TITLE
TEE_Malloc cleanup

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by etienne-lms** [comment]
Minor comment on 1st commit comment: s/was/were/ in:
 ` ... TEE_Malloc(), TEE_Realloc() and TEE_Free() was using ...`.

This change gets rid of the `CFG_TEE_CORE_USER_MEM_DEBUG` feature. It is fine (`CFG_TEE_CORE_MALLOC_DEBUG` enables the kind of debug support). Can you remove `CFG_TEE_CORE_USER_MEM_DEBUG` from **mk/confg.mk**?

**Comment by jenswi-linaro** [comment]
I'll update the commit message later when squashing etc.

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by etienne-lms** [comment]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by jenswi-linaro** [comment]
Squashed and tags applied

**Pull request merged**
