### PR TITLE
virt: add workaround for reading symbols from ".data" section

### PR DESCRIPTION
**Pull request by lorc**
configure_guest_prtn_mem() function uses certain linker-generated
symbol values to locate .bss and .data sections. Problem is that
compiler might (and GCC 8.x does) store values of those symbols
in the .data section itself.

As configure_guest_prtn_mem() maps uninitialized memory to the .data
section, there is a chance, that later it will try to read .data
address from that uninitialized memory. To workaround this, we
explicitly store those symbol values in .nex_data section.

Reported-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>
Signed-off-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
I'm a bit surprised that those values are stored in `.data`, I was expecting the literal pool instead inside `.text`. How well is this analyzed? Have you looked in the the object file `virtualization.o` and seen that this is what really is happening?

**Comment by jforissier** [comment]
@jenswi-linaro why would these symbols be in a literal pool? They are explicitly defined in the `.data` and `.bss` sections in the linker script `core/arch/arm/kernel/kern.ld.S`:

```
grep -E -w "(__data_start|__data_end)" out/arm/core/tee.dmp
0e16c200 l       .bss	00000000 __data_end
0e16c000 g       .data	00000000 __data_start
```

**Comment by jenswi-linaro** [comment]
I didn't mean the symbols, the value which is the address of the symbol.
For instance `ldr r0,=__data_start)` would result in a value in the literal pool which then would be loaded into `r0`.

**Comment by lorc** [comment]
@jenswi-linaro, yes, expected the same. But look at this:

```
        memcpy(__data_start,
 284:   aa0003e1        mov     x1, x0
 288:   90000002        adrp    x2, 0 <__data_end>
 28c:   aa1403e0        mov     x0, x20
 290:   f9400042        ldr     x2, [x2]
 294:   cb140042        sub     x2, x2, x20
 298:   94000000        bl      0 <memcpy>
```

Or in linked ELF:

```
        memcpy(__data_start,
    44108780:   aa0003e1        mov     x1, x0
    44108784:   d00002a2        adrp    x2, 4415e000 <__ctor_end>
    44108788:   aa1403e0        mov     x0, x20
    4410878c:   f940ac42        ldr     x2, [x2, #344]
    44108790:   cb140042        sub     x2, x2, x20
    44108794:   9400c909        bl      4413abb8 <memcpy>
```

As you can see, it loads `x2` with value of `__data_start` (there is no constructors, so `__data_start` == `__ctor_list` == `__ctor_end`) and then reads address at offset `#344`.

Strangelly, I can observe this behaviour only with "poky" flavor of gcc 8.2. Linaro toolchain (and all others that I tried) generates old plain `adrp`:

```
        memcpy(__data_start,
 414:   aa0003e1        mov     x1, x0
 418:   90000002        adrp    x2, 0 <__data_end>
 41c:   91000042        add     x2, x2, #0x0
 420:   cb140042        sub     x2, x2, x20
 424:   aa1403e0        mov     x0, x20
 428:   94000000        bl      0 <memcpy>
```

**Comment by jenswi-linaro** [comment]
This is clearly a bug in the compiler. The code change only makes things different enough to avoid triggering the bug.

**Comment by lorc** [comment]
May this be caused by some sort of LTO?

Actually, I don't like this patch myself, so yeah, I'd prefer not to include it in the tree, if we can live without it.

I'll try to play with compiler to find what exactly cause this.

**Comment by jenswi-linaro** [comment]
LTO, isn't that just a linker thing? In this case the problem is generated by the compiler since we can see it already in the original `.o` file.

**Pull request closed without merging**
