### PR TITLE
Addressed the problem mentioned in issue#554

### PR DESCRIPTION
**Pull request by m943040028**
Following is the issue description:

If we failed to create meta file while creating a new persistent
object. We will leave a empty tee folder in ree filesystem.

Next time when we want to create tee file when the same object id,
it will fail because the folder is already existed.

The patch solves this issue by checking if meta file is existed,
instead of just checking if the folder is existed.

Signed-off-by: SY Chiu <sy.chiu@linaro.org>
Tested-by: SY Chiu <sy.chiu@linaro.org> (MT8173)

### CODE REVIEW

**Comment by pascal-brand-st-dev** [comment]
Is there any risk that the repository exists, no meta file exists, but some blocks exist?
If so, should we remove the existing blocks?

**Comment by m943040028** [comment]
This case should not happen, because we always out-of-place update meta file. We always keep a valid meta file while update is in progress. The only possiblity that a tee file without meta can only happen while creating tee file, because the operation of create tee file folder and meta file is not atomic.

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by pascal-brand-st-dev** [comment]
Can you change the title of the commit in something like:

    File storage: creation in an empty directory

**Comment by m943040028** [comment]
Update PR.

**Comment by pascal-brand-st-dev** [comment]
Please rebase on top of master

**Comment by m943040028** [comment]
Rebased

**Pull request merged**
