### PR TITLE
symbolize.py: symbolize TA MMU regions

### PR DESCRIPTION
**Pull request by jforissier**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
For "core: print rwx flags for each MMU region when a user TA aborts"
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
Can anyone please check the Python script patch(es)?

**Comment by jforissier** [comment]
R-b added to first patch and all rebased on top of master. The Shippable CI should run and (hopefully) pass.

**Comment by jenswi-linaro** [comment]
For "scripts/symbolize.py: print ELF sections after MMU region information"
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
Shippable fails due to a checkpatch warning (line too long in commit message). Let's ignore that since it is a copy/paste of the tool output.

**Pull request merged**
