### PR TITLE
[RFC v2] Add option to restrict loading of TAs and shared libraries

### PR DESCRIPTION
**Pull request by jforissier**
Since commit c27907e1bc5a ("core: arm32: add support for dynamically
linked TAs") and commit d3aa2143a9aa ("core: arm64: add support for
dynamically linked TAs"), Trusted Applications may open additional
libraries at load time. Any UUID listed in a DT_NEEDED entry of the
dynamic table will caused the TEE core to load the corresponding ELF
file into the TA's address space.

With the introduction of the user space loader (ldelf) and especially
commit 0b414d3f9128 ("core: pta_system: ta binary handling"), a TA can
invoke the 'system' PTA to open a library at any time.
Commit ebef121c1f5c ("core, ldelf: add support for runtime loading of
shared libraries") makes it even easier by providing the dlopen() API.

This situation may raise confidentiality and security concerns. To
address them, this commit introduces a new configuration flag:
CFG_RESTRICT_TA_LOAD (default y). When enabled, a static table is
compiled into the TEE core which defines load permissions; requests
are denied by default. The source file for the table is
$(CFG_LOAD_POLICY_FILE) (default: core/pta/load_policy.ini).

Signed-off-by: Jerome Forissier <jerome@forissier.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
I'm not very keen on hard coding these rules into the OP-TEE binary so that you need to recompile it if you add a third party library. I'd prefer taking this via some runtime supplied configuration (maybe even DTB?).

However, if everyone else thinks a hard coded configuration is a splendid idea I will not stand in the way.

**Comment by jforissier** [comment]
> I'm not very keen on hard coding these rules into the OP-TEE binary

I agree this is not ideal. It is just the simplest way I could think of so we can also discuss how the rules are expressed and enforced. But I would very much like to have a more dynamic method instead. Now let's discuss a few options...

1. DTB is not really the place for such information IMO. It is supposed to be used only to describe hardware or pass some information from a prior boot stage. The information we're dealing with here concerns only OP-TEE.
2. TEE secure storage could be an option. It could be accessed via a PTA (can a PTA  secure storage by the way?). Then some kind of authentication would be needed for modify operations. Perhaps `keys/default_ta.pem` could be used for this purpose, but it may be better to use a different one. It also means each device would have to be configured individually after manufacturing (provisioning). And of course this makes the whole thing significantly more complex but probably more suitable to real world use cases.
3. Or if we don't want to go full dynamic, we could also have a signed policy file in the REE FS. The advantage over the previous solution is that it could be generated without OP-TEE running, at build time for instance, and replaced at any time.

In fact I like option 3 because it allows updating the policies yet remains relatively simple to implement.

@dmcilvaney if you have particular use cases in mind, please feel free to comment!

**Comment by dmcilvaney** [comment]
At a minimum being able to lock a specific set of shared library binaries to the kernel binary is enough (Can you set `tags` for the `[*]` entry to force specific versions?).

But if you want to extend this, it starts feeling like a general purpose policy system. IE why not also limit which UUIDs are allowed to run, or adding/removing signing keys. I'll have a quick spin around and see what everyone thinks, but my gut says one of:
1. Keep it simple and lock down a specific set of shared library binaries to the kernel binary (dynamically generate part of the `.ini` at compile time to add the tags?).
2. Figure out a full policy story where a user can provision rules. (what TAs can run, what can they access, what libraries can they load, what TA signers are allowed, etc...). Obviously much more work but more future proof (we might be able to offer support on this).

**Comment by jforissier** [comment]
Yes, with the proposed code, each UUID, i.e., each binary (TA or library) can be associated with a tag.
Please see the comment block in the .ini file. I have not included any tag since they obviously cannot be known in advance of the build, but maybe I should have given an example in a comment section.

**Pull request closed without merging**
