### PR TITLE
Actlr update

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Needed by https://github.com/OP-TEE/optee_os/pull/2055 and https://github.com/OP-TEE/optee_os/pull/2065

**Comment by jforissier** [comment]
- @HarinarayanaBhatta @glneo could you please check and ack the `plat-ti` patch? Thanks.
- Pinging @sunyanbang too although Allwinner A80 support seems pretty much abandoned

**Comment by etienne-lms** [comment]
Looks good to me (`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`) with this added:
```patch
--- a/core/arch/arm/plat-sunxi/entry.S
+++ b/core/arch/arm/plat-sunxi/entry.S
@@ -82,6 +82,10 @@ UNWIND(      .cantunwind)
        /* Enable SMP bit */
        read_actlr  r0
        orr     r0, r0, #ACTLR_SMP
+#if defined(CFG_CORE_WORKAROUND_SPECTRE_BP) || \
+     defined(CFG_CORE_WORKAROUND_SPECTRE_BP_SEC)
+       orr     r0, r0, #ACTLR_CA15_ENABLE_INVALIDATE_BTB
+#endif
        write_actlr  r0
 
        /* init BSS section */
```

**Comment by jenswi-linaro** [comment]
Thanks @etienne-lms, I've pushed the patch supplied patch.
I'll wait from some more tags before applying the tags.

**Comment by glneo** [comment]
I think this should, if possible, be moved into generic_entery_a32.S and depend on an A-15 specific CFG_, otherwise this seems to imply that this is a platform issue, when it is really specific to *all* A-15s. This would also prevent someone adding a new A-15 platform and failing to add this.

**Comment by jenswi-linaro** [comment]
@glneo, OK I'll give it a try.

**Comment by jenswi-linaro** [comment]
Update

**Comment by glneo** [comment]
Looks good and doesn't seem to break anything (on TI plats), so:

Acked-by: Andrew Davis <andrew.davis@linaro.org>

**Comment by jenswi-linaro** [comment]
@etienne-lms, OK with you?

**Comment by etienne-lms** [comment]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tags applied

**Pull request merged**
