### PR TITLE
user_ta: free all ELFs in case of error

### PR DESCRIPTION
**Pull request by lorc**
tee_ta_init_user_ta_session() leaked allocated ELFs if
there was an error during initializastion.

Signed-off-by: Volodymyr Babchuk <vlad.babchuk@gmail.com>

-----

This fixes another portion of #2327

### CODE REVIEW

**Comment by jforissier** [comment]
Good catch!
...and it looks like `mobj_free(utc->mobj_exidx);` is missing, too :(
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

Perhaps we should have a helper function to free the resources in both the normal (user_ta_ctx_destroy()) and error paths (`err:` label in `tee_ta_init_user_ta_session()`)

**Comment by lorc** [comment]
Yes, this is good  idea. I'll add this helper function.

**Comment by lorc** [comment]
Can I just call `user_ta_ctx_destroy()` from the error path? Or it will break something?

**Comment by lorc** [comment]
@jforissier I added helper function. This is a significant change, so I think that I need a new R-b from you.

**Comment by lorc** [comment]
This two commits helped a lot, but OP-TEE still leaks memory somewhere:

> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 80 bytes core/arch/arm/mm/mobj.c:431
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 128 bytes core/kernel/tee_ta_manager.c:474
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 120 bytes core/arch/arm/kernel/user_ta.c:151
> I/TC:  buffer: 72 bytes core/arch/arm/mm/mobj.c:431
> I/TC:  buffer: 72 bytes core/arch/arm/mm/mobj.c:431
> I/TC:  buffer: 72 bytes core/arch/arm/mm/mobj.c:431
> I/TC:  buffer: 200 bytes core/arch/arm/mm/mobj.c:431
> I/TC:  buffer: 128 bytes core/kernel/tee_ta_manager.c:474
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 120 bytes core/arch/arm/kernel/user_ta.c:151
> I/TC:  buffer: 88 bytes core/arch/arm/kernel/user_ta.c:90
> I/TC:  buffer: 128 bytes core/kernel/tee_ta_manager.c:474
> I/TC:  buffer: 28 bytes core/tee/tee_time_generic.c:54
> I/TC:  buffer: 88 bytes core/arch/arm/kernel/user_ta.c:90
> I/TC:  buffer: 128 bytes core/kernel/tee_ta_manager.c:474
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 800 bytes core/arch/arm/kernel/user_ta.c:965
> I/TC:  buffer: 128 bytes core/kernel/tee_ta_manager.c:474
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mmu.c:372
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 120 bytes core/arch/arm/kernel/user_ta.c:151
> I/TC:  buffer: 128 bytes core/kernel/tee_ta_manager.c:474
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 120 bytes core/arch/arm/kernel/user_ta.c:151
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mmu.c:372
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 88 bytes core/arch/arm/kernel/user_ta.c:90
> I/TC:  buffer: 800 bytes core/arch/arm/kernel/user_ta.c:965
> I/TC:  buffer: 128 bytes core/kernel/tee_ta_manager.c:474
> I/TC:  buffer: 88 bytes core/arch/arm/kernel/user_ta.c:90
> I/TC:  buffer: 800 bytes core/arch/arm/kernel/user_ta.c:965
> I/TC:  buffer: 128 bytes core/kernel/tee_ta_manager.c:474
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 120 bytes core/arch/arm/kernel/user_ta.c:151
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mmu.c:372
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 88 bytes core/arch/arm/kernel/pseudo_ta.c:287
> I/TC:  buffer: 128 bytes core/kernel/tee_ta_manager.c:474
> I/TC:  buffer: 88 bytes core/arch/arm/kernel/user_ta.c:90
> I/TC:  buffer: 800 bytes core/arch/arm/kernel/user_ta.c:965
> I/TC:  buffer: 128 bytes core/kernel/tee_ta_manager.c:474
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 120 bytes core/arch/arm/kernel/user_ta.c:151
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mmu.c:372
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 88 bytes core/arch/arm/kernel/user_ta.c:90
> I/TC:  buffer: 800 bytes core/arch/arm/kernel/user_ta.c:965
> I/TC:  buffer: 128 bytes core/kernel/tee_ta_manager.c:474
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 200 bytes core/arch/arm/mm/mobj.c:431
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 120 bytes core/arch/arm/kernel/user_ta.c:151
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mmu.c:372
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 88 bytes core/arch/arm/kernel/user_ta.c:90
> I/TC:  buffer: 800 bytes core/arch/arm/kernel/user_ta.c:965
> I/TC:  buffer: 128 bytes core/kernel/tee_ta_manager.c:474
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 120 bytes core/arch/arm/kernel/user_ta.c:151
> I/TC:  buffer: 200 bytes core/arch/arm/mm/mobj.c:431
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 72 bytes core/arch/arm/mm/mobj.c:431
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mmu.c:372
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mmu.c:372
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 88 bytes core/arch/arm/kernel/user_ta.c:90
> I/TC:  buffer: 800 bytes core/arch/arm/kernel/user_ta.c:965
> I/TC:  buffer: 128 bytes core/kernel/tee_ta_manager.c:474
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 200 bytes core/arch/arm/mm/mobj.c:431
> I/TC:  buffer: 200 bytes core/arch/arm/mm/mobj.c:431
> I/TC:  buffer: 72 bytes core/arch/arm/mm/mobj.c:431
> I/TC:  buffer: 80 bytes core/arch/arm/mm/mobj.c:431
> I/TC:  buffer: 72 bytes core/arch/arm/mm/mobj.c:431
> I/TC:  buffer: 72 bytes core/arch/arm/mm/mobj.c:431
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 80 bytes core/arch/arm/mm/mobj.c:431
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mmu.c:372
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 120 bytes core/arch/arm/kernel/user_ta.c:151
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mmu.c:372
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 88 bytes core/arch/arm/kernel/user_ta.c:90
> I/TC:  buffer: 800 bytes core/arch/arm/kernel/user_ta.c:965
> I/TC:  buffer: 128 bytes core/kernel/tee_ta_manager.c:474
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mmu.c:372
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 88 bytes core/arch/arm/kernel/user_ta.c:90
> I/TC:  buffer: 800 bytes core/arch/arm/kernel/user_ta.c:965
> I/TC:  buffer: 128 bytes core/kernel/tee_ta_manager.c:474
> I/TC:  buffer: 800 bytes core/arch/arm/kernel/user_ta.c:965
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 128 bytes core/kernel/tee_ta_manager.c:474
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 56 bytes core/arch/arm/mm/tee_mmu.c:204
> I/TC:  buffer: 120 bytes core/arch/arm/kernel/user_ta.c:151
> I/TC:  buffer: 88 bytes core/arch/arm/kernel/pseudo_ta.c:287
> I/TC:  buffer: 40 bytes core/arch/arm/mm/mobj.c:279
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:124
> I/TC:  buffer: 72 bytes core/arch/arm/mm/mobj.c:431
> I/TC:  buffer: 72 bytes core/arch/arm/mm/mobj.c:431
> I/TC:  buffer: 88 bytes core/arch/arm/kernel/pseudo_ta.c:287
> I/TC:  buffer: 48 bytes core/arch/arm/mm/mobj.c:166
> I/TC:  buffer: 48 bytes core/arch/arm/mm/mobj.c:166
> I/TC:  buffer: 48 bytes core/arch/arm/mm/mobj.c:166
> I/TC:  buffer: 104 bytes lib/libutils/ext/mempool.c:116
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:29
> I/TC:  buffer: 32 bytes core/arch/arm/kernel/generic_boot.c:739
> I/TC:  buffer: 24 bytes core/arch/arm/mm/tee_mm.c:29
> I/TC:  buffer: 16 bytes lib/libutils/isoc/bget_malloc.c:903


I suspect that there are some TA sessions leaked (maybe to or from pTAs). Will look at this closer.

**Comment by jforissier** [comment]
Thanks @lorc, looks fine to me.
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

In addition, last commit ("...add helper...") is:
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey)`

**Comment by lorc** [comment]
Thank you, @jforissier.

I added tags.

**Pull request merged**
