### PR TITLE
symbolize.py: fix decoding of ftrace dumps containing syscalls

### PR DESCRIPTION
**Pull request by jforissier**
When decoding an ftrace file with syscall tracing enabled [1], the
kernel functions are not resolved and show question marks instead.

[1] $ make CFG_FTRACE_SUPPORT=y CFG_SYSCALL_FTRACE=y CFG_ULIBS_MCOUNT=y \
           CFLAGS_ta_arm32=-pg
    [run test and copy content of /tmp/ftrace*]
    $ optee_os/scripts/symbolize.py -d optee_os/out/arm/core \
           -d out-br/build/optee_test-1.0/ta/*/out
    [paste ftrace log here]

Fixes: 105e09c24479 ("symbolize.py: add support for TEE core ASLR")
Signed-off-by: Jerome Forissier <jerome@forissier.org>

### CODE REVIEW

**Comment by jforissier** [comment]
One small fix for symbolize.py. There is another issue with symbolize with syscall tracing, which is, it does not support ASLR. We need to figure out a way for the ftrace framework to print the kernel load address.

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by b49020** [comment]
`Reviewed-by: Sumit Garg <sumit.garg@linaro.org>`

> We need to figure out a way for the ftrace framework to print the kernel load address.

Have a look at this [patch](https://github.com/b49020/optee_os/commit/014f9884f578c080e86092b8449e3336decdf70a), compile tested only. If it looks fine, please give it a try.

**Comment by jforissier** [comment]
@b49020 your patch works fine except that there appears to be some garbage at the end of the buffer. Length issue I suppose?

**Comment by b49020** [comment]
> Length issue I suppose?

Yes, you are correct. Updated [patch](https://github.com/b49020/optee_os/commit/9331b40f052e306e1766fc6cd0581ce6034f1ced) to fix it.

**Comment by jforissier** [comment]
@b49020 working fine now, thanks for the patch. I have added it to the PR, and I propose to change the "Load address" string for clarity. See additional commit. Would you mind if I fold this change into your patch? (and add my Sob).

**Comment by b49020** [comment]
> I propose to change the "Load address" string for clarity. See additional commit. Would you mind if I fold this change into your patch? (and add my Sob).

The change looks good to me. Please go ahead and update my patch.

**Pull request merged**
