### PR TITLE
plat-ti: Remove start address offset from base of TEE_RAM start

### PR DESCRIPTION
**Pull request by glneo**
We offset our start address from the start of TEE_RAM_START, this
was to allow in-place loading while keeping the OPTEE header inside
secure memory. This is not needed anymore as we relocate the image.

Signed-off-by: Andrew F. Davis <afd@ti.com>

### CODE REVIEW

**Comment by glneo** [comment]
Fixes https://github.com/OP-TEE/optee_os/issues/1556

**Comment by etienne-lms** [comment]
`Acked-by: Etienne Carriere <etienne.carriere@linaro.org>`

Travis complains because of issues in the max declared size of shm buffer:
> o regression_5006.16 Allocate_sharedMemory_MaxSize_Above_and_Below, allocate max size
> /home/travis/optee_repo/optee_test/host/xtest/regression_5000.c:443: (...) 
                                  TEEC_ERROR_OUT_OF_MEMORY, expected (...) TEEC_SUCCESS

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
> Travis complains because of issues in the max declared size of shm buffer [...]

Right, should be fixed in optee_test now. I have restarted the build for this PR.

**Comment by glneo** [comment]
Added Acks

**Pull request merged**
