### PR TITLE
Changelog 3.3.0

### PR DESCRIPTION
**Pull request by jforissier**

### CODE REVIEW

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (QEMU)`

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (QEMUv8)`
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (FVP)`

**Comment by jforissier** [comment]
3.3.0-rc1 + https://github.com/OP-TEE/optee_os/pull/2561:
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey960, GP)`

**Comment by vchong** [comment]
`Tested-by: Victor Chong <victor.chong@linaro.org> (HiKey620 AOSP)`

**Comment by igoropaniuk** [comment]
3.3.0-rc1:
```

+-----------------------------------------------------
16081 subtests of which 0 failed
74 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```

`Tested-by: Igor Opaniuk <igor.opaniuk@linaro.org> (RPi3)`

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno AArch64)`

**Comment by etienne-lms** [comment]
rc1:
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (b2120/b2260, GP)`
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1, GP)`

**Comment by nodeax** [comment]
`Tested-by: Akshay Bhat <akshay.bhat@timesys.com> (Atmel SAM)`
```
+-----------------------------------------------------
16081 subtests of which 0 failed
74 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```

**Comment by jenswi-linaro** [comment]
With https://github.com/OP-TEE/optee_os/pull/2591
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Hikey)`

**Comment by taovcu** [comment]
Tested-by: Tao Lu \<taolu@marvell.com\> (Armada-80x0)

+-----------------------------------------------------
16081 subtests of which 0 failed
74 test cases of which 0 failed
0 test case was skipped
TEE test application done!

**Comment by jenswi-linaro** [comment]
With the now merged https://github.com/OP-TEE/optee_os/pull/2595
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)`

**Comment by vchong** [comment]
3.3.0-rc2:
`Tested-by: Victor Chong <victor.chong@linaro.org> (HiKey620 AOSP)`

**Comment by jforissier** [comment]
3.3.0-rc2:
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey960, GP)`

**Comment by jforissier** [comment]
@ all: thanks for testing.

**Pull request merged**
