### PR TITLE
Two small cleanups 

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jforissier** [comment]
> Moves initialization of mobj_sec_ddr and mobj_tee_ram to mobj.c.

Why not... but why is it better than having all in the same function?

**Comment by jenswi-linaro** [comment]
`mobj_sec_ddr` and `mobj_tee_ram` relates to internal memory management in OP-TEE while the `shm_mobj` relates to how parameters are passed from normal world.

I haven't considered `sdp_mem_mobjs` yet, but I guess it will fall into the same category as `shm_mobj`.

Right now it's not a big deal, but in the SPCI prototype it makes sense and it doesn't hurt now so better upstream early.

**Comment by jforissier** [comment]
OK sounds reasonable.

`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tag applied

**Pull request merged**
