### PR TITLE
core: simple framework to execute deferred works

### PR DESCRIPTION
**Pull request by anisyanka**
Theses patches add to the kernel a new framework for the ability
to save different works, when Rich OS is still booting
and tee-supplicant has not started yet.

Also the patches adds small PTA to trigger different works for execution.
tee-supplicant starts and sends a cmd to the PTA to run all pending jobs.

This ability might be useful in different cases. For example:
 - Run some specific RPC as soon as possible, when RichOS will start;
 - Remove REE based key store or any other fs operations;
 - Save TEE boot process log

To create a new deferred work entity - use 'deferred_work_add()'.
The works will collect in a queue in the kernel.

Signed-off-by: Aleksandr Anisimov <a.anisimov@omprussia.ru>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
I'm not sure this is needed. You could just as well let an make it available via a PTA to do these action.
By the way, we already have a framework for initcalls and finalcalls in `core/include/initcall.h` that could be extended (if needed) to do more or less what's proposed here. However, I do appreciate that this doesn't involve kernel driver changes.

**Comment by anisyanka** [comment]
> By the way, we already have a framework for initcalls and finalcalls in `core/include/initcall.h` that could be extended (if needed) to do more or less what's proposed here.

Initially, I thought about init/final calls,  but in this case there is no way to make sure that REE OS has already booted and the tee-supplicant has started. Correct me if I'm wrong, please.

> I'm not sure this is needed. You could just as well let an make it available via a PTA to do these action.

Now pta for dw is already exists (`core/pta/dw.c` file in this PR). It's a generic pta, which triggers all deferred works.
These works accumulate at OPTEE boot time.

Or do you mean that we need a separate pta for every case?

**Comment by jenswi-linaro** [comment]
> > By the way, we already have a framework for initcalls and finalcalls in `core/include/initcall.h` that could be extended (if needed) to do more or less what's proposed here.
> 
> Initially, I thought about init/final calls, but in this case there is no way to make sure that REE OS has already booted and the tee-supplicant has started. Correct me if I'm wrong, please.

This https://github.com/OP-TEE/optee_os/pull/4251 was what I had in mind.

> 
> > I'm not sure this is needed. You could just as well let an make it available via a PTA to do these action.
> 
> Now pta for dw is already exists (`core/pta/dw.c` file in this PR). It's a generic pta, which triggers all deferred works.
> These works are accumulated at OPTEE boot time.
> 
> Or do you mean that we need a separate pta for every case?

No, I was just thinking that you might as well call whatever functions needs to be called directly. But given how little https://github.com/OP-TEE/optee_os/pull/4251 cost in terms of added code etc it can be used instead.

**Comment by etienne-lms** [comment]
This deferred initcall look a nice feature but these shall be deferred until... what? Some tee-supplicant services run from U-Boot as well as from Linux OS. There may be initcalls one expects deferred until some U-Boot service is ready, and there may be inicalls one expects deferred until definitive OS tee-supplicant is ready. Should these be distinguished? Maybe deferred work should be bound to some identifier and the related PTA be invoked with an identifier for the deferred works to be executed.

(This comment applies to both this P-R and #4251)

**Comment by jenswi-linaro** [comment]
> This deferred initcall look a nice feature but these shall be deferred until... what? Some tee-supplicant services run from U-Boot as well as from Linux OS. There may be initcalls one expects deferred until some U-Boot service is ready, and there may be inicalls one expects deferred until definitive OS tee-supplicant is ready. Should these be distinguished? Maybe deferred work should be bound to some identifier and the related PTA be invoked with an identifier for the deferred works to be executed.

That is a valid point. Perhaps this should be dealt with on a case by case basis. With the case to notify that tee-supplicant is ready to initialize for logging it's quite clear when that call should be done. In other cases it might not, for instance if you need to do something with RPMB as early as possible and U-Boot might have that service enabled depending on boot mode or something. What happens if tee-supplicant is restarted? The old logging service needs to be removed and a new one initialized.

**Comment by anisyanka** [comment]
> This #4251 was what I had in mind.

Thanks!
Now, I got it. I reviewed your patch and tried it in qemu. It works nice.
I would be appreciated if we got it in optee.
I'll drop my own implementation of deferred works.

Do we need a common mechanism to trigger deferred works (to call `call_deferredcalls()`)?
We could use only the pta from this PR for it.

**Comment by jenswi-linaro** [comment]
That's good. However, I'm not convinced that this is what we need yet. Which problems does it solve? What happens if tee-supplicant is restarted?

**Comment by jenswi-linaro** [comment]
Let's keep this open a little while longer.

**Comment by anisyanka** [comment]
> What happens if tee-supplicant is restarted?

If DW was already executed, it is removed from queue, therefore restarting of the supplicant can't affect dw-servise.

I want to do some new changes in this implementation:
 - This PR contains the special PTA to call `deferred_work_do_all()`. It seems it can be dropped.
   We can invoke the system-pta for this purpose.
 - The new thread in supplicant (https://github.com/OP-TEE/optee_client/pull/238) to trigger dw execution looks too redundant.
   I think we can close the PR to optee-client. Now we have the plugin framework. If someone want to use deferred calls
   or deferred inits they can write own plugin to invoke system-pta.

The supplicant loads and inits plugins during start up process, therefore we can invoke system-pta during plugin init.

**Comment by jenswi-linaro** [comment]
I'm sorry, until we have something upstream (or at least about to have) I don't see much point in this.

**Comment by anisyanka** [comment]
Thank you, let's remember this feature for the future.

**Pull request closed without merging**
