### PR TITLE
drivers: crypto: se050: limitations on RSA

### PR DESCRIPTION
**Pull request by ldts**
The supported algorithms for encryption/decryption are:
  PKCS1_OAEP
  PKCS1_V1_5

Whe using PKCS1_PSS_MGF1 the se050 also has some restrictions on the
hash algorithms that can be used depending on the RSA key size.

Source: Plug And Trust MW documentation, Release v02,14,00 (Apr 03,
2020)

Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

Fixes: https://github.com/OP-TEE/optee_os/issues/4239

### CODE REVIEW

**Comment by ldts** [comment]
@jforissier I am not sure why this fails IBART since this code only can be executed with the se050. anything I should be doing that I missed?

**Comment by jforissier** [comment]
@ldts no worries, you just need to rebase onto master. The failing tests are new ones that were added yesterday to check some crypto fixes (also merged yesterday).

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by ldts** [comment]
tag updated

**Comment by ldts** [comment]
any more comments?

**Comment by jforissier** [comment]
@ldts just back from vacation, sorry for the delay. I will let IBART run and merge this, thanks.

**Pull request merged**
