### PR TITLE
plat-rpi3: Modify addresses to work with upstream A-T-F.

### PR DESCRIPTION
**Pull request by grandpaul**
The upstream arm-trusted-firmware reserves 0x10100000-0x10300000 for
secure DRAM. Change the address according to the upstream A-T-F.

Signed-off-by: Ying-Chun Liu (PaulLiu) <paul.liu@linaro.org>

@igoropaniuk Please help review this pull request. Thanks.

### CODE REVIEW

**Comment by jbech-linaro** [comment]
I'm fine with this change as long as it doesn't brake the current setup ([build](https://github.com/OP-TEE/build#6-manifests), [manifest](https://github.com/OP-TEE/manifest/blob/master/rpi3.xml)). If it brakes the setup, then I'd like to see dependency patches in other gits submitted also. (I have a vague memory that Philip Attfield just took an address that seemed to be unused when doing the initial RPi3/OP-TEE port).

You're reducing the amount of memory quite a bit in this patch, have you been running xtest after doing the changes?

(@etienne-lms any comments from you? Since you've been digging in things like this latetly ...)

**Comment by igoropaniuk** [comment]
@jbech-linaro just will add my 2 cents here, 
all these values conform to the existing memory layout for RPi3 in the upstream ATF-A.

https://github.com/ARM-software/arm-trusted-firmware/blob/master/docs/plat/rpi3.rst

```
0x00000000 +-----------------+
           |       ROM       | BL1
0x00010000 +-----------------+
           |       FIP       |
0x00200000 +-----------------+
           |                 |
           |       ...       |
           |                 |
0x01000000 +-----------------+
           |     Kernel      |
           +-----------------+
           |                 |
           |       ...       |
           |                 |
0x02000000 +-----------------+
           |       DTB       |
           +-----------------+
           |                 |
           |       ...       |
           |                 |
0x10000000 +-----------------+
           |   Secure SRAM   | BL2, BL31
0x10100000 +-----------------+
           |   Secure DRAM   | BL32 payload
0x10300000 +-----------------+
           | Non-secure DRAM | BL33
0x11000000 +-----------------+
           |                 |
           |       ...       |
           |                 |
0x3F000000 +-----------------+
           |       I/O       |
0x40000000 +-----------------+
```

**Comment by grandpaul** [comment]
I'm currently integration all the pieces into yocto recipes. I'll paste the xtest log soon.

**Comment by jbech-linaro** [comment]
> I'm currently integration all the pieces into yocto recipes. I'll paste the xtest log soon.

Thats all good, but the default setup as described on our pages (which I linked to above) must work, since that is what people find and try to use when they are trying to run OP-TEE on a Raspberry Pi3. So I kindly ask you to try your patches using the instructions in build.git also.

**Comment by AntonioND** [comment]
I've just seen this PR. Just to mention that if it is needed to change the size of TZDRAM in the TF, that's fine, just raise a PR in the TF repository.

I assigned 2 MB because it looked to me like more than enough for what I was doing back then (I didn't even have a BL32 image). In the platforms we work with we usually fit everything in SRAM, which is 512 KB tops. I didn't want to have too much TZDRAM either.

I mean, everything is just DRAM in the end. Regular platforms don't have the luxury of defining their memory map, this is the exception because it's just a toy platform without actual secure memory.

**Comment by grandpaul** [comment]
Hi. Maybe we can shrink BL33. Because for U-boot it seems to me that it won't larger than 1MB. 
Also, for Raspbian, we currently suggest to use the rpi3-arm-tf-bootstrap, which is also very small.
I'm not sure how big is UEFI boot loader but should be small I think.

**Comment by grandpaul** [comment]
We enlarge SEC_DRAM0_SIZE in this pull request.
https://github.com/ARM-software/arm-trusted-firmware/pull/1476

**Comment by igoropaniuk** [comment]
Tested with upstream ATF + U-boot as BL33 (with changed `CONFIG_SYS_TEXT_BASE` to `0x11000000`) + Raspberry Linux 4.14 fork (https://github.com/raspberrypi/linux/tree/rpi-4.14.y + with proper optee node in dts + disabled FIQ in dwc_otg). Everything is a built for ARM64.

```
$ xtest
+-----------------------------------------------------
16081 subtests of which 0 failed
74 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```
@grandpaul FYI, this patch should be merged in a row with https://github.com/OP-TEE/build/pull/269 + other two PRs (one in manifest.git, which will change remotes to ATF, U-boot and Linux kernel; another in github.com/linaro-swg/linux.git, where I will create a branch based on https://github.com/raspberrypi/linux/tree/rpi-4.14.y + applied all optee-related patches with **not for mainline** tag), so I'll ping you ASAP when all these PRs are ready. Thanks!

`Tested-by: Igor Opaniuk <igor.opaniuk@linaro.org>`

**Comment by igoropaniuk** [comment]
How to test:
```
mkdir rpi3 && cd rpi3
repo init -u https://github.com/OP-TEE/manifest.git -m rpi3.xml
cd .repo/manifests
git fetch origin refs/pull/119/head && git checkout FETCH_HEAD
cd ../../
repo sync -j8
cd optee_os
git fetch github refs/pull/2394/head && git checkout FETCH_HEAD
cd ../build
git fetch github refs/pull/269/head && git checkout FETCH_HEAD
make toolchains && make -j4 all
```

**Comment by jforissier** [comment]
Two minor comments:
- Perhaps we should start calling Arm's trusted firmware "TF-A", since it is it's new official name
- Care to mention in the commit comment which commit of TF-A this goes with? (to help troubleshoot discrepancies). I see a number of commits here: https://github.com/ARM-software/arm-trusted-firmware/commits/aa49bde8a3e8171fbe25751b4673624c80134f59/plat/rpi3/include/platform_def.h, the first one (aa49bde) looks suitable, no?

`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by igoropaniuk** [comment]
with @jforissier comments addressed
`Reviewed-by: Igor Opaniuk <igor.opaniuk@linaro.org>`

**Comment by jforissier** [comment]
Something looks wrong: the commit message says TF-A reserves 0x10100000-0x10300000 for secure DRAM, but the TF-A commit points to a version that has 0x10100000-0x11000000 ([here](https://github.com/ARM-software/arm-trusted-firmware/blob/aa49bde8a3e8171fbe25751b4673624c80134f59/plat/rpi3/include/platform_def.h#L77-L78)).

**Comment by grandpaul** [comment]
yeah. I must calculate it wrong. 
It is because the reserved area is 15MB. And I miscalculate it because I reduce 15MB by TEE_SHMEM_SIZE 4MB. So left is 11MB. And I put 3 MB to TEE and 8 MB to TA. Must be wrong because that TEE_SHMEM starts from 0x08000000 which is another non-secure area.

I'll change it to 15MB and let TEE use 7MB and TA use 8MB. How do you think?

**Comment by jforissier** [comment]
> I'll change it to 15MB and let TEE use 7MB and TA use 8MB. How do you think?

Sounds reasonable. Please make sure `xtest` runs successfully of course :)
@igoropaniuk any issue with that?

One last thing: in the commit description, please cite the TF-A commit properly, that should be: `commit aa49bde8a3e8 ("rpi3: Move NS-DRAM out of the protected region")`. This will avoid the checkpatch warning.

**Comment by igoropaniuk** [comment]
@jforissier have been AFK since Thursday evening, will test it today

**Comment by igoropaniuk** [comment]
@jforissier seems that everything is ok
```
+-----------------------------------------------------
16081 subtests of which 0 failed
74 test cases of which 0 failed
0 test case was skipped
TEE test application done!
```

**Comment by jforissier** [comment]
@igoropaniuk let's get this fixed

**Pull request merged**
