### PR TITLE
hikey960: Initial commit

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Any reason why this isn't a variant in plat-hikey instead?

**Comment by vchong** [comment]
No good reason apparently. Will change this into a variant of hikey and resubmit.

**Comment by jenswi-linaro** [comment]
Thanks

**Comment by vchong** [comment]
Replaced by https://github.com/OP-TEE/optee_os/pull/1684.
Not overwriting this branch since arm might want to reference it.

**Pull request closed without merging**
