### PR TITLE
Enable sta and core self tests for all platforms..

### PR DESCRIPTION
**Pull request by vchong**
..by setting `CFG_TEE_CORE_EMBED_INTERNAL_TESTS ?= y` in `mk/config.mk`

`Signed-off-by: Victor Chong <victor.chong@linaro.org>`
`Suggested-by: Jerome Forissier <jerome.forissier@linaro.org>`

### CODE REVIEW

**Comment by etienne-lms** [comment]
That will change the default config for plat-d02/hikey/imx/ls/mediatek/sprd. Is it OK to do so ?

**Comment by vchong** [comment]
That is the intention, to enable it for all platforms, so that xtest 1001 actually does something instead of just returning, for the platforms you mentioned above. The self tests (as called by 1001) just test for division and malloc support, and don't depend on anything platform specific.

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

Could you update the commit first line to read "Enable static TA and core self tests for all platforms"? I find "static TA" more readable than "sta".

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by vchong** [comment]
Rebased, commit message amended and tags applied. Ready for merge. Thanks!

**Pull request merged**
