### PR TITLE
core: change io_{clr|set|clrset}bits32() address argument type

### PR DESCRIPTION
**Pull request by etienne-lms**
Change API for `io_clrbits32()`, `io_setbits32()` and `io_clrsetbits32()` to have a `vaddr_t` type address argument, rather than `uintptr_t` as previously.

### CODE REVIEW

**Comment by jforissier** [comment]
Shouldn't the callers be changed, too?

**Comment by etienne-lms** [comment]
yes, but there are very few, all stm32 stuff, always 32bit, = paddr_t == vaddr_t == unitptr_t, GCC does not complain. I prepared the drivers/platform update in former changes. Do you want me to append them to this P-R?

**Comment by jforissier** [comment]
Yeah, for consistency it would be better to adjust `core/arch/arm/plat-stm32mp1/drivers/stm32mp1_clk.c` and `core/drivers/stm32_etzpc.c` in the same patch. As you said, not many declarations to be changed.

**Comment by etienne-lms** [comment]
sorry, this needs a rebase...

**Comment by etienne-lms** [comment]
Rebased to update also stm32_gpio driver recently merged, that uses `io_clrbit32()`, see 2nd fixup commit.

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
Squashed, tag applied.

**Pull request merged**
