### PR TITLE
qemu_virt, qemu_armv8a: enable sdp

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Any motivation why SDP should be enable by default on all the vexpress based platforms?

**Comment by vchong** [comment]
Right now SDP is enabled on HiKey only in CI (HAB). It would be nice to have it enabled and tested on other platforms for comparison, especially if/when there are xtest errors. SDP is an integral part of LCR and LHG builds so it would be good to have it more thoroughly tested.

**Comment by jforissier** [comment]
I also think it's good to maximize test coverage.
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by etienne-lms** [comment]
I think the juno and vfp will not work. Their linux do not enable SDP support (ion heaps). xtest 1014 is likely to fail.

**Comment by jforissier** [comment]
> I think the juno and vfp will not work. Their linux do not enable SDP support (ion heaps). xtest 1014 is likely to fail.

Then it should be enabled for qemu and qemu_virt only I suppose.

**Comment by vchong** [comment]
Ok. I only tested on qemu and qemuv8. Is it ok then to condition the enablement for these 2 platforms only?

**Comment by vchong** [comment]
Added filter for platform flavor and tag.

**Comment by vchong** [comment]
Commit msg updated

**Comment by etienne-lms** [comment]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`
Fine with qemu_virt and qemu_v8 only. I often test such setups without issues.

**Comment by jforissier** [comment]
Merged manually. Thanks

**Comment by jforissier** [comment]
Actually this breaks QEMU when using the latest OP-TEE driver (https://github.com/linaro-swg/linux branch optee was updated from tag [optee-v4.9-20171027](https://github.com/linaro-swg/linux/tree/optee-v4.9-20171027) to tag [optee-v4.12-20180413](https://github.com/linaro-swg/linux/tree/optee-v4.12-20180413)).

I am therefore re-opening this PR.

**Comment by etienne-lms** [comment]
looks like it's spotted: fix proposal at https://github.com/linaro-swg/linux/pull/60.

**Comment by vchong** [comment]
I can send in a pr. Just `default.xml` and `qemu_v8.xml`, or all xmls that use `linaro-swg/linux`?

**Comment by vchong** [comment]
The other platforms are fvp, juno and hikey. Hikey is verified but I don't have access to fvp and juno. linaro-swg/linux#60 will not affect them though since "Their linux do not enable SDP support (ion heaps)" based on earlier [comment above](https://github.com/OP-TEE/optee_os/pull/2250#issuecomment-381069973) so it should be ok to update?

**Comment by jforissier** [comment]
I'm not merging anything that's not tested if it is your question ;-)

**Comment by vchong** [comment]
Oh, updating the kernel commit will actually change it to a different base rather than just simply adding a single commit.

https://github.com/OP-TEE/manifest/pull/103 submitted for just hikey and qemu*.

**Pull request closed without merging**
