### PR TITLE
arm32/pager: fix thread stack allocation in vmem

### PR DESCRIPTION
**Pull request by pascal-brand-st-dev**
Insure vmem allocated for stack protection (an unmaped page at
stack bottom) and effective thread stack vmem are physically
contiguous.

Reviewed-by: Pascal BRAND <pascal.brand@st.com>
Tested-by: Pascal BRAND <pascal.brand@st.com>
Signed-off-by: Pascal Brand <pascal.brand@st.com>

### CODE REVIEW

**Comment by jbech-linaro** [comment]
Commit message "Insure -> Ensure"?

**Comment by etienne-dev** [comment]
I Jens,

The current implementation as a 2-step tee_mmm_alloc() call does not insure both "mm" are contigous each other, a protection vmem is right below (lower addr) stack vmem for effective stack protection. The allocated vmem depends on the previous call to tee_mm_alloc2()/tee_mm_alloc().
Hence this change, allocating a vmem for both protection page and effective stack. Since tee_pager_add_area() requires a tee_mm_entry structure, vmem is freed/reallocated (alloc2).

Proposed code lacks of 1 thing: it should lock the alloc/frees in tee_core_vmem pool while completing its stack alloc/init sequence.

**Comment by jenswi-linaro** [comment]
The change is OK. It's the description in the commit which is confusing, we're ensuring that we get __virtually__ contiguous memory independent of allocation algorithm. There's no need for locking, this part of the code is single threaded, all other CPUs are supposed to wait for the primary CPU to be done with the early parts.

**Comment by pascal-brand-st-dev** [comment]
Commit message has been fixed according to review:

- arm32 -> arm
- Insure -> Ensure
- physically -> virtually

**Comment by jenswi-linaro** [comment]
```
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>
```

**Pull request merged**
