### PR TITLE
mm pools

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Review by jforissier — COMMENTED** [review]
With the checkpatch warning fixed;

`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Comment addressed and tag applied.

**Comment by etienne-lms** [comment]
`Reviewed-by: Etienne Carriere <etienne.carriere@foss.st.com>`

**Comment by jenswi-linaro** [comment]
Tags applied.

**Comment by jenswi-linaro** [comment]
Rebased to fix CI error

**Pull request merged**
