### PR TITLE
core: fix race in mobj_reg_shm_dec_map()

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Fixes a race in mobj_reg_shm_dec_map() when r->mm is NULL. This is similar to the race fixed by commit 06ea466f9c19 ("core: fix race in mobj_reg_shm_inc_map()"), but with one more possibility.

The problem goes like:
A. Thread 1 calls mobj_reg_shm_dec_map() at the same time as thread 2
   calls mobj_reg_shm_inc_map().
B. Thread 1 decreases mapcount to zero and tries to take the spinlock,
   but thread 1 is suspended before it has acquired the spinlock.
C. Thread 2 sees that mapcount is zero and takes the spinlock and maps
   the memory.
D. Thread 2 calls mobj_reg_shm_dec_map(), mapcount reaches zero again
   and the shared memory is unmapped and r->mm is set to NULL.
E. Thread 1 is finally resumed and acquires the spinlock, mapcount is still
   zero but r->mm is also NULL.

To fix the problem at step E above check that r->mm is still non-NULL.

Fixes: 06ea466f9c19 ("core: fix race in mobj_reg_shm_inc_map()")

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Another fix for https://github.com/OP-TEE/optee_os/issues/6120

**Comment by jenswi-linaro** [comment]
Updated the commit message for `ffa_dec_map()`.

**Review by omasse-linaro — APPROVED** [review]

**Review by jforissier — COMMENTED** [review]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tag applied.

**Comment by omasse-linaro** [comment]
Acked-by: Olivier Masse <olivier.masse@nxp.com>

**Comment by jenswi-linaro** [comment]
Tag applied

**Pull request merged**
