### PR TITLE
core/generic-boot: level up missing external DTB trace

### PR DESCRIPTION
**Pull request by etienne-lms**
Change trace message indicating absence of external DTB
from error level to debug level. Implementation and comment
clearly state the configuration is fully legitimate.

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
Perhaps `IMSG()` would be justified?
Anyways:
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by etienne-lms** [comment]
I would be Ok with an `IMSG()` trace. Here are the main generic boot traces (unsorted):
```C
	IMSG("Pager pool size: %zukB",
	IMSG("Pager is enabled. Hashes: %zu bytes", hash_size);
	DMSG("Checking hashes of pageable area");
	DMSG("OP-TEE Device Tree node already exists!\n");     // TODO: trailing '\n'
	DMSG("PSCI Device Tree node already exists!\n");       // TODO: trailing '\n'
	DMSG("No SHM configured");     // TODO: candidate for IMSG("No dynamic SHM")
	DMSG("No non-secure external DT");       // Would you prefer IMSG() here ?
	DMSG("No non-secure memory found in FDT");
	IMSG("OP-TEE version: %s", core_v_str);
	IMSG("Initializing virtualization support\n");          // TODO: trailing '\n'
	DMSG("Primary CPU switching to normal world boot\n");   // TODO: trailing '\n'
	DMSG("Secondary CPU Switching to normal world boot\n"); // TODO: trailing '\n'
	DMSG("cpu %zu: a0 0x%lx", get_core_pos(), a0);
```

**Comment by etienne-lms** [comment]
Tag applied on 1st commit.

Added a 2nd commit to have an Info trace on available DTBs.
Added a 3rd commit that removes all trailing `\n` character in traces  from generic and driver source files.

**Comment by etienne-lms** [comment]
> ` 	DMSG("No SHM configured");     // TODO: candidate for IMSG("No dynamic SHM")|

I abandoned proposal for `IMSG()` for trace `"No SHM configured"`. With current implementation,
when the trace is printed, platform will panic hence no need Info level for such error trace.

**Comment by jforissier** [comment]
For commit "core/generic-boot: level up missing external DTB trace": I know I already gave a R-b but could you please improve the subject? "level up" sounds misleading, how about "tone down"?
Also `s/generic-boot/generic_boot` for consistency with older commits (and the name of the file).

**Comment by jforissier** [comment]
For commit "core/generic-boot: consistent DTB info traces": `s/generic-boot/generic_boot`.
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jforissier** [comment]
For commit "core: remove trailing \n from generic traces", I suggest "core: trace cleanup" because you're doing various things, not just removing `\n` (and that's fine).
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by etienne-lms** [comment]
Thanks. Commit comments fixed and tag applied.

**Pull request merged**
