### PR TITLE
ta: pkcs11: CKM_RSA_X_509 ("raw RSA") support

### PR DESCRIPTION
**Pull request by etienne-lms**
Add support for raw RSA operation in the pkcs11 TA.

These changes are mainly driven by the need to support CKM_RSA_X_509 signing operation for devices using PKCS#11 API with some TLSv1.2 connections.

This is somewhat related to old https://github.com/OP-TEE/optee_os/pull/3701.

### CODE REVIEW

**Comment by etienne-lms** [comment]
Dear pkcs11 TA contributor, any comments on this change?

**Comment by etienne-lms** [comment]
It seems there is no much interest in this change. If, i guess i'll drop it.

**Comment by etienne-lms** [comment]
I propose to add a config switch to embed or not raw RSA support in the pkcs11 TA.
@Emantor, @vesajaaskelainen, any feedback?

**Review by Emantor — APPROVED** [review]
Looks good to me, introduction of a `CFG_` switch also looks good.
Do you still plan to revive the test PR?

**Comment by etienne-lms** [comment]
Yes.
May I add your `Acked-by:` tag on these commits?

**Comment by Emantor** [comment]
Sure!
`Acked-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>`

**Comment by etienne-lms** [comment]
Thanks. Review tag applied.
I've created https://github.com/OP-TEE/optee_test/pull/762 to revive the test part.

**Pull request merged**
