### PR TITLE
Qemu v8

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Removes the now obsolete plain qemu flavor

Adds initial support for QEMU virt ARMv8-A

### CODE REVIEW

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Rebased tags applied. I added this change too, I hope you're OK with that too.
```
diff --git a/core/arch/arm/plat-vexpress/platform_config.h b/core/arch/arm/plat-
index de07225..55a5e89 100644
--- a/core/arch/arm/plat-vexpress/platform_config.h
+++ b/core/arch/arm/plat-vexpress/platform_config.h
@@ -222,6 +222,10 @@
 
 #elif PLATFORM_FLAVOR_IS(qemu_armv8a)
 
+#ifdef CFG_WITH_PAGER
+#error "Pager not supported for platform vexpress-qemu_armv8a"
+#endif
+
 #define DRAM0_BASE             0x40000000
 #define DRAM0_SIZE             (0x40000000 - DRAM0_TEERES_SIZE)
 
```

**Comment by jforissier** [comment]
@jenswi-linaro that's fine.

**Comment by pascal-brand-st** [comment]
Manually merged

**Pull request closed without merging**
