### PR TITLE
Ci cleanup

### PR DESCRIPTION
**Pull request by jforissier**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Wouldn't it be nice to keep travis, but only with a few tests, like checkpatch and some sanity building of optee_os only?

**Comment by jenswi-linaro** [comment]
Especially reading the checkpatch errors from the shippable log is rather painful.

**Comment by jforissier** [comment]
I don't like much the idea of using both Travis and Shippable for the same thing, i.e., doing optee_os platform builds. Two places for similar stuff, might be a bit confusing. But I agree checkpatch errors are easier to spot with Travis.

How about running checkpatch and `make check` (QEMU `xtest`) with Travis, and the platform builds with Shippable?

**Comment by jenswi-linaro** [comment]
Sound good to me. We can at least try it for a while.

**Comment by jforissier** [comment]
Update

**Comment by jenswi-linaro** [comment]
Looks good.
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Pull request merged**
