### PR TITLE
plat-imx: remove dependency on CFG_DT=y and fix reset on IMX7

### PR DESCRIPTION
**Pull request by jordanrh1**

### CODE REVIEW

**Comment by jordanrh1** [comment]
@MrVan Please have a look. I tested the changes on Sabre IMX6 and Sabre IMX7.

**Comment by MrVan** [comment]
@jordanrh1 For the 1st patch, `Reviewed-by: Peng Fan <peng.fan@nxp.com>` For the 2nd patch, I do not know why it not work on windows, actually the code works with Linux + OPTEE on i.MX, could you share more debug info? The origianl code normally only use SRS or WDA. With your patch, you disable SRS reset.

**Comment by jordanrh1** [comment]
@MrVan I actually test reboot before Windows starts, by invoking `psci_system_reset()` from u-boot. The CPU resets, and SPL start executing again, but the last output I see from SPL is

```
U-Boot SPL 2018.05-rc1-00015-g6b8e510-dirty (May 04 2018 - 16:06:39 -0700)
Trying to boot from MMC1
```

I am unable to break in with JTAG.

I looked at the u-boot implementation of reset, which works on sabre imx7, and it sets the SRS bit. If I set the SRS bit, everything works as expected.

```
 writew(WCR_WDZST | WCR_WDBG | WCR_WDE | WCR_WDT | WCR_SRS |
                WCR_WDA | SET_WCR_WT(timeout), &wdog->wcr);
```

**Comment by MrVan** [comment]
@jordanrh1 I think you are using WDOG_B to trigger ext reset. You could try use 0x14, I think. If it works, you could use the value. If it 0x14 not works for you, it might be something needs investigation

**Comment by jordanrh1** [comment]
@MrVan Thank you for the suggestion. I have reverted the 2nd change, and instead set `ext_reset=true` if platform flavor is mx7dsabresd.

**Comment by jordanrh1** [comment]
@jenswi-linaro Added 'Reviewed-by' tag. Should be ready to merge.

**Pull request merged**
