### PR TITLE
Update CHANGELOG.md for 3.4.0

### PR DESCRIPTION
**Pull request by jforissier**
Preparing for OP-TEE release 3.4.0. As usual this PR will be used to collect `Tested-by:` tags.

### CODE REVIEW

**Comment by jbech-linaro** [comment]
RPi3 fails during boot when running latest. It seems to be related to something in TF-A since going back to the 2.0 tag in TF-A makes it boot (and run xtest successfully). See my comment here https://github.com/OP-TEE/build/issues/325#issuecomment-454795309 for more context.

**Comment by jbech-linaro** [comment]
**RPi3**: The commit when the regression was introduced here https://github.com/ARM-software/arm-trusted-firmware/commit/5341b42ec170021a4dcde3e1bd463bb8c92cdff7 in https://github.com/ARM-software/arm-trusted-firmware/pull/1637
```patch
commit 5341b42ec170021a4dcde3e1bd463bb8c92cdff7
Author: Antonio Nino Diaz <antonio.ninodiaz@arm.com>
Date:   Fri Oct 19 00:57:16 2018 +0100

    rpi3: Add mem reserve region to DTB if present
```

And the error happens when trying to set up the page tables (`rpi3_setup_page_tables(...)`). In the error callstack (0x100e4b10) it's this call (`rpi3_setup_page_tables(...) -> mmap_add(plat_rpi3_mmap);`)
https://github.com/ARM-software/arm-trusted-firmware/blob/master/plat/rpi3/rpi3_common.c#L165
that makes it fail.

Log with `LOG_LEVEL=50` gives:
```bash
INFO:    Loading image id=4 at address 0x10100000
INFO:    Image id=4 loaded: 0x10100000 - 0x1010001c
INFO:    OPTEE ep=0x10100000
INFO:    OPTEE header info:
INFO:          magic=0x4554504f
INFO:          version=0x2
INFO:          arch=0x1
INFO:          flags=0x0
INFO:          nb_images=0x1
INFO:    BL2: Loading image id 21
VERBOSE: Using Memmap
VERBOSE: FIP header looks OK.
VERBOSE: Using FIP
INFO:    Loading image id=21 at address 0x10100000
INFO:    Image id=21 loaded: 0x10100000 - 0x101453e0
INFO:    BL2: Skip loading image id 22
INFO:    BL2: Loading image id 5
VERBOSE: Using Memmap
VERBOSE: FIP header looks OK.
VERBOSE: Using FIP
INFO:    Loading image id=5 at address 0x11000000
INFO:    Image id=5 loaded: 0x11000000 - 0x11070150
NOTICE:  BL1: Booting BL31
INFO:    Entry point address = 0x100e0000
INFO:    SPSR = 0x3cd
VERBOSE: Argument #0 = 0x100bf490
VERBOSE: Argument #1 = 0xf1e2d3c4b5a6978
VERBOSE: Argument #2 = 0x0
VERBOSE: Argument #3 = 0x0
VERBOSE: Argument #4 = 0x0
VERBOSE: Argument #5 = 0x0
VERBOSE: Argument #6 = 0x0
VERBOSE: Argument #7 = 0x0
VERBOSE: Trusted SRAM seen by this BL image: 0x100e0000 - 0x100f6000
VERBOSE: Code region: 0x100e0000 - 0x100e8000
VERBOSE: Read-only data region: 0x100e8000 - 0x100eb000
VERBOSE: Coherent region: 0x100f5000 - 0x100f6000
ERROR:   mmap_add_region_check() failed. error -22
ASSERT: lib/xlat_tables_v2/xlat_tables_core.c:741:false
BACKTRACE: START: assert
0: EL3: 0x100e4884
1: EL3: 0x100e7060
2: EL3: 0x100e55c4
3: EL3: 0x100e56ac
4: EL3: 0x100e4b10
5: EL3: 0x100e0368
6: EL3: 0x100e00a0
7: EL3: 0x100b4078
BACKTRACE: END: assert

```
So, problem narrowed down. Next step is to figure out exactly what is going wrong here. Based on the commit message it seems like we shall pass things via DTB instead. But this doesn't really feel to be related to that.

**Comment by igoropaniuk** [comment]
@jbech-linaro 

Thanks for bisecting this.

Here is an explanation what happens:
In case if `RPI3_PRELOADED_DTB_BASE` isn't defined explicitly with proper address value (as a param for `make`, when building TF-A), it still is being defined by this macro in https://github.com/ARM-software/arm-trusted-firmware/blob/master/plat/rpi3/platform.mk#L133 and https://github.com/ARM-software/arm-trusted-firmware/blob/master/make_helpers/build_macros.mk#L42 as a boolean value (just trying to figure out where) with default value `1` (obviously, because you just supply `-DRPI3_PRELOADED_DTB_BASE` as a param to gcc).

For verification of this just add this patch:
```
diff --git a/plat/rpi3/rpi3_common.c b/plat/rpi3/rpi3_common.c
index 9b10974..c726f85 100644
--- a/plat/rpi3/rpi3_common.c
+++ b/plat/rpi3/rpi3_common.c
@@ -28,6 +28,9 @@
                                        MT_DEVICE | MT_RW | MT_SECURE)
 
 #ifdef RPI3_PRELOADED_DTB_BASE
+#define XSTR(x) STR(x)
+#define STR(x) #x
+#pragma message "RPI3_PRELOADED_DTB_BASE: " XSTR( RPI3_PRELOADED_DTB_BASE)
 #define MAP_NS_DTB     MAP_REGION_FLAT(RPI3_PRELOADED_DTB_BASE, 0x10000, \
                                        MT_MEMORY | MT_RW | MT_NS)
 #endif

```

Which then shows:
```
plat/rpi3/rpi3_common.c:33:9: note: #pragma message: RPI3_PRELOADED_DTB_BASE: 1
```

Which simply leads to the wrong `MAP_NS_DTB` region definition (dtb is loaded to `0x00010000`, but we put just `1` instead of `0x00010000`) here:
```
#ifdef RPI3_PRELOADED_DTB_BASE
#define MAP_NS_DTB	MAP_REGION_FLAT(RPI3_PRELOADED_DTB_BASE, 0x10000, \
					MT_MEMORY | MT_RW | MT_NS)
#endif
```

As a workaround we can set proper value for `RPI3_PRELOADED_DTB_BASE` to `0x00010000`, by letting TF-A to edit a pre-loaded DTB and add there `memreserve` region (although we're providing this info using old-school way through `memmap` kernel cmdline option in https://github.com/OP-TEE/build/blob/master/rpi3/firmware/uboot.env.txt#L36), but handling `RPI3_PRELOADED_DTB_BASE` should be fixed in TF-A.

@antonio-nino-diaz-arm FYI

**Comment by jbech-linaro** [comment]
> In case if `RPI3_PRELOADED_DTB_BASE` isn't defined explicitly with proper address value

I've just concluded the same, I got passed after setting this: https://github.com/jbech-linaro/build/commit/007a204f11734ea8c38357e0ce5955b77da56830

Now it hangs on xtest 1008, but I've probably used the wrong DT address (the one in `config.txt`). I will re-try with the one you suggested.

**Comment by jbech-linaro** [comment]
> I will re-try with the one you suggested.

Yeps, with the correct address that you suggested instead of the one I had put in my branch above, xtest now passes, thanks! I'll send a PR to build.git.

**Comment by igoropaniuk** [comment]
https://github.com/ARM-software/arm-trusted-firmware/pull/1760

**Comment by jbech-linaro** [comment]
And I've just submitted this: https://github.com/OP-TEE/build/pull/333 :)

**Comment by jforissier** [comment]
> And I've just submitted this: https://github.com/OP-TEE/build/pull/333 :)

Merged!

**Comment by igoropaniuk** [comment]
`Tested-by: Igor Opaniuk <igor.opaniuk@linaro.org> (RPi3)`

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Hikey)`

**Comment by igoropaniuk** [comment]
```
+-----------------------------------------------------
23304 subtests of which 0 failed
93 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```
`Tested-by: Igor Opaniuk <igor.opaniuk@linaro.org> (Poplar)`

**Comment by vchong** [comment]
`Tested-by: Victor Chong <victor.chong@linaro.org> (HiKey960 aosp P)`

**Comment by etienne-lms** [comment]
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (b2260)`
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1)`

Note: GP testsuite fails on GCD computation. Seems related to the recent move from MPA to MPI.
Tests gp_8548/8549/8550/8569/8660 all fail at the same point in GCD computation (trace extract below). I need to investigate deeper...
```
Panic function bigint_binary, line 358, code -16
E/TC:? 0 
E/TC:? 0 TA panicked with code 0xb16127
(...)
.../host/xtest/gp_8500.c:830: Invoke_BigIntComputeExtendedGcd(c, SESSION01, 0x00000014, 0
  gp_8550 FAILED
```

**Comment by jforissier** [comment]
@etienne-lms yep, I just merged the fix and will push 3.4.0-rc1 shortly!

**Comment by nodeax** [comment]
`Tested-by: Akshay Bhat <akshay.bhat@timesys.com> (Atmel SAM)`
```
+-----------------------------------------------------
23304 subtests of which 0 failed
93 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by bryanodonoghue** [comment]
Tested-by: Bryan O'Donoghue <bryan.odonoghue@linaro.org>

**Comment by b49020** [comment]
With https://github.com/OP-TEE/optee_os/pull/2751 incorporated:

`Tested-by: Sumit Garg <sumit.garg@linaro.org> (Developerbox)`
```
+-----------------------------------------------------
43293 subtests of which 0 failed
93 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by jforissier** [comment]
3.4.0-rc1:
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey960, GP)`

**Comment by jforissier** [comment]
3.4.0-rc1:
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (QEMU)`

**Comment by lorc** [comment]
For 3.4.0-rc1:

`Tested-by: Volodymyr Babchuk <vlad.babchuk@gmail.com> (RCAR H3)`

```
+-----------------------------------------------------
23304 subtests of which 0 failed
93 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by jforissier** [comment]
For 3.4.0-rc1:
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (QEMUv8)`
```
+-----------------------------------------------------
22710 subtests of which 0 failed
93 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by grandpaul** [comment]
Tested-by: Ying-Chun Liu (PaulLiu) <paul.liu@linaro.org> (sunxi-bpi_zero)

**Comment by jenswi-linaro** [comment]
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)`

**Comment by Emantor** [comment]
`Tested-by: Rouven Czerwinski <r.czerwinski@pengutronix.de> (mx6qsabresd)`

```
+-----------------------------------------------------
23304 subtests of which 0 failed
93 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```

**Comment by etienne-lms** [comment]
> **~~Note: GP testsuite fails on GCD computation.~~**
> **edited: Related to #2736 / #2752. Will test back...**

No issue with GP tests on my side.
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (b2260, GP)`
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1, GP)`

**Comment by etienne-lms** [comment]
Issue found in regression test building with cmake, please consider https://github.com/OP-TEE/optee_test/pull/323.

**Comment by vchong** [comment]
`Tested-by: Victor Chong <victor.chong@linaro.org> (HiKey960 AOSP P, HiKey620 AOSP P)`

**Comment by jenswi-linaro** [comment]
With https://github.com/OP-TEE/optee_os/pull/2763
`Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (FVP)`
I've retested Juno AArch32 with pager enabled with patch.

**Comment by jforissier** [comment]
@bryanodonoghue which platform have you tested? May I append `(i.MX7 WaRP)` to your `Tested-by:`?

**Comment by bryanodonoghue** [comment]
Tested-by: Bryan O'Donoghue <bryan.odonoghue@linaro.org> (i.MX7Solo WaRP7)

**Pull request merged**
