### PR TITLE
PTA: change method for checking memory in derive TA key

### PR DESCRIPTION
**Pull request by jbech-linaro**
The tee_vbuf_is_sec() which ends up as core_vbuf_is() doesn't work with
paged user space memory, so instead use tee_mmu_check_access_rights().

This resolves an regression issue found when running with the pager
enabled: https://github.com/OP-TEE/optee_test/pull/349

Signed-off-by: Joakim Bech <joakim.bech@linaro.org>
Suggested-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
How about a fixes tag?

**Comment by jbech-linaro** [comment]
> How about a fixes tag?

I was thinking about that, but we have no issue for it. The current "issue" is a pull request. So I thought this was the easiest.

**Comment by jenswi-linaro** [comment]
a30ddda9e488 "PTA: add support for deriving device and TA unique keys" obviously is broken.

**Comment by jbech-linaro** [comment]
Aha, I thought you were asking for fixes tag for a GitHub issue. Sure I can add a fixes tag for the commit itself.

**Comment by jenswi-linaro** [comment]
With that tag:
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jbech-linaro** [comment]
I've added the fixes and your R-B, looking OK?

**Comment by jenswi-linaro** [comment]
Looks good.

**Pull request merged**
