### PR TITLE
ci: se05x crypto driver: update plug-and-trust

### PR DESCRIPTION
**Pull request by ldts**
Update the Plug-and-Trust to the latest release 04.02.00

Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

### CODE REVIEW

**Review by jforissier — APPROVED** [review]
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by ldts** [comment]
@jforissier tags updated. thanks!

**Comment by ricardosalveti** [comment]
I'm testing this rev locally today and will give my tested-by.

I know this is CI specific, but that is probably what SE05X users will end up consuming.

**Comment by jforissier** [comment]
@ricardosalveti I am going to merge this as this related only to CI and I am about to tag -rc1. That being said your Tested-by would be welcome in #5550.

**Pull request merged**
