### PR TITLE
plat-k3: set TRNG as enabled unconditionally

### PR DESCRIPTION
**Pull request by glneo**
All K3 devices already have this enabled, remove the check and set this unconditionally.

### CODE REVIEW

**Review by jforissier — APPROVED** [review]
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Review by etienne-lms — COMMENTED** [review]
The commit message can be misleading IMHO. The RRNG is now default disabled for all k3 based platforms, not set unconditionally as external build config directives can still override the default config and enable PRNG.
That said,  `Acked-by: Etienne Carriere <etienne.carriere@foss.st.com>` (I may be too picky :)

**Comment by glneo** [comment]
Ping, seems this got closed due to inactivity..

**Review by etienne-lms — APPROVED** [review]
Looks like ready to be merged.

**Pull request merged**
