### PR TITLE
hikey960: add ASAN shadow offset for 32-bit build

### PR DESCRIPTION
**Pull request by jforissier**
Adds the proper CFG_ASAN_SHADOW_OFFSET value for HiKey960 in 32-bit
mode. This allows to run with the kernel address sanitizer enabled
(CFG_CORE_SANITIZE_KADDRESS=y).

Signed-off-by: Jerome Forissier <jerome@forissier.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jbech-linaro** [comment]
Seems like it wasn't enough to put new TF-A in the repo cache. I've now "up'd" the timeout from 15/60 to 30/120. That should fix it for a while I hope. I'll restart the job manually.

**Comment by jforissier** [comment]
Does IBART download the toolchains too?

**Comment by jbech-linaro** [comment]
> Does IBART download the toolchains too?

Nope, it only downloads delta to upstream gits and the delta are new commits that have been merged since the nightly cron job pulled everything into the local cache. In short:
* Toolchains, downloaded and stored locally and used by builds (requires manual updates when stepping up version).
* Gits, downloaded locally with cronjob at night, used by builds (as the mirror).
* ccache, stored locally and used by builds. 
Note however, that it always starts from scratch, i.e., from an empty (`rm -rf`) folder. So there are no stale files etc.

**Comment by jforissier** [comment]
@jbech-linaro OK thanks. I understand why you expect quick download times -- there is normally not much to download.

**Comment by jbech-linaro** [comment]
> @jbech-linaro OK thanks. I understand why you expect quick download times -- there is normally not much to download.

Right, it's not much data at all, so it's usually in the ballpark ~20 seconds or so to get all source code to all gits. Issues we've had in the past have been
1. Local cache not updated on daily basis (cronjob rule was incorrect).
2. Git's have moved to another remote, i.e., not in the local cache.
3. Timeout as we've seen this week, mainly due to "2", but in rare cases also because the remote server hasn't responded.
I think all of them have been addressed now.

**Pull request merged**
