### PR TITLE
Update CHANGELOG for 3.21.0

### PR DESCRIPTION
**Pull request by jforissier**
Update CHANGELOG for 3.21.0 and collect Tested-by tags.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
On Juno the PKCS#11 tests fails with:
```
* pkcs11_1000 Initialize and close Cryptoki library
ERR [141] LT:ckteec_invoke_init:304: TEEC open session failed ffff0008 from 3
```
The reason is that the PKCS#11 TA is missing in the rootfs. Do we miss a step in the build setup for Juno or is it a general problem?

**Comment by jforissier** [comment]
> On Juno the PKCS#11 tests fails with:
> 
> ```
> * pkcs11_1000 Initialize and close Cryptoki library
> ERR [141] LT:ckteec_invoke_init:304: TEEC open session failed ffff0008 from 3
> ```
> 
> The reason is that the PKCS#11 TA is missing in the rootfs. Do we miss a step in the build setup for Juno or is it a general problem?

Perhaps `CFG_USER_TA_TARGET_pkcs11=ta_arm64` is needed, and in this case maybe a fix like this would be preferable? https://github.com/OP-TEE/optee_os/commit/07031b23d

**Comment by jenswi-linaro** [comment]
> > On Juno the PKCS#11 tests fails with:
> > ```
> > * pkcs11_1000 Initialize and close Cryptoki library
> > ERR [141] LT:ckteec_invoke_init:304: TEEC open session failed ffff0008 from 3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The reason is that the PKCS#11 TA is missing in the rootfs. Do we miss a step in the build setup for Juno or is it a general problem?
> 
> Perhaps `CFG_USER_TA_TARGET_pkcs11=ta_arm64` is needed, and in this case maybe a fix like this would be preferable? [07031b23d](https://github.com/OP-TEE/optee_os/commit/07031b23d)

The problem isn't that the TA isn't built, it's not copied into the rootfs.

**Comment by jforissier** [comment]
> > > On Juno the PKCS#11 tests fails with:
> > > ```
> > > * pkcs11_1000 Initialize and close Cryptoki library
> > > ERR [141] LT:ckteec_invoke_init:304: TEEC open session failed ffff0008 from 3
> > > ```
> > >   
> > > The reason is that the PKCS#11 TA is missing in the rootfs. Do we miss a step in the build setup for Juno or is it a general problem?
> > 
> > 
> > Perhaps `CFG_USER_TA_TARGET_pkcs11=ta_arm64` is needed, and in this case maybe a fix like this would be preferable? [07031b23d](https://github.com/OP-TEE/optee_os/commit/07031b23d)
> 
> The problem isn't that the TA isn't built, it's not copied into the rootfs.

That's because the copy happens via `BR2_PACKAGE_OPTEE_OS_EXT_SDK` which is equal to `OPTEE_OS_TA_DEV_KIT_DIR` which is `$(OPTEE_OS_PATH)/out/arm/export-ta_arm64` for Juno because `COMPILE_S_USER := 64`. So if the in-tree TA is built in 32-bit mode there is nothing to be copied. And for Juno that is the case because `default-user-ta-target ?= $(firstword $(ta-targets))` which happens to be `ta_arm32` (see `supported-ta-targets` which leads to `ta-targets` when `CFG_USER_TA_TARGETS` is not set... `ta_arm64` is added in second position when `CFG_ARM64_core=y`)

All this is admittedly slightly confusing...

**Comment by jenswi-linaro** [comment]
Thanks for the explanation. Here's another way of fixing it https://github.com/OP-TEE/build/pull/640 .

**Comment by jenswi-linaro** [comment]
With https://github.com/OP-TEE/optee_test/pull/660 and https://github.com/OP-TEE/build/pull/640
```
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (Juno)
```

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (vexpress-qemu_armv8a)`

With one caveat: `xtest 6016` fails when `CFG_ULIBS_SHARED=y CFG_WITH_PAGER=y` with `TEE_ERROR_OUT_OF_MEMORY` errors. Bisected down to https://github.com/OP-TEE/optee_os/commit/cda03b63cf304472adce7688a07168f4c66af5c7. I believe some adjustments in `xtest` are needed.

**Comment by igoropaniuk** [comment]
For https://github.com/OP-TEE/optee_os/commit/9901df47d96ff3117ee4abc4d3fd5afb001088b5:
```
# xtest
+-----------------------------------------------------
27248 subtests of which 0 failed
104 test cases of which 0 failed
0 test cases were skipped
TEE test application done!

```
`Tested-by: Igor Opaniuk <igor.opaniuk@foundries.io> (Poplar)`

unrelated: as kernel image grew in size, fdt image load address overlaps with it again in the current buildroot-based setup. Will send a patch to u-boot ML for addressing that
```
ERROR: FDT image overlaps OS image (OS=0x30000000..0x32580000)
```

**Comment by jenswi-linaro** [comment]
Build errors for FVP, see https://github.com/OP-TEE/optee_os/issues/5936

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (rockchip-rk3399) (RockPi4B)`

Note that I found https://github.com/OP-TEE/optee_test/issues/661 which is not specific to RockPi4B.

**Comment by clementfaure** [comment]
`SM2_PKE` operations fail (`regression_4006.43`) when `CFG_NXP_CAAM=y` and `CFG_CRYPTO_DRIVER=y`, please see https://github.com/OP-TEE/optee_os/pull/5937

**Comment by jenswi-linaro** [comment]
```
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (vexpress-fvp)
```
with python2 installed.

**Comment by etienne-lms** [comment]
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1-157C_DK2)`
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (stm32mp1-157C_EV1)`

**Comment by jbech-linaro** [comment]
`Tested-by: Joakim Bech <joakim.bech@linaro.org> (RPi3B)`

**Comment by ricardosalveti** [comment]
`Tested-by: Ricardo Salveti <ricardo@foundries.io> (ZynqMP)`

**Comment by TaihuLight** [comment]
Tested-by: Longlong LIAO <liaoll@hku.hk> (HiKey960)
-----------------------------------------------------------
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 4.19.5-hikey
      Architecture: arm64
+-----------------------------------------------------
regression_1027 FAILED first error at regression_1000.c:2211
regression_1028 FAILED first error at regression_1000.c:2276
27005 subtests of which 2 failed
104 test cases of which 2 failed
0 test cases were skipped
TEE test application done!

**Comment by jforissier** [comment]
Hello @TaihuLight,

This pull request is merged, it was intended for the 3.21.0 release which was published on April 14th, 2023. However if you want to do some testing for the next release, you are more than welcome. A new pull request will be opened here with title "Update CHANGELOG for 3.22.0", please monitor this space, then you can report success of failure with HiKey. All details are documented at https://optee.readthedocs.io/en/latest/general/releases.html. Note however that the next release date has been anticipated by one week due to vacations, it is scheduled July 7th.
Thanks!

**Pull request merged**
