### PR TITLE
Misc commits

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Some small commits and one larger adding 64bit support to snprintf.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Review comments addressed.

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>
    Tested-by: Pascal Brand <pascal.brand@linaro.org> (STM platform)

Tests ok when optee_test updated with Jens's branch.

**Comment by jenswi-linaro** [comment]
Rebased on master with tags applied

**Pull request merged**
