### PR TITLE
Misc ftrace updates

### PR DESCRIPTION
**Pull request by b49020**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
In "￼ci: shippable: Enable build with ftrace config options" four new builds are added. Any chance of combining with some other build configuration to get the same effect?

**Comment by b49020** [comment]
> Any chance of combining with some other build configuration to get the same effect?

I can combine 2 of them with `CFG_TA_GPROF_SUPPORT=y` since both seems to enable debug functionality.

**Comment by b49020** [comment]
Updated PR.

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by b49020** [comment]
Tags applied.

**Pull request merged**
