### PR TITLE
plat-hikey: make DRAM0_SIZE and DRAM0_SIZE_NSEC configurable

### PR DESCRIPTION
**Pull request by zwb-233**
This pull request contains changes identical to those proposed in pull request #6718 , which was previously closed. Due to some troubles in my life, I was unable to address the feedback and make the necessary modifications until now.

### CODE REVIEW

**Review by jenswi-linaro — COMMENTED** [review]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by zwb-233** [comment]
@jenswi-linaro Hi, I found that this Pull has not been merged yet, do you still need to modify it

**Comment by jenswi-linaro** [comment]
This is ready to be merged, right @jforissier?

**Comment by jforissier** [comment]
Merging, sorry for the delay.

**Pull request merged**
