### PR TITLE
Remove license notice from STMicroelectronics files

### PR DESCRIPTION
**Pull request by etienne-lms**
Better late than never, here is an old patch i almost forgot to push...

`Signed-off-by: Etienne Carriere <etienne.carriere@st.com>`
`Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>`

### CODE REVIEW

**Comment by etienne-lms** [comment]
:)  i already removed some, seems i was a bit lazy...

**Comment by etienne-lms** [comment]
pushed back straight (squashed). happy review!

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
tag applied

**Pull request merged**
