### PR TITLE
doc: Fix MAINTAINERS.md broken link

### PR DESCRIPTION
**Pull request by ohadhawk**
doc: fix MAINTAINERS link in readme
Signed-off-by: Ohad Netz <ohadhawk@yahoo.com>
Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
Hi @ohadhawk,

Thanks for the fix. Please add your `Signed-off-by:`, otherwise I can't merge the PR.
Then also add:
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by ohadhawk** [comment]
Please check now

**Comment by jforissier** [comment]
Still not good. The tags have to be in the commit message. And we don't care about GPG-signed commits (yet).

**Comment by ohadhawk** [comment]
@jforissier Not sure what are GPG-signed commits 
Anyhow, if now is not good enough please give me your Skype so I would figure out and fix on the spot.
I causally stumbled upon this and don't have the time to continue the messages exchange.

**Comment by jforissier** [comment]
@ohadhawk I can understand that you don't want to spend more time on this, and it is perfectly fine by me. Therefore, I am closing this PR and will submit another one myself. Patch submissions are normally discussed publicly on GitHub (here), and as a maintainer I am adding the below clarifications in the hope that they will be helpful to somebody (else).

- The OP-TEE project has its rules regarding how commits have to be formatted, especially regarding tags in the commit messages. We basically follow the same rules as the Linux kernel. Details are available at https://github.com/OP-TEE/optee_os/blob/master/Notice.md#contributions. We expect patch authors to follow the rules and the established standards. In this case, `git log` trivially shows what we expect.

- The proposed patch  still does not comply with the rules (missing blank line ; missing angle brackets around email addresses). Also, why is the author e-mail not the same as the one in the Signed-off-by?. 

- About GPG-signed commits: you probably know as much as I do, because your previously pushed commit abd1e18e6ac9 ("Fixed MAINTAINERS.md broken link") does contain a signature, although your latest commit 76e2c816a56a ("doc: fix MAINTAINERS broken link in readme") does not.

```
$ git show --show-signature abd1e18e6
commit abd1e18e6ac94d6cc49aa992f184f36fe2602329
gpg: Signature made Mon 02 Apr 2018 02:29:31 PM CEST
gpg:                using RSA key 4AEE18F83AFDEB23
gpg: Can't check signature: public key not found
Author: Ohad Netz <ohad.netz@arm.com>
Date:   Mon Apr 2 15:29:31 2018 +0300

    Fixed MAINTAINERS.md broken link
    
    Changed the link to point at the MAINTAINERS text file
```

Thanks.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/2226

**Comment by ohadhawk** [comment]
Thanks for the info and sorry for the fuss.
One of the emails is my work email and the other is the one I'm registered to github with.
I have no idea about the gpg. Maybe because one commit was done through github directly and the other was done from my computer after I cloned the repo.

**Pull request closed without merging**
