### PR TITLE
arm32: Adds LPAE support

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Enables use of Large Physical Address Extension (LPAE) with
CFG_WITH_LPAE=y

To facilitate both the old V7 and the new LPAE translation tables an
abstraction layer has been added to avoid direct manipulations of the
translation tables.

Both V7 and LPAE implementation uses TEX remapping (SCTLR.TRE = 1) and
enables access flags (SCTLR.AFE = 1). This is a change in the V7 code
base as those bits where 0 before. There are two reason for this change:
1."From the introduction of the Large Physical Address Extension, ARM
   deprecates any use of the AP[2:0] scheme for defining MMU access
   permissions. This deprecation applies to software for all ARMv7-A
   implementations, regardless of whether they include the Large
   Physical Address Extension."
2. With SCTLR.TRE = 1 and SCTLR.AFE = 1 V7 and LPAE implementations uses
   the same way of specifying access permissions and memory attributes.

Currently only supported on plat-vexpress.

Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>
Tested-by: Jens Wiklander <jens.wiklander@linaro.org> (QEMU, Juno)

Note, xtest 1005 fails due to TAs using even more memory than before (when using LPAE). The test case need to be redesigned to handle different limitations on loading TAs.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Squashed and rebased on master

**Comment by pascal-brand-st-dev** [comment]
Most of the checkpatch warnings in Travis can be ignored. But few must be fixed.

**Comment by jenswi-linaro** [comment]
Review comments addressed.

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>
    Tested-by: Pascal Brand <pascal.brand@linaro.org> (STM platform)

**Comment by jenswi-linaro** [comment]
Squashed with review tags applied

**Pull request merged**
