### PR TITLE
libmbedtls: Support dynamic check CRT parameters

### PR DESCRIPTION
**Pull request by lubing521**
Keymasster VTS need enable mbedtls with CRT.
But some case of the Xtest 4006 no provide CRT
This will cause OP-tee OS check it fail. in order
to support this scenario work well,libmedtls need
frendly deal with RSA with CRT or not.

Signed-off-by: Lu Bing <lubing@eswin.com>
Tested-by: Lu Bing <lubing@eswin.com>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
The approach to check if CRT parameters are present makes sense. But basic fixes are needed.
1. I believe only a single commit is needed
2. You should try to follow the MbedTLS coding style a bit closer
3. I would really help if this was just a cherry-pick from upstream MbedTLS repository, that is, the patch was already accepted upstream

Normally when making changes to MbedTLS or any other library kept in sync with upstream we upstream the change first and then bring it into OP-TEE once the solution has been accepted. This allows us to keep a minimal delta compared to upstream. Keeping a small delta is key to be able upgrade to a later release. There's also the benefit that the patches has been reviewed by experts on the subject.

**Comment by lubing521** [comment]
> The approach to check if CRT parameters are present makes sense. But basic fixes are needed.
> 
> 1. I believe only a single commit is needed
> 2. You should try to follow the MbedTLS coding style a bit closer
> 3. I would really help if this was just a cherry-pick from upstream MbedTLS repository, that is, the patch was already accepted upstream
> 
> Normally when making changes to MbedTLS or any other library kept in sync with upstream we upstream the change first and then bring it into OP-TEE once the solution has been accepted. This allows us to keep a minimal delta compared to upstream. Keeping a small delta is key to be able upgrade to a later release. There's also the benefit that the patches has been reviewed by experts on the subject.

Thank you very much for your advice.
I will try do it on upstream.

**Comment by jenswi-linaro** [comment]
> I will try do it on upstream.

Thank you, much appreciated.

**Comment by lubing521** [comment]
> > I will try do it on upstream.
> 
> Thank you, much appreciated.

This is upstream status.

https://github.com/ARMmbed/mbedtls/pull/4721

**Pull request closed without merging**
