### PR TITLE
ta: pkcs11: fix error code in asymmetric signature update sequence

### PR DESCRIPTION
**Pull request by etienne-lms**
Correct return code in asymmetric update sequence when digest of
the input data is updated on a multi-stage operation. Prior this
change, the implementation returned CKR_GENERAL_ERROR instead of
CKR_OK because the expected success return value was loaded for
that stage.

Fixes: fb279d8b608e ("ta: pkcs11: Add support for elliptic curve signing & verification")
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

### CODE REVIEW

**Comment by ruchi393** [comment]
`Reviewed-by:Ruchika Gupta <ruchika.gupta@linaro.org>`

**Comment by etienne-lms** [comment]
tag applied.

**Comment by jforissier** [comment]
The QEMUv8 CI failure is unrelated (fix in https://github.com/OP-TEE/manifest/pull/198) but there is a checkpatch warning.

**Comment by etienne-lms** [comment]
Thanks to notice, I'll fix.

**Pull request merged**
