### PR TITLE
riscv: ldelf loader support on RISC-V

### PR DESCRIPTION
**Pull request by maroueneboubakri**
Summary of changes by this PR:
- Move `ldelf_loader.c` from core/arch/arm/kernel to core/kernel.
- Replace `is_arm32` with `is_32bit` where referenced.
-  Argument definition for ldelf dump state on RISC-V.

### CODE REVIEW

**Comment by jforissier** [comment]
For commit " core: kernel: move ldelf_loader.c to core/kernel":
"Header file is already in located outside arch folder." -> "The header file is already located outside the arch folder."
With that:

`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jforissier** [comment]
For commit "core & ldelf: replace is_arm32 with is_32bit":

With the subject fixed as mentioned above:

`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jforissier** [comment]
For commit "core & ldelf: add support for RISC-V":

With subject fixed:

`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by maroueneboubakri** [comment]
Comments addressed and tags applied.

**Pull request merged**
