### PR TITLE
plat-vexpress: FVP change shared memory range

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Changes shared memory range used on FVP since the old shared memory
region now conflicts with something else.

Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

Depends on https://github.com/OP-TEE/optee_linuxdriver/pull/41

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Ping

**Comment by jforissier** [comment]
I wouldn't mind a more precise description of "the old shared memory region now [since when? what kernel version?] conflicts with something else [what?]", but other than that:
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
I've noticed on latest for some time now, but I don't know at which version it started. But to have something we could say v4.4 because that I'm sure of. What it conflicts with I don't know, the kernel just ignores the attempt to reserve the memory.

**Comment by jenswi-linaro** [comment]
Rebased, tag applied and commit message updated

**Comment by pascal-brand-st** [comment]
Manually merged

**Pull request closed without merging**
