### PR TITLE
plat-stm32mp1: simplify IO mapping

### PR DESCRIPTION
**Pull request by etienne-lms**

### CODE REVIEW

**Comment by jforissier** [comment]
LGTM but we don't normally have Change-Id: tags.

**Comment by etienne-lms** [comment]
oups... i forgot to remove them. I'll update.

**Comment by etienne-lms** [comment]
here there are

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by etienne-lms** [comment]
tag applied

**Pull request merged**
