### PR TITLE
plat-imx: do not enable CFG_CRYPTO_DRIVER with CFG_NXP_CAAM

### PR DESCRIPTION
**Pull request by ldts**
Some IMX users might choose a different crypto driver (like the SE050)
but still require CAAM to provide the hardware unique key and perhaps
the RNG - since reading the RNG over I2C can impact performance on
some platforms.

This commit allows for such configuration.

Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

### CODE REVIEW

**Comment by ldts** [comment]
@clementfaure do you think this could get merged please?

**Comment by jforissier** [comment]
For the two `.shippable: ...` commits:
`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by ldts** [comment]
@jforissier updated tags

**Comment by ldts** [comment]
any more comments?

**Comment by jforissier** [comment]
Unless someone in @OP-TEE/plat-imx objects this looks OK to me. You may add my Acked-by: to the other commit too.

**Comment by clementfaure** [comment]
Hello all,

Sorry guys I just came back from vacation today,
About this PR, how is enabling the crypto driver when the CAAM is enabled is a problem?

**Comment by ldts** [comment]
@clementfaure just as said in the PR

```
Some IMX users might choose a different crypto driver (like the SE050)
but still require CAAM to provide the hardware unique key and perhaps
the RNG - since reading the RNG over I2C can impact performance on
some platforms.
```

So to sum up, SE050 users do not want the CAAM crypto driver and so the SE050 expects crypto driver to be disabled -as it should- before enabling it.

**Comment by clementfaure** [comment]
For us the default behavior would require the CAAM crypto driver to be enabled when the CAAM is also enabled
We would like to keep the ```CAAM enabled``` => ```Crypto driver enabled``` dependency if possible.

**Comment by ldts** [comment]
but why force CAAM crypto driver? how does this benefit a user that only needs the CAAM's RNG and HUK? 

Moreover imagine if a vulnerability is discovered in the CAAM crypto: with the current software the root of trust would be lost since the HUK can not be enabled without allowing the vulnerability (ie crypto)

functionally speaking, RNG, HUK and CRYPTO could be selectable entities and everything would be nicely partitioned.

**Comment by Emantor** [comment]
> but why force CAAM crypto driver? how does this benefit a user that only needs the CAAM's RNG and HUK?
> 
> Moreover imagine if a vulnerability is discovered in the CAAM crypto: with the current software the root of trust would be lost since the HUK can not be enabled without allowing the vulnerability (ie crypto)
> 
> functionally speaking, RNG, HUK and CRYPTO could be selectable entities and everything would be nicely partitioned.

This would also allow us to enable at least the CAAM HUK functionality unconditionally, since the HUK generation is only done on bootup and can't be interfered with by Linux toggling of the clocks. I also have a draft PR which enables the CAAM RNG for the initial seed, but uses the PRNG thereafter for the same reason. I'd be in favor of this change.

**Comment by clementfaure** [comment]
Alright, if it gives more flexibility I'm okay with that.
Since the ```CFG_NXP_CAAM = y``` will no longer imply ```CFG_CRYPTO_DRIVER = y``` could you add ```CFG_CRYPTO_DRIVER=y``` in ```.shippable.yml``` for platforms compiling with ```CFG_NXP_CAAM=y``` ?

**Comment by ldts** [comment]
@clementfaure sure, makes sense. will do that now

**Comment by ldts** [comment]
@clementfaure updated (tags still not given to https://github.com/OP-TEE/optee_os/pull/4275/commits/c01ff9d7e7e42f2080b8e608a385a63ad39bc200 nor https://github.com/OP-TEE/optee_os/pull/4275/commits/437e9b027921b4ffc5b3e367d52a5bc4db26c5d9)

**Comment by clementfaure** [comment]
For c01ff9d7e7e42f2080b8e608a385a63ad39bc200 and 437e9b027921b4ffc5b3e367d52a5bc4db26c5d9
```Acked-by: Clement Faure <clement.faure@nxp.com>```

**Comment by ldts** [comment]
ok done.

**Pull request merged**
