### PR TITLE
Add phyBOARD-Pollux support

### PR DESCRIPTION
**Pull request by ymoog**
phyBOARD-Pollux i.MX 8M Plus is an SBC based on the i.MX 8M Plus SoC. Add the board to the mx8mp-flavorlist and set board specific configs.

### CODE REVIEW

**Comment by sahilnxp** [comment]
@ymoog Is xtest running fine with this config ?

**Comment by ymoog** [comment]
> @ymoog Is xtest running fine with this config ?

Yes. I tested this according to the steps defined in [build](https://optee.readthedocs.io/en/latest/building/gits/build.html).  I had to modify other parts of OP-TEE as well as U-Boot to be able to have the phyBOARD-Pollux run (which I am planning/working on upstreaming).

**Comment by sahilnxp** [comment]
`Acked-by: Sahil Malhotra <sahil.malhotra@nxp.com>`

**Review by etienne-lms — COMMENTED** [review]
Suggestion for the commit header line: `plat-imx: Add phyBOARD-Pollux support`

**Comment by jforissier** [comment]
@ymoog would you please change the subject line as suggested by @etienne-lms, add @sahilnxp's Acked-by: and force push? Then I can merge this. Thank you!

**Comment by ymoog** [comment]
> @ymoog would you please change the subject line as suggested by @etienne-lms, add @sahilnxp's Acked-by: and force push? Then I can merge this. Thank you!

Of course; Sorry, I was ill the last days.

**Pull request merged**
