### PR TITLE
core: arm: imx: add i.MX6Q Nitrogen6x support

### PR DESCRIPTION
**Pull request by Amit-Radur**
This patch adds support for Nitogen6x based. It is based on NXP's popular i.MX6
ARM-Cortex A9 processor[1].

1. Build command:
        make PLATFORM=imx-mx6qnitrogen6x
2. Pass xtest

[1] https://boundarydevices.com/product/nitrogen6x-board-imx6-arm-cortex-a9-sbc/

Signed-off-by: Amit Singh Tomar <amittomer25@gmail.com>

### CODE REVIEW

**Comment by Amit-Radur** [comment]
Hello @sdininno 
We could use mx6qsabrelite as well but I have seen people confuse 
about nitrogen6x support in optee-os.

This just make it more obvious for people to follow and use optee-os on nitrogen6x.

Thanks
Amit

**Comment by sdininno** [comment]
@Amit-Radur sure but this looks more to me like a documentation problem than anything else
this can be solved with
+| [NXP/FSL i.MX6 Quad Nitrogen6x Board](https://boundarydevices.com/product/nitrogen6x-board-imx6-arm-cortex-a9-sbc/) |`PLATFORM=imx-mx6qsabrelite Yes | Actively maintained v3.1.0 |

**Comment by Amit-Radur** [comment]
Thanks, @sdininno. That looks smarter and sensible.

Shall I update the PR with this change, also do we need to keep changes MAINTAINERS file?

**Comment by sdininno** [comment]
Hello @Amit-Radur, 
not up to me to decide.

@jforissier , @MrVan , What should @Amit-Radur do?

**Comment by MrVan** [comment]
@Amit-Radur Do you have any other specific settings that you would like to add later that different from 6qsabrelite? If not, reuse "imx-mx6qsabrelite" is fine.

**Comment by Amit-Radur** [comment]
Hello @MrVan only concern is, there are few Nitrogen6x variants that comes with 2GB DDR .

Is it require any change in platform_config.h ?

**Pull request closed without merging**
